### ISSUE TITLE
How to read property from last invoked command?

### ISSUE THREAD

**Issue by munchie45** [darkoperator/Posh-SSH#100]
Hi,

I'm automating some hardware config backup job and command: **Invoke-SSHCommand -SessionId $sessionId -Command "backup"** gives me output:

_Output     : {File written to the location, "/backup/backup-2016-07-05.cfg"., Configuration saved.}
ExitStatus : 0
Error      : 
Host       : 192.168.100.132
Duration   : 00:00:03.3760740_

if i could access output property i could use:

**$output -split '"' -match '\/backup/([\s\S]*)')**

already tried:
**$output = Invoke-SSHCommand ... | Select -ExpandProperty Output
$output = $(Invoke-SSHCommand ...).Output**

and pass it to Get-SCPFile in order to download the backup file.
I dont want to use streams because thats how im currently backing up with SshShell module

**Comment by darkoperator** [comment]
Because it is an array you need to do a foreach against the content of the property or do a -join to turn it in to a string. The turning of the output in to an array will possibly be reverted to be a string with an option to make it in to an array in the next version. It is the reason I have not updated the version in the gallery because it is a braking event.

**Comment by munchie45** [comment]
ahhh, i was wondering why there are commas... thanks! anyway, i have another issue. when i try to download the file it says:

PS C:\cmd> **Get-SCPFile -ComputerName $IP -Credential $(Get-Credential) -RemoteFile /backup/backup.txt -LocalFile c:\cmd\test.txt -Verbose -Debug**
cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
_VERBOSE: Using SSH Username and Password authentication for connection.
VERBOSE: Fingerprint matched trusted fingerprint for host 192.168.100.132
VERBOSE: Connection successful
VERBOSE: Downloading backup.txt_
**Get-SCPFile : scp: "/backup/backup.txt": No such file or directory.
At line:1 char:1**

When i use pscp it downloads the file with no issues. From the logs on the remote hardware i can see a difference in issued commands:

**pscp:**
_executed batch command: 'scp -f /backup/backup.cfg'_

**Get-SCPFile:**
_executed batch command: 'scp -pf "/backup/backup.cfg"'_

is there any way to control what switches are used in Get-SCPFile and remove quotations marks from the filename?

**Comment by darkoperator** [comment]
Because it is not $(get-credential) but just (get-cresential)

**Comment by darkoperator** [comment]
Sorry just woke up and miss read, no there is no way to control the underline switches the library sends. What gear is this?

**Comment by munchie45** [comment]
Cisco IronPort

**Comment by darkoperator** [comment]
sadly I'm not able to replicate on linux or BSD hosts, I do not have Cisco gear to test

**Comment by munchie45** [comment]
Is there anyway i can help you with troubleshooting this?
Of course i cannot allow you to use our hardware

**Comment by darkoperator** [comment]
sadly it is hardcoded in the library the scp -pf "<file>"' command, there is no way to change this without me changing the library and probably breaking it in other platforms. sadly without access to the specific gear there is no way for me to troubleshoot it.
