### ISSUE TITLE
New-SSHSession output

### ISSUE THREAD

**Issue by Jim-Wright** [darkoperator/Posh-SSH#102]
Version 1.7.5
When used from the command line, the New-SSHSession outputs text like the following:

SessionId  Host                                                        Connected                                              
---------  ----                                                          ---------                                              
    0          172.25.254.101                                       True    

When used within a script, only the last line is shown in the output.  I tried to eliminate this output by assigning the command to a variable, for example:

$theoutput = New-SSHSession -ComputerName (etc)

This worked, and captured the same info as from the command line.  I then tried to parse this, thinking I could get back the actual SessionID, but this output was one large block.

It would be handy for the output to be passed as an Array, so that I could find the SessionID in $theoutput[0], host in $theoutput[1], and connected status in $theoutput[2].

When connecting to multiple devices via a script in a loop, the assigned SessionID is incrementing and the correct session isn't getting closed as a result.

**Comment by darkoperator** [comment]
it returns an object for the session, simply use the property for it
```
PS C:\Users\Carlos Perez> New-SSHSession 192.168.1.168 -Credential carlos | gm


   TypeName: SSH.SshSession

Name        MemberType Definition
----        ---------- ----------
Connect     Method     void Connect()
Disconnect  Method     void Disconnect()
Equals      Method     bool Equals(System.Object obj)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
ToString    Method     string ToString()
Connected   Property   bool Connected {get;}
Host        Property   string Host {get;set;}
Session     Property   Renci.SshNet.SshClient Session {get;set;}
SessionId   Property   int SessionId {get;set;}
```

**Comment by Jim-Wright** [comment]
OK, got it.  In case anyone else needs this in a script:

$theSession = New-SSHSession 192.168.1.168 -Credential carlos
# $theSession.Host 
# $theSession.SessionID
