### ISSUE TITLE
Support more SSH Ciphers and MACs

### ISSUE THREAD

**Issue by ypid** [darkoperator/Posh-SSH#103]
As of [lastest master](https://github.com/darkoperator/Posh-SSH/commit/573a3e3c8220bffa06dda0048c6048e8a5e837c0) Posh-SSH does not support state of the art ciphers and macs from OpenSSH.

Tested with `get-scpfile`. It fails for the following two options in my OpenSSH server configuration:

```
Ciphers aes256-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com
```

> get-scpfile : Client encryption algorithm not found

and

> Server HMAC algorithm not found

**Comment by darkoperator** [comment]
Expected behavior since they ar not in the list of supported ciphers in the library used 
https://sshnet.codeplex.com/ <https://sshnet.codeplex.com/>

Library used has been abandoned by the author so no future plan on adding them unless someone provides a PR with the addition.

**Comment by darkoperator** [comment]
Let me correct my self, seems the library has a new owner and it is being developed again :) https://github.com/sshnet/SSH.NET/commits/develop <https://github.com/sshnet/SSH.NET/commits/develop> can you add a feature request with them for the Ciphers?

**Comment by ypid** [comment]
Thanks for the pointer. [Done](https://github.com/sshnet/SSH.NET/issues/53).
