### ISSUE TITLE
Host is case sensitive when using New-SSHSession (-AcceptKey)

### ISSUE THREAD

**Issue by BornToBeRoot** [darkoperator/Posh-SSH#104]
When using New-SSHSession: 

If the Hostname is not exact/equal (case sensitive) the Hostname you entered on the first connection (when you accept the key), you have to accept the SSH fingerprint.

![image](https://cloud.githubusercontent.com/assets/16019165/17216851/9d17b2a6-54e2-11e6-8156-31090f1758f1.png)

If you accept again. The registry key ist not overwritten... 

Steps  to reproduce:

1) `New-SSHSession TESTDEVICE01 -AcceptKey` 
2) `New-SSHSession TestDevice01`

**Comment by darkoperator** [comment]
Thanks for reporting this, will look in to it.

**Comment by BornToBeRoot** [comment]
I am now home from work :smile:

This should only apply to the hostname... the key (check) is still case sesitive.

**Comment by darkoperator** [comment]
cool, I will check the pull request

**Comment by darkoperator** [comment]
fix merged and binary module pushed
