### ISSUE TITLE
Interactive shell like PuTTY?

### ISSUE THREAD

**Issue by BornToBeRoot** [darkoperator/Posh-SSH#107]
Is it possible to create an interactive shell like PuTTY does?

**Comment by darkoperator** [comment]
No

**Comment by BornToBeRoot** [comment]
Thx for the fast replay :smile:

I was just wondering if it's possible.

**Comment by darkoperator** [comment]
Let me correct, not with the current version but if it is possible using the library Im using, yes but don't have the time to sit and figure out how to do it at the moment but do accept Pull Request of someone is interested in adding it :)
