### ISSUE TITLE
mac osx, metasploit v4.12.18-dev-009089e load enum_ad_domain_trusts.rb is error

### ISSUE THREAD

**Issue by hktalent** [darkoperator/Posh-SSH#108]
mac osx, metasploit v4.12.18-dev-009089e load enum_ad_domain_trusts.rb is error

.msf4/modules/post/windows/gather/enum_ad_domain_trusts.rb:100: syntax error, unexpected ':', expecting ']'

**Comment by darkoperator** [comment]
Wrong github project

**Comment by darkoperator** [comment]
pushed a fix on the correct repository
