### ISSUE TITLE
Send Multiple actions for a single command

### ISSUE THREAD

**Issue by TFisher179** [darkoperator/Posh-SSH#109]
Is it possible to send multiple actions to a single command?  For example, If I send a command to reset a password, I would like to respond to both the initial password prompt and the question to retype the password.

Invoke-SSHStreamExpectAction -ShellStream $stream -Command "passwd user1" -ExpectString "password" -Action "newpassword; newpassword"

**Comment by darkoperator** [comment]
In that case you will have to code against the stream where you read the stream in a timed loop until you see the promo and the write to it then pass a carriage return so it executes the text.
