### ISSUE TITLE
New-SSHSession instantly disconnects upon connection

### ISSUE THREAD

**Issue by powershellnicholas** [darkoperator/Posh-SSH#11]
Hi,

I have used Posh-SSH successfully many times in the past but recently encountered a weird issue. I was able to SSH into routers, linux hosts, firewalls and perform I/O and scripting. Recently we have some session border controllers which seems to be rather strict when it comes to SSH connections.

By using the same New-SSHSession -Computername "SBC-IP" , the Connected status was True, however - it seems to disconnect instantly, and all subsequent Invoke-SSHcommands or etc will fail.

I found out that these devices seem to accept "interactive terminals/shells" only with ANSI/dumb terminal with some parameters. I have tested this with ChilkatDotNet45.dll with sample code and was able to connect to these devices and send commands. The implementation is more complex and not as straight forward as Posh-SSH though.

Is there a way for Posh-SSH to SSH into a device and acts as a terminal emulator (ANSI, dumb) or etc? 
There rea ways to interactively enter a SSH session using the CreateStream within powershell - but that requires an existing valid SSH before Powershell can create a stream based on it and enter the session. The problem here is that the stream cannot be created because the SSH session disconnects upon proper login and the SSHsessionID is not valid.

**Comment by darkoperator** [comment]
There is a known bug with “-“ in host names try using the IP address. The authors of the library seem to have a fix for it but I will need to merge some improvements and release “Beta” code, wish I’m a bit reluctant to do. Was hopping they finished the rest of the fixes but it has taken them months.

**Comment by powershellnicholas** [comment]
Hi, thanx for the quick response. Yeah I was aware of the hostname with "-". I tried connecting to the same host using IP address, and the result was the same.

**Comment by darkoperator** [comment]
hmm is then a way for me to simulate this device? would need to replicate to be able to fix it.

**Comment by darkoperator** [comment]
Closing since no update has been provided in over a month.
