### ISSUE TITLE
accept Client Certificate for New-SSHSession 

### ISSUE THREAD

**Issue by theking2** [darkoperator/Posh-SSH#111]
Allow a client certificate to be used to logon .

**Comment by darkoperator** [comment]
Library only allows for SSH keys.

**Comment by theking2** [comment]
thanks.

What is SSH keys?

**Comment by darkoperator** [comment]
https://help.ubuntu.com/community/SSH/OpenSSH/Keys

**Comment by theking2** [comment]
got it
