### ISSUE TITLE
Create new SFTP Directory

### ISSUE THREAD

**Issue by TFisher179** [darkoperator/Posh-SSH#115]
Is there a way to create a new directory on an FTP server?

**Comment by darkoperator** [comment]
Module is only for SFTP (SSH) not FTP or are you referimos to SFTP?

**Comment by TFisher179** [comment]
I was referring to SFTP, sorry.

**Comment by darkoperator** [comment]
There is New-SFTPDirectory in the module for creating directories on a target

**Comment by TFisher179** [comment]
Thank you for the help!
