### ISSUE TITLE
Set-SFTPFile error message is not helpful at all

### ISSUE THREAD

**Issue by vzabauski** [darkoperator/Posh-SSH#116]
Set-SFTPFile command needs only target folder provided with `-RemotePath` parameter. If you provide target path with target file name (like you do when you're using `mv` or `cp` commands in Linux) it gives strange error message:

```
Set-SFTPFile : /home/azureuser/certificates/cert.p7b does not exist.
At C:\Users\azureuser\Desktop\MomAgent_Certificate_Signer.ps1:64 char:3
+   Set-SFTPFile -SessionId $SFTPSession.SessionID -LocalFile "D:\Certs ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (SSH.SftpSession:SftpSession) [Set-SFTPFile], SftpPathNotFoundException
    + FullyQualifiedErrorId : /home/azureuser/certificates/cert.p7b does not exist.,SSH.SetSftpFile
```

It pretty obvious that target **does not** exist because we're going to copy it there.

Example command to reproduce the error:
`Set-SFTPFile -SessionId $SFTPSession.SessionID -LocalFile "D:\Certs\cert.p7b" -RemotePath "/home/user/certificates/cert.p7b" -Overwrite`

I guess it happens because Powershell command interprets `cert.p7b` like target folder name that exists but that error message gave me an hour of different thoughts before I took a look at my old script where I was using the right command.

**Comment by darkoperator** [comment]
problem is that I test if the target exist, can not validate for user error when he gives a name with a "." since you can have dir names with dot.

**Comment by ChrisMagnuson** [comment]
I just hit this issue as well. [Pull request](https://github.com/darkoperator/Posh-SSH/pull/180) submitted to update the text to indicate that it was a directory that was not found as that would help tip off the user that the parameter is testing for a directory not a file.
