### ISSUE TITLE
Posh-SSH\New-SshSession : The method or operation is not implemented. 

### ISSUE THREAD

**Issue by vtischuk** [darkoperator/Posh-SSH#118]
Greetings!
I was successful in getting posh-ssh to work on my pc.

But when I copied the posh-ssh folder to a production server module directory and tried it I received the error below:
Posh-SSH\New-SshSession : The method or operation is not implemented. 
At line:158 char:5 
- $q= Posh-SSH\New-SshSession -ComputerName $Instance -Credential $mycreds 
- 
- CategoryInfo : InvalidOperation: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], NotImplementedException 
- FullyQualifiedErrorId : SSH.NewSshSession 

The production systems are running an older version of ssh.net and the Renci.SshNet.dll so I prefixed the New-SSHSession with the module name:  Posh-SSH\New-SshSession

I am unable to do a download into the production servers as there is no internet connection.  

Any suggestions would be appreciated.

Thanks,

Victor

**Comment by darkoperator** [comment]
Did you import the module before running the command?

**Comment by vtischuk** [comment]
Hi,

The production servers have no access to the internet so I copied the Posh-SSH folder to C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\  and used combinations of the commands below:

Import-Module 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\Renci.SshNet.dll'
Import-Module 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\PoshSSH.DLL'
Import-Module 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\Posh-SSH\Posh-SSH.psd1' 

and I also removed the other modules prior with get-module | remove-module.

But the New-Session code produces the error :


InvalidOperation: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], NotImplementedException

Your suggestions are appreciated.

Victor

**Comment by vtischuk** [comment]
oops, didn't mean to click the close button..

**Comment by darkoperator** [comment]
You don’t have to do import-module on every file :)
Need to provide more details, hard to replicate a problem without the context of where it is running. I need:
Version of PowerShell
What version of windows and architecture.
What do you mean by an old version of Renci.shh

At the moment it can not co-exist with other modules using Renci loaded at the same time.

**Comment by vtischuk** [comment]
That the problem!  I have both the old and new Renci modules in memory. Production uses an old version of SSH.NET.  I thought by using remove-module in my code prior to loading the Posh-SSH module that it would be ok.  It seems like my only option now is to convert the code in all of the programs to use the new module, bounce a server and then retry the test.  If I use a subshell to test with can I avoid bouncing the server?

Thanks,

Victor

**Comment by darkoperator** [comment]
you can just not load the old library in the session. the libraries are loaded per session and only one instance of them can be loaded at once.

**Comment by vtischuk** [comment]
The old renci dll used by production seems to live forever in 'shadow copies' in memory that propogate into the new sessions.  I'm going to try a few experiments today to see if I can kill these copies but so far they're like sci-fi monsters that just won't die....

**Comment by vtischuk** [comment]
This is interesting. On a new system (Solarwinds Poller/64 bit), I tried to create a new-sshsession and still got the message below.  I'm wondering if I need to be an administrator on this box as it works fine on my pc.


Errors: ==============================================
POSH-SSH\New-SshSession : The method or operation is not implemented. 
At line:10 char:5 
+ $q= POSH-SSH\New-SshSession -ComputerName $server1 -Credential $mycreds 
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
+ CategoryInfo : InvalidOperation: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], NotImplementedException 
+ FullyQualifiedErrorId : SSH.NewSshSession

**Comment by darkoperator** [comment]
closing since this is not something I can control in the module.
