### ISSUE TITLE
Error channel for extreme switches

### ISSUE THREAD

**Issue by mgpnet** [darkoperator/Posh-SSH#119]
me help.... I searched for the solution but so far nothing.

$passwd = convertto-securestring -String $passwd -AsPlainText -Force
$access = new-object -typename System.Management.Automation.PSCredential -argumentlist $user, $passwd
            
$ssh = New-SSHSession -ComputerName $ip -Credential $access -ErrorAction Ignore
            
$index = $ssh.SessionId
Get-SSHSession -Verbose -Debug
start-sleep -m 1000
Invoke-SSHCommand -Index $index -Command " show "

Remove-SSHSession $index

SessionId  Host                                                         Connected                                             
---------  ----                                                         ---------                                             
    0      x.x.x.x                                                   True                                               
Exceção ao chamar "BeginExecute" com "0" argumento(s): "Failed to open a channel after 10 attempts."
No mydir\Documents\WindowsPowerShell\Modules\Posh-SSH\Posh-SSH.psm1:348 caractere:17
+                 $Async = $cmd.BeginExecute()
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SshException
 

######################################

Other error

######################################

$passwd = convertto-securestring -String $passwd -AsPlainText -Force
$access = new-object -typename System.Management.Automation.PSCredential -argumentlist $user, $passwd
            
$ssh = New-SSHSession -ComputerName $ip -Credential $access -ErrorAction Ignore
            

Get-SSHSession -Verbose -Debug
$ssh = New-SSHShellStream -Index $index

$index = $ssh.SessionId
$index
Remove-SSHSession $index

SessionId  Host                                                         Connected                                             
---------  ----                                                         ---------                                             
    0      x.x.x.x                                                    True                                               
Exceção ao chamar "CreateShellStream" com "6" argumento(s): "Failed to open a channel after 10 attempts."
No mydir\Documents\WindowsPowerShell\Modules\Posh-SSH\Posh-SSH.psm1:663 caractere:9
+         $stream = $ToProcess.Session.CreateShellStream($TerminalName, ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SshException
 
Add-Member : Não é possível associar o argumento ao parâmetro 'InputObject' porque ele é nulo.
No mydir\Documents\WindowsPowerShell\Modules\Posh-SSH\Posh-SSH.psm1:664 caractere:33
+         Add-Member -InputObject $stream -MemberType NoteProperty -Nam ...
+                                 ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.AddMemberCommand
 
Add-Member : Não é possível associar o argumento ao parâmetro 'InputObject' porque ele é nulo.
No mydir\Documents\WindowsPowerShell\Modules\Posh-SSH\Posh-SSH.psm1:665 caractere:33
+         Add-Member -InputObject $stream -MemberType NoteProperty -Nam ...
+                                 ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.AddMemberCommand
 
Remove-SSHSession : Não é possível associar o argumento ao parâmetro 'SessionId' porque ele é nulo.
No linha:19 caractere:19
+ Remove-SSHSession $index
+                   ~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-SSHSession], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Remove-SSHSession

**Comment by darkoperator** [comment]
Against what type of system is this? Most embedded systems that do not run Linux and OpenSSH do not support exec command and they expect a proper console. Have you tried using a stream instead?

**Comment by mgpnet** [comment]
The system´s version is "ExtremeXOS version 15.7.4.2".
I believe that is based in linux, too. 

It logged in, but does not accept a command. 
An alternative form of access was by telnet, in which he executed all commands.

For more information: [Extreme](http://www.extremenetworks.com/)

**Comment by darkoperator** [comment]
Did you tried using a SSH stream ?

**Comment by mgpnet** [comment]
yes, i tried. In the second script.
....
$ssh = New-SSHShellStream -Index $index
....

Part of error

......
Exceção ao chamar "CreateShellStream" com "6" argumento(s): "Failed to open a channel after 10 attempts."
No mydir\Documents\WindowsPowerShell\Modules\Posh-SSH\Posh-SSH.psm1:663 caractere:9

        $stream = $ToProcess.Session.CreateShellStream($TerminalName, ...

.......

**Comment by darkoperator** [comment]
Is you use plink to issue a command does it work? https://the.earth.li/~sgtatham/putty/0.58/htmldoc/Chapter7.html <https://the.earth.li/~sgtatham/putty/0.58/htmldoc/Chapter7.html>

Will try to setup a VM of the 16.x version since they seems to have a way to virtualize it https://github.com/extremenetworks/Virtual_EXOS <https://github.com/extremenetworks/Virtual_EXOS> one thing to keep in mind in version 15.x it seems that SSH is handled completely different https://gtacknowledge.extremenetworks.com/articles/How_To/How-to-obtain-and-install-ssh-module <https://gtacknowledge.extremenetworks.com/articles/How_To/How-to-obtain-and-install-ssh-module>

**Comment by darkoperator** [comment]
Wondering if it could be something with the SSH versions on the OS of the switch
<pre>
PS C:\Users\Carlos> Invoke-SSHCommand -Command 'show version' -SessionId 0 | select -ExpandProperty output
Switch      : PN:1N2039    SN:123456   Rev 0.1 BootROM: 1.2        IMG: 16.2.1.6
PSUCTRL-1   : PN:MEAD      SN:MD1      Rev 0.1 BootROM: 2.1
PSUCTRL-2   : PN:MEAD      SN:MD2      Rev 1.1 BootROM: 2.3
mouse-usb   : PN:MOUSE     SN:4321     Rev 1.1 BootROM: 4.3
floppy-A    :
PSU-1       : Internal PSU-2 PN:1N2039 SN:12345
PSU-2       : Internal PSU-3 PN:1N2039 SN:12345

Image   : ExtremeXOS version 16.2.1.6 by release-manager
          on Sat Aug 6 18:26:12 EDT 2016
BootROM : 1.2
</pre>

**Comment by darkoperator** [comment]
any update on this?

**Comment by darkoperator** [comment]
closing for now. Reopen if problem persists with updated switch OS version.
