### ISSUE TITLE
Fixing Issue 33 has broken the actual code affecting stream column width

### ISSUE THREAD

**Issue by missgt** [darkoperator/Posh-SSH#123]
Issue #33 referred to 'column' being misspelt as 'colum' in the New-SSHShellStream function parameters in Posh-SSH.psm1. It was only corrected here and hence has broken the function.
It also needs to be changed in the call to CreateShellStream with the Process script block.
Thanks,
Steve

**Comment by missgt** [comment]
Just wondering if this is going to be fixed. I have a need to get output that is 240 columns wide and would like to use the supported code stream, Not one I've fixed myself.
Cheers

**Comment by darkoperator** [comment]
Can you try the new version in Github, it should be fixed. Will push to the gallery on monday

**Comment by missgt** [comment]
That's fixed it.
Much appreciated.
