### ISSUE TITLE
Memory leak in Invoke-SSHCommand?

### ISSUE THREAD

**Issue by karezza** [darkoperator/Posh-SSH#125]
[Connecting to OpenSSH on Scientific Linux release 6.8 (Carbon)]
[From Windows7 using latest Posh-SSH code.]
I keep getting a memory leak with:

```
while ($true) {
    $Command = "/path/to/command/which/returns/some/data"
    $Result = Invoke-SSHCommand -Command $Command -SSHSession $Script:SshSession -TimeOut 20
    Remove-Variable -Name "Command" -Force -ErrorAction SilentlyContinue
    Remove-Variable -Name "Result" -Force -ErrorAction SilentlyContinue

    # Perform garbage collection
    [System.GC]::Collect()
    Sleep -Seconds 1
}
```

**Comment by darkoperator** [comment]
Why are you doing a loop that never ends and executes as fast as each connection can be executed? The module is meant for automation not monitoring

**Comment by karezza** [comment]
This is the result of going through my code working to identify a memory leak.  Eventually I identified the problem here.  The actual code is a bit of a long story, but in the end it does end up performing some commands via SSH in a loop and so over time the leak is an issue.  I can kill the process daily to keep the leak under control, but it would be nice if the leak could be stopped.

I thought maybe you would tell me there was a cleanup step I was needing to perform.  Is there a known leak?  Something that won't be fixed?

**Comment by darkoperator** [comment]
I keep looking at the PS code and cant see how a leak would be possible. If there is one it would probably bee in the library and it that case the code is way above my skill set to identify the leak if there is one in the C# code of it. Will have to do some tests on my own when I have spare cycles to look in to it.

**Comment by karezza** [comment]
As a workaround, I modified my looping powershell scripts to exit & wrapped them in a forever-looping batch script instead.  It's not ideal, as one of my scripts is listening to a network socket (So I keep closing the socket down and then reopen it next run), but it meets my needs.  Good enough to get around memory leak issue.

```
REM loop forever
:loop

REM do work
powershell -C "&{ 'run function' }"

REM log sleep
powershell -C "&{ $ts = get-date -uformat \"%%Y-%%m-%%d %%H:%%M\"; \"[$ts] Sleeping\" }"
powershell -C "&{ Sleep -Seconds (10 * 60) }"

REM perform loop again
goto loop
```

**Comment by darkoperator** [comment]
Added a new build of the core lib, can you test with it? only on the version in GitHub

**Comment by darkoperator** [comment]
Seems the issue is in the library. As long as the session is open it will cause it https://github.com/sshnet/SSH.NET/pull/7
