### ISSUE TITLE
vtysh: invalid option -- 'c' Try `vtysh --help' for more information.

### ISSUE THREAD

**Issue by thisispuneet** [darkoperator/Posh-SSH#126]
Any way to invoke-sshcommand without -c or -Command?

**Comment by darkoperator** [comment]
Well you need to specify what command it will invoke :) are you putting the command between quotes or double quotes? Did not provide much info so going off the title.

**Comment by thisispuneet** [comment]
apologies! Command I'm invoking...

`$a = Invoke-SSHCommand -Index 4 -command "show cluster all"`

It doesn't matter what command I invoke or if I use double or single quotes. I always get this output...

> $a
> Host       : 192.168.110.42
> Output     : {}
> ExitStatus : 1

and when I look for Error note property it shows

> $a.Error
> vtysh: invalid option -- 'c'
> Try `vtysh --help' for more information.

**Comment by darkoperator** [comment]
Seems like that platforms does not support the exec command used. Have you tried a stream?

**Comment by thisispuneet** [comment]
> $SSHStream = New-SSHShellStream -Index 4 
> $SSHStream.WriteLine(" show cluster all ")
> $SSHStream.read()

worked! Any link for SSHShellStream where I can learn more about it?
For eg I would like to know if: 

- I can convert .read() string to an array or hash table 
- Limitation on Buffer Size, etc

Thanks

**Comment by BornToBeRoot** [comment]
@thisispuneet Mabe this could help you. I wrote this function to execute a command on brocade switches and detect when it's finished and parse the output... 

https://github.com/BornToBeRoot/PowerShell_BrocadeICX/blob/master/Module/BrocadeICX/Core/Invoke-ICXCommand.ps1

**Comment by rmbolger** [comment]
@thisispuneet Here's another example that might help.

https://github.com/rmbolger/Posh-IBCLI/blob/master/Posh-IBCLI/Public/Invoke-IBCLICommand.ps1

**Comment by thisispuneet** [comment]
Thank you @BornToBeRoot and @rmbolger I'm trying the functions now... 👍
