### ISSUE TITLE
Posh-SSH disconnects from New-SFTPSession immediately

### ISSUE THREAD

**Issue by JBHorne** [darkoperator/Posh-SSH#127]
I'm setting up a transaction automation job using Posh-SSH (v 1.7.7). I run the command:

`New-SFTPSession -ComputerName $SftpAddress -Credential $Credential -KeyFile $Keyfile -Port $Port -ConnectionTimeout $ConnectionTimeout -Verbose`

and then:

`Set-SFTPFile -SessionId 0 -LocalFile $SftpLocalFile -RemotePath $SftpRemotePath`

but receive the error `Set-SFTPFile : Client not connected.`

Even if I run `Get-SFTPSession -SessionId 0` immediately after the `New-SFTPSession` I see Connected = False.

This is the output of  `$error[0] | fl * -force` if it helps:

> PSMessageDetails      : 
> Exception             : Renci.SshNet.Common.SshConnectionException: Client not connected.
>                            at Renci.SshNet.SftpClient.Exists(String path)
>                            at SSH.SetSftpFile.ProcessRecord()
>                            at System.Management.Automation.CommandProcessor.ProcessRecord()
> TargetObject          : 
> CategoryInfo          : NotSpecified: (:) [Set-SFTPFile], SshConnectionException
> FullyQualifiedErrorId : Renci.SshNet.Common.SshConnectionException,SSH.SetSftpFile
> ErrorDetails          : 
> InvocationInfo        : System.Management.Automation.InvocationInfo
> ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
> PipelineIterationInfo : {}

Any idea why? I can successfully connect to this server no problem using FileZilla.

Update: The hostname does NOT have a "-" in it per bug #11 . Tested via IP with same results.

Thanks!

**Comment by JBHorne** [comment]
OK! It looks like I figured out my issue! I was testing this in ISE -- if you create a session and then try to create a new session on top of the old session, it uses a new sessionID number. So, I was creating session upon session, but only looking at the first sessionID. If would be nice if "New-SFTPSession" returned the sessionID it created. :)

**Comment by waqaskhan137** [comment]
@JBHorne how do you test your code in ISE then?
