### ISSUE TITLE
Automation Use No Interactive Prompt?

### ISSUE THREAD

**Issue by philipathomas** [darkoperator/Posh-SSH#129]
Greetings, 

Maybe my PS inexperience is shining brightly in this question, but I'm trying execute a PS script, that invokes Posh-SSH,  from a monitoring tool called PRTG. It's a simple process where I've written a script that is fired by PRTG when an event occurs. The script is bellow, my issue is it appears that Posh-SSH will invoke a interactive dialog window and wait for credentials and because of this the script never completes it's execution. I'm puzzled why that dialog window from the New-SSHSession even presents itself considering I'm using a key file for authentication, but again, I don't that much PS experience so I might be missing something simple. This Newbie says thanks for any insight on my issue. 

`
# 
# Test values
$phoneNumber = 'xxxXXXxxxx'
$message = (Get-Date).DateTime
# 
#  Capture phone and message parameters from CLI 
#param([string]$phoneNumber = "phoneNumber", [string]$message = "message")
#
# Assembly send command string.
$SendCommand = "sendsms " + $phoneNumber + " " + "'" + $message + "'"
#
# Test code to pass credentials  
#$username = "alert" 
#$password = " " | ConvertTo-SecureString -asPlainText -Force
#$credential = New-Object System.Management.Automation.PSCredential($username,$password)
#
#Open SSH session using key authentication.
New-SSHSession -ComputerName 1.1.1.1 -Credential alert -KeyFile "C:\keys\keyA.key" -Port 2220
#
# Send command to fire SMS alert
Invoke-SSHCommand -Command $SendCommand -SessionId 0
#
#
# Kill SSH session
Remove-SSHSession -SessionId 0
#
# Jobs done, next?
`

**Comment by darkoperator** [comment]
The reason is that even if you provide a key the credentials param is still mandatory so we know to what user we should associate the key to. You can create a credential object with the user and a empty password and pass the key param.
