### ISSUE TITLE
PowerShell Core support

### ISSUE THREAD

**Issue by MathiasMagnus** [darkoperator/Posh-SSH#130]
I tried loading the module in the latest PS Core alpha16, but it fails to load the module. Is PS Core support on the roadmap?
```Powershell
PS C:\Users\Matty> Import-Module Posh-SSH
Import-Module : Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c56193
4e089'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
At line:1 char:1
+ Import-Module Posh-SSH
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by darkoperator** [comment]
Because core is not supported only windows PowerShell I would need to recompile the module and library for Core support

**Comment by MathiasMagnus** [comment]
.Net Core was specifically designed so one can have a single set of Assemblies that are able to run atop both runtime stacks, so long as they resort to using only .Net Standard functionality.

Don't get me wrong, I understand it is a non-zero amount of work, but the ability to run atop Linux/OSX certainly has an added value.

**Comment by Claustn** [comment]
Do you have any idea, how much work would go into recompiling it for .net core ? I have a lot of code using this on Windows, but need to run some of those scripts in Linux containers as well, and would prefer not to have to split up and maintain those scripts separately.

**Comment by joeyaiello** [comment]
@darkoperator I currently have a working build of Posh-SSH built against .NET Standard 2.0 and PowerShell Standard 5.1. Is this something you're interested in? 

If so, unfortunately, it required a pretty large refactor of your build and usage of the dotnet-cli. If yes, even if it's not in a perfectly mergeable state, I'd like to open a PR via which we can drill down issues. 

Thoughts?

**Comment by darkoperator** [comment]
Any update on this Joey?

**Comment by kleinsmk** [comment]
@joeyaiello   I'm going to be annoying an bump this as you weren't tagged directly.   The amount of people interested has only increased.

**Comment by darkoperator** [comment]
Im already doing the port my self and updating cmdlets you can see some changes in the last branch

**Comment by darkoperator** [comment]
Im moving SCP and SFTP to be item and no longer folder or file for commands, after that that the trusted key management class will be moved to use json files if a key as a param or force is not specified

**Comment by kleinsmk** [comment]
Are the assemblies for the .net ssh compiled for .net core ?  I can’t help with that in any capcity, but can work with the powershell side of things

**Comment by darkoperator** [comment]
The Renci.Shh has core and standard, planning on going standard. Will need help once I have the C# part that manages the keys to go and change the cmdlets that are in PS

**Comment by soul4soul** [comment]
I have been using Posh-SSH with PS7-preview-3 on Ubuntu 18.04 with success. I used the v3.0 branch. I applied the #247 but I'm not sure it matters much for my scenario since I'm using -Force. I ran into a [freezing bug](https://github.com/sshnet/SSH.NET/issues/355) from upstream SSH.NET. I applied the patch to `Asmodat Standard SSH.NET.dll` and recompiled.

I believe the full list of commands I have used is `New-SSHSession`, `Invoke-SSHCommand`, `Remove-SSHSession`, `Set-ScpItem`, and `Get-ScpItem`

**Comment by darkoperator** [comment]
With the patch there was no hangup?

**Comment by tmontney** [comment]
Under Debian Stretch, I get a _Microsoft.Win32.Registry Type Initialization Exception_. This is when calling  `New-SFTPSession`.

**Comment by darkoperator** [comment]
Expected since released module is a Windows Module

**Comment by tmontney** [comment]
You're saying _your_ release is a Windows module? Which one do you recommend me to use?

**Comment by darkoperator** [comment]
At the moment core support is on  dev branch waiting for the core ssh library to fix some major bugs

**Comment by darkoperator** [comment]
been trying all day to get this in alpha after forking the lib but no luck, stuck in 
```
New-SSHSession: Could not load file or assembly 'SshNet.Security.Cryptography, Version=1.3.0.0, Culture=neutral, PublicKeyToken=2fa9220ff3eadda4'. The system cannot find the file specified.
```

**Comment by jeffreymcclain** [comment]
I know this is an old issue, but I just wanted to chime in and say that this module is one of the primary reasons I haven't upgraded my scripts to run with PowerShell 7 yet. 

I totally understand that changing the underlying code and dependencies to support the latest PowerShell version is a ton of effort, so I'm happy to to see that you have continued working on this particular request. I'll simply keep using PowerShell 5.1 for now, thanks for all your hard work and I definitely look forward to this being implemented!

**Comment by darkoperator** [comment]
Most of the work is done, waiting on SSH.net library to release the next version.

**Comment by jeffreymcclain** [comment]
Awesome, glad to hear it's nearly complete 😃 Hopefully the library update is released soon, thanks again for you efforts!

**Comment by dreic** [comment]
@darkoperator do you have any ETA when will there be a version that runs on PS Core? Looks like this module is the only way to use SSH on AWS Lambda that's running .NET core 3.1

**Comment by darkoperator** [comment]
Not at the moment day job plus part time teacher for the kids in COVID times has left little time for side projects

**Comment by MMouse-23** [comment]
Hi,

Its very easy to run POSH-SSH in PS7 if you invoke back to PS5.
invoke is a lot better in 7.
And i havent tested all POSH SSH commands, but its running in 5 while i am executing from 7

**Comment by damienfinck** [comment]
Hi @MMouse-23
I am interested. Can you give us an example of how you did it?
Thank you

**Comment by MMouse-23** [comment]
> Hi @MMouse-23
> I am interested. Can you give us an example of how you did it?
> Thank you

Swap the 5 and 7 shells. Then invoke back to 5.
It works Ok ish, but not if you are already coming in through a remote shell. 
As it disconnects the already existing shell you are entering over.

So Microsoft.PowerShell session config has to point to Ps7
and PowerShell.7 session config is pointed back to 5.

That way from a default 7 session you can Invoke-Command -ComputerName localhost -ConfigurationName PowerShell.7
To get back to 5. 

This method breaks the Windows Feature installer....
https://stackoverflow.com/questions/58238481/powershell-remoting-controlling-what-edition-is-being-targeted-powershell-core
In the bottom

**Comment by majkinetor** [comment]
Since this is still open, is it considered done on pwsh (on both Windows and Linux) or not  @darkoperator ?

**Comment by darkoperator** [comment]
Its done, ticket can be closed
