### ISSUE TITLE
Support Putty and/or OpenSSH SSH agent (provided by git for windows)

### ISSUE THREAD

**Issue by jimmyharris** [darkoperator/Posh-SSH#131]
I know that the default version of SSH.NET does not have connection support for OpenSSH agent but it would be very convenient to provide support for either of these ssh agents when working with servers.

I know that winsshfs uses a modified version of the SSH.NET libraries that applies patches like this one: https://github.com/Foreveryone-cz/SSH.NET-for-winsshfs/commit/34719699c2d46d389df95080707c8622d9143e82 to support this kind of functionality. It would be very convenient if we did not need to specify a key file when creating a new SSH Session.  Agent Forwarding would also be convenient but that may be beyond the scope of the changes to SSH.NET provided by [ForEveryone-cz/SSH.NET-for-winsshfs](https://github.com/ForEveryone-cz/SSH.NET-for-winsshfs/). Any help here would be greatly appreciated.

**Comment by darkoperator** [comment]
Main problem with this is maintenance. I do not have the time and resources to maintain a fork of the library to support it.
