### ISSUE TITLE
Can't load assembly in 1.7.8 for New-SSHSession

### ISSUE THREAD

**Issue by missgt** [darkoperator/Posh-SSH#132]
Yesterday I thought I'd successfully tested a fix in 1.7.8 but have since found that I wasn't actually using the 1.7.8 code stream. Today when I went to test the code against 1.7.8 I get the following error when running New-SSHSession:

New-SSHSession : Could not load file or assembly 'Renci.SshNet, Version=2014.4.6.0, Culture=neutral, PublicKeyToken=1cee9f8bde3db106' or one of its
dependencies. The system cannot find the file specified.
At line:1 char:1
+ New-SSHSession -ComputerName computer
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SSHSession], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,SSH.NewSshSession

It works fine on the same machine if I revert back to 1.7.6.
Thanks,

**Comment by missgt** [comment]
Version 1.7.6 is using 2014.4.6-beta2 whereas version 1.7.8 is using 2016.1.0-beta1. If I replace the dll in 1.7.8 with the one from 1.7.6 the cmdlet works. Looks like something is referencing the old version.

**Comment by darkoperator** [comment]
What version of windows and ps?

**Comment by darkoperator** [comment]
Can you ensure the DLL is not blocked if downloaded via the brower and not via git, just right click on it, properties. Also ensure you have .Net 3.5 or better.

**Comment by darkoperator** [comment]
Recompiled the main module with new reference, download and try again. I believe that was the issue

**Comment by missgt** [comment]
The recompile has fixed the issue.
Many thanks.
