### ISSUE TITLE
New-SSHSession : Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by craigboey007** [darkoperator/Posh-SSH#133]
Hi,

I am trying to connect to a RHEL 7.1 server with a private key which has been confirmed working using a putty and a .ppk version of the key. I have converted the same key to an OpenSSH key using PuttyGen with no passphrase. The key is SSH-2RSA - 2048.
When i try to connect with powershell using Posh-SSH i am presented with the following error  "Exception has been thrown by the target of an invocation"

The following command was used

New-SSHSession -Computername $Computername -Acceptkey -KeyFile $keyfilePath -Port $Port -Credential $creds

The powershell host is Windows Server 2012 R2, powershell v4.0

Any help is greatly appreciated.

Regards,

**Comment by darkoperator** [comment]
Tried to replicate doing a clean install of CentOS 7 and created a key
```
login as: carlos
carlos@192.168.1.151's password:
[carlos@localhost ~]$ ssh-keygen -t rsa
Generating public/private rsa key pair.
Enter file in which to save the key (/home/carlos/.ssh/id_rsa):
Created directory '/home/carlos/.ssh'.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /home/carlos/.ssh/id_rsa.
Your public key has been saved in /home/carlos/.ssh/id_rsa.pub.
The key fingerprint is:
b3:3f:47:8d:35:66:83:2f:aa:fc:fc:d3:ee:a4:cb:0c carlos@localhost.localdomain
The key's randomart image is:
+--[ RSA 2048]----+
|                 |
|                 |
|             .   |
|            . *  |
|        S    B o |
|         o  + o  |
|        . Eo o.  |
|       . oo+oo.  |
|        oo++*=o  |
+-----------------+
[carlos@localhost ~]$ ssh-copy-id carlos@localhost
The authenticity of host 'localhost (::1)' can't be established.
ECDSA key fingerprint is 22:7a:5b:88:92:0c:9f:4c:bc:72:6c:23:21:e9:2d:20.
Are you sure you want to continue connecting (yes/no)? yes
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
carlos@localhost's password:
Permission denied, please try again.
carlos@localhost's password:

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh 'carlos@localhost'"
and check to make sure that only the key(s) you wanted were added.

[carlos@localhost ~]$
```

Then I copied the key to system with PS 4.0 and created a session where in credentials I did not gave a password since the key does not have a passphrase (/me cringes at the idea) 

```
PS C:\> New-SSHSession -ComputerName 192.168.1.151 -Credential carlos -KeyFile "C:\Users\carlos\priv.key" -Verbose
VERBOSE: Using SSH Key authentication for connection.
VERBOSE: Fingerprint for 192.168.1.151: 0:95:35:dc:72:d0:2:cd:74:f4:fb:ce:ce:9d:99:55
VERBOSE: Fingerprint matched trusted fingerprint for host 192.168.1.151

SessionId  Host                                                                                                                                 Connected
---------  ----                                                                                                                                 ---------
    0      192.168.1.151                                                                                                                           True


PS C:\>
```

I was able to create the session.

**Comment by darkoperator** [comment]
Still trying to replicate the issue.

**Comment by craigboey007** [comment]
Carlos, I think the issue maybe related to FIPS mode being activated on my windows server. Are you able to reproduce this by any chance ?

Regards

Craig

**Comment by darkoperator** [comment]
That will nuke most ciphers and algorithms in .Net if enabled on Windows. Makes the server less secure than secure

**Comment by darkoperator** [comment]
https://blogs.technet.microsoft.com/secguide/2014/04/07/why-were-not-recommending-fips-mode-anymore/

**Comment by darkoperator** [comment]
any update on this?

**Comment by cyberjamus** [comment]
Hello,

Thank you for your SSH project!

I confirm, I do have the same issue if FIPS is enabled.

Is there any way to work around the problem without disabling FIPS?

For now I just execute the following before starting a new Powershell session:
reg add "HKLM\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy" /v Enabled /t REG_DWORD /d 0 /f

And once done I just set the Reg value back to "1" enabling FIPS.
I assume this can suffice as a workaround for now...

Some Orgs have IT Policies that require FIPS to be enabled and I am sure they won't like users or local admins to meddle in their affairs, so any other non-invasive workaround would be welcome  :)

Thank you once more for all your work!

**Comment by rmbolger** [comment]
The problem with FIPS mode is an underlying .NET problem. I doubt there's anything @darkoperator can do about it per the link he posted.

**Comment by darkoperator** [comment]
Nothing I cam do. FIPS degrades the crypto security of a windows box by disabling the ciphers used.
