### ISSUE TITLE
New-SFTPSession - Unable to load Renci.SshNet

### ISSUE THREAD

**Issue by adgisticsit** [darkoperator/Posh-SSH#134]
Could not load file or assembly 'Renci.SshNet, Version=2014.4.6.0, Culture=neutral, PublicKeyToken=1cee9f8bde3db106' or one of its dependencies. The system cannot find the file specified.

I am using Posh-SSH to transfer files over SFTP. Running the script locally results in no errors.
Running the script as my logged in user on a remote server results in no errors. 
Running the script via Windows Scheduled Task as a user with Administrator permissions results in the error above.

**Comment by darkoperator** [comment]
Where is the module installed?

**Comment by darkoperator** [comment]
Also can you provide more info, version of windows, version of PS, from github or via install-module, was it installed with -allusers param if via install-module

**Comment by adgisticsit** [comment]
Windows Server 2012 R2
Powershell Version 4.0
Installed using: iex (New-Object Net.WebClient).DownloadString("https://gist.github.com/darkoperator/6152630/raw/c67de4f7cd780ba367cccbc2593f38d18ce6df89/instposhsshdev")

Moved module to: C:\Program Files\WindowsPowerShell\Modules\Posh-SSH

**Comment by darkoperator** [comment]
During the weekend there was a broken version in GitHub that was fixed yesterday with that same error. Could you redownload and test

**Comment by adgisticsit** [comment]
From what I can tell this is now working correctly using the new dll's I will monitor this evening when our tasks run but will close this as issue seems to be resolved.
