### ISSUE TITLE
You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by wleeb1010** [darkoperator/Posh-SSH#135]
I get the error above error every time I run the script below. Note that the write-debug shows the session is connected prior to throwing the error:

Import-Module SSH-Sessions
$DebugPreference = "Continue"
$networkobjects = Import-Csv "C:\tools\devices.csv"

ForEach ( $networkobject in $networkobjects ) {
$ipaddress = $networkobject.ipaddress
$username = $networkobject.username
$password = $networkobject.password

New-SSHSession -ComputerName $ipaddress -username $username -password $password 
$session = Get-SSHSession -ComputerName $ipaddress
write-debug $session.ComputerName
write-debug $session.Connected
$session.session.CreateShellStream("dumb", 0, 0, 0, 0, 1000)
$stream.Write("en`n")
$stream.Write("$password`n")
$stream.Write("terminal pager 0`n")
$stream.Write("show run`n")
$stream.Read() | Out-File "C:\tools\$ipaddress.txt"
Remove-SSHSession -RemoveAll 
}

Here are the applicable versions in use:

All Posh-SSH functions and cmdlets version: 1.7.8

PS> $PSVersionTable
Name                           Value                                                                                                                  
----                                 -----                                                                                                                  
PSVersion                       5.1.14393.693                                                                                                          
PSEdition                        Desktop                                                                                                                
PSCompatibleVersions   1.0, 2.0, 3.0, 4.0...}                                                                                                
BuildVersion                    10.0.14393.693                                                                                                         
CLRVersion                      4.0.30319.42000                                                                                                        
WSManStackVersion       3.0                                                                                                                    
PSRemotingProtocolVersion 2.3                                                                                                                    
SerializationVersion          1.1.0.1

**Comment by wleeb1010** [comment]
I forgot to include the entire error message:

You cannot call a method on a null-valued expression.
At line:19 char:1
+ $session.session.CreateShellStream("dumb", 0, 0, 0, 0, 1000)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by darkoperator** [comment]
have you tried using the function to create the stream? New-SSHShellStream int he function I use the API call  $stream = $ToProcess.Session.CreateShellStream($TerminalName, $Columns, $Rows, $Width, $Height, $BufferSize) interesting that you are giving it 0 for Colums, Rows and Width

**Comment by markwiater** [comment]
Is it possible that you haven't defined $stream?

Your example code has
 $session.session.CreateShellStream("dumb", 0, 0, 0, 0, 1000) 
where i would have expected to see
 $stream=$session.session.CreateShellStream("dumb", 0, 0, 0, 0, 1000)

**Comment by wleeb1010** [comment]
Correct, I missed it in a copy paste error. Thanks!
