### ISSUE TITLE
Posh-SSH over powershell 6.0.0 (current alpha.16) on Linux

### ISSUE THREAD

**Issue by JPBlanc** [darkoperator/Posh-SSH#137]
Not a bug, but just a question : 

Do you test your module on the top of PowerShell on Linux.

I'am trying to move some of my PowerShell scripts from Windows to Linux (keeping PowerShell).

**Comment by darkoperator** [comment]
No, the library I use does not run on .net core.

**Comment by JPBlanc** [comment]
Do you mean sshnet/SSH.NET ?

**Comment by darkoperator** [comment]
Correct, I would also have to compile the module for .Net Core, maintain 2 copies of it and add a way to tell under what env it is being loaded to load the proper assemblies and module. PS 6.0 is still an Alpha, no even a Beta, so it would be a lot of work for side project I only put a couple of hours in to a month.

**Comment by JPBlanc** [comment]
If sshnet/SSH.NET is brought to .Net core I will have a look to your code.

Thanks for your time, your library was very helpfull for me.

**Comment by darkoperator** [comment]
There is already work being done for .Net Core but, PowerShell 6.0 is alpha and should not be used in production. Once MS releases GA for it I will look at it.

**Comment by aslam28ansa** [comment]
Hi,
i am using powershell 6 and not able to connect to server.

gating error

Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembl
y 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
