### ISSUE TITLE
New-SSHSession : Value cannot be null

### ISSUE THREAD

**Issue by jwnickel** [darkoperator/Posh-SSH#138]
I'm trying to connect to a cisco ip phone but having difficulty.  I am able to connect and login with putty.

The code:
`Import-Module -Name Posh-SSH -Verbose

#Set Creds
$secpasswd = ConvertTo-SecureString PASSWORD" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential ("USERNAME", $secpasswd)

#Build SSH session
New-SSHSession -ComputerName "IPADDRESS" -Credential (Get-Credential $credential) -AcceptKey:$true -Verbose`

The results:
VERBOSE: Using SSH Username and Password authentication for connection.
New-SSHSession : Value cannot be null.
Parameter name: All lists are either null or empty.
At FILE_LOCATION\VoIP.ps1:23 char:15
+ New-SSHSession <<<<  -ComputerName "IPADDRESS" -Credential (Get-Credential $credential) -AcceptKey:$true -Verbose
    + CategoryInfo          : InvalidOperation: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], ArgumentNullException
    + FullyQualifiedErrorId : SSH.NewSshSession

Is there any thing I can do to debug this issue, or does anyone have any ideas that I can try?

**Comment by guzewski** [comment]
Have you made any progress on this? I'm having the same issue but the web resources on this subject look pretty sparse.

**Comment by darkoperator** [comment]
None, I do not own a Cisco IP phone to test sadly.

**Comment by jwnickel** [comment]
I had two issue and I have resolved them.  First, problem was this line:
$credential = New-Object System.Management.Automation.PSCredential ("USERNAME", $secpasswd)
The $credential, due to windows security I believe, will not store the $secpasswd that is retrieved from the PSCredential.  This cases only the username to be supplied to POSH.  I've hardcoded the password as a temporary fix until I find a better solution.

Secondly, I was having a mismatch between POSH and Renci.SshNet.dll.  It was a mismatch between 3.5 and 4.0 .Net framework.  

Hope this helps.

**Comment by jwnickel** [comment]
I haven't been able to work on it lately, but I'll try something at work tomorrow.  I'll let you know how it goes.

**Comment by darkoperator** [comment]
I do plan on killing support for PSv2 and that will male the module and library to .Net 4.0

**Comment by jwnickel** [comment]
Yeah, when I was modifying the code I ran into that.  I have a framework mismatch between POSH and SSH-Net.  After I matched them up, everything worked fine.

**Comment by jwnickel** [comment]
Nope, didn't work.  Here are the powershell scripts that worked for me.  I also had to match the 
framework, but I don't remember if that was an original error or one that I accidentally created.  So, if these don't work for you, I might need to send you the dll files.
[Uploading AccessDatabase-v1.txt…]()
[Uploading VoIP-SSH-v1.txt…]()

**Comment by jwnickel** [comment]
Nope, didn't work.  Here are the powershell scripts that worked for me.  I also had to match the 
framework, but I don't remember if that was an original error or one that I accidentally created.  So, if these don't work for you, I might need to send you the dll files.

**Comment by jwnickel** [comment]
Nope, didn't work.  Here are the powershell scripts that worked for me.  I also had to match the 
framework, but I don't remember if that was an original error or one that I accidentally created.  So, if these don't work for you, I might need to send you the dll files.

[Uploading VoIP-SSH-v1.txt…]()

**Comment by jwnickel** [comment]
Nope, didn't work. 
So here's my powershell script.
`
## SET PATH TO SCRIPT LOCATION
$invocation = (Get-Variable MyInvocation).Value
$path = Split-Path $invocation.MyCommand.Path
Set-Location -Path $path

## DATABASE SETTINGS
$Global:databasePath = $path + "\Cisco IP Phone Inventory Tool-v2.accdb"
$Global:AccessConnection = $null
$Global:adOpenStatic = 3
$Global:adLockOptimistic = 3
$Global:ipRecordset  = $null

## IMPORT REQUIRED EXTERNAL MODULES
import-module -name Posh-SSH -Verbose
import-module -name ".\AccessDatabase-v1.ps1" -verbose 

## CONNECT TO ACCESS DATABASE, UPDATE STATUS, THEN DISCONNECT
Connect-AccessDatabase($Global:databasePath) ## Open database connection

#Set the IP Address of the remote device
Get-AddressListing
if ($Global:ipRecordset.EOF -eq $false) {

    ## PROMPT USER FOR LOGIN CREDENTIALS
    $secpasswd = ConvertTo-SecureString "PASSWORD_HERE" -AsPlainText -Force
    $credential = New-Object System.Management.Automation.PSCredential (“USERNAME_HERE”, $secpasswd)
    
    do {
        ## GET THE IPADDRESS
        $ipaddress = $Global:ipRecordset.Fields.Item(“IP”).Value 
        
        ## BUILD SSH SESSION
        New-SSHSession -ComputerName $ipAddress -Credential (Get-Credential $credential) -ConnectionTimeout 15 -AcceptKey -Verbose
        Start-Sleep -Milliseconds 1000

        ## BUILD OPEN STREAM FOR CISCO IP PHONES
        $session = Get-SSHSession -SessionId 0
        $stream = $session.Session.CreateShellStream("dumb", 0, 0, 0, 0, 1000)
        Start-Sleep -Milliseconds 500

        ## Send commands to the cisco device and read the response
        $output = $stream.read()
        Start-Sleep -Milliseconds 500
        if ($output.Contains("login")) {
            ## LOGIN TO THE IP PHONE CONSOLE
            $stream.Write("debug`n")
            Start-Sleep -Milliseconds 500
            $output = $stream.read()
            Start-Sleep -Milliseconds 500

            if ($output.Contains("password")) {
                $stream.Write("debug`n")
                Start-Sleep -Milliseconds 500
                $output = $stream.read()
                Start-Sleep -Milliseconds 500

                if (!$output.Contains("denied")) {
                    $stream.Write("show inventory`n")
                    Start-Sleep -Milliseconds 500
                    $output = $stream.read()
                    Start-Sleep -Milliseconds 500
                    
                    if ($output.length -gt 12) {    
                        ## GET MAC ADDRESS
                        $x = $output.indexof(">") - 12
                        
                        if ($x -lt 0) {
                            $mac = $output.substring(0,12)
                        } else {
                            $mac = $output.substring($x,12)
                        } ## End If Statement
                                          
                        ## GET SERIAL NUMBER
                        $x = $output.indexof("SN: ") + 4
                        $outputSN = $output.remove(0,$x)
                        $sn = $outputSN.substring(0,11)
                        $sn = $sn.trim()
                        
                        ## GET PRODUCT IDENTIFICATION
                        $x = $output.indexof("PID: ") + 5
                        $pidOutput = $output.remove(0,$x)
                        $prodid = $pidOutput.substring(0,18)
                        $prodid = $prodid.trim()
                        
                        # UPDATE INVENTORY DATABASE
                        Update-Inventory($mac, $ipAddress, $sn, $prodid)
                    } else {
                        write-host "OUTPUT ISSUE:"
                        write-host $output
                    } ## End If Statement
                } else {
                    write-host "Console access denied"
                }# End If Statement
            } else {
                write-host "Console password not received"
            }# End If Statement
        } else {
            write-host "Console login not received"
        }# End If Statement
                
        ## CLOSE THE SSH SESSION
        Remove-SSHSession -SessionId 0
        write-host "SSH Session Closed"

        ## MOVE TO THE NEXT RECORD
        $Global:ipRecordset.MoveNext()
    } until ($Global:ipRecordset.EOF -eq $true)
} else {
    write-host "No IP addresses found in the database"
} ## End If Statement

## CLOSE DATABASE RECORDSETS AND CONNECTION
Close-AccessRecordSets
Disconnect-AccessDatabase
`

**Comment by jwnickel** [comment]
Here's the Access script if you need it.
`function Connect-AccessDatabase($dbFilePath) {
<#
.SYNOPSIS
    Establish connection to an access database for inventory tracking

.DESCRIPTION
    This code will establish the connection to an Access database which is used to track
    voip phones.
#>
    # Test to ensure valid path to database file was supplied
    if (-not (Test-Path $dbFilePath)) {
        Write-Error "Invalid Access database path specified. Please supply full absolute path to database file!"
    } ## End If statement
    
    # Create a new ADO DB connection COM object, which will give us useful methods & properties such as "Execute"!
    $Global:AccessConnection = New-Object -ComObject ADODB.Connection
  
    # Actually open the database so we can start working with its contents
    # Access 00-03 (MDB) format has a different connection string than 2007
    if ((Split-Path $dbFilePath -Leaf) -match [regex]"\.mdb$") {
        Write-Host "Access 2000-2003 format (MDB) detected!  Using Microsoft.Jet.OLEDB.4.0."
        $Global:AccessConnection.Open("Provider = Microsoft.Jet.OLEDB.4.0; Data Source= $dbFilePath")
    } ## End If statement

    # Here's the check for if 2007 connection is necessary
    if ((Split-Path $dbFilePath -Leaf) -match [regex]"\.accdb$") {
        Write-Host "Access 2007 format (ACCDB) detected!  Using Microsoft.Ace.OLEDB.12.0."
        $Global:AccessConnection.Open("Provider = Microsoft.Ace.OLEDB.12.0; Persist Security Info = False; Data Source = $dbFilePath")
    } ## End If statement
} ## End Connect-AccessDatabase Function

function Get-AddressListing() {
    $sql = "SELECT tblIPAddresses.IP FROM tblIPAddresses;"
    
    $Global:ipRecordset = New-Object -ComObject ADODB.Recordset
    $Global:ipRecordset.open($sql, $Global:AccessConnection)
} ## End Get-AddressListing Function

function Update-Inventory($paramters) {
    $tmp = $paramters -split " "
    $mac = $tmp[0]
    $ip = $tmp[1]
    $serial = $tmp[2]
    if ($serial.length -eq 0) {
        $serial = "No Serial Found"
    } ## End IF Statement
    $model = $tmp[3]
    
    $sql = "SELECT MsysInventoryListing.MACAddress FROM MsysInventoryListing 
        WHERE (((MsysInventoryListing.MACAddress)='$mac'));"

    $invRecordset = New-Object -ComObject ADODB.Recordset
    $invRecordset.open($sql, $Global:AccessConnection)
    if ($invRecordset.EOF) {
        $sql = "INSERT INTO MsysInventoryListing ( MACAddress, IPAddress, SerialNumber, Model, InventoryDate )
            VALUES ('$mac', '$ip', '$serial', '$model', Now());"
        Execute-AccessSQLStatement ($sql)
    } else {
        $sql = "UPDATE MsysInventoryListing SET MsysInventoryListing.IPAddress = '$ip', MsysInventoryListing.SerialNumber = '$serial', 
            MsysInventoryListing.Model = '$model', MsysInventoryListing.InventoryDate = Now()
            WHERE (((MsysInventoryListing.MACAddress)='$mac'));"
        Execute-AccessSQLStatement ($sql)
    } ## End If Statement
} ## End Update-Inventory Function

function Execute-AccessSQLStatement ($query) {
    $Global:AccessConnection.Execute($query)
} ## End Execute-AccessSQLStatement Function

function Close-AccessRecordSets {
    $Global:invRecordset.Close()
    $Global:ipRecordset.Close()
} ## End Close-AccessDatabaseRecordSet Function

function Disconnect-AccessDatabase {
    $Global:AccessConnection.Close()
} ## End Disconnect-AccessDatabase Function
`
