### ISSUE TITLE
Multiple-line command

### ISSUE THREAD

**Issue by tsafx** [darkoperator/Posh-SSH#139]
If send multiple string contains unrelated commands it works without problem.

> $command = '
> /system script remove [find]
> /ip ipsec peer remove [find]
>Invoke-SSHCommandStream -SessionId 0 -$command

But if send command from multiple lines it doesn't work.

> $command = '
> /system script remove [find]
> /system script add name=VPN source="
> \n:local checkPH1 do=\\\r\
> 	\n{\r\
> 	\n\t:foreach peer in=[/ip ipsec policy find sa-dst-address=\$SecondPoint] do=\\\r\
> 	\n\t{\r\
> 	\n\t\t:if ([/ip ipsec policy get \$peer disabled] = false) do=\\\r\
> 	\n\t\t{\r\
> 	\n\t\t\t/ip ipsec policy disable \$peer\r\
> 	\n\t\t\t:local net [[/ip ipsec policy get \$peer dst-address]]\r\
> 	\n\t\t\t:log info \"Disable IPSec policy \$SecondPoint - \$net\"\r\
> 	\n\t\t}\r\
> 	\n\t}\r\"
> 
>Invoke-SSHCommandStream -SessionId 0 -$command

Run only `/system script add name=VPN source="`, next lines send as a new command.

In a Putty it works. 
Can Posh-SSH do it?

**Comment by darkoperator** [comment]
You will need to write each command to the stream individually, wait for it to finish then run the next one. Sending all at once will write them to steam as one giant string.

**Comment by tsafx** [comment]
In plink it does not work either.
I found only one the solution to the problem: to upload a script on the router and run it locally.
