### ISSUE TITLE
New-SFTPSession proxy issue

### ISSUE THREAD

**Issue by chrischris2005** [darkoperator/Posh-SSH#140]
Hi there,

I get an error when using a proxyserver:

Script:
$url = "ftp.xxxx.xxxx.com"
$sFTPUser = "xxxx"
$sFTPPassword = "xxxxx"

$proxy = "proxy.xxx.xxx.xx" 
$proxyPort = 8088

$securesFTPPassword = ConvertTo-SecureString -String $sFTPPassword -AsPlainText -Force
$Credentials = New-Object System.Management.Automation.PSCredential ($sFTPUser, $securesFTPPassword)

$session = New-SFTPSession -ComputerName "xxx.xxx.xxx.xxx" -Credential $Credentials -AcceptKey -ProxyServer $proxy -ProxyPort $proxyPort

Error:
New-SFTPSession : Object reference not set to an instance of an object.
At C:\Users\xxxx\Documents\Untitled1.ps1:15 char:12
+ $session = New-SFTPSession -ComputerName "xxx.xxx.xxx.xxx" -Credential $Credenti ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SFTPSession], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,SSH.NewSftpSession

Any ideas?

Pls help. Thanx in advance.

Regards,
Chris

**Comment by darkoperator** [comment]
What type of Proxy server is it? (http, sock5 ..)

**Comment by chrischris2005** [comment]
Hi,

It is a HTTP proxy. Using the -ProxyType HTTP parameter did not help. Same error.

By the way, using the WinSCP client with the same config does work.

**Comment by chrischris2005** [comment]
Is there a ProxyUseDefaultCredential like parameter that I can try, like invoke-webrequest has? Maybe that will work.

**Comment by darkoperator** [comment]
No, if the proxy requieres auth you can pass those in a separate param. At the moment I’m moving so all my lab gear is in boxes so it will take a while for me to look in to the bug. Sorry.

**Comment by darkoperator** [comment]
Check branch proxy_fix to see if the fix I made there fixes your issue.

**Comment by glennpegden** [comment]
Excellent, I was just coming here to report that if you're not using ssh keys, it seems to only attempt the pass the username and password if a username isn't configured.

Nice work Carlos, it's very much appreciated!

**Comment by chrischris2005** [comment]
Yes it solved the issue. Thanx for your help!

**Comment by chrischris2005** [comment]
When I give proxy credential by:

Script:
$url = "ftp.xxxx.xxxx.com"
$sFTPUser = "xxxx"
$sFTPPassword = "xxxxx"

$proxy = "proxy.xxx.xxx.xx"
$proxyPort = 8088
$proxycredential = Get-Credential

$securesFTPPassword = ConvertTo-SecureString -String $sFTPPassword -AsPlainText -Force
$Credentials = New-Object System.Management.Automation.PSCredential ($sFTPUser, $securesFTPPassword)

$session = New-SFTPSession -ComputerName "xxx.xxx.xxx.xxx" -Credential $Credentials -AcceptKey -ProxyServer $proxy -ProxyPort $proxyPort -ProxyCredential $proxycredential

I get the following error:

New-SFTPSession : String reference not set to an instance of a String.
Parameter name: s
At C:\Users\xxxxx\Documents\Untitled2.ps1:17 char:12
+ $session = New-SFTPSession -ComputerName "xxx.xxx.xxx.xxx" -Credential $Credenti ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Renci.SshNet.SftpClient:SftpClient) [New-SFTPSession], ArgumentNullException
    + FullyQualifiedErrorId : SSH.NewSftpSession

**Comment by chrischris2005** [comment]
Any chance you will add a ProxyUseDefaultCredentials parameter? For some reason our proxy server does not accept credentials via the ProxyCredential parameter. Same deal with for example invoke-webrequest cmdlet. Using the ProxyUseDefaultCredentials parameter thens does work.

**Comment by darkoperator** [comment]
Not at this moment. What auth method does your proxy use? The library I use is limited to only some and does not do NTLM

**Comment by chrischris2005** [comment]
NTLM, Kerberos

**Comment by darkoperator** [comment]
Sadly neither is supported for proxy in the library

**Comment by darkoperator** [comment]
closing issue until library used (Renci.SSH supports this)
