### ISSUE TITLE
New-SshSession missing in 1.7.x

### ISSUE THREAD

**Issue by Ben-Conrad** [darkoperator/Posh-SSH#141]
This is similar to issue #95.   Posh-SSH was updated from 1.6.x to 1.7.5  (anything in the 1.7.x does not work) and we noticed that New-SshSession is not available.

This is a problem on Windows 7, Windows 2008 R2 and Windows 2012 R2.  All running PowerShell 4.0.

Is there a fix for this?

Ben

**Comment by darkoperator** [comment]
Did you installed it from the PSGallery?

**Comment by Ben-Conrad** [comment]
I used psget to get it from the gallery and then copied the module directory to a unc path \\server\share\modules\posh-ssh.  

Here is the before and after showing the missing cmdlet in the first screenshot, I ended up switching all installations of posh-ssh to be local 

![image](https://cloud.githubusercontent.com/assets/11560403/24458475/06412c6e-1467-11e7-8891-50b498db7d0a.png)

![image](https://cloud.githubusercontent.com/assets/11560403/24458496/170cb4aa-1467-11e7-9bca-2099a4cad856.png)

**Comment by darkoperator** [comment]
You should specify the folder not the psm1, the manifest loads and checks for a lot of stuff not in the psm1
