### ISSUE TITLE
WARNING: You are running an outdated version of the module

### ISSUE THREAD

**Issue by zussmc** [darkoperator/Posh-SSH#143]
Hi, I'm running version 1.7.7, I'm unable to perform the upgrade to version 1.7.8.
Please help me to perform upgrade to 1.7.8 or how to completely remove the old version and install the latest version.

Thank you

**Comment by darkoperator** [comment]
how did you installed the module originally?

**Comment by zussmc** [comment]
Hi, i have installed it with:
iex (New-Object Net.WebClient).DownloadString("https://gist.github.com/darkoperator/6152630/raw/c67de4f7cd780ba367cccbc2593f38d18ce6df89/instposhsshdev")

**Comment by darkoperator** [comment]
just delete the module from $($env:USERPROFILE)\Documents\WindowsPowerShell\Modules and install again

**Comment by zussmc** [comment]
Hi,
tried that and i'm getting these errors:
. : The term 'C:\Program Files\WindowsPowerShell\Modules\posh-ssh\1.7.7\Trust.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\posh-ssh\1.7.7\Posh-SSH.psm1:17 char:3
+ . "$PSScriptRoot\Trust.ps1"
+   ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...1.7.7\Trust.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
. : The term 'C:\Program Files\WindowsPowerShell\Modules\posh-ssh\1.7.7\Sftp.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\posh-ssh\1.7.7\Posh-SSH.psm1:18 char:3
+ . "$PSScriptRoot\Sftp.ps1"
+   ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...\1.7.7\Sftp.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


 C:\> Get-PoshSSHModVersion
WARNING: You are running an outdated version of the module.

InstalledVersion CurrentVersion
---------------- --------------
1.7.7            1.7.8

**Comment by darkoperator** [comment]
Strange the method you used for installing does not places the module in C:\Program Files\WindowsPowerShell\Modules\ for a user. My recommendation would be to delete the module form that location and re-install using PowerShell Gallery. Next major release will drop support for PSv2 and the method for install will be via the gallery.

**Comment by zussmc** [comment]
Here is what i did, i deleted the module from C:\Program Files\WindowsPowerShell\Modules\ and tried to install, but i did get this error:
 C:\> iex (New-Object Net.WebClient).DownloadString("https://gist.github.com/darkoperator/6152630/raw/c67de4f7cd780ba367cccbc2593f38d18ce6df89/instposhsshdev")
Downloading latest version of Posh-SSH from https://github.com/darkoperator/Posh-SSH/archive/master.zip
File saved to C:\Users\<myuser>\AppData\Local\Temp\Posh-SSH.zip
Uncompressing the Zip file to C:\Users\<myuser>\Documents\WindowsPowerShell\Modules
Renaming folder
Module has been installed
Import-Module : The specified module 'posh-ssh' was not loaded because no valid module file was found in any module directory.At line:17 char:1
+ Import-Module -Name posh-ssh
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (posh-ssh:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

so i copied the module from C:\Users\<myuser>\Documents\WindowsPowerShell\Modules to 
C:\Program Files\WindowsPowerShell\Modules

and issued: Import-Module -Name posh-ssh

now i'm runing version 1.7.8
 C:\> Get-PoshSSHModVersion

InstalledVersion CurrentVersion
---------------- --------------
1.7.8            1.7.8       

Hope this helps.

Thank you for your prompt help.
