### ISSUE TITLE
Set-SFTPContent without -Append behaviour

### ISSUE THREAD

**Issue by MVKozlov** [darkoperator/Posh-SSH#148]
`Set-SFTPContent` without `-Append` switch replaces content unusual way
It not set total file length to new content length

```
PS C:\> Set-SFTPContent -SFTPSession $sftp -Path '/tmp/config' -Value "LONG_DATA_TEXT=1`n" -Encoding ASCII
PS C:\> Set-SFTPContent -SFTPSession $sftp -Path '/tmp/config' -Value "DATA_=2`n" -Encoding ASCII
PS C:\> Get-SFTPContent -SFTPSession $sftp -Path '/tmp/config' -Encoding ASCII
DATA_=2
A_TEXT=1
```
my suggestion: Add `-Truncate` or "opposite way" switch depending on what should be the default
current behaviour also can be desirable, so switch can help

**Comment by MVKozlov** [comment]
btw, `Set-SFTPContent` should have an option to write `UTFxx` content without BOM

**Comment by darkoperator** [comment]
What is BOM?

Sent from Mail for Windows 10

**Comment by MVKozlov** [comment]
Byte order mark
https://en.wikipedia.org/wiki/Byte_order_mark :)

**Comment by darkoperator** [comment]
It will depend on what the library allows. The default behavior will not change but not problem adding switches to modify it. Right now the library I use is going through some changes in this part from what I see in their issue tracker.

**Comment by MVKozlov** [comment]
in addition, seems the library have no `session.AppendAllBytes()`
and you silently do not support `-Append` switch with `bytes[]` ValueType ?
``` c#
                        if ($Append)
                        {
                            $session.session.WriteAllBytes($Path, $Value)
                        }
                        else
                        {
                            $session.session.WriteAllBytes($Path, $Value)
                        }
```
May be we should create issue about it ?

**Comment by darkoperator** [comment]
They are going with System.IO compatibility, at the moment they are doing a full refactor of that code. Since System.IO does not have it for bytes I doubt they will add it and recommend to use stream writter instead. I will control the parameters with ParametrSet

**Comment by darkoperator** [comment]
New version of the module pushed. The BOM issue should be resolved. Re-Open if problem persists
