### ISSUE TITLE
Cannot write to the registry key.

### ISSUE THREAD

**Issue by al-heisner** [darkoperator/Posh-SSH#15]
After initial installation, when trying to list or add to trusted hosts, I received errors "Cannot write to the registry key." or "You cannot call a method on a null-valued expression.". This appears to be caused by the non-existence of HKCU/Software/PoshSSH key.

This seemed to fix it, you may want to add it to the module before the OpenSubKey('Software\PoshSSH', $true) calls:

New-Item -Path HKCU:\Software -Name PoshSSH –Force

**Comment by al-heisner** [comment]
Oops, -Force would remove existing keys. 

$Test_Path_Result = Test-Path -Path "hkcu:\Software\PoshSSH"
if ($Test_Path_Result -eq $false) {New-Item -Path HKCU:\Software -Name PoshSSH}

**Comment by darkoperator** [comment]
Thanks will make the fix tomorrow on the next release. Just look for the branch release_04, I plan on doing testing from now until release early next week of the new re-written version of the module.

**Comment by darkoperator** [comment]
Please test release 1.7 pushed out today.

**Comment by al-heisner** [comment]
I got this during install, looks like there's a "." where a "," should be
in Trust.ps1 on line 62

Missing ')' in method call.
At
C:\Users\aheisner\Documents\WindowsPowerShell\Modules\posh-ssh\Trust.ps1:62
char:81
+         $softkey =
[Microsoft.Win32.Registry]::CurrentUser.OpenSubKey('Softwa
re' <<<< . $true)
    + CategoryInfo          : ParserError: (CloseParenToken:TokenId) [],
Parse
   Exception
    + FullyQualifiedErrorId : MissingEndParenthesisInMethodCall

**Comment by darkoperator** [comment]
Just pushed the cchange to git to change that can you download and re-test

**Comment by al-heisner** [comment]
It's working now. Installed without error, and Get-SSHTrustedHost now adds
registry key if it does not exist. I also tested adding a host key via
New-SSHTrustedHost and that also worked as expected, adding the key when
necessary.
