### ISSUE TITLE
install in offline environment

### ISSUE THREAD

**Issue by daurrutia** [darkoperator/Posh-SSH#150]
Import-module or is there another way?

**Comment by BornToBeRoot** [comment]
Download the latest Release
Copy the folder Posh-SSH to C:\Users\%username%\Documents\WindowsPowerShell\Modules\
Open up a PowerShell as an admin and set the execution policy: Set-ExecutionPolicy RemoteSigned
Import the Module with the command Import-Module Posh-SSH (Maybe add this command to your PowerShell profile)

**Comment by rmbolger** [comment]
Part of the problem with doing that is that the latest release package on GitHub is only 1.7.5 rather than the 1.7.8 referenced in the master branch.

**Comment by darkoperator** [comment]
Will update the release. This will be the last PSv2.0 compatible release. Next version will meed to be installed in PSv5 using install-module command

**Comment by rmbolger** [comment]
Technically PowerShellGet (the module that contains Install-Module) is available for PSv3 and PSv4. There's a link on the http://www.powershellgallery.com/ site.

**Comment by darkoperator** [comment]
Yep, the module will be compiled for .net 4.0 so it will work in all of those. Just not 2.0

**Comment by darkoperator** [comment]
1.7.8 . Release added to github

**Comment by daurrutia** [comment]
Main reason for asking is for install in offline environments, without psget/install-module capability. 
I was able to do so by manually mimicking the steps I found here: https://gist.github.com/darkoperator/6152630 after reading the recommended install method here: http://www.powershellmagazine.com/2014/07/03/posh-ssh-open-source-ssh-powershell-module/

**Comment by darkoperator** [comment]
Only way is downloading the latest release and by hand placing in the module path. Other thing would be building a MSI :\
