### ISSUE TITLE
Invoke-SSHCommand how to wait for its return?

### ISSUE THREAD

**Issue by simonfangyingzhang** [darkoperator/Posh-SSH#151]
Hi Guru,

thanks for Posh-SSH, it is great!

I am using Invoke-SSHCommand to issue kinds of commands to my host, these commands usually running for a long time (days maybe) but once failed they will return at once, so I want Invoke-SSHCommand help to do the below:
1) keep waiting when running well
2) finish and return once failed

I tried using -timeout, but loos like it did not do 2)? how should I do? thank you

**Comment by darkoperator** [comment]
Best option would be a SSHStream and read from it in a loop until result instead of Invoke-SSHCommand

**Comment by simonfangyingzhang** [comment]
you are right, I should use SSHStream, thanks a lot

**Comment by simonfangyingzhang** [comment]
Hi Guru,

could Invoke-SSHCommand add one option such as -wait waiting for this kind of tasks to return? 

using SSHStream looks like not simple
