### ISSUE TITLE
Is there any way to get the similar output and exit code from SSHShellStream just like what we get from Invoke-SSHCommand

### ISSUE THREAD

**Issue by shubhamgupta514** [darkoperator/Posh-SSH#154]
Hi,

It would be helpful if you give me some suggestions for that.

Thanks

**Comment by MVKozlov** [comment]
`/usr/bin/program; echo $?`
and analyze output

**Comment by shubhamgupta514** [comment]
Thanks MVKozlov for the reply. 
But the challenge for me is that analyzing part because when I read the shell stream it includes user prompt as well as the last executed command and then the actual output comes into picture. 

The challenge is I am writing a generalize powershell script for different linux flavours and to analyze such kind of output is very difficult  for me. 

I want to know how are you analyzing the same in invoke-sshcommand cmdlet or suggest me some logic for this kind of situation. 

Thanks in Advance

**Comment by darkoperator** [comment]
Try something like this 
https://gist.github.com/darkoperator/93fc457ca1c2de14c3a62a55d98020eb

**Comment by darkoperator** [comment]
did the Gist helped you solve the issue?

**Comment by shubhamgupta514** [comment]
The gist you shared is quite helpful and i have one modification to it in the very starting when shell stream creates, I use to export PS1="" as my first command which removes the user prompt in the output and now I need only blank lines. 

Thanks for your suggestion

**Comment by shubhamgupta514** [comment]
*now I need to ignore only blank lines in the final output.
