### ISSUE TITLE
how to convert output from invoke-sshcommand to table?

### ISSUE THREAD

**Issue by simonfangyingzhang** [darkoperator/Posh-SSH#155]
Hi Guru,

using invoke-sshcommand I was issuing such as lsblk to linux, the output looks like the below, it has multi ple lines of string, I think converting it to table, so foreach I can use like $_.NAME, but I did not figure out how to? please help me, many thanks

NAME                      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sr0                        11:0    1 1024M  0 rom
sda                         8:0    0   24G  0 disk
├─sda1                      8:1    0  500M  0 part /boot
└─sda2                      8:2    0 23.5G  0 part
  ├─sys_vg-root (dm-0)    253:0    0   10G  0 lvm  /
  ├─sys_vg-swap (dm-1)    253:1    0    4G  0 lvm  [SWAP]
  ├─sys_vg-tmp (dm-3)     253:3    0    4G  0 lvm
  └─sys_vg-var_log (dm-4) 253:4    0    4G  0 lvm  /var/log
sdc                         8:32   0   60G  0 disk
└─data-data (dm-2)        253:2    0  100G  0 lvm  /tmp
sdb                         8:16   0   40G  0 disk
└─sdb1                      8:17   0   40G  0 part
  └─data-data (dm-2)      253:2    0  100G  0 lvm  /tmp

**Comment by darkoperator** [comment]
No clue there, Linux does not generate objects but text

**Comment by simonfangyingzhang** [comment]
thank you, looks like no existing cmdlet in powershell help to parse it?

**Comment by MVKozlov** [comment]
there is a `ConvertFrom-String` but it too hard to use. better to write your own (bi)cycle :-)

**Comment by simonfangyingzhang** [comment]
thanks for the remind :); I wrote the below script kind of working now,

###

$outputs = (Invoke-SSHCommand -SSHSession $s -Command lsblk).output

$outputcount = ($outputs|Measure-Object).count

$indexs = foreach ($index in 0..(($outputs|foreach {$_.length}|sort|select -First 1)-1)){
	if(!($outputs|foreach {$_[$index]}|where {$_ -ne " "})){
		$index
	}
}

$indexcount = ($indexs|Measure-Object).count

$namevalues = 
foreach ($output in $outputs) {
	foreach ($i in (0..$indexcount)){
		if ($i -eq 0){$output.substring(0,$indexs[0])}
		elseif ($i -eq $indexcount) {$output.substring($indexs[$i-1])}
		else {$output.substring($indexs[$i-1],$indexs[$i]-$indexs[$i-1])}
	}
}

$namevalues = 
foreach($namevalue in $namevalues) {
	if (0..($namevalue.length -1)|where{$namevalue[$_] -ne " "}|foreach{$_}) {$namevalue -replace " "}
	else {$namevalue[0]}
}

$results = @()

1..($outputcount-1)|foreach {
	$result = New-Object System.Object
	$start = $_*($indexcount+1)
	0..$indexcount|foreach {		
		$result| Add-Member -type NoteProperty -name $namevalues[$_] -value $namevalues[$start+$_]
	}
	$results += $result
}

$results

###
