### ISSUE TITLE
GetAndRemove-SFTPFile 

### ISSUE THREAD

**Issue by KonradDa** [darkoperator/Posh-SSH#156]
Hi Darkoperator, Hi Internet

I’m not 100% shure if it’s the right place to posting it, so if it is wrong, please ignore it :-).

I have a small script witch does logon to some ssh-servers, list a directory there, download all files from the directory and then delete the files from the ssh-server. 

A couple days ago, we moved the script to another server (with windows Server 2012 R2) and something bad has happened. Through a bug/error/mistake/ ever  in the Task Scheduler “new” Unified Background Process Manager (UBPM) environment variables are not 100% loaded to the PowerShell (https://support.microsoft.com/en-us/help/3133689/ubpm-doesn-t-set-environmental-variables-correctly-when-you-run-schedu) witch run’s in the Task Scheduler with a user how is not logged in on the server the script failed with the folling conditions:

Files not downloaded from remote ssh-server and file deleted from remote server. Witch was a ugly Situation. 

Okay now are more way’s to ensure that this situation never happened again. 
My Approach was to compare Remote and Local files and then start the remove (only if they marched), I did this in PowerShell, it worked very well, and it was easy to implant. 

But I guess in a perfect world the “Get-SCPFile” should have an Parameter like compareAfterDownload and will then return a value or so. What do you think ?

PS: I’f darkoperator or some other expirenced devloper finde the idee fine, i will try to imeplent it Posh-SSH if that is okay.
Kind Regards 
KD

**Comment by darkoperator** [comment]
With SCP it would not be possible, probably with SFTP, will add it to my backlog to take a look. 


From: KonradDa
Sent: Monday, July 10, 2017 12:47 PM
To: darkoperator/Posh-SSH
Cc: Subscribed
Subject: [darkoperator/Posh-SSH] GetAndRemove-SFTPFile (#156)

Hi Darkoperator, Hi Internet
I’m not 100% shure if it’s the right place to posting it, so if it is wrong, please ignore it :-).
I have a small script witch does logon to some ssh-servers, list a directory there, download all files from the directory and then delete the files from the ssh-server.
A couple days ago, we moved the script to another server (with windows Server 2012 R2) and something bad has happened. Through a bug/error/mistake/ ever in the Task Scheduler “new” Unified Background Process Manager (UBPM) environment variables are not 100% loaded to the PowerShell (https://support.microsoft.com/en-us/help/3133689/ubpm-doesn-t-set-environmental-variables-correctly-when-you-run-schedu) witch run’s in the Task Scheduler with a user how is not logged in on the server the script failed with the folling conditions:
Files not downloaded from remote ssh-server and file deleted from remote server. Witch was a ugly Situation.
Okay now are more way’s to ensure that this situation never happened again.
My Approach was to compare Remote and Local files and then start the remove (only if they marched), I did this in PowerShell, it worked very well, and it was easy to implant.
But I guess in a perfect world the “Get-SCPFile” should have an Parameter like compareAfterDownload and will then return a value or so. What do you think ?
PS: I’f darkoperator or some other expirenced devloper finde the idee fine, i will try to imeplent it Posh-SSH if that is okay.
Kind Regards
KD

**Comment by darkoperator** [comment]
Remove the ErrorAction to SilentlyContinue. You are telling the command with that to not raise an error, no error then nothing is catched

PS C:\Users\Carlos> try {Get-SFTPFile -SessionId 0 -RemoteFile "/home/carlos/.bashrc1" -LocalPath ./bashrc1} catch { write-host "catched"}
Catched


PS C:\Users\Carlos> Get-SFTPFile -SessionId 0 -RemoteFile "/home/carlos/.bashrc1" -LocalPath ./bashrc1
Get-SFTPFile : Cannot find path 'C:\Users\Carlos\bashrc1' because it does not exist.
At line:1 char:1
+ Get-SFTPFile -SessionId 0 -RemoteFile "/home/carlos/.bashrc1" -LocalP ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Carlos\bashrc1:String) [Get-SFTPFile], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,SSH.GetSftpFile

**Comment by Liturgist** [comment]
Carlos,

Thank your for your message. I removed the -ErrorAction and it fails in the
same way.

My $ErrorActionPreference is 'Continue'.

**Comment by darkoperator** [comment]
Again you are telling it to not have a terminating error and continue. Erroraction should be Stop or none specified to the try/catch statement to catch it

**Comment by Liturgist** [comment]
Carlos,

Perhaps I have it. Because Get-SFTPFile does not produce a terminating
error when the file is not found, I do need to use -ErrorAction Stop in
order to catch it.

Thanks for your guidance to this solution.
