### ISSUE TITLE
how to catch return from start-job using sshsession?

### ISSUE THREAD

**Issue by simonfangyingzhang** [darkoperator/Posh-SSH#158]
Hi Guru,

I am using start-job to format all disks in linux vm, 

each job completed successfully, but unable to catch return from each job, do you know how I should do it? many thanks

PowerShell C:\>                             $jobs =
>>                                 foreach ($freedisk in $freedisks) {
>>                                     start-job -scriptblock {
>>                         param([SSH.SshSession]$Session, $freedisk)
>>                                         invoke-sshcommand -sshsession $Session -cmd "yes|mkfs.ext4 /dev/$freedisk"
>>                                     } -argumentlist $Session, $freedisk
>>
>>                                 }
PowerShell C:\>
PowerShell C:\>                             $results =
>>                                 foreach ($job in $jobs) {
>>                                     $job|Receive-Job -Wait
>>                                 }
Unable to find type [SSH.SshSession].
    + CategoryInfo          : InvalidOperation: (SSH.SshSession:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
    + PSComputerName        : localhost

Unable to find type [SSH.SshSession].
    + CategoryInfo          : InvalidOperation: (SSH.SshSession:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
    + PSComputerName        : localhost

Unable to find type [SSH.SshSession].
    + CategoryInfo          : InvalidOperation: (SSH.SshSession:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
    + PSComputerName        : localhost

Unable to find type [SSH.SshSession].
    + CategoryInfo          : InvalidOperation: (SSH.SshSession:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
    + PSComputerName        : localhost

Unable to find type [SSH.SshSession].
    + CategoryInfo          : InvalidOperation: (SSH.SshSession:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
    + PSComputerName        : localhost

PowerShell C:\>

**Comment by darkoperator** [comment]
Each job is its own PS instance you will need to create the session inside the job itself.

**Comment by simonfangyingzhang** [comment]
thanks, I see
