### ISSUE TITLE
Posh-SSH fingerprint

### ISSUE THREAD

**Issue by shrv** [darkoperator/Posh-SSH#16]
Good afternoon.
Use your module for Posh script. Script works with Cisco switches, helping helpdesk to connect to printers floors without reference to our department.

Prompt how to implement the adoption of auto signature key from the switch(box with the inscription I fingeprint Y or N)?

Thanks in advance.

**Comment by darkoperator** [comment]
There is an option to auto-accept the key on new-sshsession cmdlet is it not working?

**Comment by shrv** [comment]
my question is just this, how?
I have a connection to the Cisco made the following code:
New-SSHSession -ComputerName $selected_router -Credential($Cred) | Out-Null
          $session = Get-SSHSession -Index 0
          $stream = $session.Session.CreateShellStream("dumb",0,0,0,0,1000)
          $stream.Write("conf t")
          $stream.Write("int $port_router_int`n")
          $stream.Write("switchport access vlan $selected_vlan`n")
          $stream.Write("switchport mode access`n")
          $stream.Write("ip arp inspection limit rate 150`n")
          $stream.Write("spanning-tree portfast`n")
          $stream.Write("exit`n")
          $stream.Write("exit`n")
          $stream.Write("wr mem`n")
          Remove-SSHSession -RemoveAll

after the first line, and a window appears with the text key fingerprint and accept the request or not ... So it is necessary to have the script automatically say yes

**Comment by darkoperator** [comment]
New-SSHSession -ComputerName $selected_router -Credential($Cred)  -AcceptKey $true

:) just needed to do Get-Help New-SSHSession

**Comment by shrv** [comment]
New-SSHSession -ComputerName "11.11.11.11" -Credential ($cred) -AcceptKey $true
Correctly understood you?

**Comment by shrv** [comment]
:)   Get-help used, but without your tips are not realized.
Thank you so much.

**Comment by darkoperator** [comment]
yep 

PS C:\Users\Carlos Perez> help New-SSHSession -parameter acceptkey

-AcceptKey [<Boolean>]
    Automatically accepts a new SSH fingerprint for a host

    Required?                    false
    Position?                    named
    Default value                False
    Accept pipeline input?       true (ByPropertyName)
    Accept wildcard characters?  false
