### ISSUE TITLE
Set-SFTPFile Encoding

### ISSUE THREAD

**Issue by ThiloL** [darkoperator/Posh-SSH#162]
It seems, that Set-SFTPFile do not use the correct encoding. I have UTF-8 Files without BOM. After copying to the server, it seems that they have a BOM.

**Comment by darkoperator** [comment]
Will open an issue with the project of the library I'm using, in the upload of a file there is no parameter that allows me to control this.

**Comment by darkoperator** [comment]
Here is the issue in the main project https://github.com/sshnet/SSH.NET/issues/274

**Comment by darkoperator** [comment]
Can you provide more info like what is the target (OS and Version of SSH) also what version of the module you are using? I'm not able to replicate against OpenSSH on Linux and FreeBSD

I ran 

```powershell
Set-SFTPFile -SessionId 0 -RemotePath /tmp -LocalFile .\Desktop\testnobom.txt
```
When I check I do not see a BOM
```
 hexdump -n 3 -C testnobom.txt
00000000  74 65 73                                          |tes|
00000003
```

**Comment by ThiloL** [comment]
I'm on holidays. Give me 3 weeks.

**Comment by MVKozlov** [comment]
I get similar behavior with `Set-SFTPContent -UTF8` as I'm already mentioned in #148
on VMWare ESXi (5.5, 6.0). Sorry can't give more info until tomorrow, I'll test `Set-SFTPFile` on these systems

**Comment by darkoperator** [comment]
@MVKozlov I think I found a fix for it when using UTF8 specifically for Set-SFTPContent

**Comment by MVKozlov** [comment]
Yes, this fixed problem with Set-SFTPContent, thanks

and I cannot confirm `Set-SFTPFile` adding BOM on ESXi

**Comment by darkoperator** [comment]
The issue should be fixed with the latest release. Reopen if the issue persists.
