### ISSUE TITLE
Install Error with folder redirection.

### ISSUE THREAD

**Issue by rayholtz** [darkoperator/Posh-SSH#164]
My company has folder redirection configured for our Documents folders.  When I ran the iex..... install command, the 'import-module -Name posh-ssh' failed with: 

```
Import-Module : The specified module 'posh-ssh' was not loaded because no valid module file was found in any module
directory.
At line:17 char:1
+ Import-Module -Name posh-ssh
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (posh-ssh:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

My theory is because the iex saves then uncompressed the .zip file to  "C:\Users\<username>\Documents\WindowsPowerShell\Modules", but Powershell is looking to my real Modules  folder at "\\server\share\username\My Documents\WindowsPowerShell\Modules" so the 'import-module' command fails.

Could the iex install command be updated to look at more of an environment variable (ex: $env:HOMESHARE) then the 'Documents\WindowsPowerShell\Modules' path?

**Comment by rayholtz** [comment]
Ah, I think I found it.  In the installation file:

(https://gist.githubusercontent.com/darkoperator/6152630/raw/c67de4f7cd780ba367cccbc2593f38d18ce6df89/instposhsshdev ) 

the 7th line:

`$targetondisk = "$($env:USERPROFILE)\Documents\WindowsPowerShell\Modules"`

might be able to be updated to use `$env:HomeDrive$env:HomePath` instead of `$env:USERPROFILE`.

I'm not too familier on how to make these changes for consideration in Github myself, so I wanted to do this to suggest to DarkOperator.

Thanks for this module! It's great!

**Comment by darkoperator** [comment]
Actually the next version that will be out soon will drop PSv2 support and installs will be simpler since it will use the Install-Module cmdlet to install directly from the PSGallery

**Comment by rayholtz** [comment]
That works too!  Thanks!
