### ISSUE TITLE
Get-SCPFile Error "Access to the path is denied" where path is a current folder

### ISSUE THREAD

**Issue by tftm** [darkoperator/Posh-SSH#165]
Hello!
Get-SCPFile return error "Access to the path is denied", where path is a current folder.
For example when I run the command:
C:\Windows\System32> Get-SCPFile -LocalFile C:\Folder\test.txt -RemoteFile "/tmp/test.txt" -ComputerName a.b.c.d -Credential (Get-Credential $cred)

PS return error
"Access to the path is denied "C:\Windows\System32"

If I run from
C:\Users\Admin> Get-SCPFile -LocalFile C:\Folder\test.txt -RemoteFile "/tmp/test.txt" -ComputerName a.b.c.d -Credential (Get-Credential $cred)

return "Access to the path is denied "C:\Users\Admin"
and so on...
Operations Set-SCPFile && Get-SCPFolder with same paramters is working.

PS version: 4.0
Posh-SSH version: 2.0.1

**Comment by tftm** [comment]
p.s. Run scripts from Win 2012R2 Stanard

**Comment by darkoperator** [comment]
just committed a fix for it that will be in the next release

**Comment by darkoperator** [comment]
Just pushed version 2.0.2, the issue should be addressed. Reopen if the issue persists.
