### ISSUE TITLE
Set-SFTPContent passing weird characters

### ISSUE THREAD

**Issue by james30522** [darkoperator/Posh-SSH#166]
When I am using Set-SFTPContent to add contents to a file it looks fine before it gets to the correct location. This is what I see windows side when I test with Set-Content to a test text file.
Field-1,Field-2,Field-3,Field-4,Field-5,Field-6,Field-7,Field-8,Field-9,Field-10,Field-11,Field-12,Field-13,Field-14,Field-15,Field-16,Field-17,Field-18,Field-19,Field-20,Field-21,Field-22

When I use Set-SFTPContent and check on the UNIX box the information looks like this:
ï»¿Field-1,Field-2,Field-3,Field-4,Field-5,Field-6,Field-7,Field-8,Field-9,Field-10,Field-11,Field-12,Field-13,Field-14,Field-15,Field-16,Field-17,Field-18,Field-19,Field-20,Field-21,Field-22

Not sure why or how these strange characters at the beginning ("ï»¿") are coming from. Any help would be appreciated!

**Comment by darkoperator** [comment]
It is adding BOM to the file in the next release there will be a fix for this #162

**Comment by james30522** [comment]
Thank you for the quick response! 
I am not sure that this is causing the issues we are seeing because only one of the Fields are affected. But wanted to rule that out anyways. 

Is there any ETA for the next version?

**Comment by darkoperator** [comment]
No ETA at the moment

**Comment by james30522** [comment]
I was able to resolve the issue I was having by setting the encoding to ASCII. Thank you for the help.

**Comment by darkoperator** [comment]
Version 2.0.2 was pushed and should fix this issue. Reopen if it persists
