### ISSUE TITLE
Set-SCPFile performance

### ISSUE THREAD

**Issue by MathiasMagnus** [darkoperator/Posh-SSH#17]
I am using Set-SCPFile to copy file to an Ubuntu Server machine over Ethernet, and the script performs at around 5.5 Mb/s, while scp.exe does at around 55 Mb/s. How can there be a 10X performance hit to using Set-SCPFile?

The progress bar that Set-SCPFile uses updates an awful lot. I did not check source code to see if this is the limitation or not, but I believe it would be more useful to see human readable sizes, such as KB, MB, GB, etc when applicable, instead of the insanely fast byte counter.

**Comment by darkoperator** [comment]
This will be addressed in version 1.7 released next week

**Comment by darkoperator** [comment]
For a list of changes and fixes you can look in the change log for version 1.7 in the development ranch for the version https://github.com/darkoperator/Posh-SSH/blob/Release_0.4/Readme.md <https://github.com/darkoperator/Posh-SSH/blob/Release_0.4/Readme.md>

**Comment by darkoperator** [comment]
Please test release 1.7 pushed out today.

**Comment by MathiasMagnus** [comment]
Tested copying a ~200MB file to an Ubuntu Server 14.04 installed in Hyper-V locally:

Posh-SSH v1.6: 310 sec
OpenSSH: 30 sec
Posh-SSH v1.7: 15 sec

Performance is excellent. The progress bar is very choppy now, but that is a cosmetic issue only. Thank you for the fix.

**Comment by darkoperator** [comment]
The reason for the choppiness is that it hold the download/upload when I update the screen, slowing down the process o I know only update eery 10% or so. It is a trade off. I will close the issue as resolved.
