### ISSUE TITLE
Invoke command only gets output

### ISSUE THREAD

**Issue by chantisnake** [darkoperator/Posh-SSH#170]
there is no place for error?

**Comment by darkoperator** [comment]
You should be getting back an object that includes the error and output should be a property 

https://github.com/darkoperator/Posh-SSH/blob/master/Posh-SSH.psm1#L269


From: chantisnake
Sent: Thursday, August 31, 2017 12:33 PM
To: darkoperator/Posh-SSH
Cc: Subscribed
Subject: [darkoperator/Posh-SSH] Invoke command only gets output (#170)

there is no place for error?

**Comment by chantisnake** [comment]
Oh! I see that now, but the error is not printed on the screen:
![capture](https://user-images.githubusercontent.com/10100995/29996194-dc2b545e-8fc7-11e7-9ee1-34cb8e6fcdb5.PNG)

If I look into error it will give me the error, but when I just glancing the object, it is not printed out

**Comment by darkoperator** [comment]
That is due to formatting but if you look at the return object property you should see it. Just pipe it to format-list -property * to show all

**Comment by darkoperator** [comment]
Closing issue. if further info needed please reopen the issue.
