### ISSUE TITLE
Get-SCPFile is using _keyfile instead of _localfile for path to local download file

### ISSUE THREAD

**Issue by soul4soul** [darkoperator/Posh-SSH#175]
In file GetScpFile line 529 replace:
```
                        ProviderInfo provider;
                        var pathinfo = GetResolvedProviderPathFromPSPath(_keyfile, out provider);
                        var localfullPath = pathinfo[0];
```

with:
```
                        var localfullPath = GetUnresolvedProviderPathFromPSPath(_localfile);
```

1. Replaced _keyfile with _localfile
2. Replaced GetResolvedProviderPathFromPSPath with GetUnresolvedProviderPathFromPSPath. It is frustrating to have to make an empty file so the path can be resolved before calling the Get-SCPFile command. Using GetUnresolvedProviderPathFromPSPath removes such requirement.

**Comment by KyronSr** [comment]
Glad you raised this -- this just bit me, luckily I had my private key file backed up somewhere else!

**Comment by darkoperator** [comment]
Did it destroyed your private key?

**Comment by KyronSr** [comment]
Yup, overwrote the key.  One solution to keep that is to make sure they are read only but luckily I had it backup up.

**Comment by darkoperator** [comment]
Ok will try to push a fixed version today

**Comment by darkoperator** [comment]
looks like I have the fix on the 2.0.2 branch, will do a new build and push it out soon

**Comment by darkoperator** [comment]
taking a bit of time because I had to be evacuated out of PR and could not bring my lab with me so working from a single laptop, building a couple of small VMs to test.

**Comment by darkoperator** [comment]
Just pushed a fixed version to the gallery. update and re-open the ticket if the problem persists.
