### ISSUE TITLE
New-SSHSession  fails with String Reference Error.

### ISSUE THREAD

**Issue by willspe** [darkoperator/Posh-SSH#176]
I am new to this Module and have been looking into using it. This is the call to the New SSHSession: 
"$sSession = New-SSHSession -ComputerName $sHost -ea Stop -Credential $cRemoteCredentials -AcceptKey"

However, I am getting the following Error:
"String reference not set to an instance of a String"
"Parameter name: s" 

This device is a network switch, however I do not know which kind or specific OS type.   This fails only on a few devices and from what I assume there must be some kind of exception that is thrown and not handled properly, causing this unexpected error.   There is no reference to "s" in my code and I can inspect before then after the call to tell that the call declares the variable.  Any and all ideas are appreciated. 

The New-SSHSession cmdlet works on all UNIX and most switches I have tested.  

Kind regards,
Peter

**Comment by willspe** [comment]
It was determined that the credentials were in error.  So this misleading error returned, is the result of a wrong credential.   Odd that this error is detected that way.

Kind regards,
Peter

**Comment by darkoperator** [comment]
yep it is a werid one, cant find S as a variable in my code, must be in the library I use. Will keep an eye open for it but for the time being closing the ticket.
