### ISSUE TITLE
-ShellStream .read() differences with RHEL6 and RHEL7

### ISSUE THREAD

**Issue by Mallkrawler** [darkoperator/Posh-SSH#177]
When reading the commands from a RHEL7 box within a ShellStream it outputs in a weird format\encoding.  The same command on a RHEL6 outputs properly.  
When using Invoke-SSHCommand with RHEL7 the same command will work. However I need to use the ShellStream because I need to run the command as root and root does not have ssh access. 

rhel7 output - NOTICE the extra characters around "active"
PS C:\WINDOWS\system32> $SSHStream.WriteLine("grep active /etc/audisp/plugins.d/syslog.conf")
PS C:\WINDOWS\system32> $SSHstream.read()
grep active /etc/audisp/plugins.d/syslog.conf
[01;31m[Kactive[m[K = no
[root@localhost ~]# 

rhel6 output
PS C:\WINDOWS\system32> $SSHStream.WriteLine("grep active /etc/audisp/plugins.d/syslog.conf")
PS C:\WINDOWS\system32> $SSHstream.read()
grep active /etc/audisp/plugins.d/syslog.conf
active = no
[root@localhost ~]# 

Adding to the weirdness:
Exporting the command to a text file then reading the file works. (Really don't want to use this option)
$SSHStream.WriteLine("grep active /etc/audisp/plugins.d/syslog.conf > test.txt")
PS C:\WINDOWS\system32> $SSHStream.WriteLine("cat test.txt")
PS C:\WINDOWS\system32> $SSHstream.read()
cat test.txt
cat: test.txt: No such file or directory
[root@localhost ~]#

**Comment by MVKozlov** [comment]
?
https://superuser.com/questions/543105/how-do-i-disable-terminal-control-escape-sequences-in-linux

**Comment by Mallkrawler** [comment]
interesting article. I made the change and it did not fix the issue.  I still think it has to do with how the ShellStream is writing and reading commands.  Since I don't see the same results with a regular invoke.

**Comment by darkoperator** [comment]
More than likely colored text. You need to disable color in the terminal

**Comment by Mallkrawler** [comment]
How would I disable color withing a posh shell stream?  I tried "ls --color=none"

**Comment by MikeMM70** [comment]
Try adding  -TerminalName 'dumb' on your New-SSHShellStream statement.
Documentation on it isn't extensive, but I think that sets the terminal
type on the remote shell session (TERM=dumb).  Please correct me if I'm
wrong!

**Comment by Mallkrawler** [comment]
Thank you very much MikeMM70.  That little change fixed all my issues!!!  I knew it had to be something 'dumb' I was missing ;) :D

Thanks to MVKozlov & darkoperator as well!
