### ISSUE TITLE
Error New-SSHSession

### ISSUE THREAD

**Issue by PSfreak** [darkoperator/Posh-SSH#191]
When i try to use New-SSHSession
With the command New-SSHSession 10.xxx.xxx.xxx (Get-Credential user) i got the error 
+ CategoryInfo          : InvalidOperation: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], TargetInvocationE
ception
+ FullyQualifiedErrorId : SSH.NewSshSession

I am using it to connect to a Ubuntu 16.04 SSH

**Comment by darkoperator** [comment]
Make sure the server is not using elliptical curve keys only RSA or DSA

**Comment by nSilberg** [comment]
I have tried on several Win2012R2 with same result as OP. These servers does not have internet connection so I installed POSH-SSH manually with Import-Module $path
I have tried to connect to several different devices like HPE iLO, HPE OA, Cisco UCS Manager..
I am unsure about what keytype my devices use.
I also tried on a Win2016 with internet and have no issues at all.

**Comment by darkoperator** [comment]
if you try another SSH client like PuTTY are you are you able to connect?

**Comment by nSilberg** [comment]
yes it works with Putty/Plink

**Comment by darkoperator** [comment]
what does it say on the device logs when a connection is attempted against it?

**Comment by nSilberg** [comment]
Nothing. None of the devices log an attempt to logon.

**Comment by darkoperator** [comment]
That is weird, just did a clean install and tested on CentOS and Ubuntu without any problem. By doing an install by hand did you unblocked the zip?

**Comment by darkoperator** [comment]
Can you try with Verbose so as to see how it is negotiating the connection and if it gets the server key?

```

PS C:\Users\Carlos> New-SSHSession -Verbose -ComputerName 192.168.1.10 -Credential (get-credential)

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
VERBOSE: Using SSH Username and Password authentication for connection.
VERBOSE: Fingerprint for 192.168.1.10: b3:69:48:4:c7:47:e7:2a:a9:3e:45:df:a7:4a:79:4a
VERBOSE: Fingerprint matched trusted fingerprint for host 192.168.1.10

SessionId  Host                                                                                  Connected
---------  ----                                                                                  ---------
    0      192.168.1.10                                                                              True
```

**Comment by nSilberg** [comment]
Yes the Zip was unblocked.

New-SSHSession -ComputerName hostname -Credential Get-Credential -verbose

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
VERBOSE: Using SSH Username and Password authentication for connection.
New-SSHSession : Exception has been thrown by the target of an invocation.
At line:2 char:1
+ New-SSHSession -ComputerName hostname -Credential $cred -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], TargetInvocationException
    + FullyQualifiedErrorId : SSH.NewSshSession

**Comment by darkoperator** [comment]
you need to put Get-Credential between parenthesis :)

New-SSHSession -ComputerName hostname -Credential (Get-Credential) -verbose

The specific error there is that Get-Credential is not running first to get the creds you need. With Parenthesis we make sure it runs first and the resulting object is passed to the parameter.

**Comment by nSilberg** [comment]
Didnt make any difference with parenthesis.. actually I used saved credentials in prior tests: $cred=Get-Credential. Also this exact cmd line was tested with success on another server where I installed using NuGet.

```
New-SSHSession -ComputerName hostname -Credential (Get-Credential) -verbose

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
VERBOSE: Using SSH Username and Password authentication for connection.
New-SSHSession : Exception has been thrown by the target of an invocation.
At line:1 char:1
+ New-SSHSession -ComputerName hostname-Credential (Get-Credentia ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], TargetInvocationException
    + FullyQualifiedErrorId : SSH.NewSshSession
```

**Comment by darkoperator** [comment]
Really no clue on my side. Installed a Win2k12 R2 server, downloaded a clone from master, unblocked the zip, decompressed it and  moved the inner folder to desktop, imported and connected to my test FreeBSD server with no issues. 
```
SystemDirectory : C:\Windows\system32
Organization    :
BuildNumber     : 9600
RegisteredUser  : Windows User
SerialNumber    : 00252-10000-00000-AA228
Version         : 6.3.9600



PS C:\Users\Administrator> Import-Module .\Desktop\Posh-SSH -verbose
VERBOSE: Loading module from path 'C:\Users\Administrator\Desktop\Posh-SSH\Posh-SSH.psd1'.
VERBOSE: Loading 'Assembly' from path
'C:\Users\Administrator\Desktop\Posh-SSH\Assembly\Renci.SshNet.dll'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\Users\Administrator\Desktop\Posh-SSH\Format\SSHSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\Users\Administrator\Desktop\Posh-SSH\Format\SFTPSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\Users\Administrator\Desktop\Posh-SSH\Format\Renci.SshNet.SshCommand.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\Users\Administrator\Desktop\Posh-SSH\Format\Renci.SshNet.Sftp.SftpFile.Format.ps1xml'.
VERBOSE: Loading module from path 'C:\Users\Administrator\Desktop\Posh-SSH\PoshSSH.dll'.
VERBOSE: Importing cmdlet 'Get-SCPFile'.
VERBOSE: Importing cmdlet 'Get-SCPFolder'.
VERBOSE: Importing cmdlet 'Get-SFTPFile'.
VERBOSE: Importing cmdlet 'Set-SFTPFile'.
VERBOSE: Importing cmdlet 'New-SFTPSession'.
VERBOSE: Importing cmdlet 'New-SSHSession'.
VERBOSE: Importing cmdlet 'Set-SCPFile'.
VERBOSE: Importing cmdlet 'Set-SCPFolder'.
VERBOSE: Loading module from path 'C:\Users\Administrator\Desktop\Posh-SSH\Posh-SSH.psm1'.
VERBOSE: Exporting function 'Get-SSHTrustedHost'.
VERBOSE: Exporting function 'New-SSHTrustedHost'.
VERBOSE: Exporting function 'Remove-SSHTrustedHost'.
VERBOSE: Exporting function 'Get-SFTPSession'.
VERBOSE: Exporting function 'Remove-SFTPSession'.
VERBOSE: Exporting function 'Get-SFTPChildItem'.
VERBOSE: Exporting function 'Test-SFTPPath'.
VERBOSE: Exporting function 'Remove-SFTPItem'.
VERBOSE: Exporting function 'Set-SFTPLocation'.
VERBOSE: Exporting function 'Get-SFTPLocation'.
VERBOSE: Exporting function 'Rename-SFTPFile'.
VERBOSE: Exporting function 'Get-SFTPPathAttribute'.
VERBOSE: Exporting function 'Set-SFTPPathAttribute'.
VERBOSE: Exporting function 'New-SFTPSymlink'.
VERBOSE: Exporting function 'Get-SFTPContent'.
VERBOSE: Exporting function 'Set-SFTPContent'.
VERBOSE: Exporting function 'New-SFTPFileStream'.
VERBOSE: Exporting function 'New-SFTPItem'.
VERBOSE: Exporting function 'New-SSHLocalPortForward'.
VERBOSE: Exporting function 'New-SSHRemotePortForward'.
VERBOSE: Exporting function 'New-SSHDynamicPortForward'.
VERBOSE: Exporting function 'Get-SSHPortForward'.
VERBOSE: Exporting function 'Stop-SSHPortForward'.
VERBOSE: Exporting function 'Start-SSHPortForward'.
VERBOSE: Exporting function 'Get-SSHSession'.
VERBOSE: Exporting function 'Remove-SSHSession'.
VERBOSE: Exporting function 'Invoke-SSHCommand'.
VERBOSE: Exporting function 'Get-PoshSSHModVersion'.
VERBOSE: Exporting function 'Invoke-SSHCommandStream'.
VERBOSE: Exporting function 'New-SSHShellStream'.
VERBOSE: Exporting function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Exporting function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Importing function 'Get-PoshSSHModVersion'.
VERBOSE: Importing function 'Get-SFTPChildItem'.
VERBOSE: Importing function 'Get-SFTPContent'.
VERBOSE: Importing function 'Get-SFTPLocation'.
VERBOSE: Importing function 'Get-SFTPPathAttribute'.
VERBOSE: Importing function 'Get-SFTPSession'.
VERBOSE: Importing function 'Get-SSHPortForward'.
VERBOSE: Importing function 'Get-SSHSession'.
VERBOSE: Importing function 'Get-SSHTrustedHost'.
VERBOSE: Importing function 'Invoke-SSHCommand'.
VERBOSE: Importing function 'Invoke-SSHCommandStream'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Importing function 'New-SFTPFileStream'.
VERBOSE: Importing function 'New-SFTPItem'.
VERBOSE: Importing function 'New-SFTPSymlink'.
VERBOSE: Importing function 'New-SSHDynamicPortForward'.
VERBOSE: Importing function 'New-SSHLocalPortForward'.
VERBOSE: Importing function 'New-SSHRemotePortForward'.
VERBOSE: Importing function 'New-SSHShellStream'.
VERBOSE: Importing function 'New-SSHTrustedHost'.
VERBOSE: Importing function 'Remove-SFTPItem'.
VERBOSE: Importing function 'Remove-SFTPSession'.
VERBOSE: Importing function 'Remove-SSHSession'.
VERBOSE: Importing function 'Remove-SSHTrustedHost'.
VERBOSE: Importing function 'Rename-SFTPFile'.
VERBOSE: Importing function 'Set-SFTPContent'.
VERBOSE: Importing function 'Set-SFTPLocation'.
VERBOSE: Importing function 'Set-SFTPPathAttribute'.
VERBOSE: Importing function 'Start-SSHPortForward'.
VERBOSE: Importing function 'Stop-SSHPortForward'.
VERBOSE: Importing function 'Test-SFTPPath'.
VERBOSE: Exporting function 'Get-PoshSSHModVersion'.
VERBOSE: Exporting function 'Get-SFTPChildItem'.
VERBOSE: Exporting function 'Get-SFTPContent'.
VERBOSE: Exporting function 'Get-SFTPLocation'.
VERBOSE: Exporting function 'Get-SFTPPathAttribute'.
VERBOSE: Exporting function 'Get-SFTPSession'.
VERBOSE: Exporting function 'Get-SSHPortForward'.
VERBOSE: Exporting function 'Get-SSHSession'.
VERBOSE: Exporting function 'Get-SSHTrustedHost'.
VERBOSE: Exporting function 'Invoke-SSHCommand'.
VERBOSE: Exporting function 'Invoke-SSHCommandStream'.
VERBOSE: Exporting function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Exporting function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Exporting function 'New-SFTPFileStream'.
VERBOSE: Exporting function 'New-SFTPItem'.
VERBOSE: Exporting function 'New-SFTPSymlink'.
VERBOSE: Exporting function 'New-SSHDynamicPortForward'.
VERBOSE: Exporting function 'New-SSHLocalPortForward'.
VERBOSE: Exporting function 'New-SSHRemotePortForward'.
VERBOSE: Exporting function 'New-SSHShellStream'.
VERBOSE: Exporting function 'New-SSHTrustedHost'.
VERBOSE: Exporting function 'Remove-SFTPItem'.
VERBOSE: Exporting function 'Remove-SFTPSession'.
VERBOSE: Exporting function 'Remove-SSHSession'.
VERBOSE: Exporting function 'Remove-SSHTrustedHost'.
VERBOSE: Exporting function 'Rename-SFTPFile'.
VERBOSE: Exporting function 'Set-SFTPContent'.
VERBOSE: Exporting function 'Set-SFTPLocation'.
VERBOSE: Exporting function 'Set-SFTPPathAttribute'.
VERBOSE: Exporting function 'Start-SSHPortForward'.
VERBOSE: Exporting function 'Stop-SSHPortForward'.
VERBOSE: Exporting function 'Test-SFTPPath'.
VERBOSE: Exporting cmdlet 'Get-SCPFile'.
VERBOSE: Exporting cmdlet 'Get-SCPFolder'.
VERBOSE: Exporting cmdlet 'Get-SFTPFile'.
VERBOSE: Exporting cmdlet 'Set-SFTPFile'.
VERBOSE: Exporting cmdlet 'New-SFTPSession'.
VERBOSE: Exporting cmdlet 'New-SSHSession'.
VERBOSE: Exporting cmdlet 'Set-SCPFile'.
VERBOSE: Exporting cmdlet 'Set-SCPFolder'.
VERBOSE: Importing cmdlet 'Get-SCPFile'.
VERBOSE: Importing cmdlet 'Get-SCPFolder'.
VERBOSE: Importing cmdlet 'Get-SFTPFile'.
VERBOSE: Importing cmdlet 'New-SFTPSession'.
VERBOSE: Importing cmdlet 'New-SSHSession'.
VERBOSE: Importing cmdlet 'Set-SCPFile'.
VERBOSE: Importing cmdlet 'Set-SCPFolder'.
VERBOSE: Importing cmdlet 'Set-SFTPFile'.
VERBOSE: Importing function 'Get-PoshSSHModVersion'.
VERBOSE: Importing function 'Get-SFTPChildItem'.
VERBOSE: Importing function 'Get-SFTPContent'.
VERBOSE: Importing function 'Get-SFTPLocation'.
VERBOSE: Importing function 'Get-SFTPPathAttribute'.
VERBOSE: Importing function 'Get-SFTPSession'.
VERBOSE: Importing function 'Get-SSHPortForward'.
VERBOSE: Importing function 'Get-SSHSession'.
VERBOSE: Importing function 'Get-SSHTrustedHost'.
VERBOSE: Importing function 'Invoke-SSHCommand'.
VERBOSE: Importing function 'Invoke-SSHCommandStream'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Importing function 'New-SFTPFileStream'.
VERBOSE: Importing function 'New-SFTPItem'.
VERBOSE: Importing function 'New-SFTPSymlink'.
VERBOSE: Importing function 'New-SSHDynamicPortForward'.
VERBOSE: Importing function 'New-SSHLocalPortForward'.
VERBOSE: Importing function 'New-SSHRemotePortForward'.
VERBOSE: Importing function 'New-SSHShellStream'.
VERBOSE: Importing function 'New-SSHTrustedHost'.
VERBOSE: Importing function 'Remove-SFTPItem'.
VERBOSE: Importing function 'Remove-SFTPSession'.
VERBOSE: Importing function 'Remove-SSHSession'.
VERBOSE: Importing function 'Remove-SSHTrustedHost'.
VERBOSE: Importing function 'Rename-SFTPFile'.
VERBOSE: Importing function 'Set-SFTPContent'.
VERBOSE: Importing function 'Set-SFTPLocation'.
VERBOSE: Importing function 'Set-SFTPPathAttribute'.
VERBOSE: Importing function 'Start-SSHPortForward'.
VERBOSE: Importing function 'Stop-SSHPortForward'.
VERBOSE: Importing function 'Test-SFTPPath'.
PS C:\Users\Administrator> New-SSHSession -ComputerName 192.168.1.10 -Credential (Get-Credential)

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential

Server SSH Fingerprint
Do you want to trust the fingerprint b3:69:48:4:c7:47:e7:2a:a9:3e:45:df:a7:4a:79:4a
[] Y  [] N  [?] Help (default is "N"): y

SessionId  Host                                                      Connected
---------  ----                                                      ---------
    0      192.168.1.10                                                 True

```

**Comment by nSilberg** [comment]
Well I believe it is a problem on the 2012R2 servers I use. I have just tried on an old server with Win2008R2 and from here it works fine, same network. I will just work from this 2008R2 server until I get the others reinstalled with 2016.
Thanks for your support. Its a great module that i am happy to have found :)

**Comment by jooshil** [comment]
Getting below error while connecting the ssh , all the whole this version was working 


New-SSHSession : Permission denied (keyboard-interactive).
At line:1 char:1
+ New-SSHSession -Computername xxxxxx  -Creden ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], SshAuthenticationException
    + FullyQualifiedErrorId : SSH.NewSshSession

**Comment by darkoperator** [comment]
You are getting a permission. Denied from the server, did you checked the target log as to see the reason it denied the connection?

**Comment by jooshil** [comment]
It's actually enabled  I am able to do a normal ssh using the putty
But not authenticate from the power shell

**Comment by darkoperator** [comment]
Was there anything on the target logs? Permission denied is a mesaage from the server need to figure why it sent it

**Comment by darkoperator** [comment]
Also what is the target? What version of PS and the module you are running

**Comment by CollinChaffin** [comment]
Even in latest build cannot create new connection WIN7x64 terminates with:

```
New-SSHSession : Could not load file or assembly 'Renci.SshNet, Version=2016.1.0.0, Culture=neutral,
PublicKeyToken=1cee9f8bde3db106' or one of its dependencies. The system cannot find the file specified.
At line:1 char:8
+ $ssh = New-SSHSession -ComputerName SERVER01 -Credential $(Get-Crede ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SSHSession], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,SSH.NewSshSession
```

Despite all assemblies listed in the manifest being properly installed in the module directory as shown here:

![clover_ibb9ewmum4](https://user-images.githubusercontent.com/9301483/62976168-9c5ad300-bde1-11e9-9e9a-48805d66c513.png)
![clover_ha40td6mE9](https://user-images.githubusercontent.com/9301483/62976183-a2e94a80-bde1-11e9-97e4-d19ac9d30184.png)

**Comment by darkoperator** [comment]
Hmm did you use install-module or downloaded it from Github releases?

**Comment by CollinChaffin** [comment]
From PSGallery (you can see it's PSGetModuleInfo.xml in the screenshot above).  I even forced a reinstall/update error persists.

**Comment by CollinChaffin** [comment]
I believe the issue is in the GAC and after this is upgraded, if the wrong version of the Renci is in the GAC the error occurs.  Ensuring the GAC is updated to the same version of the Renci did finally resolve the issue for me.

**Comment by darkoperator** [comment]
How did you achieved this?

**Comment by CollinChaffin** [comment]
I actually just released/published a small module (psNGENposh) to the PSGallery that performs the required NGEN generations/updates that I have always used internally.  I've been asked enough I figured I'd just release it.

1. Start Powershell, loading your profile, import this (and any other modules if not profile-loaded) and run:

```
Import-Module psNGENposh

Invoke-NGENposh
```

if need be (or wanted) you can force it to install/update all loaded assemblies using the `-Force` and if you REALLY want you can run it system-wide (will be far beyond your loaded POSH assemblies) using the `-All` but read warning first as it takes much time for the ALL and rewrites entire cache which can bloat incremental/diff backups etc.

**Comment by CollinChaffin** [comment]
Note @darkoperator it's not typically something to worry about however in this case, like many I have other modules that also load Renci SSH and even a couple apps and my GAC had simply not been updated.  Forcing the update I could watch the cache for that assembly updated/reinstalled into the GAC and merely forced it.  Again, not something I would think your module should even have to worry about. :)

Hope it helps!

**Comment by BasvanH** [comment]
I solved it by manually adding the assembly once.
```Add-Type -Path "$modulePath\Posh-SSH\2.2\Assembly\Renci.SshNet.dll"```

**Comment by darkoperator** [comment]
please test https://www.powershellgallery.com/packages/Posh-SSH/2.3.0-Beta1

**Comment by deeptha1992** [comment]
> Getting below error while connecting the ssh , (But I am able to connect by giving the credentials as user input)
> 
> New-SSHSession : Permission denied (keyboard-interactive). At line:1 char:1
> 
> * New-SSHSession -Computername xxxxxx  -Creden ...
> * ```
>     + CategoryInfo          : SecurityError: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], SshAuthenticationException
>     + FullyQualifiedErrorId : SSH.NewSshSession
>   ```

**Comment by darkoperator** [comment]
Can you provide more info? What OS, version of module, how are you calling the command, against what are you running it

**Comment by deeptha1992** [comment]
It is windows server 2019 Datacenter.
Module Posh-SSH version 3.0.8

$PSVersionTable

Name                           Value                                                                                             
----                           -----                                                                                             
PSVersion                      5.1.17763.3770                                                                                    
PSEdition                      Desktop                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                           
BuildVersion                   10.0.17763.3770                                                                                   
CLRVersion                     4.0.30319.42000                                                                                   
WSManStackVersion              3.0                                                                                               
PSRemotingProtocolVersion      2.3                                                                                               
SerializationVersion           1.1.0.1 


I am trying to connect a Linux OS cluster node which is in Cohesity helios cluster.

I am able to connect the node like this , so it will prompt for user input. I can give the credentials then.
New-SSHSession -Verbose -ComputerName $nodeIP

VERBOSE: Using SSH Username and Password authentication for connection.
VERBOSE: ecdsa-sha2-nistp256 Fingerprint for 10.133.140.91: a2:ee:6:ca:8b:49:ab:b8:9a:6e:2:5d:3a:33:49:36
VERBOSE: Fingerprint matched trusted ecdsa-sha2-nistp256 fingerprint for host 10.xxx.xxx.xx

SessionId  Host                                                           Connected                                              
---------  ----                                                           ---------                                              
    1      10.xxx.xxx.xx                                                    True   


The below script giving me an access denied(password) error

$username="Uname"
$password="Testpassword" | ConvertTo-SecureString -AsPlainText -Force
$Credentials = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $username, $password
New-SSHSession -Verbose -ComputerName $nodeIP -Credential $Credentials

your valuable suggestions will be helpful.
Thank you.

**Comment by deeptha1992** [comment]
It's resolved. Actually my password contains $ symbol. So I put the PWD in single quote.

Thanks for the support
