### ISSUE TITLE
New-SSHSession : String reference not set to an instance of a String

### ISSUE THREAD

**Issue by eduardogt72** [darkoperator/Posh-SSH#203]
Hello good afternoon, I'm relatively new with the use of this module, however I have some equipment working with POSH SSH. Lately I am working with a proxy server, which has connection to several computers, but I have not achieved connection, I get the following error

New-SSHSession: String reference not set to an instance of a String.
Parameter name: s

Any idea what that parameter means?

**Comment by darkoperator** [comment]
Is it a socks or HTTP proxy?

**Comment by eduardogt72** [comment]
Hello, good morning, it's an SSH server, which uses port 8022 for user input, and uses ports 22 to the computers. So from Powershell I'm trying to connect through port 8022, it's the only thing different from the scripts I've done previously. I am also checking the server side if there is any parameter that is not allowing the connection Since making the manual connection from PuTTY does not give me any problem.

**Comment by darkoperator** [comment]
Looks like a problem with my code trying to figure out where

**Comment by eduardogt72** [comment]
Hello, we have solved the problem, apparently the welcome message to the server, caused problems, we use a user profile that does not give the welcome messages and it worked.

**Comment by darkoperator** [comment]
Uhmm it should not crash the session thanks for the info it will help me in trying to replicate the issue

**Comment by keithga** [comment]
Another cause of this error may be when the remote system has more than one kind of prompt. 
Like for example:
```
Password:
You are required to change your password immediately (root enforced)
Changing password for tanadmin.
(current) UNIX password:
```
Since posh-ssh only supports one kind of Authentication Prompt others (like this example) will fail.

**Comment by asztymelski** [comment]
Any progress on that guys? I have the same issue on my CentOS.
Thanks in advance

**Comment by dokki767** [comment]
I've seen this when there's multiple password prompts.  i.e. normal password then a multi-factor auth passcode prompt

**Comment by darkoperator** [comment]
Sadly this not something the library I’m using supports
