### ISSUE TITLE
SSHShellStream show output

### ISSUE THREAD

**Issue by aristosv** [darkoperator/Posh-SSH#204]
I am using something like this to run multiple commands on a remote Linux computer.
```
$sshsession = New-SSHSession -AcceptKey -ComputerName $guestvm -Credential $cred
$sshstream  = New-SSHShellStream -Index 0
$sshstream.WriteLine("
apt-get update
apt-get -y upgrade
df -h
")
```
Is there a way to see the output of these commands while they are running?

**Comment by darkoperator** [comment]
You would need to send the commands one by one and then use the method on the object for reading use a regex for the promot to know the command ended and then run the next. Something like this https://gist.github.com/darkoperator/93fc457ca1c2de14c3a62a55d98020eb
