### ISSUE TITLE
SSHCommand not working for Set-Inform in Unifi

### ISSUE THREAD

**Issue by AdminTurnedDevOps** [darkoperator/Posh-SSH#210]
Hi,

Currently moving some Unifi devices over to a cloud controller sitting in DO. To do this, you need to run a set-inform command while SSH'd into the devices. It looks like this;
set-inform http://ip-of-controller:8080/inform

```
Name                           Value
----                           -----
PSVersion                      5.1.15063.909
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.909
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```
Function New-UnifiSSH {
    Param (
        [Parameter(ParameterSetName = 'DeviceIP',
            Position = 0,
            Mandatory,
            ValueFromPipeline,
            ValueFromPipelineByPropertyName)]
        [string[]]$deviceIP
    )
    Begin {
        Import-Module Posh-SSH
        $Pass = New-Object System.Management.Automation.PSCredential -ArgumentList ubnt, (Read-Host 'Please enter password' | ConvertTo-SecureString -AsPlainText -Force)
    }
    Process {
    
        $deviceArray = @()
        $deviceArray += $deviceIP
    
        $SSHSession = New-SSHSession -ComputerName $deviceArray -Credential $Pass
    
        Foreach ($Device in $SSHSession) {
    
            Invoke-SSHCommand -SSHSession $Device -Command "set-inform http://public-IP:8080/inform"
    
        }
    }#Process
    End {Get-SSHSession | Remove-SSHSession}
}#Function
```

Above is my small, itty bitty function. SSH works great and picks up both IP's that I'm testing with. Problem is, the command isn't running as I do not see the devices in the cloud controller. I don't get an error, but I do get an exit status of 127.

Any way to get around this? I've also tried with;
```
$Test = Invoke-SSHCommand -SSHSession $Device -Command "set-inform http://public-IP:8080/inform"
$Test.Output
```

**Comment by WindowsAdmin92** [comment]
UPDATE: I tried the same thing by using the Session ID instead, and I got an error stating that the command doesn't exist. However, it definitely does exist. Any fix for this?

**Comment by darkoperator** [comment]
Unifi uses a shell so so you will need to use a stream, they use a clone of VyOS so this function should help

https://gist.github.com/darkoperator/93fc457ca1c2de14c3a62a55d98020eb <https://gist.github.com/darkoperator/93fc457ca1c2de14c3a62a55d98020eb>

**Comment by dagelf** [comment]
``
$ alias
set-inform='mca-cli-op set-inform'
``

This means that instead of "set-inform" you need to use "mca-cli-op set-inform"
