### ISSUE TITLE
Using FTPES with New-SFTPSession

### ISSUE THREAD

**Issue by BentelerGR** [darkoperator/Posh-SSH#212]
See Wikipedia FTPS article (https://en.wikipedia.org/wiki/FTPS) under heading **Methods of Invoking Security**.

I can't seem to get New-Session to connect to an SFTP server that requires explicit mode.  Is there a setting to do this?

**Comment by ksbarnt** [comment]
As the Wikipedia article you link to there points out FTPS is not the same as SFTP, with the former being a TLS/SSL extension of FTP (a la HTTPS vs. HTTP), while SFTP is the SSH File Transfer Protocol, which is an extension of the SSH protocol for file transfers.

This module is meant for the latter, not the former. If you're using FTPS, you'll need to look elsewhere, and if you're using SFTP, you'll want to make sure you're careful about calling it the right thing.

**Comment by BentelerGR** [comment]
Thanks for the clarification Kenny - when I first started the project I
didn't realize our client was using FTPS because they kept saying SFTP.
And then it all became clear that they are two different animals and I was
using the wrong one!  I appreciate your response.
