### ISSUE TITLE
Character Encoding

### ISSUE THREAD

**Issue by ThiloL** [darkoperator/Posh-SSH#214]
Can Get-SFTPChildItem handle **path names** in ISO8859-1 encoding? FileZilla has an connection option:
![image](https://user-images.githubusercontent.com/2923889/40777145-3fd907be-64cd-11e8-9b24-b871c3f48027.png)

I think there is a Encoding property in the SSH.Net's connection info object.

**Comment by darkoperator** [comment]
To be honest, no clue. Never tested that

**Comment by MVKozlov** [comment]
I've tested
`$session.Session.ConnectionInfo.Encoding = [System.Text.Encoding]::GetEncoding($myencoding)` method for file listings - it works, May be it also will work for file names in transfer
