### ISSUE TITLE
New-SSHSession : Key exchange negotiation failed. SecurityError: (Renci.SshNet.SshClient:SshClient)

### ISSUE THREAD

**Issue by aristosv** [darkoperator/Posh-SSH#216]
**Windows Version**
Windows 10 Version 1803 (OS Build 17134.112)
**Powershell Version**
Major  Minor  Build  Revision
5             1      17134  112 

The problem is when I try to create an ssh session, I get the below.
```
$cred = New-Object System.Management.Automation.PSCredential ("user", (ConvertTo-SecureString "pass" -AsPlainText -Force))
$guestvm    = "192.168.1.15"
New-SSHSession -AcceptKey -ComputerName $guestvm -Credential $cred

New-SSHSession : Key exchange negotiation failed.
At line:1 char:1
+ New-SSHSession -AcceptKey -ComputerName $guestvm -Credential $cred
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (Renci.SshNet.SshClient:SshClient 
   ) [New-SSHSession], SshConnectionException
    + FullyQualifiedErrorId : SSH.NewSshSession
```

**Comment by darkoperator** [comment]
Ensure the target server is not using elliptic curve keys. Some Linux distros have moved to them but SSH.Net library does not support them

**Comment by PoshKazun** [comment]
Try to remove:
`Get-SSHTrustedHost | Remove-SSHTrustedHost`

**Comment by sudheeshjasmin** [comment]
Thanks, the command "Get-SSHTrustedHost | Remove-SSHTrustedHost" fixed the issue.

**Comment by jagdishrajan** [comment]
Thank you.  Get-SSHTrustedHost | Remove-SSHTrustedHost worked for me.  Where is the list of trusted hosts maintained?  And is there a way that New-SFTPSession -AcceptKey can automatially update this trusted key?

**Comment by darkoperator** [comment]
It is kept in the registry, in the PSv7 I’m thinking of using a JSON file to keep the host fingerprint pairs.

**Comment by carloselectro** [comment]
It fixed my problem too while connecting to a brocade sw in SSH.
Thanx!

**Comment by DjBangAdmin** [comment]
Adding -force at the end of the New-SSHSession line fixed it for me.

New-SSHSession -ComputerName $HostnameorIP -Credential $LoginCreds -AcceptKey:$true -force

**Comment by darkoperator** [comment]
That means the host key changed

**Comment by shkumesh** [comment]
Thanks, the command "Get-SSHTrustedHost | Remove-SSHTrustedHost" fixed the issue.
