### ISSUE TITLE
Don't have an answer from docker

### ISSUE THREAD

**Issue by Phoenix204** [darkoperator/Posh-SSH#220]
Hello! 
I use the posh-ssh to connect from Windows to the server Ubuntu 16.04, everything is fine, but why is the response from the docker is empty?
I'm trying to get answer from command "cleos --help", where
alias cleos='docker exec -it eosio /opt/eosio/bin/cleos -u http://0.0.0.0:8888 --wallet-url http://0.0.0.0:8888' (alias is constant and writing ~/.bash_aliases)
In Putty everything is fine (screenshot 1) 
![1](https://user-images.githubusercontent.com/41704007/43223936-5d191e84-905d-11e8-8345-d793384e874d.jpg)
But in PowerShell i don't have answer (screenshot 2)
![2](https://user-images.githubusercontent.com/41704007/43224345-9f6c9bc0-905e-11e8-9b22-4252a4eefaa1.jpg)
But i have answer from command 'docker --help' (screenshot 3)
![3](https://user-images.githubusercontent.com/41704007/43224368-b4699064-905e-11e8-9568-4d402c36daa1.jpg)

Thanks in advance for the answer and sorry for my english.

**Comment by darkoperator** [comment]
Are you using a shellstream? You will nit have aliases and other stuff without a full shell that is only available via shellstream

**Comment by darkoperator** [comment]
well it is a stream, there is no other way than a read, you will probably need to check that the command finished executing, similarly to what I do in this function https://gist.github.com/darkoperator/93fc457ca1c2de14c3a62a55d98020eb <https://gist.github.com/darkoperator/93fc457ca1c2de14c3a62a55d98020eb>
