### ISSUE TITLE
built in help appears to be missing examples

### ISSUE THREAD

**Issue by billkindle** [darkoperator/Posh-SSH#221]
I've looked a the built in help for a few commands and they appear to be missing examples. I see there are MD files available which are nice, but will these ever be implemented in the built-in help?

**Comment by billkindle** [comment]
Right now the only one's I've seen are the invoke-* commands. I just went back and looked again to be sure and they are all missing examples. Syntax shows up though. I applaud you trying to use the MAML and XML help. I took one look at that when building my last module and quickly threw in the towel.

**Comment by darkoperator** [comment]
Sadly with binary modules it is the only way to do help. will take a look when I start refactoring the module later this year.

**Comment by billkindle** [comment]
No worries, the MD files are helping for now. I'm planning on putting this to use soon for a number of environments where I have a few Linux nodes that I need to manage with PowerShell. Thanks for the quick reply!
