### ISSUE TITLE
How to verify if the command got completed in the shellstream

### ISSUE THREAD

**Issue by azam1980** [darkoperator/Posh-SSH#222]
Hello,
I would like to know if the command got completed if I invoke it in the shellstream. Instead of doing read and see everytime.

New-Sshsession -computername servername -credential (get-credential) -acceptkey
$aced = get-sshsession | ? {$_.host -eq servername} |Select -expand sessionid
$sess = get-sshsession -index $aced
$stream = $sess.session.CreateShellStream("dumb",0,0,0,0,1000)
$stream.write("Somecommand")

Instead of reading with $stream.read() to verify the command got completed and the shell is on the prompt. Is there any way I can verify that the command got completed and shell is on prompt.
I have kept the sleep in between them, but some commands usually runs faster compare to others, so its delaying the script because of sleep.

Thanks
Azam

**Comment by darkoperator** [comment]
Sadly there is not. I simply wrote a function for my stiff to assist with it

**Comment by azam1980** [comment]
Thanks. Do let me know if any best practice to overcome it. :)

**Comment by darkoperator** [comment]
This what I use with VyOS routers https://gist.github.com/darkoperator/93fc457ca1c2de14c3a62a55d98020eb

**Comment by azam1980** [comment]
You are awesome. Thanks a Lot. :):)
