### ISSUE TITLE
new-sftpdirectory not available

### ISSUE THREAD

**Issue by ecobben** [darkoperator/Posh-SSH#223]
new-sftpdirectory and  multiple other commands aren't imported in powershell
I've tried install-module and import-module in powershell but also first downloaded from the GitHub. 
how to solve this?

Attached a screenshot, of the import. 
Using windows 10/2016[
![screen_shot](https://user-images.githubusercontent.com/42273635/43960885-f7278f00-9ca2-11e8-87d4-7838d750cfe7.png)
](url)

**Comment by darkoperator** [comment]
Because it was changed to new-sftpitem several versions ago, in 1.7 to be exact. Are you going from an old writeup of the module?

**Comment by ecobben** [comment]
No I installing a new version, but possible using old info.

**Comment by darkoperator** [comment]
slowly moving to everything is an Item just like regular PS, for version 3.0 it will be Core .Net and will loose dependency on registry.
