### ISSUE TITLE
Cannot change path in session

### ISSUE THREAD

**Issue by veepee78** [darkoperator/Posh-SSH#227]
Is it possible to change path inside session? Seems that is stays in home directory all the time. tried to cd to docker directory under profile to run docker-compose. I'd need to be in specific directory to run the command.

Tried like this:
Invoke-SSHCommand -Command "cd /home/docker/docker/logstash_5_5_2 | docker-compose down" -SSHSession $s -TimeOut 60

and
Invoke-SSHCommand -Command "cd /home/docker/docker/logstash_5_5_2" -SSHSession $s -TimeOut 60
Invoke-SSHCommand -Command "docker-compose down" -SSHSession $s -TimeOut 60

neither worked.. if I do "cd /home/docker/docker/logstash_5_5_2  | ls" , it's still in home dir.

**Comment by darkoperator** [comment]
No you can not since it is not a shell. Invoke-sshcommand simply tells the system to execute a command with options using the sshexec call. For a shell you need to create a shell stream and write and read from it
