### ISSUE TITLE
Get-SFTPChildItem -Filter

### ISSUE THREAD

**Issue by christianquirante** [darkoperator/Posh-SSH#232]
please support -Filter command for Posh-SSH

**Comment by darkoperator** [comment]
For name?

**Comment by christianquirante** [comment]
yes for the file name, I just want to process files with the file extension *.txt* something like that even though the folder has other file extensions.

**Comment by darkoperator** [comment]
The API does not provide a way to filter remotely on the host so it would have to be done on the client side :\ so performance would be similar to using where-object or foreach :(

**Comment by christianquirante** [comment]
okay, thank you for the explanation!

**Comment by darkoperator** [comment]
I was exited for 15 minutes until I saw the library overloads and code for the list call :(
