### ISSUE TITLE
Remove-SFTPItem Should accept more than on file in Path Parameter

### ISSUE THREAD

**Issue by darkoperator** [darkoperator/Posh-SSH#24]
Remove-SFTPItem Should accept more than on file in Path Parameter

**Comment by darkoperator** [comment]
Added a -Force parameter for none empty directories to Release_v2. Still considering if I should add the ability to pass multiple locations as an array since it will mean a change from terminating error to none terminating and will impact existing scripts by users,

**Comment by ManasviBhargava** [comment]
Hi
Please let me know if this gets implemented anytime soon. 'm fairly new to this and I need to delete multiple files from a location before pushing new files. I keep getting this error:
**bin/./. is not an empty directory.**

**Comment by darkoperator** [comment]
Next week

**Comment by ManasviBhargava** [comment]
Thank you very much for the update. :) 
I'm assuming the fix would include something on the lines of an -rf that can be used with Remove-Directory or in this case Remove-SFTPItem.

Also, I wanted to understand why each directory appears as a subdirectory inside a directory named '.' or '..'
My debugger took me to this part of the code in sftp.ps1

function Get-SFTPDirectoryRecursive 
        {
            param($Path,$SFTPSession)
            
            $total = $Sess.Session.ListDirectory($Path)

            #List Files
            $total | ? {$_.IsDirectory -eq $false}
            
            #List non filtered directories
            $total | ? {$_.IsDirectory -eq $true -and @('.','..') -contains $_.name}           
            
            #Get items in a path
            $total | ? {$_.IsDirectory -eq $true -and @('.','..') -notcontains $_.Name } |
            % {Get-SFTPDirectoryRecursive -Path $_.FullName -SFTPSession $sess}
       
        }

**Comment by darkoperator** [comment]
. and .. represent current folder and the one above the structure, They should not be shown in my opinion, will remove them from the output when recursively listing directories in V2.0 


rom: ManasviBhargava
Sent: Thursday, August 3, 2017 6:34 AM
To: darkoperator/Posh-SSH
Cc: Carlos Perez; Assign
Subject: Re: [darkoperator/Posh-SSH] Remove-SFTPItem Should accept more thanon file in Path Parameter (#24)

Thank you very much for the update. :)
I'm assuming the fix would include something on the lines of an -rf that can be used with Remove-Directory or in this case Remove-SFTPItem.
Also, I wanted to understand why each directory appears as a subdirectory inside a directory named '.' or '..'
My debugger took me to this part of the code in sftp.ps1
function Get-SFTPDirectoryRecursive
{
param($Path,$SFTPSession)
        $total = $Sess.Session.ListDirectory($Path)

        #List Files
        $total | ? {$_.IsDirectory -eq $false}
        
        #List non filtered directories
        $total | ? {$_.IsDirectory -eq $true -and @('.','..') -contains $_.name}           
        
        #Get items in a path
        $total | ? {$_.IsDirectory -eq $true -and @('.','..') -notcontains $_.Name } |
        % {Get-SFTPDirectoryRecursive -Path $_.FullName -SFTPSession $sess}
   
    }

**Comment by darkoperator** [comment]
Forgot to mention the Fix is the -Force paramter

**Comment by ManasviBhargava** [comment]
-Force parameter it is. I am really in need of this to fix something at work. Please let me know when the release is available. Thank you very much!

All that I'm trying to do is remove everything from a directory called bin which consists of some folders and files. Each folder has a few files in it too. I am able to delete all files by using conditions like 

if(file.IsRegularFile)
{
Remove-SFTPItem -path $file.FullName
}

But, it wouldn't read empty directories as empty as it considers each directory within '.' and '..' as a subdirectory in each, every time it reads a directory. :(

**Comment by ManasviBhargava** [comment]
Hi - any update on the new release? :)

**Comment by darkoperator** [comment]
documenting stuff to be able to release it

**Comment by ManasviBhargava** [comment]
Hi. Thanks for the new release.
The Get-SFTPChildItem cmdlet is not returning folders inside the target directory. I have a bin folder which contains some folders and files. The Get-SFTPChildItem only returns files in bin and files inside the subfolders but does not get the subfolders.
Also the force parameter doesn't allow for recursive delete.
Error : (Tried to delete bin with a few blank folders inside)

Method invocation failed because [SSH.SshModHelper] doesn't contain a method named 'DeleteDirectoryRecursive'.
At C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\Sftp.ps1:367 char:25
+                         [SSH.SshModHelper]::DeleteDirectoryRecursive($Path, $ses ...
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
 


Can you give me some solution for this or maybe help me solve this problem another way? :(

**Comment by darkoperator** [comment]
Will push fixes tonight

**Comment by darkoperator** [comment]
Fixes pushed to PS Gallery
