### ISSUE TITLE
Add support for FIPS mode

### ISSUE THREAD

**Issue by bwright86** [darkoperator/Posh-SSH#240]
I know this is a hot topic in the Renci SSH arena. But it seems there are a lot of companies that use FIPS as a "one-click security solution" when it comes to ciphers. It is easy, it uses older less secure ciphers, and there are better ones available for use, etc...

It appears OctopusDeploy has added a method call in the ConnectionInfo class to enable FIPS.
https://github.com/OctopusDeploy/SSH.NET/blob/f9db0bb30e0797d7c4bc251c7f35f79aa714958c/src/Renci.SshNet/ConnectionInfo.cs#L476

It would be helpful for those using FIPS in their companies to have an easy solution when using Posh-SSH.

Could a similar solution be built into Posh-SSH to provide this ability?

Let me know your thoughts.

**Comment by bwright86** [comment]
Well, I spent some time today trying to figure out which ciphers are allowed and usable when FIPS is enabled. Unfortunately, I have not been able to find a combination of ciphers that allow a connection.

If anyone wants to point to a list of working ciphers, I would certainly appreciate it.

**Comment by darkoperator** [comment]
My guess based on SSH.Net issues is that the library will need to be updated there and made to work. Several people are trying sadly orgs still thing that enabling FIPS improves security
