### ISSUE TITLE
Multiple Commands with Invoke-SSHStreamExpectSecureAction

### ISSUE THREAD

**Issue by StevenNoel** [darkoperator/Posh-SSH#244]
Looking for a way to automate changing the root password across multiple hosts in our environment.

It works via the unsecure/plaintext method, but I'd like to use the Invoke-SSHStreamExpectSecureAction to secure the creds being passed.

I'm currently trying this

> Invoke-SSHStreamExpectSecureAction -ShellStream $sshshellstream -Command 'passwd' -ExpectString "New password:" -SecureAction ($securePass) -Verbose

However, I need to re enter the password on the 2nd confirmation prompt.

Is there any way to send multiple SecureActions using this command?

**Comment by darkoperator** [comment]
At the moment no, the function is in PowerShell and not C# so you should be able to grab the code from it and build a custom one based on it.

**Comment by StevenNoel** [comment]
Thanks.  Got it working with 

> Invoke-SSHStreamExpectSecureAction -ShellStream $sshshellstream -Command 'passwd' -ExpectString "New password:" -SecureAction ($securePass) -SecureAction2 ($securePass) -Verbose

Had to change Posh-SSH.psm1:
Add 2nd parameter ($SecureAction2)
`		        # SecureString representation of action once an expression is matched.
        [Parameter(Mandatory=$true,
                   ValueFromPipelineByPropertyName=$true,
                   Position=3)]
        [securestring]
        $SecureAction2,`

and then modified the 'Process' with a start-sleep command and a 2nd $ShellStream
`start-sleep -seconds 2`
`$ShellStream.WriteLine([Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureAction2)))`

**Comment by dokki767** [comment]
Trying to do the same thing here....Is cloning the sshstream function and adding the 2nd action parameter still the expectation here?  Just trying to avoid re-inventing the wheel if there was an update made to the module code base to explicitly support this.

**Comment by darkoperator** [comment]
You can code your own function using SSHStream, no need to modify the psm1 file. It allows you to update the module with out loosing your custom function. 
>

**Comment by wsmelton** [comment]
Had to do this for Ubuntu and just sharing this for reference...

```powershell
<#
	Input prompts on Ubuntu:
	$ passwd
	Changing password for <account>.
	(current) UNIX password:
	Enter new UNIX password:
	Retype new UNIX password:
	passwd: password updated successfully
	$
#>

$user = 'user2'
$password = ConvertTo-SecureString -String 'P@ssword123456' -AsPlainText -Force
$cred = New-Object System.Management.Automation.PSCredential -ArgumentList $user,$password
$newPasswd = ConvertTo-SecureString -String 'P@ssword09876' -AsPlainText -Force
$session = New-SSHSession -ComputerName lab-x-ubuntu18 -Port 22 -Credential $cred
$shellStream = New-SSHShellStream -SessionId $session.SessionId

$command = "passwd"
$shellStream.WriteLine("$command")
#pass in current password
$shellStream.WriteLine([Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($password)))
Start-Sleep -Seconds 2
#pass in current password
$shellStream.WriteLine([Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($newPasswd)))
Start-Sleep -Seconds 2
#pass in current password
$shellStream.WriteLine([Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($newPasswd)))
Start-Sleep -Seconds 2
# Clear buffer, should see "password updated" message
$shellStream.Read()

$shellStream.Dispose()
$session | Remove-SSHSession

<#
# Good output
.....
Last login: Tue May 19 00:08:45 2020 from 10.10.10.1
$ passwd
Changing password for user2.
(current) UNIX password:
Enter new UNIX password:
Retype new UNIX password:
passwd: password updated successfully
$
True

#>
```
