### ISSUE TITLE
Synch / Copy / Clone sFTP folder contents to DEV & UAT folders

### ISSUE THREAD

**Issue by DMANSKI** [darkoperator/Posh-SSH#252]
I'm looking for an elegant way to copy any/all files in a sFTP folder and replicate to 2 other sFTP folders. The purpose is to process the files in parallel environments but i receive only one file in one sfFTP folder a day.

Is there a good way to do this without copying locally and uploading for-each file?  I will be using powershell and would prefer to effectively clone the target directory nightly and overwrite where the file(s) exist.

Thanks,

**Comment by darkoperator** [comment]
Sadly not with the module and SFTP. What you are looking for is rsynch via ssh where you can keep folders in sync. Something like this 
https://www.digitalocean.com/community/tutorials/how-to-copy-files-with-rsync-over-ssh
