### ISSUE TITLE
Set-SCPFolder : scp: error: unexpected filename: .

### ISSUE THREAD

**Issue by Mytza** [darkoperator/Posh-SSH#254]
Hi,

I am running a script in azure, that is generating a folder with csv files in it and then uploading them to a SFTP like: 

Set-SCPFolder -ComputerName $ftpAddress -Credential $FtpCredential -LocalFolder "$folder" -RemoteFolder $folder -KeyFile $keyFile -Force -ErrorAction Stop

A couple of days ago it started failing at upload  without any change with error:

> Set-SCPFolder : scp: error: unexpected filename: .
> At line:66 char:1
> Set-SCPFolder -ComputerName $ftpAddress -Credential $FtpCredential -L ...
> 
>     CategoryInfo          : InvalidOperation: (Renci.SshNet.ScpClient:ScpClient) [Set-SCPFolder], ScpException
>     FullyQualifiedErrorId : SSH.SetScpFolder
> 

Any hints what can cause this issue, we did not do any change to our script it just started failing. Does this have to do something with the scp server ? Or it is a problem that can be fixed from script.

**Comment by darkoperator** [comment]
An you provide info on the type of VM you are running on Azure and the version of OpenSSH on it? Want to tey to replicate the issue.

**Comment by Mytza** [comment]
I am running an automation script in azure, that is run on a VM with Windows Server 2016.
I am not sure what the target server is running. I know only it is a linux but not sure what version as it is a server provided by out customers.
I initially checked with them but they are stating nothing has changed.

I tried also running the script locally on my machine running windows 10 and get the same result.

**Comment by darkoperator** [comment]
I trust what they say just want to build a similar vm in mu azure env to be able to debug it

**Comment by Mytza** [comment]
I checked on the VM but there is no OpenSSH installed. Posh-SSH 2.0.2 installed there.

On my local Windows 10 the following version is running OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4 also Posh-SSH installed

**Comment by darkoperator** [comment]
I meant the machine you are connecting to. My guess the machine you are copying the file to is Ubuntu

**Comment by Mytza** [comment]
Here it is what the customer is running:
OpenBSD: sshd_config,v 1.100 2016/08/15 12:32:04 naddy Exp
OpenSSH_7.4p1 Debian-10+deb9u5, OpenSSL 1.0.2q  20 Nov 2018
Distro:  Debian GNU/Linux 9

**Comment by ralfsf** [comment]
Hi, did you manage to solve this problem? I am getting the same error.

**Comment by Mytza** [comment]
Hi, No i am still getting the same error, at the moment i am uploading manually to ftp using filezilla. 
I am not sure why the error is generated because i get no more info than i posted. 
I did not have time to search for alternatives yet.

**Comment by darkoperator** [comment]
Think it is a recent change in OpenSSH that affects how the library performs the upload 
https://github.com/sshnet/SSH.NET/pull/515

**Comment by tdubb123** [comment]
getting same error too. any workaround?

**Comment by darkoperator** [comment]
Still waiting for a fix on the library, I recommend switching to SFTP while it gets addressed

**Comment by juancastingo** [comment]
Any update on this? Thanks.

**Comment by darkoperator** [comment]
Sadly no fix yet on the core library

**Comment by soul4soul** [comment]
There is a workaround for this issue posted at [sshnet/SSH.NET#515](https://github.com/sshnet/SSH.NET/pull/515).  I test that it's possible to patch just the SCPClient*.cs files from the 2016.0.0 release.

@darkoperator would you consider maintaining your own fork of SSH.NET? This issue and the [sshnet/SSH.NET#355](https://github.com/sshnet/SSH.NET/issues/355) are major problems that are impacting the usability of Posh-SSH. I considered switching to New-PSSession using SSH for transport but its a real pain to use compared to this module.

**Comment by darkoperator** [comment]
It is something I have been trying to avoid and seems I have little to no choice given that the author is not maintaining it properly. I’m not a crypto person so I will have to test as carefully as I can .

**Comment by darkoperator** [comment]
can you test the new alpha version to see if the changes address it https://github.com/darkoperator/Posh-SSH/releases/tag/2.3-alpha

**Comment by dimaaan** [comment]
@darkoperator  i have same issue and would like to test it. Can you please tell, how i can install or import this alpha release?

**Comment by darkoperator** [comment]
The alpha is for testing not production JIC, you download the zip from the releases, right click and make sure to unblock the zip, unzip and then import-module pointing it to the psd1 manifest file to test.

**Comment by dimaaan** [comment]
`Import-Module ./Posh-SSH-Alpha/Posh-SSH.psd1`
did the job, but now i'm getting
`New-SSHSession : Key exchange negotiation failed`
Anyway, thanks for help!

**Comment by darkoperator** [comment]
Not without knowing the specific algorithms configured and server on the other side

**Comment by darkoperator** [comment]
Can you establish a ssh session without problem? Outside of SCP?

**Comment by dimaaan** [comment]
Well, here is my script:
```powershell
#Import-Module Posh-SSH
#Import-Module ./Posh-SSH-Alpha/Posh-SSH.psd1 # temporary

$hostAddr = "..."
$hostUser = "..."
$hostPass = ConvertTo-SecureString "..." -AsPlainText -Force
$creds = New-Object System.Management.Automation.PSCredential($hostUser, $hostPass)
$publishDir = "..."
$deployDir = "..."

$sshSession = New-SSHSession -ComputerName $hostAddr -Credential $creds -ErrorAction Stop
Invoke-SSHCommand -SSHSession $sshSession -Command "command1" -ErrorAction Stop
Set-SCPFolder -LocalFolder $publishDir -RemoteFolder $deployDir -ComputerName $hostAddr -Credential $creds -ErrorAction Stop
```

When i use `Import-Module Posh-SSH`
i'm getting
`Set-SCPFolder : scp: error: unexpected filename: .`
Note that `command1` executes succesfully

When i use `Import-Module ./Posh-SSH-Alpha/Posh-SSH.psd1`
i'm getting
```
New-SSHSession : Key exchange negotiation failed.
+ ... shSession = New-SSHSession -ComputerName $hostAddr -Credential $creds ...
```

Also, i'm able to ssh into remote machine with `ssh user@host` and typing password.
But `scp -r publishDir user@host:deployDir` gives me
```
connect to host {host} port {port}: Connection timed out
lost connection
```

Looks like its not Posh-SSH issue and i suspect this starts to happen after i updated my remote Ubuntu with apt-get upgrade
