### ISSUE TITLE
Empty username

### ISSUE THREAD

**Issue by fjf2002** [darkoperator/Posh-SSH#256]
Hi,
I'm trying to connect to a LANCOM Router per SSH. Unfortunately the router needs an empty username (but a non-empty password). With PuTTY, it works. With Posh-SSH sadly not.

The code I used:
```
$Credential = New-Object PSCredential -ArgumentList ([pscustomobject] @{ 
  UserName = '';
  Password = (ConvertTo-SecureString -AsPlainText -Force -String $password)[0]
})

$ssh = New-SSHSession -ComputerName $lancomIp -Credential $Credential -Verbose
```

The Error Message is

    New-SSHSession : username

Regards,
fjf2002

**Comment by darkoperator** [comment]
to be honest no clue, I do not have any system where I would SSH with an empty user and a password that I can use to replicate the scenario.

**Comment by fjf2002** [comment]
Meanwhile I found out that on my LANCOM device, empty username is equivalent to username root, so I can circumvent the problem.

Regards
fjf2002
