### ISSUE TITLE
Move-SFTPItem exception if destination exists

### ISSUE THREAD

**Issue by KeithwNZ** [darkoperator/Posh-SSH#267]
If destination file already exists, Move-SFTPItem results in the following exception:
	Exception calling "MoveTo" with "1" argument(s): "File already exists"
	At C:\Users\admkeith\Documents\WindowsPowerShell\Modules\Posh-SSH\Release\Posh-SSH.psm1:1360 char:17
	+                 $itemInfo.MoveTo($Destination)
	+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
		+ FullyQualifiedErrorId : SshException
 
Possibly add logic "if (Test-SFTPPath -SFTPSession $session -Path $Destination)" in function Move-SFTPItem to handle existence of destination file , e.g. 
 
      Process
     {

        foreach($session in $ToProcess)
        {

            if (Test-SFTPPath -SFTPSession $session -Path $Path)
            {
                if (Test-SFTPPath -SFTPSession $session -Path $Destination)
                {
                    Write-Verbose("Unable to move $($path) to $($Destination). Destination already exists")
                }
                else
                {
                    $itemInfo = $session.Session.Get($path)
                    Write-Verbose("Moving $($path) to $($Destination).")
                    $itemInfo.MoveTo($Destination)
                }
            }
            else
            {
                throw "Specified path of $($Path) does not exist."
            }

        }
     }

**Comment by darkoperator** [comment]
That is to be expected if the file exists and you are overwriting it. It is preventing that behaviour that could be detrimental. it is throwing a terminating event because other actions may depend on such a move and it should be handled inside a try/catch statement to account for it.
