### ISSUE TITLE
feature request - jumphost support

### ISSUE THREAD

**Issue by matsmcp** [darkoperator/Posh-SSH#270]
I would like to request support/functionality to connect through jump/bastion hosts.

in our segmented network we must jump through jumphosts on the border of a network segment to be allowed to access systems in that segment.

the manual way is to do ssh -J user@jumphost user@targetsystem resulting in a shell on the target system.

However I haven't been able to find out how to do it in Posh-SSH. Therefore I do believe that support for it needs to be added to make it possible

**Comment by darkoperator** [comment]
Sadly this is not something that the library I use supports

**Comment by matsmcp** [comment]
bummer ;)
I do have a feature request at ssh net too, feel free to upvote it .....
