### ISSUE TITLE
Connecting with a password

### ISSUE THREAD

**Issue by mikantchap** [darkoperator/Posh-SSH#272]
Hi

Sorry to ask a basic question, but we have username@xxx.xxx.xxx.xxx and passwords.

Can we (using PoshSSH + Powershell) connect to our multiple clients with a script without entering passwords to run a few SSH commands on each? I can't seem to find a simple example for this?

Thanks Mike

**Comment by darkoperator** [comment]
Just like you would any other cmdlet in PS that uses credentials. In the case of Posh-SSH you can also use password protected keys also. Here is an example of storing a credential object for later use in the same host
https://interworks.com/blog/trhymer/2013/07/08/powershell-how-encrypt-and-store-credentials-securely-use-automation-scripts/ <https://interworks.com/blog/trhymer/2013/07/08/powershell-how-encrypt-and-store-credentials-securely-use-automation-scripts/>
