### ISSUE TITLE
Update Get-SCPItem PathType options to match Test-Path PathType options

### ISSUE THREAD

**Issue by soul4soul** [darkoperator/Posh-SSH#273]
I am wondering why the options of `Get-SCPItem`'s PathType parameter are `File` and `Directory`. The command options for `Test-Path`'s PathType parameter are `Leaf` and `Container`. Would it make sense to update them to be `Leaf` and `Container`? I do understand `Test-Path` also has `Any` which probably wouldn't be Valid for `Get-SCPItem`

**Comment by darkoperator** [comment]
Sadly with SCP it is as you mentioned file or directory. Test-Path since it has to work with registry, ad, SQL .. any provider it has to be more abstract. Wish I do do value set aliases. For the time being don’t plan to change it since it would be a breaking change.
