### ISSUE TITLE
"Cannot set percent" error when downloading folder using Get-SFTPItem

### ISSUE THREAD

**Issue by ryanjgillies** [darkoperator/Posh-SSH#276]
I'm not sure if this error has stemmed from the recent 2.2 update, but my folder downloads are failing when using `Get-SFTPItem` - it processes about a quarter of the files in question before crashing out.

I did some digging and found that its producing the following error on most of the files when it downloads them:
```
Cannot set percent because PercentComplete cannot be greater than 100.
Parameter name: value
Actual value was 25600
```
The actual value varies. I tried passing `-NoProgress` as a workaround, but no luck.

![PercentComplete](https://user-images.githubusercontent.com/9565005/59582902-3e28b100-910c-11e9-8296-b9b810e1c80d.png)

**Comment by darkoperator** [comment]
Thats a mew one I have not seen before. What ia the target server, version of SSH and size of the items in the folder so I can replicate
