### ISSUE TITLE
New-SSHSession : Permission denied (keyboard-interactive)

### ISSUE THREAD

**Issue by I3udder** [darkoperator/Posh-SSH#278]
When connecting to a switch we get an error that permission is denied.
I enabled logging on the switch and it states the following

267294: Jul  2 13:57:01.444: %SSH-5-SSH2_SESSION: SSH2 Session request from x.y.z.a (tty = 1) using crypto cipher '3des-cbc', hmac 'hmac-md5' Succeeded

Also the strange thing is when using get-credential instead of the self defined credential object it works.

Using 2.0.2 version of Posh-SSH and below powershell version

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by I3udder** [comment]
Switching to 2.2 version of Posh-SSH doesn't make a difference

**Comment by darkoperator** [comment]
How are you defining the. Credential object? Would be good to compare how the Username and Password fields are in one vs the other.

**Comment by I3udder** [comment]
Probably found the error. We are using an XML input sheet and the convert it to a credential. Probably forgot to change the password.

**Comment by darkoperator** [comment]
Also XML od a PSCredential object is unique to the machine where it was created since it uses the users DPAPI master key that ran Export-CliXML if that was the case.
