### ISSUE TITLE
Session operation has timed out... GOOD MORNING! :D

### ISSUE THREAD

**Issue by GregJobs** [darkoperator/Posh-SSH#280]
When I do this to a device that I cannot get to for whatever reason:

New-SSHSession $machine_ip -port $port -Credential $mycreds -AcceptKey:$true

I time out, understandable. 

I get the standard:

New-SSHSession : Session operation has timed out
At line:5 char:12
+ $Session = New-SSHSession $machine_ip -port $port -Credential $mycred ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationTimeout: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], SshOperationTimeout 
   Exception
    + FullyQualifiedErrorId : SSH.NewSshSession

So, I tried:

 Try {
$Session = New-SSHSession $machine_ip -port $port -Credential $mycreds -AcceptKey:$true
}
Catch {
$LogMsg = "New-SSHSession failed Msg: $($_.Exception.Message)"

Write-Host $LogMsg

To stop the error and catch it, do something with it, but, well, that doesn't work. Thoughts/ideas?

**Comment by darkoperator** [comment]
If you try with the windows 10 ssh client or putty does it work?

**Comment by GregJobs** [comment]
When I use putty/kitty/openssh they "unexpectedly close" out and pop up an error. That's my point though, since posh is timing out, how come I can't capture that as a variable or in a try/catch and use posh as a means to "test" ssh on a device?

**Comment by darkoperator** [comment]
set ErrorAction to Stop, it is a nonterminating event and you can make it into one with that 
```
PS C:\Users\carlos\Documents\Posh-SSH\Release> try {New-SshSession -ComputerName 192.168.1.214 -Credential carlos } catch {Write-Host "error"}
New-SshSession : Connection failed to establish within 10000 milliseconds.
At line:1 char:6
+ try {New-SshSession -ComputerName 192.168.1.214 -Credential carlos }  ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationTimeout: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], SshOperationTimeoutException
    + FullyQualifiedErrorId : SSH.NewSshSession

PS C:\Users\carlos\Documents\Posh-SSH\Release> try {New-SshSession -ComputerName 192.168.1.214 -Credential carlos -ErrorAction Stop} catch {Write-Host "error"}
error
```

**Comment by GregJobs** [comment]
Nice! Thank you.
