### ISSUE TITLE
Addition Subfolder created in Get-SFTPItem

### ISSUE THREAD

**Issue by ScriptXaaS** [darkoperator/Posh-SSH#281]
SFTP Server:  OpenSSH 7.4 on RHEL 7.4

I would like to transfer the whole backup folder, its sub-directories, and files to a CIFS share eventually.  To start, make the destination to a local Windows folder.

$srcPath = "/folder/subfolderA "
$destPath = "c:\destFolder"
Get-SFTPItem -SessionId 0 -Path $srcPath -Destion $destPath

I expected the result to be:
c:\destFolder\file1.txt
c:\destFolder\file2.txt, etc.

Instead, it created an additional sub-folder from the srcPath and the result is like:
c:\destFolder\subfolderA\file1.txt
c:\destFolder\subfolderA\file2.txt, etc.

Intriguingly, if I ran Set-SFTPLocation first with $srcPath, then run
Get-SFTPItem -SessionId 0 -Path . -Destion $destPath

The additional subfolder would still be createdl, but this time named as "v1.0" (if executing from PowerISE) like:
c:\destFolder\v1.0\file1.txt
c:\destFolder\v1.0.\file2.txt, etc.

In both scenarios above, when executing Get-SFTPItem, the powershell session would crush and restart, but files transfer and creation of folders appear to complete before that happens.

In contrast, if executing in the powershell console, the additional sub-directory name created would be the login username (e.g. johndoe) instead of" v1.0", and powershell console shell would also crush and restart. 

I wonder anyone experience the same symptoms and a fix may be available soon.  I plan to run ths powershell script in a schedule task.  If the powershell session keeps crushing, the schedule task would work right.  Thanks.

**Comment by darkoperator** [comment]
I think it is behaving like it should since it is "*Path" the parameter, you specify the location to place the file or folder, it behaves just like the Item cmdlets. by "crushing" you mean crashing?  Will look as to why it is crashing on ISE, I do most of my development in code so I rarely use the ISE.

**Comment by darkoperator** [comment]
You ca see on the first case it is behaving as expected. The example in help shows the way it behaves. on the second case can you do a -verbose?
```
PS C:\Users\carlos\Documents\Posh-SSH\Release> help Get-SFTPItem -Examples

NAME
    Get-SFTPItem

SYNOPSIS
    Downloads via SFTP an item from a SSH server.


    Example 1

    PS C:\>Get-SFTPItem -SessionId 0 -Path .ssh -Destination ./ -Verbose

    Downloads the .ssh folder from the server to the current directory.
```
