### ISSUE TITLE
Add -NewName param for Get-SftpItem

### ISSUE THREAD

**Issue by Szeraax** [darkoperator/Posh-SSH#285]
Similar to https://github.com/darkoperator/Posh-SSH/issues/152, sometimes you want to transfer an item and have it transferred with a different name. 

In my case, I am trying to download a file that has illegal characters (colons) to a windows machine (it looks like it'll spit out a file with everything after the illegal characters present, but that's not good as it is unexpected).

**Comment by Szeraax** [comment]
nevermind, I haz the dumb. Get-SftpItem gives an error when trying to get a file that contains illegal characters:

    Get-SFTPItem : The given path's format is not supported.

**Comment by Szeraax** [comment]
(For anyone in the future if this doesn't get fixed, my workaround is to Move-SftpItem to a new name and then get the item)

**Comment by darkoperator** [comment]
Not a bug to be fixed. Sadly it will not be implemented because then it breaks the pipeline functionality where folder content can be piped to be then uploaded via SFTP or a filter selection of files.
