### ISSUE TITLE
New-SFTPSession High Port when using Socks5 Proxy failing

### ISSUE THREAD

**Issue by mercuryjlt** [darkoperator/Posh-SSH#287]
Using New-SFTPSession, I am unable to connect to an SSH port other than port 22 when using a Socks5 Proxy

The following does not work:

$_SSHHost = "192.168.1.10"
$_SSHHostPort = 1122
$_ProxyServer = "proxy123.proxyserver.com"
$_ProxyPort = 789
$_ProxyType = "Socks5"
    
$_SFTPSession = New-SFTPSession -Credential $_Credentials -ComputerName $_SSHHost -Port $_SSHHostPort -ProxyServer $_ProxyServer -ProxyPort $_ProxyPort -ProxyCredential $_Credentials -ProxyType $_ProxyType -AcceptKey

The exception is: New-SFTPSession : SOCKS5: General failure.

Changing only $_SSHHostPort to 22 successfully connects and all subsequent SFTP commands succeed.
If I move to a server on a subnet local to the server, with the following, it will also succeed.

$_SSHHost = "192.168.1.10"
$_SSHHostPort = 1122
$_SFTPSession = New-SFTPSession -Credential $_Credentials -ComputerName $_SSHHost -Port $_SSHHostPort -AcceptKey

Other clients using Socks5 proxy to reach the remote server (Putty, WinSCP) succeed on the non-standard port.

I’ve tried multiple high numbered ports as well to see if it’s a port-range issue. They all fail. Only port 22 is succeeding and we’re trying to close down Port 22 on these systems.

**Comment by darkoperator** [comment]
What proxy software are you using so I can try and replicate?

**Comment by darkoperator** [comment]
closing for lack of reply, reopen if still and issue.
