### ISSUE TITLE
Inconsistent behavior of AcceptKey

### ISSUE THREAD

**Issue by xxbiohazrdxx** [darkoperator/Posh-SSH#288]
In `New-SSHSession` the parameter `AcceptKey` is simply a switch and so the following is valid:

`New-SSHSession -ComputerName $ComputerName -AcceptKey`

However, in `Set-SCPFile` the parameter `AcceptKey` is a full blown parameter and requires a boolean to be supplied.

`Set-SCPFile -ComputerName $ComputerName -AcceptKey`

results in an error

`Set-SCPFile : Missing an argument for parameter 'AcceptKey'. Specify a parameter of type 'System.Boolean' and try again.`

I haven't checked elsewhere to see where this behavior might be repeated, but it would be nice if AcceptKey was consistent across the module

**Comment by xxbiohazrdxx** [comment]
`Get-SCPFile` also has  `AcceptKey` as a switch, so specifying `$true` is not needed

**Comment by darkoperator** [comment]
This will have to be updated on the next major version since it is breaking change for existing scripts

**Comment by darkoperator** [comment]
New Alpha release should address this
