### ISSUE TITLE
'Invoke-SSHStreamExpectSecureAction' wait for return to prompt

### ISSUE THREAD

**Issue by ASG-Github-Admin** [darkoperator/Posh-SSH#289]
Hi!

This is my first time posting, so hopefully I do not clash with any rules.

I have a script that uses the Invoke-SSHStreamExpectSecureAction' function and works well when output is returned swiftly. However, the issue I face is when it executes a script that takes many minutes to complete.

I have been web searching, and looking through the module documentation, but I have not found a clear way to accomplish the task. The workaround I have is Ben's solution here:
https://github.com/darkoperator/Posh-SSH/issues/71

Here is pseudo code to demonstrate what I did before:

$Sesh = Invoke-SSHSession -ComputerName LinuxServer -Port 22 -Credential $Cred -AcceptKey
$Stream = New-SSHShellStream -SSHSession $Sesh
$Invoke = Invoke-SSHStreamExpectSecureAction -ShellStream $Stream -Command "sudo -u anotheruser -i ./LongRunningScript.sh"  -ExpectString "[sudo] password for $($Cred.UserName):" -SecureAction $Cred.Password
$Sesh.Read()

And what it returns by reading too early:
Script started
Script in the middle

And what it returns when allowed the time:
Script started
Script in the middle
Script finished
[user@computer ~]$

I guess I am looking for SSHStreamExpectSecureAction to have an extra parameter to wait for the prompt to return and a timeout in the event it takes too long to complete!

**Comment by darkoperator** [comment]
You will have to code it against a stream by writing command, entering carriage return and reading the stream in a loop until you hit the output you want and then writing again to it

**Comment by ASG-Github-Admin** [comment]
Thank you. I stuck with the .Expect() method approach, as it appears to work ok.
