### ISSUE TITLE
New-SFTPSession : Permission denied (keyboard-interactive).

### ISSUE THREAD

**Issue by jirvineparagonpayroll** [darkoperator/Posh-SSH#293]
I am getting this error message when running my PS script on one server, but not on another. Can anyone point me in the right direction? It has to be a configuration on the server, but I can't find it.

New-SFTPSession : Permission denied (keyboard-interactive).

Here is the section of script which calls it:

import-module posh-ssh #sftp

#build the credentials
$SecureString = ConvertTo-SecureString $pass -AsPlainText -Force
$ftpcred = New-Object System.Management.Automation.PSCredential -argumentlist $user, $SecureString

Write-Host "Connecting to FTP" 
#connect to the server
$Session = New-SFTPSession -ComputerName $sFtp -Credential $ftpcred -Port $port

**Comment by darkoperator** [comment]
And the same script works against another? Wonder if the sftp component is installed, has happened to me against CentOS machines where SFTP is installed separetly from SSH

**Comment by jirvineparagonpayroll** [comment]
Yes it is installed. I even reinstalled it to be sure.

[A close up of a logo    Description automatically generated]
Joe Irvine
IT Manager
Tel: 866.444.4615 x1007
Fax: 866.446.7222
www.paragonpayroll.com<http://www.paragonpayroll.com/>

**Comment by jirvineparagonpayroll** [comment]
Absolutely nothing in the logs on the machine. The only troubleshooting I have done so far is try the same script on another server where it worked before. This is a new server, so it is likely I have something misconfigured or missing that is required. I have other scripts running Posh-SSH on this server without issue, and I use the same basic script.

[A close up of a logo    Description automatically generated]
Joe Irvine
IT Manager
Tel: 866.444.4615 x1007
Fax: 866.446.7222
www.paragonpayroll.com<http://www.paragonpayroll.com/>

**Comment by jflieben** [comment]
for those googling this error in the future: this error, in my case, meant the password was wrong
