### ISSUE TITLE
Set-SFTPFile : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by TLA50** [darkoperator/Posh-SSH#294]
I am trying to upload a csv file to a sftp site, but keep getting this error. "Set-SFTPFile : Object reference not set to an instance of an object."

My code is below. 

# Set the credentials
$Password = ConvertTo-SecureString 'BlahBlah' -AsPlainText -Force
$Credential = New-Object System.Management.Automation.PSCredential ('UserNAME', $Password)

# Set local file path, SFTP path, and the backup location path which I assume is an SMB path
$FilePath = "C:\Temp\MY_CSV_FILE.csv"
$SftpPath = '/'
$SmbPath = 'C:\temp\Backup'

# Set the IP of the SFTP server
$SftpIp = 'sftp.place.co.uk'

# Load the Posh-SSH module
Import-Module Posh-SSH

# Establish the SFTP connection
$ThisSession = New-SSHSession -ComputerName $SftpIp -AcceptKey $Credential

# Upload the file to the SFTP path
Set-SFTPFile -SessionId ($ThisSession).SessionId -LocalFile $FilePath -RemotePath $SftpPath

#Disconnect all SFTP Sessions
Get-SFTPSession | % { Remove-SFTPSession -SessionId ($_.SessionId) }

# Copy the file to the SMB location
Copy-Item -Path $FilePath -Destination $SmbPath

**Comment by darkoperator** [comment]
Ould you try set-sftpitem? That cmdlet is deprecated and replaced by sftpitem

**Comment by dbrennand** [comment]
I am experiencing the same issue. For both Set-SFTPFile and Set-SFTPItem.

**Comment by darkoperator** [comment]
What is the remote server? Need to be able to replicate the issue

**Comment by dbrennand** [comment]
It looks like the function isn't working correctly when passing a `-SessionId` with an active SSH session using `New-SSHSession`. 

I fixed this issue by creating a SFTPSession using `New-SFTPSession`. Then passing that object directory into `New-SFTPItem` and `Set-SFTPItem`.

Here is my working code:
```powershell
 
$Test = New-SFTPSession -ComputerName "Someip" -AcceptKey -KeyFile "somekeyfilepath" -Credential $Credential -Verbose:($PSBoundParameters["Verbose"] -eq $true) -ErrorAction "Stop"

New-SFTPItem -SFTPSession $Test -Path "Path to file" -ItemType "File"
Set-SFTPItem -SFTPSession $Test -Destination "somedestination" -Path "somefile" -Force -Verbose:($PSBoundParameters["Verbose"] -eq $true) -ErrorAction "Stop"
```

**Comment by darkoperator** [comment]
```
PS C:\Users\carlos\Documents\Posh-SSH\Release> New-SFTPSession -ComputerName 192.168.1.213 -Credential carlos

SessionId  Host                                                                                Connected
---------  ----                                                                                ---------
    0      192.168.1.213                                                                          True


PS C:\Users\carlos\Documents\Posh-SSH\Release> Get-SFTPSession -SessionId 0

SessionId  Host                                                                                Connected
---------  ----                                                                                ---------
    0      192.168.1.213                                                                          True


PS C:\Users\carlos\Documents\Posh-SSH\Release> New-SFTPItem -SessionId 0 -Path /tmp/test.tx -ItemType file


FullName       : /tmp/test.tx
LastAccessTime : 2/27/2020 9:21:13 PM
LastWriteTime  : 2/27/2020 9:21:13 PM
Length         : 0
UserId         : 1000



PS C:\Users\carlos\Documents\Posh-SSH\Release> Set-SFTPItem -SessionId 0 -Destination /tmp -Path C:\deploy.ps1
VERBOSE: Uploading C:\deploy.ps1 to /tmp
```

Could I be missing something? this is against a Ubuntu system running Open-SSH.

**Comment by dbrennand** [comment]
Try using `New-SFTPItem` with an object created from `New-SSHSession`.

**Comment by darkoperator** [comment]
Should be New-SFTPSession and not New-SSHSession, SSH and SFTP are different sessions

**Comment by dbrennand** [comment]
Ok, but the [documentation](https://github.com/darkoperator/Posh-SSH/blob/master/docs/New-SFTPItem.md) to me implies that `New-SSHSession` can be used. It just says to use `-SessionId`. I interpreted this as being able to use `New-SSHSession`.

**Comment by darkoperator** [comment]
SessionId is generic 🤷‍♂️ Further down you can see the object type is sftp. Can I close the ticket?
