### ISSUE TITLE
Remove all files in a remote dir but leave dir existing

### ISSUE THREAD

**Issue by bccrew** [darkoperator/Posh-SSH#295]
Hi,

I don't see any way to setup a sftp session to a remote server and delete all files in a certain directory.

for now, I have this piece of code but it deletes the "test" directory and not all files inside recursively.

```
Import-Module Posh-SSH
$username = "root"
$password = "password" | ConvertTo-SecureString -AsPlainText -Force
$server = "192.168.1.100"
$SftpPath = '/storage/test/.'
$credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $username,$password
$ThisSession = New-SFTPSession -ComputerName $server -Credential $credential -AcceptKey
Remove-SFTPItem -SessionId ($ThisSession).SessionId -Path $SftpPath -Force
```

How can I make this work? It is not accepting 

$SftpPath = '/storage/test/*'

or 

$SftpPath = '/storage/test/*.*'

+ FullyQualifiedErrorId : Specified path of /storage/htntemp/test/*.* does not exist.

**Comment by darkoperator** [comment]
What is the target server? No symlinks in the directory?

**Comment by bccrew** [comment]
The target server is an embedded device with an openssh server. The device is running a daemon which stuffs a folder full of logfiles. Because we cannot make any changes to the device and the dir must now be cleaned manually, I was looking for an automated solution.

It seems that the -Path parameter is not accepting wildcards like *.* or * 

I could probably work my way around by enumerating a list of all files in a remote directory and sequentially remove all files separately but my powershell skills are limited :)

**Comment by darkoperator** [comment]
Sadly no wildcard, my only guess would be that a process still has a handle opened on the folder since that last version support for deletion of folder with content was added.

**Comment by breezytm** [comment]
I would so something like this 

$contents = Get-SFTPChildItem -SessionId ($session).SessionId -Path $remotePath -Recursive

And then do a  foreach  loop and delete each items. one at a time. foreach content in contents remove-sftpitem -Path $content.FullName -SessionId ($session).SessionId
