### ISSUE TITLE
New-SFTPSession - forcibly closed error

### ISSUE THREAD

**Issue by ryanjgillies** [darkoperator/Posh-SSH#298]
I'm having issues with a connection to a server running OpenSSH - its the first time I've tried connecting to this type of ssh server.

Upon entering the following command:
`New-SFTPSession -ComputerName $sftp_address -Port $sftp_port -Credential $sftp_creds -ConnectionTimeout 50000 -Verbose`

I get the following error back:
```
VERBOSE: Using SSH Username and Password authentication for connection.
New-SFTPSession : An existing connection was forcibly closed by the remote host
At D:\POS_Import\SFTP Trusted Hosts.ps1:10 char:1
+ New-SFTPSession -ComputerName $sftp_address -Port $sftp_port -Credent ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (Renci.SshNet.SftpClient:SftpClient) [New-SFTPSession], SshConnectionExcep 
   tion
    + FullyQualifiedErrorId : SSH.NewSftpSession
```

All of my other connections work correctly, and when I connect to this openssh server using other client software I have no issues. Can anyone shed any light for me?

**Comment by darkoperator** [comment]
Weird all of my testing is against OpenSSH only. What version and what target OS?
