### ISSUE TITLE
New-SSHSession fails if ComputerName has an underscore in it

### ISSUE THREAD

**Issue by FireInWinter** [darkoperator/Posh-SSH#3]
If a host has an underscore "_" character in its name, New-SSHSession fails with the error message "host".  It doesn't even matter if the host exists or not, it doesn't look like it makes it that far.  It would be great to have this fixed as this module fills a lot of the needs I have to connect PowerShell to Linux systems.

For example:
``` 
$Cred = Get-Credential
New-SSHSession -ComputerName 'server1_dev' -Credential $Cred

    New-SSHSession : host
    At line:1 char:1
    + New-SSHSession -ComputerName 'server1_dev' -Credential $Cred
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [New-SSHSession], ArgumentException
        + FullyQualifiedErrorId : System.ArgumentException,SSH.NewSshSession
```

P.S. I know that an underscore character is not supposed to be used in a hostname, but unfortunately DNS doesn't prevent it and the company where I am uses it in hostnames.

**Comment by FireInWinter** [comment]
Any chance of the most recent build of SSHNet being rolled in soon?   Thanks. Looking forward to using this a lot more once it's there.

**Comment by darkoperator** [comment]
version 1.7 is in the works, almost finished with the re-write of it and it will use the newest version of the lib that fixes this

**Comment by darkoperator** [comment]
just tested against the code for the next release and it is resolved on it https://github.com/darkoperator/Posh-SSH/tree/Release_0.4 now just need to finish testing and XML help and it will be ready for release :)

**Comment by darkoperator** [comment]
Please test release 1.7 pushed out today.

**Comment by darkoperator** [comment]
My own test show it is working, no confirmation given. Closing it for the time being. If it is still a problem please re-open.
