### ISSUE TITLE
Invoke-SSHCommand doesn't ouput anything and the command isn't run

### ISSUE THREAD

**Issue by stonetwig** [darkoperator/Posh-SSH#300]
Hello,

First off, I really enjoy the module and it works great when transferring files but when I try to run commands such as this one:

`Invoke-SSHCommand -SessionId ($ThisSession).SessionId -Command "systemctl --user stop my.service"`

Nothing happens, the command isn't invoked and there is no output.

Am I doing anything wrong here?

Thanks in advance!

**Comment by darkoperator** [comment]
It may require a proper shell instead of  syscall to run a command. Try shellatream

**Comment by stonetwig** [comment]
Sorry, it was my mistake, I had used a SFTP connection and not an SSH connection!
