### ISSUE TITLE
Move-SFTPItem Force

### ISSUE THREAD

**Issue by breezytm** [darkoperator/Posh-SSH#301]
Hi, 

Any change of adding -Force to Move-SFTPItem?
I would like to the ability to overwrite the existing file.

Regards,

**Comment by darkoperator** [comment]
Will check if the API allows it

**Comment by breezytm** [comment]
thanks

**Comment by darkoperator** [comment]
Sadly it is not supported by the API and the method used on the file does not have an override for it. 

PS C:\Users\carlos\Documents\Posh-SSH\Release> $items = Get-SFTPChildItem -SessionId 0
PS C:\Users\carlos\Documents\Posh-SSH\Release> $items[0]


FullName       : /home/carlos/.profile
LastAccessTime : 7/20/2019 9:07:11 AM
LastWriteTime  : 1/21/2019 3:44:48 PM
Length         : 962
UserId         : 1000



PS C:\Users\carlos\Documents\Posh-SSH\Release> $items[0].MoveTo

OverloadDefinitions
-------------------
void MoveTo(string destFileName)
