### ISSUE TITLE
Set-SCPFile and Get-SCPFolder are not displaying a progress bar

### ISSUE THREAD

**Issue by jwaltrip4** [darkoperator/Posh-SSH#309]
As stated in title.
Everything else seems to be working just fine.

**Comment by darkoperator** [comment]
Is the file a large one? For small files it happens so fast it does not show progress

**Comment by jwaltrip4** [comment]
Very small.  Maybe 2.5 k

Have same with get-scpfolder....  that is 10 to 50 html files.  No large.

But had Hoped to see it as it tells me it is working :)

**Comment by darkoperator** [comment]
For such small files -Verbose would be the best option. Printing progress for very small sizes slows down transfer considerably and the library does not report progress for each byte causing the progress bar to hang and stay on screen. SO this behavior is by design.

**Comment by jwaltrip4** [comment]
I will try that.  thanks
