### ISSUE TITLE
Error: New-SFTP Session

### ISSUE THREAD

**Issue by thezackm** [darkoperator/Posh-SSH#310]
> OS: Server 2019
> PS Version: 5.1.17763.592
> Module: Posh-SSH 2.2

I am having inconsistencies with passing a credential in the `New-SFTPSession` cmdlet as seen below.

When interactively adding the credentials using `Get-Credential`, everything works as expected.
```
New-SFTPSession -ComputerName "127.0.0.1" -Credential ( Get-Credential ) -AcceptKey -Verbose | Format-List -Property *
```

![image](https://user-images.githubusercontent.com/30831476/75586613-6f4ad680-5a3a-11ea-8935-1092db8eaf95.png)

However, when passing in a prebuilt PSCredential Object, the connection fails to authenticate.
```
$username = "Administrator"
$password = ConvertTo-SecureString "P@$$w0rd!" -AsPlainText -Force
$psCred = New-Object System.Management.Automation.PSCredential -ArgumentList ($username, $password)
New-SFTPSession -ComputerName "127.0.0.1" -Credential $psCred -AcceptKey -Verbose | Format-List -Property *
```

![image](https://user-images.githubusercontent.com/30831476/75586842-c94b9c00-5a3a-11ea-828d-08b8308be851.png)

This error is consistent across multiple user/pass combinations

**Comment by darkoperator** [comment]
You are using double quotes instead of single quotes for the password so the $ is being interpreted inside the string 

```
PS C:\Users\administrator> $username = "Administrator"
PS C:\Users\administrator> $psCred = New-Object System.Management.Automation.PSCredential -ArgumentList ($username, $password)
PS C:\Users\administrator> $username = "Administrator"
PS C:\Users\administrator> $password = ConvertTo-SecureString "P@$$w0rd!" -AsPlainText -Force
PS C:\Users\administrator> $psCred = New-Object System.Management.Automation.PSCredential -ArgumentList ($username, $password)
PS C:\Users\administrator> $psCred.GetNetworkCredential() | fl *


UserName       : Administrator
Password       : P@Administratorw0rd!
SecurePassword : System.Security.SecureString
Domain         :
```

**Comment by thezackm** [comment]
holy smokes; confirmed and corrected. thanks for the second set of eyes to catch that.
