### ISSUE TITLE
NEW-SFTPSession : Permission denied (password)

### ISSUE THREAD

**Issue by BubblestheKhan** [darkoperator/Posh-SSH#311]
Hi,

I am trying to access the SFTP but when I use the script below, it gets the "NEW-SFTPSession : Permission denied (password)" error. Please see below:

$password = password
$username = SFTPusername
$sftpPassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$sftpCredential = [pscredential]::New($username,$password)
New-SFTPSession -ComputerName sftp.test.com -Credential $sftpCredential -Accept  -verbose

I tried the password in the normal Get-Credential prompt and it works perfectly fine. Not sure what the error could be. 

![image](https://user-images.githubusercontent.com/11967550/75932797-5aa97c80-5e46-11ea-9008-a2ce09a661f4.png)

**Comment by darkoperator** [comment]
Does your password has any special characters that may be interpreted by PowerShell? Try enclosed in single quotes

**Comment by BubblestheKhan** [comment]
It is enclosed in single quotes, and there are no special characters.

**Comment by darkoperator** [comment]
Only thing that comes to mind is you checking the password in the pscredential object since it works with get-credential. 

Like in this recent issue https://github.com/darkoperator/Posh-SSH/issues/293

**Comment by BubblestheKhan** [comment]
Password is correct from what I see

**Comment by darkoperator** [comment]
I do not believe it is an issue with the module since the PSCredential object from get-credential works. Only advice I can give is to check logs on the target system as to see why it was denied. In would also create a credential object with both methods and compare, but the issue is with the object and not the module

**Comment by tjsas1** [comment]
Just want to share that on our testing. It was because the password was enclosed using double quote instead of single quote. To fix, please use single quote.
