### ISSUE TITLE
New/Set-SFTPItem exception on Windows Server 2019

### ISSUE THREAD

**Issue by dbrennand** [darkoperator/Posh-SSH#313]
Using `New-SFTPItem` I am receiving the following error when attempting to create a file on a Windows Server 2019 VM: 
```
Exception calling "Get" with "1" argument(s): "No such file"
```
The command I am using: 
```powershell
New-SFTPItem -SFTPSession $SFTPSession -Path "C:\Users\username\test.json" -ItemType "File"
```
I have also tried using linux pathing using forward slashes. The strange thing is the error occurs, but the file is created on the VM. Furthermore, trying to then set the contents of this file using `Set-SFTPItem` produces the following error: 
```
Set-SFTPItem : C:\Users\username does not exist
```
The command I am using for this:
```powershell
Set-SFTPItem -SFTPSession $SFTPSession -Destination "C:\Users\username" -Path "test.json" -Force -Verbose:($PSBoundParameters["Verbose"] -eq $true) -ErrorAction "Stop"
```
I have verified that the file is in fact created in the correct path and the destination path exists.

**Comment by darkoperator** [comment]
For creating a file and setting its content by hand would be something like this:
```
PS C:\Users\carlos\Documents\Posh-SSH\Release> New-SFTPItem -SessionId 0 -Path "/tmp/test.json" -ItemType file


FullName       : /tmp/test.json
LastAccessTime : 3/16/2020 8:06:02 AM
LastWriteTime  : 3/16/2020 8:06:02 AM
Length         : 0
UserId         : 1000



PS C:\Users\carlos\Documents\Posh-SSH\Release> Set-SFTPContent -SessionId 0 -Path "/tmp/test.json" -Value "this is a test" -Encoding UTF8


FullName       : /tmp/test.json
LastAccessTime : 3/16/2020 8:06:02 AM
LastWriteTime  : 3/16/2020 8:07:24 AM
Length         : 14
UserId         : 1000
```

Set-SFTPItem is to upload a file with its content, if a file already exists already you will get the error
```
C:\Users\carlos\Documents\Posh-SSH\Release> Set-SFTPItem -SessionId 0 -Destination "/tmp" -Path .\PoshSSH.dll -Verbose
BOSE: Uploading C:\Users\carlos\Documents\Posh-SSH\Release\PoshSSH.dll to /tmp

PS C:\Users\carlos\Documents\Posh-SSH\Release> Get-SFTPChildItem -SessionId 0 -Path /tmp | where fullname -like "*dll"


FullName       : /tmp/PoshSSH.dll
LastAccessTime : 3/16/2020 8:11:41 AM
LastWriteTime  : 3/16/2020 8:11:41 AM
Length         : 62976
UserId         : 1000



PS C:\Users\carlos\Documents\Posh-SSH\Release> Set-SFTPItem -SessionId 0 -Destination "/tmp" -Path .\PoshSSH.dll -Verbose
VERBOSE: Uploading C:\Users\carlos\Documents\Posh-SSH\Release\PoshSSH.dll to /tmp
Set-SFTPItem : File already exists on remote host.
At line:1 char:1
+ Set-SFTPItem -SessionId 0 -Destination "/tmp" -Path .\PoshSSH.dll -Ve ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (SSH.SftpSession:SftpSession) [Set-SFTPItem], SftpPermissionDeniedException
    + FullyQualifiedErrorId : File already exists on remote host,SSH.SetSftpItem

PS C:\Users\carlos\Documents\Posh-SSH\Release>

```

**Comment by darkoperator** [comment]
dont have a Win 2k19 system to test, will try later today to build one and setup SSH on it

**Comment by dbrennand** [comment]
> 
> 
> For creating a file and setting its content by hand would be something like this:
> 
> ```
> PS C:\Users\carlos\Documents\Posh-SSH\Release> New-SFTPItem -SessionId 0 -Path "/tmp/test.json" -ItemType file
> 
> 
> FullName       : /tmp/test.json
> LastAccessTime : 3/16/2020 8:06:02 AM
> LastWriteTime  : 3/16/2020 8:06:02 AM
> Length         : 0
> UserId         : 1000
> 
> 
> 
> PS C:\Users\carlos\Documents\Posh-SSH\Release> Set-SFTPContent -SessionId 0 -Path "/tmp/test.json" -Value "this is a test" -Encoding UTF8
> 
> 
> FullName       : /tmp/test.json
> LastAccessTime : 3/16/2020 8:06:02 AM
> LastWriteTime  : 3/16/2020 8:07:24 AM
> Length         : 14
> UserId         : 1000
> ```
> 
> Set-SFTPItem is to upload a file with its content, if a file already exists already you will get the error
> 
> ```
> C:\Users\carlos\Documents\Posh-SSH\Release> Set-SFTPItem -SessionId 0 -Destination "/tmp" -Path .\PoshSSH.dll -Verbose
> BOSE: Uploading C:\Users\carlos\Documents\Posh-SSH\Release\PoshSSH.dll to /tmp
> 
> PS C:\Users\carlos\Documents\Posh-SSH\Release> Get-SFTPChildItem -SessionId 0 -Path /tmp | where fullname -like "*dll"
> 
> 
> FullName       : /tmp/PoshSSH.dll
> LastAccessTime : 3/16/2020 8:11:41 AM
> LastWriteTime  : 3/16/2020 8:11:41 AM
> Length         : 62976
> UserId         : 1000
> 
> 
> 
> PS C:\Users\carlos\Documents\Posh-SSH\Release> Set-SFTPItem -SessionId 0 -Destination "/tmp" -Path .\PoshSSH.dll -Verbose
> VERBOSE: Uploading C:\Users\carlos\Documents\Posh-SSH\Release\PoshSSH.dll to /tmp
> Set-SFTPItem : File already exists on remote host.
> At line:1 char:1
> + Set-SFTPItem -SessionId 0 -Destination "/tmp" -Path .\PoshSSH.dll -Ve ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (SSH.SftpSession:SftpSession) [Set-SFTPItem], SftpPermissionDeniedException
>     + FullyQualifiedErrorId : File already exists on remote host,SSH.SetSftpItem
> 
> PS C:\Users\carlos\Documents\Posh-SSH\Release>
> ```

What OS are you running those commands against? A Windows box?

**Comment by darkoperator** [comment]
A Ubuntu system, don’t have Windows test targets with SSH enabled at the moment. Installing one today

**Comment by dbrennand** [comment]
Thanks, I was using it incorrectly. However, deleting the file and using Set-SFTPItem as you propose still doesn't work. It errors with directory doesn't exist and doesn't create the file on the target machine.

Furthermore, using the first example `New-SFTPItem` and `Set-SFTPContent`. Does work however, when running both, they produce the following errors:


```
New-SFTPItem -SessionId $SFTPSession.SessionId -Path "C:\Users\username\test.json" -ItemType "File"
Exception calling "Get" with "1" argument(s): "No such file"

Set-SFTPContent -SessionId $SFTPSession.SessionId -Path "C:\Users\username\test.json" -Value "testing" -Encoding UTF8 -Verbose
VERBOSE: Saving a String to C:\Users\username\test.json.
Set-SFTPContent : Failed to write content to file C:\Users\username\test.json
```
The workaround we have found is using the following:
```powershell
Set-SCPFile -ComputerName $PublicIP -AcceptKey $true -KeyFile $SSHPrivateKeyPath -Credential $Credential -LocalFile "test.json" -RemotePath "C:\Users\username" -Verbose
```

**Comment by dbrennand** [comment]
So after some more troubleshooting.

It is possible to place it in the correct directory on windows. The usage is as follows:
```powershell
Set-SFTPItem -SFTPSession $SFTPSession -Destination "/Users/username" -Path "test.json" -Force -Verbose:($PSBoundParameters["Verbose"] -eq $true) -ErrorAction "Stop"
```

There is no way to supply the drive letter so it looks like on Windows, if you wanted to place the file anywhere other than C:\, I cannot see how this would work. Also, it looks like it only accepts Linux paths.

**Comment by dbrennand** [comment]
Nevermind, so looking into it some more. It is possible to create files on other drive letters. But it's just the syntax for the path is pretty crazy 😄 

```powershell
Get-SFTPLocation -SessionId $SFTPSession.SessionId
/C:/Users/aksengineclientuser
New-SFTPItem -SessionId $SFTPSession.SessionId -Path "/D:/test.json" -ItemType "File"


FullName       : /D:/test.json
LastAccessTime : 16/03/2020 13:56:58
LastWriteTime  : 16/03/2020 13:56:58
Length         : 0
UserId         : 0
```

**Comment by darkoperator** [comment]
Ahhhh so it is working as expected? I have been fighting Windows 2019 to allow me to set a local user to auth remotely ..

**Comment by dbrennand** [comment]
It is odd because Set-SCPFile allows the remote path to be a Windows path ie with backslashes. Whereas, NewSFTPItem produces the error: `Exception calling "Get" with "1" argument(s): "No such file"` but does create the file on the remote host. I believe something with an underlying library is causing an issue here. Specifically, the error points to a Get path method.

```
At C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\2.2\Posh-SSH.psm1:2499 char:25
+                         $sess.Session.Get($Path)
```

**Comment by darkoperator** [comment]
SCP and SFTP are 2 different implementations with specs, could be SFTP tries to be as close as FTP as possible maybe

**Comment by darkoperator** [comment]
can I close the issue

**Comment by dbrennand** [comment]
Yeah this issue is resolved.
