### ISSUE TITLE
New-SSHSession : Failed to negotiate key exchange algorithm.

### ISSUE THREAD

**Issue by dbrennand** [darkoperator/Posh-SSH#314]
Hello 😄 

I am receiving the following error when attempting to use POSH-SSH to create a New-SSHSession to a machine:
```New-SSHSession : Failed to negotiate key exchange algorithm.```
SSHing to the VM manually works. On further debugging the key algorithm being used is: `debug1: kex: algorithm: curve25519-sha256`.

I believe this relates to issue: https://github.com/sshnet/SSH.NET/issues/461.

**Comment by darkoperator** [comment]
Yes that cipher is not supported at the moment.

**Comment by darkoperator** [comment]
you can reopen the ticket after the next release. SSH.Net will release a new versions and once they do I will release a new version supporting.

**Comment by dbrennand** [comment]
Hmmm a strange way of approaching it. Shouldn't this issue be left open until it is fixed... ??

**Comment by darkoperator** [comment]
You are correct, should have linked the other tickets for the same issue that are open. Will don that later today. There is an alpha version thst should support the cipher under releases, can you test with that one?

**Comment by dbrennand** [comment]
Are you aware of what key exchange algorithms are supported?

**Comment by darkoperator** [comment]
Current version is in the README and alpha version is on the release notes.

Supports diffie-hellman-group-exchange-sha256, diffie-hellman-group-exchange-sha1, diffie-hellman-group14-sha1 and diffie-hellman-group1-sha1 key exchange methods.

**Comment by dbrennand** [comment]
> 
> 
> you can reopen the ticket after the next release. SSH.Net will release a new versions and once they do I will release a new version supporting.

Hey @darkoperator, any updates with SSH.NET upstream to support more key exchange algorithms ciphers?
