### ISSUE TITLE
credential with private key

### ISSUE THREAD

**Issue by Ponder-Stibbons-U** [darkoperator/Posh-SSH#319]
Hi, we would use a script for filehandling between SAP and a Unix-device, so far so good, but the Password for the Server expires every three months. there is a private and a public Key for the log- in, but unfortunably I dont have a idea how to integreate this in our script. here is the example for the login with  Password:

$password = ConvertTo-SecureString "Password" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential("user",$password)
$session = New-SFTPSession -ComputerName Server -Credential $credential -ConnectionTimeOut 300 -Port 22
$session

I hope you can help me
and thanks in advance

**Comment by barky11** [comment]
This should work. I've used the same style before for SSH public key authentication.

    $nopasswd = new-object System.Security.SecureString
    $credential = New-Object System.Management.Automation.PSCredential ("user",$nopasswd)

    New-SFTPSession -computername Server -credential $credential -ConnectionTimeOut 300 -Port 22 -Keyfile "Private_Key"

**Comment by Ponder-Stibbons-U** [comment]
Thank you, I've already tried it that way, unfortunately it did not work, the existing key is not linked to a user and that will be the problem. it doesn't seem to work without specifying a user. I am now trying to create a key pair for a user.








it doesn't seem to work without specifying a user

**Comment by darkoperator** [comment]
Correct the entire logic is around a user + key or user + password. Not key only. It is the only supported methods by the library
