### ISSUE TITLE
SFTP authentication with password and private key

### ISSUE THREAD

**Issue by PowerShell2020** [darkoperator/Posh-SSH#326]
Hello,

first off thank you very much for Posh-SSH. 
I have an issue.
My destination is a ftp server. This ftp server is using a password and a private key for authentication.
On stackoverflow I read that if you set a password and you use a keyfile then the password will be used for the keyfile and not for the ftp server credentials.
Without a keyfile the password will be used for the ftp server credentials.

Is there a way that I can set a password for the keyfile AND for the ftp server credentials or is the only way to get around that issue to remove the password from the ftp server and only using the keyfile?

Thank you.

Powershell2020

**Comment by darkoperator** [comment]
The module is for SFTP as part of SSH and not for FTP over SSL, want to make sure there is no confusion there, many times people have had that happened. In SSH you can authenticate with a Key that is protected with passphrase. The passphrase is used to encrypt the key file. By associating the key to a user you can us something you have and know to authenticate. With the library I use I support the first method method mentioned in this article. The second one is not supported https://askubuntu.com/questions/1019999/key-based-ssh-login-that-requires-both-key-and-password <https://askubuntu.com/questions/1019999/key-based-ssh-login-that-requires-both-key-and-password>

**Comment by PowerShell2020** [comment]
Thank you for your fast reply.
I use SFTP-3 with SSH-2.
So let me get this right. 
If I have a server who requires a private key (password protected), a username and a password for authentication I can't use your module?
Your module only works if the server wants a username and a keyfile but not a password for authentication?

**Comment by PowerShell2020** [comment]
https://stackoverflow.com/questions/52896957/provide-private-key-passhprase-password-for-posh-ssh-new-sshsession
Please look at the answers.
That is the issue I have.

**Comment by darkoperator** [comment]
If you want key with passphrase + Username + password no
Username and  key with passphrase  yes

**Comment by darkoperator** [comment]
The Credential object when no key is used is the users username and password. When a key is used the objects password is used as the keys passphrase

**Comment by PowerShell2020** [comment]
So two-factor authentication not possible. 
It's a shame it doesn't work that way.

Thank you very much for your fast replies.
Have a nice day.

Powershell2020
