### ISSUE TITLE
Set-SFTPFile: Function returns before upload is ready

### ISSUE THREAD

**Issue by xyz0815** [darkoperator/Posh-SSH#327]
I've made a powershell function "Backup-Direcrory" that is used in a larger backup system but can also be used by itself to backup a single directory as zip archive. In a last step, it moves the archive to a target directory OR uploads it to a SFTP server.

Everything is going well until the archives get larger than around 120MB.

While the SFTP upload progress is still showing, the script suddenly proceeds until it returns.
Subsequently, the whole powershell window crashes.

The uploaded data is ok, even for big files > 1GB, but the function cannot be used in a larger context because it ends the calling script immediately.

I've added a screenshot that documents the behavior in MS Terminal.

The relevant code looks like this (you can see I've already tried the timeout parameters of New-SFTPSession):

```
  if($useSFTP){ 
        
	$sftpSession = New-SFTPSession -ComputerName $sshServer -Credential $sshCredentials -Force -OperationTimeout 600 -ConnectionTimeout 600 -KeepAliveInterval 5

        Get-SFTPChildItem -SFTPSession $sftpSession -Path $TargetDirectory |
            Where-Object {$_.Name.EndsWith("-$archiveBaseName.zip")} | 
            Sort-Object Name -Descending | 
            Select-Object -skip 6 | 
            ForEach-Object { Remove-SFTPItem -SFTPSession $sftpSession -Path $_.Fullname -Force }

    }

    Write-Host "Creating archive $now-$archiveBaseName.zip ..."
    & $7z a $archiveZip $SourceDirectory | Out-Null
    $archiveZipFile = Get-ChildItem $archiveZip

    $hash = (Get-FileHash $archiveZip -Algorithm 'SHA256').Hash
    $bckRecContent = $hash + ":" + $archiveZipFile.Name + ":" + $archiveZipFile.Length
    $bckRecContent | Out-File -FilePath $archiveBckRec -Encoding utf8 -Force

    if($useSFTP){
        Write-Host "SFTP Upload ..."
        Set-SFTPFile -SFTPSession $sftpSession -LocalFile $archiveZip -RemotePath $TargetDirectory -Overwrite:$true
        Set-SFTPFile -SFTPSession $sftpSession -LocalFile $archiveBckRec -RemotePath $TargetDirectory -Overwrite:$true
        Remove-SFTPSession -Session $sftpSession | Out-Null
        Remove-Item $archiveZip
        Remove-Item $archiveBckRec
    }
```
Please note that the manual upload of the same file to the same server via WinSCP works fine.
The issue happens on both Win10-boxes with PS 5.1 I've tested with.
I also tried Set-SFTPItem => same issue.

Thank you for your time!
![Set-SFTPFile](https://user-images.githubusercontent.com/327665/81511592-c6aed200-931a-11ea-88bd-165a2ad5dd5b.png)

xyz0815

**Comment by xyz0815** [comment]
Closing the issue - switched to other library.

**Comment by darkoperator** [comment]
Can you share to which one you switch to?

**Comment by xyz0815** [comment]
WinSCPnet.dll - works great, is thoroughly documented and runs also in powershell core.
