### ISSUE TITLE
Set-SCPFolder transfer speed

### ISSUE THREAD

**Issue by McGreggor** [darkoperator/Posh-SSH#328]
Hi,

FYI - Set-SCPFolder upload speed is only around 100KB/s for me, same files/hosts using winscp is much faster around 27MB/s.  I note from a previous issue there was a similar performance issue with Set-SCPFile which was resolved, and the performance of that cmdlet is comparable to winscp speeds, so it would be good to have the same optimisations in Set-SCPFolder please ;)

**Comment by darkoperator** [comment]
If you disable progress report it should be faster. The showing of progress impacts performance
