### ISSUE TITLE
"New-SshSession : Key exchange negotiation failed" after OpenSSH 8.x upgrade AIX

### ISSUE THREAD

**Issue by netaware-NJ** [darkoperator/Posh-SSH#329]
Hello, I am using POSH-SSH v2.2 with Windows 10 and PS v5. connecting to an AIX server.
 **Everything was working fine until AIX techs recently updated to OpenSSH to v8.x.** 
Now i am getting _"New-SshSession : Key exchange negotiation failed"_

Can you please help? MY AIX Techs have tried everything and it seems to be pointing to POSH-SSH on my Windows machine

**AIX techs added but still no luck:** 
sshd -T |grep -i kex
kexalgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1

**Here is additional info on my Powershell env:**
PS> Get-SSHTrustedHost
SSHHost     Fingerprint
11.3.43.245 7e:82:7a:32:d4:c4:d6:68:ed:5c:de:a8:e0:88:9a:58

PS> $psversiontable
Name                           Value
PSVersion                      5.1.17134.858
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.858
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS> Find-Module Posh-SSH
Version    Name                                Repository           Description
2.2        Posh-SSH                            PSGallery            Provide SSH and SCP functionality for executing commands against remote hosts.

**Comment by darkoperator** [comment]
Try the alpha under the releases, more than likely is a cipher change. Waiting for the underlying library to release an oficial release with the added support  to then release an updates version

**Comment by netaware-NJ** [comment]
Alpha release of POSH-SSH?  where can i get them?

**Comment by netaware-NJ** [comment]
sorry closed by accident

**Comment by netaware-NJ** [comment]
what version should i try?

**Comment by darkoperator** [comment]
https://github.com/darkoperator/Posh-SSH/releases/tag/2.3-alpha

**Comment by netaware-NJ** [comment]
Got it! do i need to uninstall old version, 2.2?

**Comment by netaware-NJ** [comment]
Hello, I installed 2.3 alpha. Initially, it didn't work, I got the same message. 
However when I used the -force parameter, it worked!
Please tell me what that -force parameter does!

THANK YOU!!!

**Comment by darkoperator** [comment]
It ignored the ssh key fingerprint. Probably they it changed in the upgrade because it changed ciphers

**Comment by netaware-NJ** [comment]
v2.2 doesn't have that feature, correct? i don't remember seeing it.

**Comment by darkoperator** [comment]
It does

**Comment by wsmelton** [comment]
Confirm I got this on Ubuntu 18.04 as well and the `-Force` parameter addresses it. In my case though the fingerpint has not changed, I'm just using `New-SSHSession` to test as a heartbeat of sorts for the user's password.

```powershell
try {
	$session = New-SSHSession -ComputerName $Server -Credential $cred -AcceptKey -ErrorAction Stop -Force
	$session | Remove-SSHSession > $null
	return $true
} catch {
	throw "Error connecting to $Server - $($_.Exception)"
}
```

Side note that 2.3 fixes import on Server 2019 as well, which I've found is only an issue on the desktop release. I can use 2.2 on the non-desktop release of Server 2019 with no issues at all. I'm fairly sure it is something with the dotnet on that OS, missing a version one of the dependent DLLs requires but have not been able to track it down.

**Comment by darkoperator** [comment]
Force cancels accept key, it will simply not validate the key against the values in the registry or promp to confirm it

**Comment by netaware-NJ** [comment]
Thanks for all the help! My fingerprint hadn't changed either. The -force helped that.

**Comment by netaware-NJ** [comment]
Sorry but i have one more question:
How do i stop this message from appearing when i use the -Force parameter
WARNING: Host key is not being verified since Force switch is used.

**Comment by darkoperator** [comment]
Piping the output to out-null

**Comment by wsmelton** [comment]
You can simply add this to your call of the command `-WarningAction SilentlyContinue` and it will prevent you from seeing the warning.

**Comment by dbrennand** [comment]
I'm not sure if this is related however, when attempting to do the following:
```powershell
$BlankPassword = New-Object -TypeName System.Security.SecureString
$Credential = New-Object PSCredential -ArgumentList ("username", $BlankPassword)
$MasterSshSession = New-SSHSession -ComputerName "iphere" -AcceptKey -KeyFile ".\id_rsa" -Credential $Credential -Verbose:($PSBoundParameters["Verbose"] -eq $true) -ErrorAction "Stop"
```
I receive the key exchange negotiation failed error.
With the `-Force` parameter it works. However, it should be working without 🤔 

I have troubleshooted a little and the key exchange algorithm on the server is: `KexAlgorithms curve25519-sha256@libssh.org`

Checking the authorized_keys file the correct public key is present. So not sure why the exchange is failing.

I am using the latest beta module:
```powershell
Get-Module -ListAvailable Posh-SSH

VERBOSE: Populating RepositorySourceLocation property for module Posh-SSH.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\2.3.0\PoshSSH.dll'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\2.3.0\Posh-SSH.psm1'.


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   2.3.0      Posh-SSH                            {Get-SCPFile, Get-SCPFolder, Get-SCPItem, Get-SFTPFile...}

Any other troubleshooting suggestions?

**Comment by darkoperator** [comment]
Has the key on this host changed? try Get-SSHTrustedHost | Remove-SSHTrustedHost

**Comment by dbrennand** [comment]
> 
> 
> Has the key on this host changed? try Get-SSHTrustedHost | Remove-SSHTrustedHost

Hey @darkoperator thanks for the response. 
I believe this may have been the issue 🤦 Thanks for your assistance. 😄

**Comment by DjBangAdmin** [comment]
> I receive the key exchange negotiation failed error.
> With the `-Force` parameter it works. However, it should be working without 🤔

adding -Force did the trick for me
