### ISSUE TITLE
Cisco SG300

### ISSUE THREAD

**Issue by fluidityUK** [darkoperator/Posh-SSH#333]
Hi,

I am new to the module, but love the idea!

I am trying to connect to a Cisco SG300. I can run New-SSH and create the connection, the swich log files show the log in as sucessful.

However, when I run Invoke-SSHCommand -SessionId 0 -Command "show run" I get a timeout error.  -Verbose doesn't provide any additional information, and the switch doesn't log any activity.  

Exception calling "EndExecute" with "1" argument(s): "Command 'show run' has timed 
out."
At C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\2.2\Posh-SSH.psm1:260 char:25
+                         $Output = $_.cmd.EndExecute($_.Async)
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SshOperationTimeoutException

Running the command in a PUTTY session work perfectly. 

Any thoughts on what I am doing wrong here?

Thanks

David

**Comment by darkoperator** [comment]
For Cisco gear you need to use a ShellStream since Cisco does not have binaries but a shell for all of its commands. Invoke-SSHCommand behaves like Plink.
