### ISSUE TITLE
Can I to make fortigate config download with posh-ssh?

### ISSUE THREAD

**Issue by marcelo-0511** [darkoperator/Posh-SSH#335]
Hello, I have some fortigates and i want to make backups using posh-ssh, is that possible?

under is the fortinet KB: 

https://kb.fortinet.com/kb/documentLink.do?externalID=FD43754

but my fortigate are not using the default ssh port.

**Comment by marcelo-0511** [comment]
At the moment i am using the PSCP but it is hangs all time when it is running in a script.

**Comment by darkoperator** [comment]
You can specify the port with the -port parameter in the scp functions

**Comment by marcelo-0511** [comment]
can you show me a example?

In PSCP I am doing it this way:

pscp.exe -P 4022  admin@198.18.0.214:sys_config c:\bkp\myfortigatebackup.txt 
In PSPC it works.

In Get-SCPFile, I am doing this way:
![image](https://user-images.githubusercontent.com/67024069/85015724-d94cd000-b13e-11ea-8b60-633264652f90.png)

And it is not working.

:(

**Comment by marcelo-0511** [comment]
And when I execute this command the powershell Hangs.

**Comment by darkoperator** [comment]
Let me guess again a Fortinet device. Any specific model ? It seems to connect and pull the information based on the verbose messages so it is connecting on the port. As to why it is hanging I have no clue since no error is shown. Are you running as Administrator the PowerShell prompt?

**Comment by darkoperator** [comment]
Been trying to replicate with linux hosts with no luck. This is a recent install of ubuntu 20 server

**Comment by marcelo-0511** [comment]
Hello, thanks for your time.
 Yes, they are fortigate devices, it is ocurring in any device.
I did a test like powershell administrator, and the error is the same.

![image](https://user-images.githubusercontent.com/67024069/85211135-61d49780-b31c-11ea-840a-5561b399973f.png)

**Comment by marcelo-0511** [comment]
If you want, I could get a test fortivm.

**Comment by marcelo-0511** [comment]
I did the test in some fortigates and FortiVMs and the behavior is the same.

**Comment by marcelo-0511** [comment]
![image](https://user-images.githubusercontent.com/67024069/85211377-ecb69180-b31e-11ea-81f9-7168da8abf49.png)

above is a verbose from pscp

**Comment by marcelo-0511** [comment]
And a fortigate log:
![image](https://user-images.githubusercontent.com/67024069/85211400-2edfd300-b31f-11ea-89f0-1e26979d8ce4.png)


When I tried get-scpfile no one log shows.

**Comment by darkoperator** [comment]
Requested a demo of the FortigateOS VM to test on my side. So far all the those ciphers should be supported in the Beta1 and all my tests against Linux and Windows hosts are working. I do not know what change they could have done to their fork of OpenSSH.

**Comment by marcelo-0511** [comment]
Hello, Good Morning

Yes, it is so stranger, is there more tests that i can to do?

**Comment by darkoperator** [comment]
Sadly no, waiting for Fortinet to approve me downloading the VM

**Comment by marcelo-0511** [comment]
![image](https://user-images.githubusercontent.com/67024069/85296421-bf312b80-b477-11ea-8e12-82f3fe6e58de.png)

that is my posh version.

**Comment by darkoperator** [comment]
Yes

**Comment by darkoperator** [comment]
Was this issue also caused by the deep packet inspection?
