### ISSUE TITLE
Newest module version does not export the command New-SFTPSession

### ISSUE THREAD

**Issue by hematic** [darkoperator/Posh-SSH#336]
Under functions to Export "New-SFTPSession" is not included in version 2.2.

The command is still there in the code but it isn't exported and therefore you cant call it.

**Comment by darkoperator** [comment]
If you do a import-module posh-ssh -verbose does it not show as loading? How did you install the module?

**Comment by jcoryatjr** [comment]
I have not seen this. I am 2.2 and that cmdlet is exported and visible.

**Comment by darkoperator** [comment]
have not been able to replicate this issue

**Comment by sdeycode** [comment]
Trying to install posh-ssh module in powershell 5. What am I doing wrong? I could install the Posh-ssh in powershell 7 (which is core) but several functionalities for sftp is not working in powershell 7
![Posh-ssh issue_unable to install in Powershell5](https://user-images.githubusercontent.com/69658611/90203114-6ca02b80-dda5-11ea-91fa-6847b2fc7db7.png)

**Comment by darkoperator** [comment]
Trying to check but seem the PowerShell gallery is down at this moment dont know if that is the issue

**Comment by sdeycode** [comment]
We could downoad powershell 7. Is there an alternate way to install the package?

**Comment by darkoperator** [comment]
You can download the release and place it in one of your modules paths. https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-packages/manual-download
