### ISSUE TITLE
Result of New-SSHShellStream cannot be traced back to SSHSession object

### ISSUE THREAD

**Issue by janhanekom** [darkoperator/Posh-SSH#34]
Hi

Feature request:  would it be possible to incorporate something into either SSHSession or SSHShellStream objects that allow them to be related to each other?

I'm finding it difficult detecting whether an SSHShellStream session is still connected, and also whether it's connected to the host I'm expecting it to be connected to.

If I could relate a SSHShellStream to an SSHSession, I could for example use the "connected" property of the SSHSession to get a reasonable estimate of whether I should try to send commands over the SSHShellStream.  For now, I'm tearing down and creating a new SSHShellStream too often, which is a slow operation.

**Comment by darkoperator** [comment]
would something like this be what you would like?
```Powershell
PS C:\> $sshstream = New-SSHShellStream -SessionId 0
PS C:\> $sshstream | fl


SessionId     : 0
Session       : Renci.SshNet.SshClient
DataAvailable : True
CanRead       : True
CanSeek       : False
CanWrite      : True
Length        : 79
Position      : 0
CanTimeout    : False
ReadTimeout   :
WriteTimeout  :



PS C:\> $sshstream.Session

ForwardedPorts           ConnectionInfo                        IsConnected KeepAliveInterval
--------------           --------------                        ----------- -----------------
{}                       Renci.SshNet.Connecti...                     True 00:00:10

```

**Comment by janhanekom** [comment]
That would be most useful, yes!

**Comment by darkoperator** [comment]
ok I will push that to 1.7.2 and make a github release and update the module in the PowerShell gallery
