### ISSUE TITLE
<---More---> kind of output using shellstream

### ISSUE THREAD

**Issue by Deepan824** [darkoperator/Posh-SSH#341]
Good Day.!

I have been using Posh-SSH for automating linux & Unix boxes which is awesome.

In this case I am using shellstream method to get the output .

Shellstream method is working properly as I am getting the output but it is partial and not full.

Kindly help in getting the Full output.. Thanks!

**Sample Output:**

![posh](https://user-images.githubusercontent.com/68958236/88812570-7e92a380-d1d5-11ea-8e68-40536194ad48.png)

**Script Sample:**
$session = $swssh.SessionId
$stream =New-SSHShellStream -SessionId $session -TerminalName dumb
$stream.Write("Show disk`n")
Start-Sleep -Milliseconds 2000
$res=$stream.Read()
$res|Out-String -Width 4096 
Remove-SSHSession -SessionId $session

**Comment by darkoperator** [comment]
You need to send a backtick n so it will page and give you the rest

**Comment by Deepan824** [comment]
$stream.Write("Show disk`n") - already a backtick n is in place along with the code. should I give one more?

**Comment by darkoperator** [comment]
Yes, you read your stream in a loop until you get the more string using regex and send another and keep doing it untill you get a prompt, you will need to write  a regex that will match om the specific prompt for the device

**Comment by Deepan824** [comment]
Thank you so much Carlos 👍  :-)
