### ISSUE TITLE
no support for elliptic curve (ssh-ed25519) "Failed to negotiate key exchange algorithm"

### ISSUE THREAD

**Issue by fgodskesen** [darkoperator/Posh-SSH#343]
connecting to SSH servers that only support ssh-ed25519 fails with 

PS C:\Users\flgod> $s= New-SSHSession -ComputerName 10.111.20.10 -Credential $cred
New-SSHSession : Failed to negotiate key exchange algorithm.
At line:1 char:5
+ $s= New-SSHSession -ComputerName 10.111.20.10 -Credential $cred
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], SshConnectionException
    + FullyQualifiedErrorId : SSH.NewSshSession

Support for ed25519 is included in SSH.NET since January, so perhaps a merge from SSH.NET is possible?
https://github.com/sshnet/SSH.NET/pull/496

/fgodskesen

**Comment by darkoperator** [comment]
This support is on the beta releases

**Comment by fgodskesen** [comment]
Awesome! Thanks you for the quick reply!

**Comment by fgodskesen** [comment]
fixed in the beta.
