### ISSUE TITLE
Switch user

### ISSUE THREAD

**Issue by green0tree22** [darkoperator/Posh-SSH#344]
``new-sshsession -computername myip -credential (get-credential) i got connected to target machine then i execute invoke-sshcommand -index 0 -command "uname: -a; cd/ ;ls -l but no results?

Or is there a switch user parameters?

**Comment by darkoperator** [comment]
Ivoke-sshcommand is like plink it executes a binary on the bin, sbin or full path provided with the arguments you give it for a complete shell use sshshellstream

**Comment by green0tree22** [comment]
Hi 
I just found a script using the 
invoke-sshstreamexpectsecureaction -stream new-sshshell stream -commamd 'user2' -expectstring 'password:' -secureaction (read-host -assecurestring) -verbose

But there is a output that the tput:unknown terminal "PoshSShTerm"
And i noticed it exit

**Comment by darkoperator** [comment]
In the terminal when you create it use xterm as the name, this is fixed in the beta versions

**Comment by green0tree22** [comment]
Should i used  -terminalbmname xterm?

**Comment by darkoperator** [comment]
Yes

**Comment by green0tree22** [comment]
Great it works now.but there is a prob.
Its exited on the console.

I just want once the user2 are able to login i need to execute a command
inside the user2.

Here is the script hope you can help me out.

New-sshsession -computer server -credential user1
$stream=new-sshshellstream -index 0 -terminalname xterm
Invoke-sshstreanexpectsecureaction -shellstream $stream -command
-expectstring 'password:' -secureaction (read-host -assecurestring) -verbose
$stream.read()

The output
Authenticating using Pingid..
Pingid success
User1]$user2
[Sudo] password for user1:

Ps c:\users\user1>

I dont know if i inside the user2 it just exited.
Hope can execute the cimmand in user2?

**Comment by darkoperator** [comment]
The stream should be running under the other user context, just write and read from it issuing commands to check the current context.

**Comment by green0tree22** [comment]
Its working now.
I just add a pipe line
Like
'User2|ls"

Am i right?

**Comment by green0tree22** [comment]
Should i use pipe for every command?

**Comment by darkoperator** [comment]
To be honest no clue, that is more a linux question than a posh-ssh one

**Comment by green0tree22** [comment]
I see...hope this can be solve.
Anyway thanks for your help.

Ill be try to test.
