### ISSUE TITLE
Please push v2.3 beta 2 to PowerShellGallery

### ISSUE THREAD

**Issue by chrgraefe** [darkoperator/Posh-SSH#346]
Please push v2.3 beta 2 to PowerShellGallery

**Comment by TheARKitectsEND** [comment]
I second this, we have some production servers where I haven't been able to talk the team into installing the beta branch. If it is pushed to the pshell gallery as an official release it will be easier to have it updated.

**Comment by legoBenny** [comment]
I would like to upvote this too. we have been using the 2.3 Beta release for 3 months now and it has been working great, but we can't push it to our production environment until it is an official release. If you could at lease let us know if there is a timeline for release it would be much appreciated.

**Comment by darkoperator** [comment]
Ok, will push the version to the gallery as final on Monday after I merge some updates.
