### ISSUE TITLE
Unable to pass keystroke "RETURN/Enter" for message "Press RETURN to get Started" in cisco switch

### ISSUE THREAD

**Issue by VarunDcoder** [darkoperator/Posh-SSH#350]
Hi,

I am trying to use posh-ssh to connect  switches and running commands but when I get this message "Press RETURN to get Started" after reload command this below stream is not working.

$stream.Write("`n").

Could you please check what I am missing here.

**Comment by darkoperator** [comment]
Try carriage return “`r”

**Comment by VarunDcoder** [comment]
Yes, tried but it's also not working.  Giving blank output when i did $stream.Read() .

**Comment by darkoperator** [comment]
Did you see a sleep of a couple fo seconds to give it time to put stuff out in to the stream? Only options that come to mind are `r and `n or both together and then do a loop reading until a loop appears with a counter and a sleep to control how many times to read and for how long.

**Comment by VarunDcoder** [comment]
Yes, Agreed. 
For example when I tried manually using putty by pressing "Enter" after that message, it's getting to "User access verification command" in approx 5 seconds but using code still after making loop and passing through $stream..waiting for 5 to 10 seconds or more..still got stuck at that message only. Any idea?

**Comment by darkoperator** [comment]
No idea
>

**Comment by VarunDcoder** [comment]
Thanks for fast replying..  I will try my best to find the solution and I will update you.

**Comment by VarunDcoder** [comment]
Hi,
Issue resolved now, after giving one extra new line within the loop then it's hitting that keystroke and getting full output.
Thanks.
