### ISSUE TITLE
"instposhsshdev" download script doesn't work now that the PSD1 is under .\Release

### ISSUE THREAD

**Issue by cwmoriarty** [darkoperator/Posh-SSH#352]
iex (New-Object Net.WebClient).DownloadString("https://gist.github.com/darkoperator/6152630/raw/c67de4f7cd780ba367cccbc2593f38d18ce6df89/instposhsshdev") 

This unzips the master, yet the psd1 file is buried in a subdirectory.

I can do a PR to fix later.

**Comment by darkoperator** [comment]
I need to remove that people should be installing from the gallery
