### ISSUE TITLE
FileInfo doesn't properly handle SFTP Working directory

### ISSUE THREAD

**Issue by Szeraax** [darkoperator/Posh-SSH#358]
Please feel free to close this issue as a workaround exists. 

## Environment

Using an SFTP provider with virtual roots disabled (everyone has / as their ~), I have found that I MUST use absolute paths or else I get a permission denied error on $itemInfo.MoveTo(): https://github.com/darkoperator/Posh-SSH/blob/a4b987637a74b41cc7248f173fe27355c3a567a5/Release/Posh-SSH.psm1#L1360

Using .session.RenameFile() does work based on my current working dir, so I assume the bug must be with fileInfo.MoveTo().

Discovered because Move-SftpItem fails if I specify a path that is based on current working dir. 

## Workaround available that I'm using
Specify dest absolute path in the destination or use the session.RenameFile() method.

## Specific error

    Exception calling "MoveTo" with "1" argument(s): "Permission denied"

**Comment by darkoperator** [comment]
the way that the library used works is that for MoveTo you need to specify a full path. This would need to be an issue opened with the SSH.Net project if you want the change
