### ISSUE TITLE
Chained sessions

### ISSUE THREAD

**Issue by eosfor** [darkoperator/Posh-SSH#36]
It would be great to have an option to open chained sessions in one command. I mean when we go to some jumpbox and then connect to some internal server. For such cases it would be ood to have a command which makes a forwarding to port 22 on the second box and then makes a new session via that forwarding.

**Comment by darkoperator** [comment]
You need portforwading and it would not do it in a cmdlet or function since it can lead to problems do to the way the library does currently forwarding and in the future. One forwarding is fixed by the SSH.Net guys I can enable the functions and you should be able to script it or run it by hand. No ETA on it. Hoping for v2.0 they will have it fixed and I can enable the functions.

**Comment by eosfor** [comment]
What is the issue with the library?

---------------------------------------
С уважением, Андрей Вернигора
MCSA, MCDBA, MCSE, MCT


2015-03-26 16:11 GMT+03:00 Carlos Perez <notifications@github.com>:

**Comment by eosfor** [comment]
Perhaps it would be good to just disable dynamic part of forwarding and leave the rest? Looks like issues are only with dynamic part of it?

**Comment by darkoperator** [comment]
the problem also happens with single port. After some data the port gets stuck and will just time out. They say they fixed it in the latest beta but seems to still be broken in my tests, firs minute it work and then it starts getting slower and slower until it just hangs and timeouts connections through it

**Comment by eosfor** [comment]
Here what i tryed to explain:
New-SSHSession -ComputerName server1 -KeyFile keyfile.key -AcceptKey -Credential (Get-Credential userName)
New-SSHLocalPortForward -RemoteAddress 1.1.1.1 -RemotePort 22 -BoundHost localhost -BoundPort 6661 -SessionId 0 -Verbose
New-SSHSession -ComputerName localhost  -Port 6661 -KeyFile keyfile2.key -Credential (Get-Credential userName2)

At first this set of commands is quite complicated. Also on closure int would be good to make sure that second connection going to be closed first.

**Comment by darkoperator** [comment]
Yep I know what you tried to explain. After you have used the third command for a while or use a ssh stream it will start to slow down and then time out after a while. What you want is all that workflow condensed in one command or two commands, problem is that the cmdlets minus Port Forwarding are set to work with groups of machines. I personally do not see it as much work to have the 3 commands and then have logic to have proper stoping of port forwarding before disconnecting the sessions. It would be one ugly set of parameter sets to jam all in in to a single one.

**Comment by eosfor** [comment]
Agree. I'm just trying to find a solution. Perhaps it could be some kind of flag in the list of sessions showing that some sessions are opened via port forwarding to filter them first and close?
I'm not concerned about slowness at the moment as I just need to issue could of commands :). But in general yes, it is bad.

Andrey Vernigora

-----Исходное сообщение-----
От: "Carlos Perez" <notifications@github.com>
Отправлено: ‎27.‎03.‎2015 15:15
Кому: "darkoperator/Posh-SSH" <Posh-SSH@noreply.github.com>
Копия: "eosfor" <eosfor@gmail.com>
Тема: Re: [Posh-SSH] Chained sessions (#36)

Yep I know what you tried to explain. After you have used the third command for a while or use a ssh stream it will start to slow down and then time out after a while. What you want is all that workflow condensed in one command or two commands, problem is that the cmdlets minus Port Forwarding are set to work with groups of machines. I personally do not see it as much work to have the 3 commands and then have logic to have proper stoping of port forwarding before disconnecting the sessions. It would be one ugly set of parameter sets to jam all in in to a single one.

**Comment by eosfor** [comment]
Well, i've found the way of doing this. The "master" session contains forwarded ports, with necessary details, so it is easy to iterate through it
