### ISSUE TITLE
Doesn't work well with Pwsh 

### ISSUE THREAD

**Issue by DH-Illidan** [darkoperator/Posh-SSH#360]
When I use `New-SSHSession`, It occurs:

New-SSHSession: Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

**Comment by darkoperator** [comment]
Because the modules is for Windows PowerShell and not Core or 7
