### ISSUE TITLE
Do not receive full command output from Invoke-SSHCommand 

### ISSUE THREAD

**Issue by hristomirster** [darkoperator/Posh-SSH#364]
Do not receive full command output from Invoke-SSHCommand 

I just only receive a couple of rous ending with 
...}

**Comment by darkoperator** [comment]
What is the command? What is the target platform? Need more details that what is mentioned 
>

**Comment by hristomirster** [comment]
Hi @darkoperator,

let me share more dertails:
Windows server client system:
Windows servever 2012 R2
Target system:
NetApp Release 8.2.5P2 7-Mode: Wed Oct 24 05:14:37 PDT 2018
SE010882> options ssh
ssh.access                   *
ssh.enable                   on
ssh.idle.timeout             0
ssh.passwd_auth.enable       on
ssh.port                     22
ssh.pubkey_auth.enable       on
ssh1.enable                  off
ssh2.enable                  on

The commnads executed form windows client:

$NewSession = New-SSHSession  -ComputerName SE010882.ztbpre.icbpre.commerzbank.com $cred -AcceptKey:$true 

write $NewSession.SessionId

Get-SSHSession

$outputNetappServer = Invoke-SSHCommand -SessionId $NewSession.SessionId -Command "df -gx"
Remove-SSHSession -SessionId $NewSession.SessionId

$outputNetappServer
0

SessionId  Host                                                                                                Connected                                                                                    
---------  ----                                                                                                ---------                                                                                    
    0      SE010882.ztbp...                                                                                       True                                                                                      
True

Output     : {Filesystem               total       used      avail capacity  Mounted on, /vol/SV_SE010867_01/        8GB        0GB        8GB       0%  /vol/SV_SE010867_01/, /vol/SE010910_etc/         
             0GB        0GB        0GB       1%  /vol/SE010910_etc/, /vol/vol1/               120GB       14GB      105GB      12%  /vol/vol1/...}
ExitStatus : 0
Error      : 
Host       : SE010882.ztbpre.icbpre.commerzbank.com
Duration   : 00:00:00.1958958

My cincern si about the output section:
Output     : {Filesystem               total       used      avail capacity  Mounted on, /vol/SV_SE010867_01/        8GB        0GB        8GB       0%  /vol/SV_SE010867_01/, /vol/SE010910_etc/         
             0GB        0GB        0GB       1%  /vol/SE010910_etc/, /vol/vol1/               120GB       14GB      105GB      12%  /vol/vol1/...}

This output is not complete. For example the same command executed from Putty should like this one:

SE010882> df -gx
Filesystem               total       used      avail capacity  Mounted on
/vol/SV_SE010867_01/        8GB        0GB        8GB       0%  /vol/SV_SE010867_01/
/vol/SE010910_etc/         0GB        0GB        0GB       1%  /vol/SE010910_etc/
/vol/vol1/               120GB       14GB      105GB      12%  /vol/vol1/
/vol/SE010914_etc/         0GB        0GB        0GB       1%  /vol/SE010914_etc/
/vol/SE010906_etc/         0GB        0GB        0GB       2%  /vol/SE010906_etc/
/vol/SV_SE010904_01/      100GB        0GB       99GB       0%  /vol/SV_SE010904_01/
/vol/SV_SE010809_01/      540GB      350GB      189GB      65%  /vol/SV_SE010809_01/
/vol/vol0/               190GB        8GB      181GB       4%  /vol/vol0/
/vol/SE010905_etc/         0GB        0GB        0GB       2%  /vol/SE010905_etc/
/vol/SV_SE010903_01/      232GB       64GB      167GB      28%  /vol/SV_SE010903_01/
/vol/SV_SE000852_03/        0GB        0GB        0GB       0%  /vol/SV_SE000852_03/
/vol/SV_SE010903_03/       98GB       17GB       81GB      18%  /vol/SV_SE010903_03/
/vol/SV_SE000852_01/      121GB       21GB      100GB      18%  /vol/SV_SE000852_01/
/vol/restore/           1024GB      108GB      915GB      11%  /vol/restore/
/vol/SV_SE010903_02/      570GB      487GB       82GB      85%  /vol/SV_SE010903_02/
/vol/SE010909_etc/         0GB        0GB        0GB       1%  /vol/SE010909_etc/
/vol/SE010913_etc/         0GB        0GB        0GB       1%  /vol/SE010913_etc/
/vol/SE010917_etc/         0GB        0GB        0GB       2%  /vol/SE010917_etc/
/vol/SV_SE000999_02/      240GB       35GB      204GB      15%  /vol/SV_SE000999_02/
/vol/SV_SE010809_02/     1800GB     1150GB      649GB      64%  /vol/SV_SE010809_02/
/vol/SV_SE000852_02/       64GB       22GB       41GB      35%  /vol/SV_SE000852_02/
/vol/SV_SE010915_02/     1345GB      706GB      639GB      52%  /vol/SV_SE010915_02/
/vol/TEST_DFSdata/      1945GB      683GB     1262GB      35%  /vol/TEST_DFSdata/
/vol/Vorstand_test/        0GB        0GB        0GB      32%  /vol/Vorstand_test/
/vol/SV_SE014070_01/     1958GB     1769GB      189GB      90%  /vol/SV_SE014070_01/

**Comment by darkoperator** [comment]
Any test system I could get access to to test? I have never worked with Netapp gear or have access to one to test.

**Comment by hristomirster** [comment]
We have not test systems unfortunately. If you fave ant suggestions i can test it by myself.

**Comment by darkoperator** [comment]
Try with Plink to see if you get the same result, I do not know if it uses its own shell like Cisco, also try with a ShellStream instead of invoke-sshcommand

**Comment by hristomirster** [comment]
C:\Users\ehava9o>plink -l %U% -pw %P% SE010882.ztbpre.icbpre.commerzbank.com df -gx
Filesystem               total       used      avail capacity  Mounted on
/vol/SV_SE010867_01/        8GB        0GB        8GB       0%  /vol/SV_SE010867_01/
/vol/SE010910_etc/         0GB        0GB        0GB       1%  /vol/SE010910_etc/
/vol/vol1/               120GB       14GB      105GB      12%  /vol/vol1/
/vol/SE010914_etc/         0GB        0GB        0GB       1%  /vol/SE010914_etc/
/vol/SE010906_etc/         0GB        0GB        0GB       2%  /vol/SE010906_etc/
/vol/SV_SE010904_01/      100GB        0GB       99GB       0%  /vol/SV_SE010904_01/
/vol/SV_SE010809_01/      540GB      350GB      189GB      65%  /vol/SV_SE010809_01/
/vol/vol0/               190GB        8GB      181GB       4%  /vol/vol0/
/vol/SE010905_etc/         0GB        0GB        0GB       2%  /vol/SE010905_etc/
/vol/SV_SE010903_01/      232GB       64GB      167GB      28%  /vol/SV_SE010903_01/
/vol/SV_SE000852_03/        0GB        0GB        0GB       0%  /vol/SV_SE000852_03/
/vol/SV_SE010903_03/       98GB       17GB       81GB      18%  /vol/SV_SE010903_03/
/vol/SV_SE000852_01/      121GB       21GB      100GB      18%  /vol/SV_SE000852_01/
/vol/restore/           1024GB      108GB      915GB      11%  /vol/restore/
/vol/SV_SE010903_02/      570GB      487GB       82GB      85%  /vol/SV_SE010903_02/
/vol/SE010909_etc/         0GB        0GB        0GB       1%  /vol/SE010909_etc/
/vol/SE010913_etc/         0GB        0GB        0GB       1%  /vol/SE010913_etc/
/vol/SE010917_etc/         0GB        0GB        0GB       2%  /vol/SE010917_etc/
/vol/SV_SE000999_02/      240GB       35GB      204GB      15%  /vol/SV_SE000999_02/
/vol/SV_SE010809_02/     1800GB     1150GB      649GB      64%  /vol/SV_SE010809_02/
/vol/SV_SE000852_02/       64GB       22GB       41GB      35%  /vol/SV_SE000852_02/
/vol/SV_SE010915_02/     1345GB      706GB      639GB      52%  /vol/SV_SE010915_02/
/vol/TEST_DFSdata/      1945GB      683GB     1262GB      35%  /vol/TEST_DFSdata/
/vol/Vorstand_test/        0GB        0GB        0GB      32%  /vol/Vorstand_test/
/vol/SV_SE014070_01/     1958GB     1769GB      189GB      90%  /vol/SV_SE014070_01/

**Comment by darkoperator** [comment]
Just to be sure did you expand output property of the returned object? 

$myvar = poshsshcommand
$myvae.output

Or pipped to Select-Object -expandproperty output

**Comment by hristomirster** [comment]
Hi @darkoperator,

this solved my problem, thank you very much for the help.

As you can see below the output is complete and even formatted correctly:

![image](https://user-images.githubusercontent.com/41720388/104084503-40071780-5250-11eb-8848-865842809fe9.png)

**Comment by hristomirster** [comment]
$myvar = poshsshcommand
$myvae.output
