### ISSUE TITLE
Discussion: Dropping Windows powershell support and other

### ISSUE THREAD

**Issue by MVKozlov** [darkoperator/Posh-SSH#366]
About removing Windows PowerShell support:

I don't think this is necessary. In its current state, the module is completely ready for use with 5.1, except for Json
The library under 5.1 throws an exception about the System.Buffers version.

I tried to downgrade the Powershell standard to 5.1 and replaced the Json library with Newtonsoft.
Thus, it works completely under both Core and Windows PS versions.

Since registry support will be completely discontinued, and after reading about the problems in the current implementation of the System.Text.Json it seems to me that at the current stage we can go to NewtonSoft.Json and attach a script to convert TrostedHost records from the registry to JSon.

**Comment by MVKozlov** [comment]
If we do such thing, there can be one more improvement.

Since PublicKey type is known at the time of fingerprint verification, this type can also be saved in the keystore.
If, at the same time, we transfer the verification of the key inside the `IStore` interface, and add `GetKeyTypes(hostname)` to the public interface, it becomes possible to support setting an acceptable type of keys for the library

code for key verification can be like this:
``` C#
if (keyStorage.GetKeyType(hostname, out string keytype)) { // some keys present
  if (! strong.isNullOrEmpty(keytype)) {
     // filter conninfo.HostKeyAlgorithms to only supported known key type
  }
  else {}  // fallback to unknown key type - no filtering
//.....
var verificatioResult = keyStorage.VerifyKey(hostname, keytype, fingerprint);
// the verification should support empty key type and defined key type.
// it should check "keytype+finterprint" or "fintgerprint" only
if (verificationResult == OK) {
   keyStorage,SetKey(hostname, keytype, fingerprint) // to save keytype instead of empty (if applicable)
  //
}
else if (verificationResult == Fail) {
// throw "invalid fingerprint"
}
else { // Unknown
 // host is uknown, ask for confirmation
  if (confirmed) {
    keyStorage,SetKey(hostname, keytype, fingerprint)
  }
}
```

**Comment by darkoperator** [comment]
To make a module that will work on both Windows PowerShell 5.1 and PowerShell Core then the module needs to be made to be a PowerShell Standard Library Module using https://www.nuget.org/packages/PowerShellStandard.Library <https://www.nuget.org/packages/PowerShellStandard.Library> according to https://devblogs.microsoft.com/powershell/powershell-standard-library-build-single-module-that-works-across-windows-powershell-and-powershell-core/ <https://devblogs.microsoft.com/powershell/powershell-standard-library-build-single-module-that-works-across-windows-powershell-and-powershell-core/> Don’t what the headache of maintaining and pusblishing 2 different modules to the PowerShell Gallery, specially given that MS will not expand Windows PowerShell outside of security fixes. 

Verification in SSH.Net <http://ssh.net/> is done via events as long as we can have verbose messaging showing the key and host, we can accept new key, auto accept new keys or simply ignore with force I have no issue so as to maintain the behavior.

**Comment by darkoperator** [comment]
I need to play with it https://devblogs.microsoft.com/powershell/powershell-standard-library-build-single-module-that-works-across-windows-powershell-and-powershell-core/ <https://devblogs.microsoft.com/powershell/powershell-standard-library-build-single-module-that-works-across-windows-powershell-and-powershell-core/>

**Comment by MVKozlov** [comment]
Yes, I am testing `PoshSSH.Core.csproj` which is compiled for netstandard2.0.

I have already tried the project creation method from this blog to compare the project with the existing `PoshSSH.Core.csproj`
and it shows no difference.

I was trying to compile Json using `System.Text.Json` on this project and couldn't get it to work with netstandard2.0 under .Net 4.8.
So I suggest using `NewtonSoft.JSon`

Here is my code https://github.com/MVKozlov/test-MSjson_netstd2.0

**Comment by darkoperator** [comment]
Ok let go for Newtonsoft
