### ISSUE TITLE
New-SSHSession not working for Foreach-Object -Parallel {}

### ISSUE THREAD

**Issue by sbkurid** [darkoperator/Posh-SSH#367]
Parallel Session are not working when we use Foreach-Object -Parallel {} in PowerShell 7.1

PS C:\Users\krishna.shanmugam> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\krishna.shanmugam>

Error :
Cannot process argument transformation on parameter 'Credential'. A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: Enter your credentials.

**Comment by darkoperator** [comment]
Module is not supported in PS core or 7, the next release is being worked on to work on those versions. Based on the error did you tries with -force so it does not check the host key? It asks if not seen before if you want to trust it, that is if I go literally by the error this also seems as if a credential object was not passed and was left with only username or get-credential in parentheses

**Comment by sbkurid** [comment]
Thank you for the comment.

1. I have used Import-module Posh-SSH -UseWindowsPowershell command to import the module.
2. I have used -AcceptKey parameter and also -Force whcich gives the same error.
3. I have tried the below two ways for passign the credential but no luck.
    a. I have saved the password to a variable by calling get-credential commendlet 
    b. Also New-SSHSession -Computer "Computer/IP Address" -Credential (Get-Credential)

**Comment by darkoperator** [comment]
-parallel uses remoting to create new runspaces, any command like get-credial that prompts for input it will fail. Abs hen you read the help for it it covers passing a variable from main runspce to the other with the $using: keyword. Are you doing that for credentials like the docs specify? 

$computers = 'computerA','computerB','computerC','computerD' 
$logsToGet = 'LogA','LogB','LogC' 

# Read specified logs on each machine, using custom module
$logs = $computers | ForEach-Object -ThrottleLimit 10 -Parallel {
    Import-Module MyLogsModule 
    Get-Logs -ComputerName $_ -LogName $using:logsToGet 
}

**Comment by sbkurid** [comment]
Hi, thanks again for commenting...

I'm not specifying anything $using: for the credential and also i couldnt find proper document for reference.

Could you please share me any article for that to check it.

**Comment by darkoperator** [comment]
https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/ForEach-Object?view=powershell-7 <https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/ForEach-Object?view=powershell-7>

Your sessions will only be valid inside the script block since they live in a global variable per sunspace.

**Comment by sbkurid** [comment]
Hi Again,

Thank you for the reference article and I have tried with $using: keyword and now I'm getting different error as pasted below.

PS C:\Users\krishna.shanmugam\Desktop> $Serverlist = Get-Content .\LinuxVMs.txt
PS C:\Users\krishna.shanmugam\Desktop> $Serverlist | ForEach-Object -Parallel {
>> $MyCreds = $using:MyCred
>> New-SSHSession -ComputerName $_ -Credential $MyCreds -AcceptKey
>> $ReSession = Get-SSHSession | Select-Object -ExpandProperty SessionID -First 1
>> Write-Host $ReSession}
>>
New-SSHSession:
Line |
   3 |  New-SSHSession -ComputerName $_ -Credential $MyCreds -AcceptKey
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
New-SSHSession:
Line |
   3 |  New-SSHSession -ComputerName $_ -Credential $MyCreds -AcceptKey
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
New-SSHSession:
Line |
   3 |  New-SSHSession -ComputerName $_ -Credential $MyCreds -AcceptKey
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
New-SSHSession:
Line |
   3 |  New-SSHSession -ComputerName $_ -Credential $MyCreds -AcceptKey
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
PS C:\Users\krishna.shanmugam\Desktop>

**Comment by darkoperator** [comment]
Because as I said it os not supported yet in PS 6 or 7 only Windows PowerShell

**Comment by sbkurid** [comment]
thank you for the update @darkoperator 

is there any plan for the updated Posh-SSH module to support powershell core ?

**Comment by darkoperator** [comment]
Yes, there is a build currently being worked on

**Comment by sbkurid** [comment]
Thank you for the update..

**Comment by sbkurid** [comment]
Is Posh-SSH version 3.0 is supported for Powershell 7.x ??

**Comment by darkoperator** [comment]
Yes it is supported on PowerShell 7
