### ISSUE TITLE
Get-SFTPFile/Set-SFTPFile fail with 'Object reference not set to an instance of an object.' when called with SFTPSession

### ISSUE THREAD

**Issue by camilohe** [darkoperator/Posh-SSH#37]
Get-SFTPFile/Set-SFTPFile fail with 'Object reference not set to an instance of an object.' when called with SFTPSession. This occurs in version 1.7.2 of Posh-SSH running in PowerShell 3.0 on a Windows 7 x64 machine.

```` PowerShell
Get-SFTPFile -SFTPSession $sess -RemoteFile '/home/apps/app-1.0.1.apk' -LocalPath 'C:\Temp'
Get-SFTPFile : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-SFTPFile -SFTPSession $sess -RemoteFile '/home/apps/app-1.0.1.apk' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-SFTPFile], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,SSH.GetSftpFile
````
Both functions worked OK using SFTPSession in version 1.6.0 of Posh-SSH.
Both functions work fine if you call them passing SessionId instead.
**Note that you can call the function passing the SessionId like this as a workaround**
````PowerShell
Get-SFTPFile -SessionId $sess.SessionId -RemoteFile  '/home/apps/app-1.0.1.apk' -LocalPath 'C:\Temp'
````
After some research I traced the issue to these lines in the files GetSftpFile.cs/SetSftpFile.cs:
```` CSharp
switch (ParameterSetName)
{
    case "Session":
        ToProcess.AddRange(_session);
        break;
````

**Comment by darkoperator** [comment]
Thanks, just merged the changes you provided.
