### ISSUE TITLE
Error to execute more than one invoke-sshcommand

### ISSUE THREAD

**Issue by Jathh** [darkoperator/Posh-SSH#370]
Hi,
I've detected that it's impossible to execute more than one invoke-sshcommand at the same time, to different connections/sessions.
To do this i'm using runspaces. To execute per remotehost one runspace, the only way to execute fine commands it's limit the concurrent executions to 1.
In my first step i create as pretask in this step i create all the new-sshsessions yo be used after.

There is something in this command that use temporary files ir something like that and makes it impossible to use this command at the same time?

Best regards

**Comment by darkoperator** [comment]
No clue on what could be an issue. If the session is created in each runspace and the resulting object used there should be no problem. But since my work environment never goes over 20 and ssh.net not being thread friendly I have not had the need to test that

**Comment by Jathh** [comment]
My fault, i've detected the problem. If creates the SSH sessions importing the module in the principal process, it's needed to load too the module per runspace, if not you got many errors. 

So, sorry for the inconvenience and thanks for your quick answer.
