### ISSUE TITLE
OpenSSH Hostname is Base64 encoded.

### ISSUE THREAD

**Issue by darkoperator** [darkoperator/Posh-SSH#372]
![image](https://user-images.githubusercontent.com/521246/106372045-17030f80-6342-11eb-85bf-dfad7fed9f1f.png)

@MVKozlov have you seen this case? was testing and noticed that on a Ubuntu System the OpenSSH known_hosts when imported the host is encoded while on Windows OpenSSH it is not.

**Comment by darkoperator** [comment]
OK I see they are hashed. Something I better document that is the config in ssh is set to hash them that the files will not be of user https://blog.rootshell.be/2010/11/03/bruteforcing-ssh-known_hosts-files/

**Comment by MVKozlov** [comment]
Yes, at most of linuxes hostnames hashed by default.
I mention it several times in previos issues.
https://github.com/darkoperator/Posh-SSH/issues/362#issuecomment-753601403
https://github.com/darkoperator/Posh-SSH/issues/362#issuecomment-767654554

That the main reason to OpenSSH storage be readonly.

**Comment by darkoperator** [comment]
Cool, now I remember :)
