### ISSUE TITLE
"Client not connected" error when attempting to use New-SSHSession through an Azure Runbook

### ISSUE THREAD

**Issue by ShowMeTheGita** [darkoperator/Posh-SSH#384]
I've tried locally on my machine and I'm able to connect to an Azure VM on our tenant. I've applied all the security rules necessary both locally and on Azure, but for some reason on Azure I cannot connect when attempting to do so through an Azure PowerShell Runbook (which in theory the same code should work just as it does in my personal PC). The error:
`New-SSHSession : Client not connected. At line:64 char:16 + ... hsession = (New-SSHSession -ComputerName $vmpubip -Credential $ ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : SecurityError: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], SshConnectionException + FullyQualifiedErrorId : SSH.NewSshSession `

Are there any reported issues attempting to use Posh-SSH through Azure runbooks? I got the package directly from the Modules Gallery:
![image](https://user-images.githubusercontent.com/72092270/109816293-78abe780-7c28-11eb-88d6-7629d419896e.png)

Thanks in advance!

**Comment by darkoperator** [comment]
Yes, if not the Alpha version because it depends on registry being present, something not available in Azure Runbooks.

**Comment by ShowMeTheGita** [comment]
Is there any way around it? I'm attempting to create a script that connects to a linux VM in Azure through an Azure Runbook. This package was perfect for what I was trying to achieve :(

**Comment by darkoperator** [comment]
Use the Alpha version

**Comment by ShowMeTheGita** [comment]
Updated to the alpha version, now instead of "client not connected" I'm getting "An established connection was aborted by the server":

`New-SSHSession : An established connection was aborted by the server. At line:59 char:16 + ... hsession = (New-SSHSession -ComputerName $vm -Credential $ ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : SecurityError: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], SshConnectionException + FullyQualifiedErrorId : SSH.NewSshSession `

Updated to alpha locally and attempted on my machine and it worked as well, but on Azure the problem remains:

![image](https://user-images.githubusercontent.com/72092270/109828299-6a63c880-7c34-11eb-8859-66daaf0fea7b.png)

Here's my code for the connection in the script (for connection testing purposes):  

` $sshsession = (New-SSHSession -ComputerName $vmpublicip -Credential $cred -AcceptKey -Verbose)`

`Invoke-SSHCommand -Command "ls /" -SSHSession $sshsession`

`Remove-SSHSession -SSHSession $sshsession`

Creds are working as per local testing.

**Comment by MVKozlov** [comment]
may be some server logs can shine the light on this?

**Comment by darkoperator** [comment]
That error is that the connection was actively denied. As Max mentioned the logs should say why

**Comment by ShowMeTheGita** [comment]
Latest error:
`New-SSHSession : An established connection was aborted by the server.`

And serverside, here are the logs:
Mar  3 18:16:46 syoneint sshd[101682]: debug1: Forked child 103167.
Mar  3 18:16:46 syoneint sshd[103167]: debug1: Set /proc/self/oom_score_adj to 0
Mar  3 18:16:46 syoneint sshd[103167]: debug1: rexec start in 5 out 5 newsock 5 pipe 7 sock 8
Mar  3 18:16:46 syoneint sshd[103167]: debug1: inetd sockets after dupping: 3, 3
Mar  3 18:16:46 syoneint sshd[103167]: Connection from 52.236.160.186 port 24384 on 10.8.134.6 port 22
Mar  3 18:16:46 syoneint sshd[103167]: debug1: Client protocol version 2.0; client software version Renci.SshNet.SshClient.0.0.1
Mar  3 18:16:46 syoneint sshd[103167]: debug1: no match: Renci.SshNet.SshClient.0.0.1
Mar  3 18:16:46 syoneint sshd[103167]: debug1: Local version string SSH-2.0-OpenSSH_7.4
Mar  3 18:16:46 syoneint sshd[103167]: debug1: Enabling compatibility mode for protocol 2.0
Mar  3 18:16:46 syoneint sshd[103167]: debug1: SELinux support enabled [preauth]
Mar  3 18:16:46 syoneint sshd[103167]: debug1: permanently_set_uid: 74/74 [preauth]
Mar  3 18:16:46 syoneint sshd[103167]: debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
Mar  3 18:16:46 syoneint sshd[103167]: debug1: SSH2_MSG_KEXINIT sent [preauth]
Mar  3 18:16:46 syoneint sshd[103167]: Connection closed by 52.236.160.186 port 24384 [preauth]
Mar  3 18:16:46 syoneint sshd[103167]: debug1: do_cleanup [preauth]
Mar  3 18:16:46 syoneint sshd[103167]: debug1: monitor_read_log: child log fd closed
Mar  3 18:16:46 syoneint sshd[103167]: debug1: do_cleanup
Mar  3 18:16:46 syoneint sshd[103167]: debug1: Killing privsep child 103168

**Comment by MVKozlov** [comment]
disconnection during ** preauth** as far as I know indicates problems with hostkeys.
please try connect with `-Verbose` switch to see host key type and fingerprint.

and also you may try `-Force`

**Comment by ShowMeTheGita** [comment]
Using -Force for some reasons results in an error after the first verbose log:
`VERBOSE: Using SSH Username and Password authentication for connection.
New-SSHSession : Object reference not set to an instance of an object.`

For some reason, after maybe 30 attempts the connection worked ONCE after adding the -Verbose flag. Also tried to add -ConnectionTimeout 300 to allow up to 5 minutes of attempts. Got this error in return:

`New-SSHSession : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond`

As for the Verbose flag, logging doesn't show up on the runbook logs for some reason. I did activate the runbook logging and nothing new to add except this particular log I managed to catch when that one connection did work:

`Log: Using SSH Username and Password authentication for connection. 
Log: ssh-ed25519 Fingerprint for [vmIPv4]: [vmIPv6] `

What's interesting is that this last fingerprint log only shows up on the one run that managed to connect. All others show the connection errors afterwards, a couple of runs ago I got:

`New-SSHSession : Connection failed to establish within 10000 milliseconds`

Which was what led me to add the -ConnectionTimeout flag, still with no results. This inconsistency is very strange

**Comment by darkoperator** [comment]
Yep i fixed that in the code but have not pushed the beta of 3.0. Will do tonight

**Comment by ShowMeTheGita** [comment]
Thank you. This is a fantastic module by the way.
Will the package be able for direct-import via https://www.powershellgallery.com/packages/Posh-SSH/3.0.0-alpha?

**Comment by darkoperator** [comment]
Yep just that it will be beta

**Comment by ShowMeTheGita** [comment]
I will be attempting with the -Force flag once the fix is implemented and will get back to you

**Comment by darkoperator** [comment]
https://www.powershellgallery.com/packages/Posh-SSH/3.0.0-beta1 Beta1 is now in the gallery.  Sent from Mail for Windows 10 From: ShowMeTheGitaSent: Wednesday, March 3, 2021 11:07 PMTo: darkoperator/Posh-SSHCc: Carlos Perez; CommentSubject: Re: [darkoperator/Posh-SSH] "Client not connected" error when attempting to use New-SSHSession through an Azure Runbook (#384) I will be attempting with the -Force flag once the fix is implemented and will get back to you—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ShowMeTheGita** [comment]
We found out that the issue most likely has to do with the worker that runs the runbook in Azure. I've reached no conclusion unfortunately but everything seems alright with the module therefore I'm closing with this comment. Thanks for the help.
