### ISSUE TITLE
openssh key type: ssh-rsa is not supported

### ISSUE THREAD

**Issue by AndrewRRoe** [darkoperator/Posh-SSH#388]
Having trouble using priv/pub key to connect using Posh-ssh.  I was under the impression RSA keys were supported - I am using rsa ssh2 4096 bit key.  Any help would be appreciated.

POSH-SSH Version - Manifest   3.0.0      beta1      Posh-SSH                            

new-session command throws this error: 

"new-sshsession : openssh key type: ssh-rsa is not supported"

command resembles -  new-sshsession -computername mysystem -Credential $cred -KeyFile C:\users\jondoe\Documents\SSH_KEY_PRIV.pem

$cred = get-credential ( values supplied are usrename and private key pass phrase)

**Comment by darkoperator** [comment]
For RSA it is only the old format, the newer format is still held up as a PR for the library https://github.com/sshnet/SSH.NET/pull/614 <https://github.com/sshnet/SSH.NET/pull/614>

**Comment by AndrewRRoe** [comment]
Thank you I didn't realize that ....

**Comment by et1975** [comment]
@darkoperator Sorry, if I understand it correctly https://github.com/sshnet/SSH.NET/issues/883 was supposed to have solved this issue? And if I understand your comment there 3.0 release is including it and should have this issue addressed?
I'm just confused cause I'm still seeing this with posh-ssh 3.0.0

**Comment by darkoperator** [comment]
Still not supported it was mentioned that it was holding release which it was not. So it could be me miss understanding the message

**Comment by wbloos** [comment]
Looked up how to create "the old format" (PEM) on a linux machine:
`$ ssh-keygen -m PEM -t rsa -b 4096`

**Comment by synthead** [comment]
Is there any plan to support 4096-bit RSA keys?

**Comment by darkoperator** [comment]
I know the library supports OpenSSH format, but I do not believe PEM cert v01 is supported.
