### ISSUE TITLE
Being able to "su -" with invoke-sshcommand

### ISSUE THREAD

**Issue by joafri** [darkoperator/Posh-SSH#39]
Either to be able to run "invoke-sshcommand -command 'su -'" or maybe "invoke-sshcommand -su -command...".

As it is today you can run the command but not input a password which kind of defeats the purpose.

**Comment by darkoperator** [comment]
You need to use a stream for that look at the stream functions

**Comment by darkoperator** [comment]
you can do in a stream
```
:\PS>Invoke-SSHStreamExpectSecureAction -ShellStream $stream -Command 'su -' -ExpectString 'Passord:' -SecureAction (read-host -AsSecureString) -Verbose

***********
VERBOSE: Executing command su -.
VERBOSE: Waiting for match.
VERBOSE: Executing action.
VERBOSE: Action has been executed.
True
PS C:\> $stream.Read()

Last login: Sat Mar 14 18:18:52 EDT 2015 on pts/0
Last failed login: Sun Mar 15 08:52:07 EDT 2015 on pts/0
There were 2 failed login attempts since the last successful login.
[root@localhost ~]#
```

sadly there is no way to do this via invoke-sshcommand. You can do sudo with the trick here http://stackoverflow.com/questions/233217/pass-password-to-su-sudo-ssh but this will leave a password in memory and in history.
