### ISSUE TITLE
Error Handling for Invoke-SSHStreamExpectSecureAction

### ISSUE THREAD

**Issue by piercj2** [darkoperator/Posh-SSH#397]
is there a way to handle errors when using Invoke-SSHStreamExpectSecureAction
for example, if an incorrect password is passed ?

$sshStream = New-SSHShellStream -index $sshSession.SessionId
Invoke-SSHStreamExpectSecureAction -ShellStream $SSHStream -Command 'sudo su -' -ExpectString "Password:" -SecureAction ($sshRootPass) -Verbose
$sshStream.read()
$sshStream.WriteLine("pwd")
Start-Sleep -Seconds 3
$sshStream.Read()
Start-Sleep -Seconds 3

If the contents of $sshRootPass are incorrect, sudo mode authentication will fail and the "pwd" command will never execute.
is there a way to capture the authentication failure and pause/break before the command is executed ?

**Comment by darkoperator** [comment]
There is none, you would have to script it yourself with the object to look for the error messages and match them via regex

**Comment by piercj2** [comment]
Thanks for the quick reply. The verbose output of Invoke-SSHStreamExpectSecureAction is
VERBOSE: Executing command st en.
VERBOSE: Waiting for match.
VERBOSE: Matching by String.
VERBOSE: Executing action.
VERBOSE: Action has been executed.
True
 
su: Authentication failure

It looks like the command executes successfully but, the error happens inside the remote shell session.
Not sure how i'd script for that

**Comment by darkoperator** [comment]
https://github.com/darkoperator/Posh-SSH/blob/master/Posh-SSH/Posh-SSH.psm1#L764 <https://github.com/darkoperator/Posh-SSH/blob/master/Posh-SSH/Posh-SSH.psm1#L764> here is the code of the function that you can use as reference

**Comment by piercj2** [comment]
Thanks,
I was able to find a solution, redirecting the verbose output of $sshStream.Read() to a variable and then manipulating the variable 
$redirect = $sshStream.Read() 4>&1
                   if ($redirect -like '*Authentication failed!*'){
                       Write-Host -ForegroundColor DarkGreen "captured the error"
                       ......
                   }
