### ISSUE TITLE
Set times: operation not permitted error when using Set-SCPFile cmdlet

### ISSUE THREAD

**Issue by mdinicola** [darkoperator/Posh-SSH#40]
I have just upgraded from v1.6 to 1.7.2

Now, when I use the Set-SCPFile cmdlet to upload a file, I get an error when the upload is almost complete.

```
Set-SCPFile : scp: /home/somefile.zip: set times: Operation not permitted
```

This did not happen in v1.6.  The same file uploaded successfully to the same destination without any errors.

**Comment by darkoperator** [comment]
can you provide more info on the target so as to try to replicate? this is a common SCP error when the user does not have permission to modify file time after upload. Can you confirm the file did upload?

**Comment by mdinicola** [comment]
I can confirm that the file does upload.

The target is a Linux environment, that has a mount to a Windows shared drive.  Both the Windows shared drive and the Linux mount currently have permissions set to that everyone is able to read/write to them.

I read that some tools, like WinSCP for example, provide an option to disable the option for "preserve timestamps" to avoid this error.  Is something like that an option here?

**Comment by darkoperator** [comment]
sadly the library I use does not give the option, I can modify the library but it will not compile for .Net 3.5 but only .Net 4.5 so it would be PowerShell 4.0 only. That would not sit well with the majority of user that for reason or another are stuck in PS 2.0. Only other option would be when you mount to set a proper fmask and dmask in the mount command to allow changing of file times. 

can you share ehe full error message? when it happened do a $error[0] | fl * -force

**Comment by mdinicola** [comment]
I think I solved it. By setting the uid parameter when doing the mount, and now I no longer get the error when I upload a file.

But here is the full error message anyways, from when I was getting it:

    PSMessageDetails      : 
    Exception             : Renci.SshNet.Common.ScpException: scp: /home/somefile.zip: set times: Operation not permitted
                           at Renci.SshNet.ScpClient.CheckReturnCode(Stream input)
                           at Renci.SshNet.ScpClient.InternalUpload(IChannelSession channel, Stream input, Stream source, String filename)
                           at Renci.SshNet.ScpClient.InternalUpload(IChannelSession channel, Stream input, FileInfo fileInfo, String filename)
                           at Renci.SshNet.ScpClient.Upload(FileInfo fileInfo, String path)
                           at SSH.SetScpFile.ProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
    TargetObject          : 
    CategoryInfo          : NotSpecified: (:) [Set-SCPFile], ScpException
    FullyQualifiedErrorId : Renci.SshNet.Common.ScpException,SSH.SetScpFile
    ErrorDetails          : 
    InvocationInfo        : System.Management.Automation.InvocationInfo
    ScriptStackTrace      : at <ScriptBlock>, C:\Projects\Deployment\helpers\deployment-helpers.psm1: line 172
                        at Send-Files<Process>, C:\Projects\Deployment\helpers\deployment-helpers.psm1: line 159
                        at <ScriptBlock>, C:\Projects\Deployment\deploy-release.ps1: line 46
                        at <ScriptBlock>, <No file>: line 1
