### ISSUE TITLE
Missing Set-SFTPFile, Set-SFTPFolder, Set-SFTPItem in v 3.0

### ISSUE THREAD

**Issue by Dhincy** [darkoperator/Posh-SSH#401]
I had used the Set-SFTP File command in v 2.3.0. When I attempted to use it in v 3.0.0 it was missing.  It appears that the last three commands were cut off.  Thank you

**Comment by MVKozlov** [comment]
Set-SFTPItem available and can be used instead bot xxFile/xxFolder things

**Comment by darkoperator** [comment]
Correct, it is something I had been warning about in the changelog and why I have been doing betas this time with so many changes for a major version :)
