### ISSUE TITLE
Integrity check question

### ISSUE THREAD

**Issue by othias** [darkoperator/Posh-SSH#402]
Greetings,

When I upload files using SFTP via Posh-SSH, I want to make sure of the integrity of the transferred files. Right now I'm computing the md5sum of the local file and transferred file and checking if they match.

Upon reading on SFTP I realized that the protocol is already doing some integrity checking. Does Set-SFTPFile do checksum ? Is there a way to get the checksum (md5 or otherwise) upon calling Set-SFTPFile without having to manually do it afterward ?

Thank you,
Lucas

**Comment by MVKozlov** [comment]
Has you read https://stackoverflow.com/questions/30056566/how-to-perform-checksums-during-a-sftp-file-transfer-for-data-integrity ?
In the opinion of many, this is a useless exercise, but among the answers there is a link on how to do it using Renсi.
To do this, in terms of this module you need to create a ssh connection by `New-SSHConnection` and use
`Invoke-SSHCommand`

**Comment by darkoperator** [comment]
Sadly it is not something built in to the library I'm using.
