### ISSUE TITLE
Error when connecting

### ISSUE THREAD

**Issue by redwiz666** [darkoperator/Posh-SSH#404]
I'm trying to get posh-ssh working with our SSH server, and no matter what command I run I keep getting the same error `an exception has been thrown by the target of an invocation
`
I tried `new-sshsession -computername $target -credential $cred -force` and also the Get-SCPItem command. When looking in the logs on the server it seems like there is never a connection attempt being made. We currently have version 2.3 installed.

these commands are being ran from a Win10 box with powershell 5.1 going to an ubuntu server running OpenSSH

**Comment by darkoperator** [comment]
Can you put the output of the error? Also anything on the logs of the server

**Comment by redwiz666** [comment]
Disregard. It seems FIPS was turned on by admins causing the issue. Once I disabled it, everything works

**Comment by darkoperator** [comment]
Ahh good old FIPS the best way to degrade .Net encryption on a host
