### ISSUE TITLE
Question regarding versions, roadmap and usage

### ISSUE THREAD

**Issue by Klaboe** [darkoperator/Posh-SSH#405]
Hello thank you for you efforts regarding this module. Consider this issue as just a clearifaction on the releases, what is supposed to work where, and general usage 😅 

First of: I have installed the module version 2.3.0 as listed i PSGallery as the last stable. But here on github, 2.2 is marked as the latest release, and 2.3.0 does not exist at all. Also the changelog jumps from 2.1 to 3.0alpha. I believe i read somewhere that you release directly to PSGallery which is fair enough, but i would have liked to see the changelog at least to match up with the releases 👍

So to mye problem:

The usecase was simple; scp a file to a remote (linux) machine. And i followed https://mcpmag.com/articles/2018/07/19/transfer-files-via-scp-with-powershell.aspx (This is where i learned of the project). The only thing i didn't do here was the use of `Get-Credentials`, i just provided the username for ssh login on the linux machine.

Im on a Win10 machine with Poweshell 7.1.3 (admin elevated mostly) and i got the error 

`Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.`

I know that i 3.0 this has changed from `Set-SCPFile` to `Set-SCPItem` but i dont think that should have anything to say.

The other issue that references `System.Security.Cryptography.HMACRIPEMD160` talks about using it from linux and i as i understand it _then_ you have to use 3.0betaX.

So am i missing something in regards to Powershell-compabillity, usage or something else?

**Comment by darkoperator** [comment]
Ps version 7 is the core/netstandard version ao you will have to use the beta. Yep i do need to update the changelog. Since it is a hobby project I have been lax in updating docs and the releases in github have been such a pain of people installing from ot and having issues I have avoided doing more releases there but I should. The 2.x version works up to 5.1 not PS 6+

**Comment by Klaboe** [comment]
I see! Thank you so much for you quick response!
