### ISSUE TITLE
3.0.0 Beta5 Remove-SSHSession - enumeration error

### ISSUE THREAD

**Issue by McGreggor** [darkoperator/Posh-SSH#407]
Hi,

When running:

Get-SSHSession -SessionID 5 | Remove-SSHSession 

The command seems to work, and I get boolean response, but I also receive error:

Collection was modified; enumeration operation may not execute.
..Posh-SSH.psm1:62 char:29
foreach($session in $SshSessions)

**Comment by MVKozlov** [comment]
seems all branches of `Get-SSHSession`
should collect sessions before returning it. just like 2nd

but may be slightly optimized :)

**Comment by MVKozlov** [comment]
Sorry about all branchless commits.
they all the same
I strongly confused something with branches.

**Comment by darkoperator** [comment]
fixes merged
