### ISSUE TITLE
Cannot install module per instructions given, import-module fails

### ISSUE THREAD

**Issue by dachshund-digital** [darkoperator/Posh-SSH#41]
PS C:\Users\Test> iex (New-Object Net.WebClient).DownloadString("https://gist.github.com/darkoperator/6152630/raw/c67de4f7cd780ba367cccbc2593f38d18ce6df89/instposhsshdev")
Downloading latest version of Posh-SSH from https://github.com/darkoperator/Posh-SSH/archive/master.zip
File saved to C:\Users\TEST~1\AppData\Local\Temp\Posh-SSH.zip
Uncompressing the Zip file to C:\Users\Test\Documents\WindowsPowerShell\Modules
Renaming folder
Module has been installed
Import-Module : The specified module 'posh-ssh' was not loaded because no valid module file was found in any module directory.
At line:17 char:1
+ Import-Module -Name posh-ssh
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (posh-ssh:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by darkoperator** [comment]
if you go to C:\Users\Test\Documents\WindowsPowerShell\Modules did the module decompress well?

**Comment by darkoperator** [comment]
also what version of PS are you running and on what version of windows

**Comment by dachshund-digital** [comment]
PowerShell 4.0, Windows 7 (fully updated).  The decompression appears to be complete, but the import-module sequence fails, per the error message displayed.  The module does not appear in the list of available modules via get-module.

 

Schorschi

**Comment by darkoperator** [comment]
What is the execution policy? "Get-executionpolocy"

**Comment by darkoperator** [comment]
can you make sure the folder structure and execution policy are like in this output:
```
PS C:\Users\Carlos Perez\Documents\WindowsPowerShell\Modules> ls


    Directory: C:\Users\Carlos Perez\Documents\WindowsPowerShell\Modules


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----         3/17/2015   9:27 PM            ISESteroids
d----         3/18/2015   8:27 PM            Posh-Shodan
d----         3/23/2015   5:11 PM            Posh-SSH
d----         3/18/2015   8:22 PM            Posh-Tweet
d----         3/18/2015   8:30 PM            Posh-VirusTotal
d----         11/7/2014  12:28 PM            PSReadline
d----         3/18/2015   9:04 PM            Veil-PowerView


PS C:\Users\Carlos Perez\Documents\WindowsPowerShell\Modules> ls .\Posh-SSH\


    Directory: C:\Users\Carlos Perez\Documents\WindowsPowerShell\Modules\Posh-SSH


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----         3/18/2015   6:14 PM            Assembly
d----         3/18/2015   6:14 PM            en-US
d----         3/18/2015   6:14 PM            Format
d----         2/25/2015   9:16 AM            PoshSSH
d----         3/18/2015   6:14 PM            tests
-a---         2/20/2015  11:37 AM        562 .gitattributes
-a---         2/20/2015  11:37 AM       2133 .gitignore
-a---         2/20/2015  11:37 AM       1505 License.md
-a---         3/18/2015   6:14 PM      17377 PortForward.ps1
-a---         3/25/2015   9:11 AM       2975 Posh-SSH.psd1
-a---         3/25/2015  11:14 AM      17161 Posh-SSH.psm1
-a---         3/28/2015   8:09 AM      40960 PoshSSH.dll
-a---         3/25/2015  11:33 AM      10468 Readme.md
-a---         3/18/2015   6:14 PM      44199 Sftp.ps1
-a---         3/20/2015  11:52 AM       3715 Trust.ps1


PS C:\Users\Carlos Perez\Documents\WindowsPowerShell\Modules> Get-ExecutionPolicy
Unrestricted
```

**Comment by dachshund-digital** [comment]
PS C:\Users\Test> get-executionpolicy

RemoteSigned

**Comment by dachshund-digital** [comment]
Sure…

 

PS C:\users\test\documents\windowspowershell\modules> ls

 

 

    Directory: C:\users\test\documents\windowspowershell\modules

 

 

Mode                LastWriteTime     Length Name

----                -------------     ------ ----

d----        04/15/2015     08:46            Posh-SSH

 

PS C:\users\test\documents\windowspowershell\modules\Posh-ssh> ls

 

 

    Directory: C:\users\test\documents\windowspowershell\modules\Posh-ssh

 

 

Mode                LastWriteTime     Length Name

----                -------------     ------ ----

d----        04/15/2015     08:46            Assembly

d----        04/15/2015     08:46            en-US

d----        04/15/2015     08:46            Format

d----        04/15/2015     09:18            PoshSSH

d----        04/15/2015     08:46            tests

-----        03/28/2015     05:16        536 .gitattributes

-----        03/28/2015     05:16       1970 .gitignore

-----        03/28/2015     05:16       1478 License.md

-----        03/28/2015     05:16      16778 PortForward.ps1

-----        03/28/2015     05:16       2879 Posh-SSH.psd1

-----        03/28/2015     05:16      16579 Posh-SSH.psm1

-----        03/28/2015     05:16      40960 PoshSSH.dll

-----        03/28/2015     05:16      10230 Readme.md

-----        03/28/2015     05:16      42539 Sftp.ps1

-----        03/28/2015     05:16       3592 Trust.ps1

**Comment by dachshund-digital** [comment]
Also…

 

PS C:\Users\Test> iex (New-Object Net.WebClient).DownloadString("https://gist.github.com/darkoperator/6152630/raw/c67de4f7cd780ba367cccbc2593f38d18ce6df89/instposhsshdev")

Downloading latest version of Posh-SSH from https://github.com/darkoperator/Posh-SSH/archive/master.zip

File saved to C:\Users\TEST\AppData\Local\Temp\Posh-SSH.zip

Uncompressing the Zip file to C:\Users\Test\Documents\WindowsPowerShell\Modules

Renaming folder

Module has been installed

Import-Module : The specified module 'posh-ssh' was not loaded because no valid module file was found in any module directory.

At line:17 char:1

+ Import-Module -Name posh-ssh

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : ResourceUnavailable: (posh-ssh:String) [Import-Module], FileNotFoundException

    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

 

 

PS C:\Users\Test\documents\WindowsPowerShell\modules\posh-ssh> ls

 

 

    Directory: C:\Users\Test\documents\WindowsPowerShell\modules\posh-ssh

 

 

Mode                LastWriteTime     Length Name

----                -------------     ------ ----

d----        04/19/2015     07:14            Assembly

d----        04/19/2015     07:14            en-US

d----        04/19/2015     07:14            Format

d----        04/19/2015     07:14            PoshSSH

d----        04/19/2015     07:14            tests

-----        03/28/2015     05:16        536 .gitattributes

-----        03/28/2015     05:16       1970 .gitignore

-----        03/28/2015     05:16       1478 License.md

-----        03/28/2015     05:16      16778 PortForward.ps1

-----        03/28/2015     05:16       2879 Posh-SSH.psd1

-----        03/28/2015     05:16      16579 Posh-SSH.psm1

-----        03/28/2015     05:16      40960 PoshSSH.dll

-----        03/28/2015     05:16      10230 Readme.md

-----        03/28/2015     05:16      42539 Sftp.ps1

-----        03/28/2015     05:16       3592 Trust.ps1

 

PS C:\Users\Test\documents\WindowsPowerShell\modules\posh-ssh> write-host $env:PSModulePath

C:\Program Files (x86)\VMware\Infrastructure\vSphere PowerCLI\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules\

 

Schorschi

**Comment by dachshund-digital** [comment]
A bit more… per the install script…

 

This fails…

 

Import-Module -Name posh-ssh 

 

This seems to work…

 

Import-Module "c:\users\test\documents\windowspowershell\modules\posh-ssh"

 

PS C:\Users\Test\documents\WindowsPowerShell\modules> get-module

 

ModuleType Version    Name                                ExportedCommands

---------- -------    ----                                ----------------

Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}

Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}

Manifest   1.7.2      posh-ssh                            {Get-SCPFile, Get-SCPFolder, Get-SFTPFile, New-SFTPSession...}

 

Get-Command Posh-SSH…

 

CommandType     Name                                                                           Definition                                                                   

-----------     ----                                                                           ----------                                                                   

Function        Get-PoshSSHModVersion                                                          ...                                                                          

Function        Get-SFTPChildItem                                                              ...                                                                          

Function        Get-SFTPContent                                                                ...                                                                          

Function        Get-SFTPCurrentDirectory                                                       ...                                                                          

Function        Get-SFTPDirectoryList                                                          ...                                                                          

Function        Get-SFTPLocation                                                               ...                                                                          

Function        Get-SFTPPathAttribute                                                          ...                                                                          

Function        Get-SFTPSession                                                                ...                                                                          

Function        Get-SSHSession                                                                 ...                                                                          

Function        Get-SSHTrustedHost                                                             ...                                                                          

Function        Invoke-SSHCommand                                                              ...                                                                          

Function        Invoke-SSHStreamExpectAction                                                   ...                                                                          

Function        Invoke-SSHStreamExpectSecureAction                                             ...                                                                          

Function        New-SFTPDirectory                                                              ...                                                                          

Function        New-SFTPFileStream                                                             ...                                                                          

Function        New-SFTPItem                                                                   ...                                                                          

Function        New-SFTPSymlink                                                                ...                                                                          

Function        New-SSHShellStream                                                             ...                                                                          

Function        New-SSHTrustedHost                                                             ...                                                                          

Function        Remove-SFTPDirectory                                                           ...                                                                          

Function        Remove-SFTPFile                                                                ...                                                                          

Function        Remove-SFTPItem                                                                ...                                                                          

Function        Remove-SFTPSession                                                             ...                                                                          

Function        Remove-SSHSession                                                              ...                                                                          

Function        Remove-SSHTrustedHost                                                          ...                                                                          

Function        Rename-SFTPFile                                                                ...                                                                          

Function        Set-SFTPContent                                                                ...                                                                          

Function        Set-SFTPCurrentDirectory                                                       ...                                                                          

Function        Set-SFTPLocation                                                               ...                                                                          

Function        Test-SFTPPath                                                                  ...                                                                          

Cmdlet          Get-SCPFile                                                                    ...                                                                          

Cmdlet          Get-SCPFolder                                                                  ...                                                                          

Cmdlet          Get-SFTPFile                                                                   ...                                                                          

Cmdlet          New-SFTPSession                                                                ...                                                                          

Cmdlet          New-SSHSession                                                                 ...                                                                          

Cmdlet          Set-SCPFile                                                                    ...                                                                          

Cmdlet          Set-SCPFolder                                                                  ...                                                                          

Cmdlet          Set-SFTPFile                                                                   ...                                                                           

 

Now I can invoke New-SSHSession as expected… I get prompted for credentials as expected for example… and connect…

 

New-SSHSession -ComputerName Test -Credential (Get-Credential root)

Connected : True

SessionId : 0

Host      : Test

Session   : Renci.SshNet.SshClient 

 

 

From: Schorschi [mailto:schorschi@dc.rr.com] 
Sent: Sunday, April 19, 2015 07:21
To: 'darkoperator/Posh-SSH'
Subject: RE: [Posh-SSH] Cannot install module per instructions given, import-module fails (#41)

 

Also…

 

PS C:\Users\Test> iex (New-Object Net.WebClient).DownloadString("https://gist.github.com/darkoperator/6152630/raw/c67de4f7cd780ba367cccbc2593f38d18ce6df89/instposhsshdev")

Downloading latest version of Posh-SSH from https://github.com/darkoperator/Posh-SSH/archive/master.zip

File saved to C:\Users\TEST\AppData\Local\Temp\Posh-SSH.zip

Uncompressing the Zip file to C:\Users\Test\Documents\WindowsPowerShell\Modules

Renaming folder

Module has been installed

Import-Module : The specified module 'posh-ssh' was not loaded because no valid module file was found in any module directory.

At line:17 char:1

+ Import-Module -Name posh-ssh

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : ResourceUnavailable: (posh-ssh:String) [Import-Module], FileNotFoundException

    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

 

 

PS C:\Users\Test\documents\WindowsPowerShell\modules\posh-ssh> ls

 

 

    Directory: C:\Users\Test\documents\WindowsPowerShell\modules\posh-ssh

 

 

Mode                LastWriteTime     Length Name

----                -------------     ------ ----

d----        04/19/2015     07:14            Assembly

d----        04/19/2015     07:14            en-US

d----        04/19/2015     07:14            Format

d----        04/19/2015     07:14            PoshSSH

d----        04/19/2015     07:14            tests

-----        03/28/2015     05:16        536 .gitattributes

-----        03/28/2015     05:16       1970 .gitignore

-----        03/28/2015     05:16       1478 License.md

-----        03/28/2015     05:16      16778 PortForward.ps1

-----        03/28/2015     05:16       2879 Posh-SSH.psd1

-----        03/28/2015     05:16      16579 Posh-SSH.psm1

-----        03/28/2015     05:16      40960 PoshSSH.dll

-----        03/28/2015     05:16      10230 Readme.md

-----        03/28/2015     05:16      42539 Sftp.ps1

-----        03/28/2015     05:16       3592 Trust.ps1

 

PS C:\Users\Test\documents\WindowsPowerShell\modules\posh-ssh> write-host $env:PSModulePath

C:\Program Files (x86)\VMware\Infrastructure\vSphere PowerCLI\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules\

 

Schorschi

**Comment by darkoperator** [comment]
hum seems you do not have your documents folder in your modules path. You should have it by default 

```
PS C:\Users\Test\documents\WindowsPowerShell\modules\posh-ssh> write-host $env:PSModulePath

C:\Program Files (x86)\VMware\Infrastructure\vSphere PowerCLI\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
```
you will have to add it by hand to your profile file https://msdn.microsoft.com/en-us/library/dd878326(v=vs.85).aspx

**Comment by dachshund-digital** [comment]
I found several Google references where the opposite appears to be true… so this issue may not be that uncommon?  I use number of modules and snap-ins and never had an issue before.

 

Schorschi

**Comment by darkoperator** [comment]
I Will ase yo the docs to verify before installing.

**Comment by jstore** [comment]
I'm having a similar, but slightly different issue. The install works fine on my workstation, but fails on my server and I can't find away to "unblock" the file on my server. Could you tell me where the module gets installed so I can just copy it from workstation to my server? I figured it would be in:
C:\Windows\System32\WindowsPowerShell\v1.0\Modules
but it isn't.
I just need to know the directories that Posh-SSH gets installed to. I would really appreciate it.

**Comment by darkoperator** [comment]
It installed under the users Documents\Windows PowerShell\Modules

you can place it in C:\Windows\System32\WindowsPowerShell\v1.0\Modules by hand if you like to have it available to all users.
