### ISSUE TITLE
Problem using Invoke-SSHCommand

### ISSUE THREAD

**Issue by SnehasishNandy** [darkoperator/Posh-SSH#414]
Hi All

I am executing the below command to create user against HP switch after taking a SSH Session (using POSH-SSH)

`$Session = New-SSHSession -ComputerName $sHost -Credential $cred`
`[string]$SystemView = $(Invoke-SSHCommand -SSHSession $Session -Command "system-view").Output
 `$SystemView`
[string]$CreateUser = $(Invoke-SSHCommand -SSHSession $Session -Command "local-user nocadmin class manage").Output`
`$CreateUser`

The result I am getting like
`
<AAA6HPEDIS02>system System View: return to User View with Ctrl+Z.`
`
<AAA6HPEDIS02>local-user nocadmin class manage               ^  % Unrecognized command found at '^' position.
`
Same when I ran through putty, it worked fine

<img width="295" alt="error" src="https://user-images.githubusercontent.com/34299076/130429313-981e7544-e7e6-4c77-aaf2-10b223978119.PNG">

Please let me know what is the issue.

**Comment by darkoperator** [comment]
Because Putty is an interactive shell and invoke-sshcommand does not work on shell but executes a binary directly. Try with a shellstream since that is an interactive shell

**Comment by SnehasishNandy** [comment]
@darkoperator : Yes, tried doing using `New-SSHShellStream` and worked fine. thanks
