### ISSUE TITLE
SFTP commands replaced with SCP but don't support reusing session

### ISSUE THREAD

**Issue by plmcgrn** [darkoperator/Posh-SSH#419]
It looks like version 3.0.0 retired all the SFTP commands, but did so in a way that makes them inefficient with auth.

Example, New-SCPItem needs credentials passed to each call.  This means that, unlike the previous SFTP commands, you can't create a session and reuse that.  If one wants to loop through a list of files for audit purposes, instead of uploading the folder they live in, it makes this process a bit inefficient on connections.  I don't see anywhere in the documentation that notes a way to get a 1:1 replacement of the SFTP file upload commands without handling auth within an upload loop.

Also, the cmdlets were removed, but the documentation for those cmdlets are still in the package.

**Comment by darkoperator** [comment]
I just did a clean install of version 3.0 and the SFTP command are there under PowerShell 5.1.  SCP was ob version 2.x it is another protocols since some system may not have SFTP. If you do a import-module posh-ssh with -verbose -force does it show the SFTP commands being loaded?

**Comment by plmcgrn** [comment]
I ended up doing a clean uninstall and forced a reinstall of 2.3.0, which had me back up and running.  Server patching for August seemed to have broken something with the .NET library this module relies on.  I opted not to refactor my code to use New-ScpItem because of the way it requires auth on a per-command basis, vs. Set-SftpItem which could reuse an existing established session.  My process needs audit logging to cover each file upload, so I wanted to ensure that at least the session management stayed efficient, even if I do have to loop through each file.

**Comment by darkoperator** [comment]
A refactor was not needed because

1. SFTP cmdlets where not removed
2. SCP cmdlets did not replace it and they are not even knew.

**Comment by plmcgrn** [comment]
Um, the change log says otherwise.  Also, when attempting to use a clean install of 3.0.0, it was saying the cmdlets my script was calling don't exist.

From [https://github.com/darkoperator/Posh-SSH/blob/master/CHANGELOG.md](https://github.com/darkoperator/Posh-SSH/blob/master/CHANGELOG.md)

`Set-SFTPFile and Set-SFTPFolder cmdlets removed (use Set-SCPItem instead).`

**Comment by MVKozlov** [comment]
> use Set-SCPItem instead

read this carefully :)

**Comment by darkoperator** [comment]
A typo in the changelog the command is now set-sftpitem

**Comment by plmcgrn** [comment]
OK, and I see that this command does take an existing Session object/ID, so that should cover my session efficiency concerns.

**Comment by darkoperator** [comment]
Reopen the issue if there are still problems, making the changes to the changelog
