### ISSUE TITLE
Invoke-SSHStreamExpectSecureAction : Reading the stream is not working

### ISSUE THREAD

**Issue by hervej** [darkoperator/Posh-SSH#42]
Hello,
My config : Linux opensuse

I would like to pass commands with root by "su -"

I use the "

here is my script "
$ SSHStream = New SSHShellStream -Index 0
Invoke- SSHStreamExpectSecureAction -ShellStream $ SSHStream -Command ' su -' -ExpectString ' Passord: ' -SecureAction (read -host -AsSecureString ) -Verbose
"

I get good " Action has-been Executed .
True " but when I do" SSHStream.Read $ () "
I did not return e .

The idea is to root "su - " and then place orders in Stream.

Thank you in advance for your help

Furthermore, there is a typo in your examples ' Passord: 'instead of ' " Password:"

Hervé.J

**Comment by hervej** [comment]
SSHStream.read() et not SSHStream.Read().

Sorry

**Comment by darkoperator** [comment]
When you read the stream what do you get back?

**Comment by hervej** [comment]
Nothing

**Comment by darkoperator** [comment]
Weird you should at least see the shell prompt when you read the stream
```
PS C:\> $steam = New-SSHShellStream -SessionId 0
PS C:\> $steam.Read()
Last failed login: Mon Apr 20 09:06:18 EDT 2015 from infidel01.darkoperator.com on ssh:notty
There was 1 failed login attempt since the last successful login.
Last login: Wed Mar 25 11:17:48 2015 from 192.168.1.104
[admin@localhost ~]$

PS C:\> Invoke-SSHStreamExpectSecureAction -ShellStream $steam -Command 'su -' -ExpectString 'Password:' -SecureAction (Read-Host -AsSecureString)
***********
True
PS C:\> $steam.Read()

Last login: Wed Mar 25 08:52:13 EDT 2015 on tty1
[root@localhost ~]#
```

**Comment by hervej** [comment]
Oui bizarre, je vais essayer sur un autre serveur

**Comment by hervej** [comment]
I tried SINCE the terminal PowerShell , it works.

But Ca ISE me nothing back

**Comment by hervej** [comment]
I confirm that it works very well in powershell console but no turning powershell ISE .

Super this module, thank you

If you have an idea for ise 'm curious

**Comment by darkoperator** [comment]
On ISE for PowerShell 4.0 I do not have this problem. What version of PowerShell are you using?

**Comment by hervej** [comment]
I have version 4.0. If you run this script Stream.Read () works ?

"New-SSHSession -ComputerName "nomserveurLinux" -Port 22
$SessionId=Get-SSHSession
$SessionId=$SessionId.SessionId
$SSHStream = New-SSHShellStream -Index $SessionId
Invoke-SSHStreamExpectSecureAction -ShellStream $SSHStream -Command 'su -' -ExpectString "Password:" -SecureAction (read-host -AsSecureString) -Verbose
$SSHStream.read()
$SSHStream.WriteLine("pwd")
$SSHStream.read()
Remove-SSHSession -SessionId $SessionId -Verbose
"

**Comment by darkoperator** [comment]
you need to add a sleep time between writing and reading so as to give enough time for the command to finish execution.

**Comment by hervej** [comment]
Thank you for the solution , it works.
