### ISSUE TITLE
ssh command " export " "source filename" not work for setting environment variable

### ISSUE THREAD

**Issue by iciiu** [darkoperator/Posh-SSH#420]
Hi, I try to Invoke SSHCommand to set environment variable before some other operation on remote linux host.
But after invoke sshcommand such as export A=B, or source filename.sh, both won't work.

example：
 Invoke-SSHCommand -SSHSession $temp_session-Command "export temp_key=temp_value"
 $Result = Invoke-SSHCommand -SSHSession $temp_session-Command "env | grep -w temp_key"

$Result.Output will be {}

**Comment by MVKozlov** [comment]
`Invoke-SSHCommand` opens a new shell every time it is used.
assign env before any command
"export temp_key=temp_value; env | grep -w temp_key"
or use shell stream

**Comment by iciiu** [comment]
> `Invoke-SSHCommand` opens a new shell every time it is used.
> assign env before any command
> "export temp_key=temp_value; env | grep -w temp_key"
> or use shell stream

Thanks.

**Comment by darkoperator** [comment]
Because invoke-sshcommand does not create an interactive session, you need to use a shellstrram
