### ISSUE TITLE
Receive timeout when using module in Microsoft Azure

### ISSUE THREAD

**Issue by smneal** [darkoperator/Posh-SSH#43]
Hi,

I've not found a lot online about using this within Azure, however I've uploaded the module into Azure, and am trying to connect to an SSH enabled server, but keeping receiving New-SSHSession : Session operation has timed out.

The code is very basic at the moment, and works fine on my local machine

$secpwd = ConvertTo-SecureString "mypassword" -AsPlainText -Force
$mycreds = New-Object System.Management.Automation.PSCredential ("myusername", $secpwd)
New-SSHSession -ComputerName "myservername" -Credential $mycreds -ConnectionTimeout 30 -AcceptKey -Verbose
 
Invoke-SSHCommand -Index 0 -Command "pwd"
 
Remove-SSHSession -SessionId 0

Any help appreciated.

Thanks,

Steve

**Comment by darkoperator** [comment]
If you try to connect with plink or putty from the same host to the target does it work?

**Comment by smneal** [comment]
Hi, Thanks for your response. I haven't tried this, but what I have done is use the error output from this in a try catch clause to determine if the VM is shutdown or not. It seems that shutting down a Linux VM from bash in Azure doesn't communicate back to the Azure management interfaces that it is shutdown.

Calling this command generates either a System.Net.Sockets.SocketException or a Renci.SshNet.Common.SshOperationTimeoutException depending on whether the vm is shutdown or running respectively.

Not the neatest, but it works.

Thanks
