### ISSUE TITLE
Get-SCPItem fetch connection failed - error

### ISSUE THREAD

**Issue by lleitner-hub** [darkoperator/Posh-SSH#430]
Hello,

I am trying to fetch a config.xml from a firewall with following code (added linebreaks for this post):

```
try{ 
Get-SCPItem -ComputerName $ip -Credential $credential -Path $configPath 
-PathType File -Destination "$($_savePath)" 
-NewName "$($firewallName)_config.xml" -AcceptKey -Force -WarningAction Ignore
}
catch{
    ... <log erro> ...
    return -1
}
```

I have four firewalls and two of them are currently up and I can successfully fetch the configs. 
But the other two are down and I get this error on the powershell window:
`Connection failed to establish within 10000 milliseconds.`
Can I also fetch this "error"? I want to write it in the logfile.
Thanks!

**Comment by darkoperator** [comment]
Bu down I take it as off, of they are off the scp/ssh service will be off so you will not be able to connect

**Comment by MVKozlov** [comment]
add `-ErrorAction Stop`

**Comment by lleitner-hub** [comment]
> 
> 
> add `-ErrorAction Stop`

ah perfect, simple. Thanks!


> Bu down I take it as off, of they are off the scp/ssh service will be off so you will not be able to connect
> […](#)

That is totally fine. I just wanted to keep track of these "notifications".
