### ISSUE TITLE
Installer Missing Files? Unable to find type [SSH.Stores.MemoryStore]

### ISSUE THREAD

**Issue by Cynomus** [darkoperator/Posh-SSH#433]
PS C:\> Install-Module -Name Posh-SSH -Force
PS C:\> Import-Module -Name Posh-SSH -Verbose
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Posh-SSH.psd1'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\VMware.VimAutomation.Common\12.4.0.18627061\net45\Newtonsoft.Json.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\VMware.VimAutomation.Common\12.4.0.18627061\net45\Newtonsoft.Json.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\2.2\Assembly\Renci.SshNet.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\2.2\Assembly\Renci.SshNet.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Assembly\SshNet.Security.Cryptography.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Assembly\SshNet.Security.Cryptography.dll'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Format\SSHSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Format\SFTPSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Format\Renci.SshNet.SshCommand.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Format\Renci.SshNet.Sftp.SftpFile.Format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module Posh-SSH.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\PoshSSH.dll'.
VERBOSE: Importing cmdlet 'Get-SCPFile'.
VERBOSE: Importing cmdlet 'Get-SCPFolder'.
VERBOSE: Importing cmdlet 'Get-SCPItem'.
VERBOSE: Importing cmdlet 'Get-SFTPFile'.
VERBOSE: Importing cmdlet 'Get-SFTPItem'.
VERBOSE: Importing cmdlet 'Set-SCPItem'.
VERBOSE: Importing cmdlet 'Set-SFTPFile'.
VERBOSE: Importing cmdlet 'Set-SFTPFolder'.
VERBOSE: Importing cmdlet 'Set-SFTPItem'.
VERBOSE: Importing cmdlet 'New-SFTPSession'.
VERBOSE: Importing cmdlet 'New-SSHSession'.
VERBOSE: Importing cmdlet 'Set-SCPFile'.
VERBOSE: Importing cmdlet 'Set-SCPFolder'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Posh-SSH.psm1'.
At **C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Posh-SSH.psm1:3277** char:32
'+'     class SSHRegistryKeyStore: SSH.Stores.MemoryStore {
'+'                                ~~~~~~~~~~~~~~~~~~~~~~
**Unable to find type [SSH.Stores.MemoryStore].**
At C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Posh-SSH.psm1:3285 char:31
'+'                  $hostData = [SSH.Stores.KnownHostValue]@{ HostKeyNam ...
'+'                               ~~~~~~~~~~~~~~~~~~~~~~~~~
Unable to find type [SSH.Stores.KnownHostValue].
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TypeNotFound

**Comment by MVKozlov** [comment]
what is your os/ps versions ?
did you tried to clear C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0 before install (there might be a beta version)

I think the problem here
>VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\VMware.VimAutomation.Common\12.4.0.18627061\net45\Newtonsoft.Json.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\VMware.VimAutomation.Common\12.4.0.18627061\net45\Newtonsoft.Json.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\2.2\Assembly\Renci.SshNet.dll'.

The Newtonsoft loaded from VMware and Renci.SshNet from v2.2

**Comment by Cynomus** [comment]
Thank you, yes I had a parallel install of 2.2 and 3.0. I removed v2.2 and the install and load of v3.0 now works. This all started because Posh-SSH would not New-SSHSession to a 'VMware ESXi 7.0.2 build-18538813' VMhost. It is now working, thanks again for all of your effort on this Module, I use it often, and have written many functions that rely on it.
