### ISSUE TITLE
New-SSHSession doesn't properly timeout on new fingerprint

### ISSUE THREAD

**Issue by MikeMM70** [darkoperator/Posh-SSH#44]
Creating a new session using:

    New-SSHSession -ComputerName  192.168.10.9 -Credential (Get-Credential) -ConnectionTimeOut 10
does not timeout after 10 seconds if the ServerSSH fingerprint is new / not trusted which basicly hangs the script when it should return a timeout error specifying that the command recieved an untrusted fingerprint and expired waiting for input.  
   If there was a new man-in-the-middle and '-AcceptKey $True' was not specified (as would be recommended for security reasons), the script would just hang with no indication why if it was running as a scheduled task.
  Thanks for creating this module!

**Comment by bielawb** [comment]
I don't think ConnectionTimeout is suitable for that scenario. Instead, I would rather see a parameter that fails if acceptance of key is needed (similar to batch mode in plink/putty).

**Comment by darkoperator** [comment]
Correct the TimeOut Option does not apply for the acceptance of the key. I designed the module with functions to manage keys so as to minimize this problem and ensure proper secure best practices when associating a key with a server.

**Comment by darkoperator** [comment]
If a MiTM Attack happens and the key does not match it will exit with an error
```
throw new System.Security.SecurityException("SSH fingerprint mismatch for host " + computer1);
```
https://github.com/darkoperator/Posh-SSH/blob/master/PoshSSH/PoshSSH/NewSSHSession.cs#L276

**Comment by FireInWinter** [comment]
I agree with bielawb. I think an option to error on hosts with unknown keys would be a good idea.  That way if you have a list of servers and you don't want to accept the key automatically, you could just have it give you an error if it isn't trusted ( i.e. host/key not in Get-SSHTrustedHost list ).  A parameter like BatchMode, ErrorOnUntrusted, or TrustedOnly would be a help in those situations.  It would be possible to work around it using Get-SSHTrustedHost on each host, but isn't very convenient.

**Comment by darkoperator** [comment]
Added -ErrorOnUntrusted switch to SCP cmdlets, New-SSHSession and New-SFTPSession on branch 1_7_5 C# code for next version 1.7.5, once merged in to master and published to gallery will update.

**Comment by darkoperator** [comment]
uploaded 1.7.5 to the gallery
