### ISSUE TITLE
Execute Shell script (on remote machine) from Powershell using Invoke-SSHCommand 

### ISSUE THREAD

**Issue by JyotiPrakashMallick** [darkoperator/Posh-SSH#440]
Context: While trying to execute a shell script using Invoke-SSHCommand from PowerShell is not working while trying to execute a shell script.

script block:
```
$usrName = "<user_Name>";
        $passw = "<Password>"
$remoteMachine = "<machine_name>"
        $password = ConvertTo-SecureString $passw -AsPlainText -Force;
        $pscredential = New-Object -TypeName System.Management.Automation.PSCredential($usrName, $password);
        $cmd = "bash getEPOHTime.sh";
    
        $currentSessionID = New-SSHSession -ComputerName $remoteMachine -Credential $pscredential -Force 
        #$rest = Invoke-SSHCommand -SSHSession $currentSessionID -Command "pwd" <working fine>
        $rest = Invoke-SSHCommand -SSHSession $currentSessionID -Command $cmd <not working, error below>
        Write-Host "------------>"$rest.Output
```

Error Message:
```
Exception calling "EndExecute" with "1" argument(s): "Command 'bash getEPOHTime.sh' has timed out."
At C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\2.2\Posh-SSH.psm1:260 char:25
+                         $Output = $_.cmd.EndExecute($_.Async)
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException       
    + FullyQualifiedErrorId : SshOperationTimeoutException
```

I tried to change it using following,
```
$cmd = "bash ./getEPOHTime.sh" [not working]
$rest = Invoke-SSHCommand -SSHSession $currentSessionID -Command $($cmd) [not working]
$rest = Invoke-SSHCommand -SSHSession $currentSessionID -Command "$($cmd)" [not working]
$rest = Invoke-SSHCommand -SSHSession $currentSessionID -Command "$cmd" [not working]
```
What I am missing because Invoke-SSHCommand -SSHSession $currentSessionID -Command "pwd" works fine

**Comment by MVKozlov** [comment]
any chance to see what in `getEPOHTime.sh` ? may be it wait for input ?

**Comment by JyotiPrakashMallick** [comment]
#!/usr/bin/env bash 

delayTime=$1

getFututeEPOCHTime(){
    if [ "$1" ]; then
    #main script... 
            if [[ "$1" -gt 1 && "$1" -le 24 ]]; then
                date -d"+$1hour" +%s%3N
            elif [[ "$1" -ge 25 && "$1" -le 60 ]]; then
                date -d"+$1minutes" +%s%3N
            elif [[ "$1" -ge 61 && "$1" -le 172900 ]]; then
                date -d"+$1seconds" +%s%3N
            else
                 date -d"+$1seconds" +%s%3N
            fi

    else
        echo "Retrievning the Current EPOCH time"
        date  +%s%3N
    fi

}

getFututeEPOCHTime "$delayTime"
# end of the script



$SHELL

**Comment by MVKozlov** [comment]
@JyotiPrakashMallick, your `$SHELL` in the end of script launch current shell, so you script is never ended
simple test:
``` bash
#!/bin/bash
echo $SHELL started
$SHELL
echo $SHELL ended
```

**Comment by JyotiPrakashMallick** [comment]
Missed it completely , removing $shell from the bottom of the script fix the issue
