### ISSUE TITLE
Can't Import Module 

### ISSUE THREAD

**Issue by consocio** [darkoperator/Posh-SSH#444]
Hi, i've dowloaded the master as zip unblocked and extracted in C:\Program Files\WindowsPowerShell\Modules 
but when i run `import-module posh-ssh -verbose` i get: 

VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\posh-ssh\posh-ssh.psd1'.
VERBOSE: Loading 'Assembly' from path 'C:\Program
Files\WindowsPowerShell\Modules\posh-ssh\Assembly\Newtonsoft.Json.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program
Files\WindowsPowerShell\Modules\posh-ssh\Assembly\Newtonsoft.Json.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\posh-ssh\Assembly\Renci.SshNe
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\posh-ssh\Assembly\Renci.SshNe
VERBOSE: Loading 'Assembly' from path 'C:\Program
Files\WindowsPowerShell\Modules\posh-ssh\Assembly\SshNet.Security.Cryptography.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program
Files\WindowsPowerShell\Modules\posh-ssh\Assembly\SshNet.Security.Cryptography.dll'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\posh-ssh\Format\SSHSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\posh-ssh\Format\SFTPSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\posh-ssh\Format\Renci.SshNet.SshCommand.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\posh-ssh\Format\Renci.SshNet.Sftp.SftpFile.Format.ps1xml'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\posh-ssh\PoshSSH.dll'.
import-module : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral,
PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ import-module posh-ssh -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

can you help me?

**Comment by darkoperator** [comment]
What version of Windows and version of PowerShell? It is failing on the assembly so the main suspect is version of .Net and/or PowerShell

**Comment by consocio** [comment]
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4.0\Client
    Version    REG_SZ    4.0.0.0

**Comment by darkoperator** [comment]
Windows 10?

**Comment by consocio** [comment]
Windows Server 2k12 R2

**Comment by consocio** [comment]
SOLVED installing .NET framework 4.8

**Comment by darkoperator** [comment]
That is a very old version of windows, you will need to upgrade to the latest version of .Net that was supported for it.
