### ISSUE TITLE
updating Posh-SSH module requires manual intervention

### ISSUE THREAD

**Issue by MikeMM70** [darkoperator/Posh-SSH#45]
Not a big deal really, but if you try to upgrade the module using the orginal install script
   invoke-expression (New-Object Net.WebClient).DownloadString("https://gist.github.com/darkoperator/6152630/raw/c67de4f7cd780ba367cccbc2593f38d18ce6df89/instposhsshdev")
with a shell open that has used any of the Posh-SSH module commands it will fail to rename the  "Posh-SSH-master" copy of the folder to "Posh-SSH" because the file/folder will be in use. I'm not sure if there is much you can do about this though.  Can the module be unloaded to unlock the folder before the rename?

**Comment by darkoperator** [comment]
It can not since one the assembly is loaded it can not be unloaded sadly. powershell intance needs to be closed and a new one opened
