### ISSUE TITLE
Import-Module : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by mkanet** [darkoperator/Posh-SSH#450]
I have a **Windows Server 2016** server that doesn't have access to the Internet.  Hence, I manually copied the latest Posh-SSH module folder (and all respective contents); and, placed it under the below folder:
`C:\Program Files\WindowsPowerShell\Modules`

When I try to import the module, I get the below error message:

![Posh-SSH-Module](https://user-images.githubusercontent.com/811008/162085941-c67d2719-6afb-486b-bdc9-b5736f475845.png)

What's the quickest/easiest way to import the module on this server?
PS:  The same thing happens if I copy it to any other modules folders in the Modules paths.

Do I need to install a specific version of the .NET Framework Runtime?

**Comment by MVKozlov** [comment]
Yes, you need 4.71 (4.61 at least)
https://github.com/darkoperator/Posh-SSH/issues/437#issuecomment-1012539193

@darkoperator  I think it is need to mention it in readme/requirements on powershellgallery and here
and, please add 3.0 and 3.0.1 to /Releases

**Comment by darkoperator** [comment]
In the readme I state 5.1 and 7 as the versions of PS. Is the framework install needed for 5.1? Dont know which version this error is in

**Comment by mkanet** [comment]
> In the readme I state 5.1 and 7 as the versions of PS. Is the framework install needed for 5.1? Dont know which version this error is in

I am using the default PS version that ships with Windows Server 2016... PS Version 5.1.

**Comment by MVKozlov** [comment]
> > Yes, you need 4.71 (4.61 at least) [#437 (comment)](https://github.com/darkoperator/Posh-SSH/issues/437#issuecomment-1012539193)
> > @darkoperator I think it is need to mention it in readme/requirements on powershellgallery and here and, please add 3.0 and 3.0.1 to /Releases
> 
> Thank you. So I can install any version of .NET Framework, as long as it's version >=4.61? I was thinking of installing version 4.8
Not sure about 4.61, but sure about 4.71+, just not core

**Comment by MVKozlov** [comment]
> In the readme I state 5.1 and 7 as the versions of PS. Is the framework install needed for 5.1? Dont know which version this error is in

Can't remember about 4.61. May be I do not test it, may be tests fails, but in earlier beta i set framework minimum as "4.7" but ps does not understand anything other but "4". Because 4.7 is buggy, let minimal requirement be 4.7.1

**Comment by mkanet** [comment]
I just installed version 4.8.  It resolved the issue.  Thanks again!

**Comment by darkoperator** [comment]
I see it can be replicated with windows 2016 running PS 5.1
