### ISSUE TITLE
How to capture the remote device's entire SSH session?

### ISSUE THREAD

**Issue by mkanet** [darkoperator/Posh-SSH#456]
I am able to automate the below manual commands I type on a Cisco router terminal session:

```
CISCO-ROUTER#config t
Enter configuration commands, one per line.  End with CNTL/Z.
CISCO-ROUTER(config)#int Gi1/0/6
CISCO-ROUTER(config-if)#no shut
CISCO-ROUTER(config-if)#exit
CISCO-ROUTER(config)#exit
CISCO-ROUTER#
```

...using something similar to the Posh-SSH script example below:

```
$Command = "config t"
New-SSHSession -ComputerName $DeviceName -AcceptKey -Force -Credential $Credential
$session = Get-SSHSession -Index 0 
foreach ($Command in $Commands) {
   $stream = $session.Session.CreateShellStream("dumb", 0, 0, 0, 0, 1000)
   $stream.Write("$Command`n")
   sleep 3
   $Response += $stream.Read()
}
Write-Output $Response
```

How can I **_also_** capture the text as it appears on the remote Cisco device **in addition to** the response instead of returning the response only?  My script will only display the response:

I.E.:
```
Enter configuration commands, one per line.  End with CNTL/Z.
CISCO-ROUTER(config)#
CISCO-ROUTER(config-if)#
CISCO-ROUTER(config-if)#
CISCO-ROUTER(config)#
```

I would like for it to display the whole session, not just the results:

I.E.:
```
CISCO-ROUTER#config t
Enter configuration commands, one per line.  End with CNTL/Z.
CISCO-ROUTER(config)#int Gi1/0/6
CISCO-ROUTER(config-if)#no shut
CISCO-ROUTER(config-if)#exit
CISCO-ROUTER(config)#exit
CISCO-ROUTER#
```

Is there something like an `$stream.Read.DisplayLocalEcho()` method or any other easy way to do this?

**Comment by darkoperator** [comment]
To be honest I do not believe it can. I only use the module for automation and not for documenting actions.

**Comment by mkanet** [comment]
@darkoperator thank you so much for the quick and honest response.  I was able to recreate a fake remote command prompt by adding an extra carriage return (then capturing it) like this:

```
$stream.Write("`n")
sleep 1
$Prompt = $stream.Read()
$Prompt = $Prompt.trim()
$FakePrompt = "$Prompt$Command"
```
