### ISSUE TITLE
Posh-SSH 3.0.1 doesn't work correctly inside PoshRSJob jobs

### ISSUE THREAD

**Issue by Georgy-Sav** [darkoperator/Posh-SSH#457]
Hi,

Currently we are using Posh-SSH version 2.2 to collect some information from Linux servers. As we are checking quite a lot of servers once in several minutes we need some parallelization. PoshRSJob works without any issues, but we still get some problems because of the Renci .NET library timeouts bug.

I tried to update Posh-SSH to version 3.0.1 today and I'm getting a lot of "The process cannot access the file 'C:\Users\username\.poshssh\hosts.json' because it is being used by another process.". Some of the servers are checked properly at the same time.

Error happens at time then PowerShell creates a session with this command:
`New-SSHSession $NodeName -Credential $Credential -AcceptKey -ErrorAction:Stop`

Jobs are started with this command:
`$linuxNodes | Start-RSJob { some code } -ModulesToImport 'Posh-SSH' -Throttle $Throttle -Name { $_.NodeName }`

Please check if it can be fixed.

**Comment by MVKozlov** [comment]
You may try to workaround it thru direct use of `new-sshjsonstore` outside of rsjob and use this store as parameter to new-XXXsession

**Comment by Georgy-Sav** [comment]
Thank you for your reply. I didn't find this function, although, I think, you pointed me to a right direction.
`Get-SSHJsonKnowHost` should help in this situation, I think I'll try to use separate files for different servers, as only 1 thread is connecting to a server at a time.
Like this:
`Get-SSHJsonKnowHost -LocalFile $path\$serverName.json`

**Comment by MVKozlov** [comment]
Yes, that is the command I mean (sorry, I was far away from computer)
My idea was to preload store before use
``` powershell
# get the store object
$store = Get-SSHJsonKnowHost
# preload file into memory, it use lazy loading
Get-SSHTrustedHost -KnowHostStore $store | Out-Null
# use it
Start-RSJob {
  New-SSHSession -KnownHost $using:store .....
}
```

**Comment by Georgy-Sav** [comment]
I tried this approach and I got the same error in 1 of the jobs.
I had 4 servers, all of them successfully added their keys to the file, but still I got `The process cannot access the file 'C:\work\test_ssh.json' because it is being used by another process.` error. I'm not sure what exactly produces this error as I see server key from failed job in the file.
This was the code I ran:
```
$json_store = Get-SSHJsonKnowHost C:\work\test_ssh.json
$hosts | Start-RSJob {
  $ssh = New-SSHSession $_ -Credential $Using:cred -AcceptKey -ErrorAction:Stop -KnownHost $Using:json_store;
  Remove-SSHSession $ssh
}
```
I suspect error is caused by Set method of Json store object. I tried to call it by itself and it writes to a specified file immediatly after Set method call.

I also tried to use separate files for each Linux server, on test server set it works fine, so it should solve my problem.

Thank you for your help!

**Comment by MVKozlov** [comment]
@Georgy-Sav, seems You have some server that not in your store, because `Set` called only on new key. You can check it by removing `-AcceptKey` parameter

I just test your case and cannot confirm that there any problem when all hosts already known and in the file

My test was:
``` powershell
$json_store = Get-SSHJsonKnowHost
$json_store | Get-SSHTrustedHost # list of hosts
$j = $hosts | Start-RSJob {
    New-SSHSession $_ -Credential $using:cred -KeyString $using:keystring -ErrorAction:Stop -KnownHost $Using:json_store;
$j.Error # to test for any errors
```
if $hosts contains only known and accepted hosts than $j.Error will be empty
If any of $hosts not contained in store, there will be something like
".....localized error message......  Do you want to trust the fingerprint ....fingerprint.... "

**Comment by darkoperator** [comment]
In vesion 3 you can also try New-SSHMemoryKnownHost
