### ISSUE TITLE
Sequence contains more than one element

### ISSUE THREAD

**Issue by christianBoman** [darkoperator/Posh-SSH#46]
When trying to connect to a server using get-scp, new-sftpsession or any other command I get a "Sequence contains more than one element". An example command might be: 

new-sftpsession -computername $server -Credential (Get-Credential)

The server is on a different domain, so my credentials are passed as DOMAIN\username if that helps.

**Comment by darkoperator** [comment]
That is because Posh-SSH does not work with Kerberos or NTLM so the the DOMAIN\User format does not work for creds

**Comment by christianBoman** [comment]
Thanks, that makes sense. Weird thing is that I still get the same error if I leave off the domain from my username. I pass credentials using get-credential or by creating a new PSCredential object. I can get to other servers using password/key auth just fine so something with the configuration of this server must be causing problems. 

I apologize if this is not the appropriate place to post this issue as it might not be an issue with your code. Am wondering if you can tell from the error message where in the source this error is occurring and if maybe I'm just doing something wrong. Thanks!

**Comment by darkoperator** [comment]
Your logs on the Linux server should be able to provide a clue on what is wrong with the configuration

**Comment by FireInWinter** [comment]
Actually this is because of how the username retrieved from the credential object in the Posh-SSH code.  I added a different issue since I didn't read the details of this first.  But the problem is that it is using _credential.GetNetworkCredential().UserName, which doesn't include the domain.  Problem goes away if you use _credential.UserName.

**Comment by christianBoman** [comment]
Yes, the Linux server that I am trying to connect to is on a different domain so that makes sense.

**Comment by darkoperator** [comment]
Download the latest version from Github and test to see if it now fixes the issue.

**Comment by christianBoman** [comment]
Yes, this appears to be resolved. Thank you!
