### ISSUE TITLE
$SSHStream.Connected returns nothing

### ISSUE THREAD

**Issue by shabbir1282** [darkoperator/Posh-SSH#466]
$SSHStream = New-SSHShellStream -Index 0 -Columns 150

Write-Host $SSHStream.Connected

# the above returns nothing. 

# so
# the following too does not work.

if ($SSHStream.Connected -like "True") {

**Comment by MVKozlov** [comment]
`$SSHStream -eq $null` ?

btw, if you want to test _connected_ use `if ($SSHStream.Connected) {}`
there is no reasons to convert boolean to string and compare it with `-like`. It for wildcards

**Comment by shabbir1282** [comment]
thanks, I tried **if ($SSHStream.Connected)** too, actually when i try to print the value of **$SSHStream.Connected** it returns nothing and it is the same for successful and unsuccessful connections. 

tried with version 3.0.0 and then upgraded to 3.0.4, results are same.

**Comment by MVKozlov** [comment]
did you created shell session already by `New-SSHSession` ?
because ShellStream uses Shell Session
If you have session is it in Connected state?

**Comment by darkoperator** [comment]
The test should be against the session object and not on that property but rather on the renci object in the session object that is the one that updates with the state. 

```
 Carlos Perez@DESKTOP-LH0AJLB  ~  $sess = Get-SSHSession
 Carlos Perez@DESKTOP-LH0AJLB  ~  $sess.Session

ForwardedPorts ConnectionInfo              IsConnected KeepAliveInterval
-------------- --------------              ----------- -----------------
{}             Renci.SshNet.ConnectionInfo        True 00:00:10

 Carlos Perez@DESKTOP-LH0AJLB  ~  $sess.Session.IsConnected
True
 Carlos Perez@DESKTOP-LH0AJLB  ~  $sess.Session.IsConnected
False
 Carlos Perez@DESKTOP-LH0AJLB  ~  $sess.Session.IsConnected | gm

   TypeName: System.Boolean

Name        MemberType Definition
----        ---------- ----------
CompareTo   Method     int CompareTo(System.Object obj), int CompareTo(bool value), int IComparable.CompareTo(System.O…
Equals      Method     bool Equals(System.Object obj), bool Equals(bool obj), bool IEquatable[bool].Equals(bool other)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
GetTypeCode Method     System.TypeCode GetTypeCode(), System.TypeCode IConvertible.GetTypeCode()
ToBoolean   Method     bool IConvertible.ToBoolean(System.IFormatProvider provider)
ToByte      Method     byte IConvertible.ToByte(System.IFormatProvider provider)
ToChar      Method     char IConvertible.ToChar(System.IFormatProvider provider)
ToDateTime  Method     datetime IConvertible.ToDateTime(System.IFormatProvider provider)
ToDecimal   Method     decimal IConvertible.ToDecimal(System.IFormatProvider provider)
ToDouble    Method     double IConvertible.ToDouble(System.IFormatProvider provider)
ToInt16     Method     short IConvertible.ToInt16(System.IFormatProvider provider)
ToInt32     Method     int IConvertible.ToInt32(System.IFormatProvider provider)
ToInt64     Method     long IConvertible.ToInt64(System.IFormatProvider provider)
ToSByte     Method     sbyte IConvertible.ToSByte(System.IFormatProvider provider)
ToSingle    Method     float IConvertible.ToSingle(System.IFormatProvider provider)
ToString    Method     string ToString(), string ToString(System.IFormatProvider provider), string IConvertible.ToStri…
ToType      Method     System.Object IConvertible.ToType(type conversionType, System.IFormatProvider provider)
ToUInt16    Method     ushort IConvertible.ToUInt16(System.IFormatProvider provider)
ToUInt32    Method     uint IConvertible.ToUInt32(System.IFormatProvider provider)
ToUInt64    Method     ulong IConvertible.ToUInt64(System.IFormatProvider provider)
TryFormat   Method     bool TryFormat(System.Span[char] destination, [ref] int charsWritten)
```

here I connected to a raspberry pi and then shutdown the raspberry, you can see the connection state was updated. for the main property, it sadly does not get updated as it happens so using the renci object inside the session object is better.

**Comment by shabbir1282** [comment]
> did you created shell session already by `New-SSHSession` ? because ShellStream uses Shell Session If you have session is it in Connected state?

yes, the session is created and is connected.

**Comment by shabbir1282** [comment]
Hi 

> The test should be against the session object and not on that property but rather on the renci object in the session object that is the one that updates with the state.
> 
> ```
>  Carlos Perez@DESKTOP-LH0AJLB  ~  $sess = Get-SSHSession
>  Carlos Perez@DESKTOP-LH0AJLB  ~  $sess.Session
> 
> ForwardedPorts ConnectionInfo              IsConnected KeepAliveInterval
> -------------- --------------              ----------- -----------------
> {}             Renci.SshNet.ConnectionInfo        True 00:00:10
> 
>  Carlos Perez@DESKTOP-LH0AJLB  ~  $sess.Session.IsConnected
> True
>  Carlos Perez@DESKTOP-LH0AJLB  ~  $sess.Session.IsConnected
> False
>  Carlos Perez@DESKTOP-LH0AJLB  ~  $sess.Session.IsConnected | gm
> 
>    TypeName: System.Boolean
> 
> Name        MemberType Definition
> ----        ---------- ----------
> CompareTo   Method     int CompareTo(System.Object obj), int CompareTo(bool value), int IComparable.CompareTo(System.O…
> Equals      Method     bool Equals(System.Object obj), bool Equals(bool obj), bool IEquatable[bool].Equals(bool other)
> GetHashCode Method     int GetHashCode()
> GetType     Method     type GetType()
> GetTypeCode Method     System.TypeCode GetTypeCode(), System.TypeCode IConvertible.GetTypeCode()
> ToBoolean   Method     bool IConvertible.ToBoolean(System.IFormatProvider provider)
> ToByte      Method     byte IConvertible.ToByte(System.IFormatProvider provider)
> ToChar      Method     char IConvertible.ToChar(System.IFormatProvider provider)
> ToDateTime  Method     datetime IConvertible.ToDateTime(System.IFormatProvider provider)
> ToDecimal   Method     decimal IConvertible.ToDecimal(System.IFormatProvider provider)
> ToDouble    Method     double IConvertible.ToDouble(System.IFormatProvider provider)
> ToInt16     Method     short IConvertible.ToInt16(System.IFormatProvider provider)
> ToInt32     Method     int IConvertible.ToInt32(System.IFormatProvider provider)
> ToInt64     Method     long IConvertible.ToInt64(System.IFormatProvider provider)
> ToSByte     Method     sbyte IConvertible.ToSByte(System.IFormatProvider provider)
> ToSingle    Method     float IConvertible.ToSingle(System.IFormatProvider provider)
> ToString    Method     string ToString(), string ToString(System.IFormatProvider provider), string IConvertible.ToStri…
> ToType      Method     System.Object IConvertible.ToType(type conversionType, System.IFormatProvider provider)
> ToUInt16    Method     ushort IConvertible.ToUInt16(System.IFormatProvider provider)
> ToUInt32    Method     uint IConvertible.ToUInt32(System.IFormatProvider provider)
> ToUInt64    Method     ulong IConvertible.ToUInt64(System.IFormatProvider provider)
> TryFormat   Method     bool TryFormat(System.Span[char] destination, [ref] int charsWritten)
> ```
> 
> here I connected to a raspberry pi and then shutdown the raspberry, you can see the connection state was updated. for the main property, it sadly does not get updated as it happens so using the renci object inside the session object is better.

the following worked, if ($sess.Session.IsConnected) {

thanks for your help.
