### ISSUE TITLE
New-SSHSession to Linux with PowerBroker fails

### ISSUE THREAD

**Issue by FireInWinter** [darkoperator/Posh-SSH#47]
We have some Linux servers that are using PowerBroker ( for Active Directory integration) and I can't connect to those although putty works fine.  I get "new-sshsession : Permission denied (password).".

Looking at the source code in NewSSHSession.cs, it looks like you are using "_credential.GetNetworkCredential().UserName" to get the username.  This strips out the domain information from the user.  So instead of the user MyDomin\MyUser, it gets \MyUser.  If you were to use "_credential.UserName", I think that would fix the issue.

Thanks.

**Comment by FireInWinter** [comment]
I just looked some more and it looks like the same thing is being used in the following files:
ConnectionInfoGenerator.cs
GetScpFile.cs
GetScpFolder.cs
NewSftpSession.cs
NewSSHSession.cs
SetScpFile.cs
SetScpFolder.cs

**Comment by darkoperator** [comment]
issue should be fixed now, download the latest version from github

**Comment by FireInWinter** [comment]
I downloaded the current version and it is fixed.  Thanks for making that change that fast.  Also I can now verify that another changed that happened a while ago is fixed with connecting to hosts with and "_" in the name
