### ISSUE TITLE
New-SSHSession -Verbose:$false not working

### ISSUE THREAD

**Issue by espressionist** [darkoperator/Posh-SSH#472]
Does anyone know how to get rid of the following line when connecting to a new host? I've tried adding "-Verbose:$false" in the New-SSHSession cmdlet but it doesn't seem to do the trick
`VERBOSE: Set host key for w.x.y.z to aa:bb:cc:dd.....`

**Comment by darkoperator** [comment]
sadly the way I implemented it from the host side you can not disable it.

**Comment by antonisathanasiou** [comment]
Thanks for confirming, at least it wasn't me doing something stupid :) 
will work my way around this!

**Comment by Ultchad** [comment]
I have the same problem,
This is work fine on 3.0.0
This not work (verbose:$false) on 3.0.4

I think this line don't have `if (MyInvocation.BoundParameters.ContainsKey("Verbose"))` before:
https://github.com/darkoperator/Posh-SSH/blame/faf38d3cd8b9b0d424e2b154a69e6b75b482d06e/Source/PoshSSH/PoshSSH/NewSessionBase.cs#L333

I don't code in C# sorry if it's not the cause , i try to help

**Comment by ycambourieu** [comment]
Same problem here.
It works on 3.0.1 and it is broken after that.
This verbose message is displayed even if `-Verbose:$false` or `$VerbosePreference = 'SilentlyContinue'` are set. It is impossible to remove this `VERBOSE: Set host key for w.x.y.z to aa:bb:cc:dd.....` messages when a new host key is added to the hosts.json file.


In Posh-SSH/Source/PoshSSH/PoshSSH/NewSessionBase.cs, Replacing Line 333 by :
```
if (MyInvocation.BoundParameters.ContainsKey("Verbose"))
     {
       Host.UI.WriteVerboseLine(string.Format("Set host key for {0} to {1}", computer1, fingerPrint));
 }
```
And Line 336 by :
```
if (MyInvocation.BoundParameters.ContainsKey("Verbose"))
     {
       Host.UI.WriteVerboseLine("Host key is not updated in store.");
 }
```
Should do the trick based on the rest of your code.

Hope it will help 😄
