### ISSUE TITLE
ExitStatus 225

### ISSUE THREAD

**Issue by green0tree22** [darkoperator/Posh-SSH#473]
below are the code that i used to execute the comand ls -l im able to connect to my target machine.
also pingID are also get approved but i notice once the pingID is appear on my phone and get approved its disconnecting and 
and got Exitstataus=225

it was my first time to use and test..my goal is to change password remotely in 15 centos machines.

please help how can i achieve on this.
Thanks
`$getcredential = "testuser"
New-SSHSession -ComputerName 192.168.12.12 -Credential ($getcredential) -Verbose

$session = Get-SSHSession -Index 0
$stream = $session.Session.CreateShellStream("dumb", 0, 0, 0, 0, 1000)
$stream.Write("ls- l") #("show ver`n")
$stream.Read()
Invoke-SSHCommand -Index 0 -Command "ls-l"`

**Comment by green0tree22** [comment]
any help

**Comment by darkoperator** [comment]
This is againg a Cisco switch or something? Invoke-SSHcommand will not work if it is. Why are you ru running both shellstream and invoke-sshcommand? Which one generates the error? What is the target?What version of the module is it?

**Comment by green0tree22** [comment]
this to connect to centos machine.
in shellstream it show the pingid authentication token  i dont know if this
get authenticated and then the invoke-sshcommand show exitstatus 225

and also the news-sshsession showing connected status but when i used the
invoke-sshcommand the status is exitstatus 225 maybe this is not
authenticating. so i add the shellstream for authentication token.

all i want is to change password remotely to all 15 centos machine.

thanks

**Comment by green0tree22** [comment]
> This is againg a Cisco switch or something? Invoke-SSHcommand will not work if it is. Why are you ru running both shellstream and invoke-sshcommand? Which one generates the error? What is the target?What version of the module is it?
> […](#)
> Sent from my iPhone
> On Aug 23, 2022, at 7:22 AM, green0tree22 ***@***.***> wrote: ﻿ any help — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Hi,
What is the target?Limux
What version of the module is it? 2.2        Posh-SSH

**Comment by green0tree22** [comment]
H DarkOperator,
What is the target?Limux
What version of the module is it? 2.2 Posh-SSH

**Comment by darkoperator** [comment]
If the password change is requested at logon, it will not be possible with Posh-SSH, if it is a command after logon the a shellstream will have to be use. Invoke-sshcommand does not work in a terminal, it instructs the sshd process to run a given command with parameters while shellstream is an actual terminal that maintains state. The module you are running is very old. Version 3.x has been out for a while. Maybe https://github.com/darkoperator/Posh-SSH/blob/master/docs/Invoke-SSHStreamExpectAction.md could be used if it is via shell command in a terminal

**Comment by green0tree22** [comment]
is invoke- SSHsteamExpectaction can be used remotely?

**Comment by darkoperator** [comment]
```
PS C:\Users\Carlos Perez> New-SSHSession 192.168.1.165 pi

SessionId  Host                                                      Connected
---------  ----                                                      ---------
    0      192.168.1.165                                               True


PS C:\Users\Carlos Perez> $stream = New-SSHShellStream -SessionId 0
PS C:\Users\Carlos Perez> Invoke-SSHStreamExpectAction -ShellStream $stream -Command "command to run" -ExpectString "expectedstring"
```

The terminal is a Stream so you can read and write to it just like a file stream

**Comment by green0tree22** [comment]
"command to run" is this like any command?

**Comment by darkoperator** [comment]
The command/text is written  to the terminal and a new carriage return is entered. You can look at the source of that function and the invoke-sshshellstreamcommand function to get and idea how to code it up as long as it is not a prompt at time of connection.
