### ISSUE TITLE
Assistance needed:  Capturing $stream.Read() response without issuing "blind" Start-Sleep command afterwards

### ISSUE THREAD

**Issue by mkanet** [darkoperator/Posh-SSH#475]
Considering there are a couple of known issues with Cisco devices and Posh-SSH, I have to use SSH streams in Posh-SSH.  

Hence, I created a PS function `Send-SSHCommand`_(below)_ which will send any sequence of commands to a Cisco device; and, return the output as _FAST_ as possible.

Instead of putting a _blind_ `Start-Sleep 5` command after issuing `$ResponseRaw = $stream.Read()`, I would like to use a clever way to wait the minimum amount of time (before reading the entire stream) by using some kind of `while` command.  For example:  `while (!($stream.EndExpect("$DeviceName#"))) { Start-Sleep 60 }`.  I know that I can't use the method `.EndExpect` like that.  But, I think you'll at least understand my goal.

Note:  The only thing I know for sure is that the end of the output ALWAYS ends with `$DeviceName#`.  

```
function Send-SSHCommand {
    Param(
        [Parameter(Mandatory=$true)]
        [Array]$Commands,
        [Parameter(Mandatory=$false)]
        [string]$DeviceName
    )

    BEGIN       {
                    $Final = @()
                    remove-variable Response -ErrorAction SilentlyContinue
                    Get-SSHSession | select SessionId | Remove-SSHSession | Out-Null
                    New-SSHSession -ComputerName $DeviceName -AcceptKey -Credential $Credential -ErrorAction SilentlyContinue | Out-Null
                    while ((Get-SSHSession).Host -ne $DeviceName) {      
                    
                        New-SSHSession -ComputerName $DeviceName -AcceptKey -Credential $Credential -ErrorAction SilentlyContinue | Out-Null
                        sleep -mill 500
                    }

                    $session = Get-SSHSession -Index 0 
                    $stream = $session.Session.CreateShellStream("dumb", 0, 0, 0, 0, 1000)
                    $stream.Write("terminal Length 0`n")
                    sleep -mill 60
                    $stream.Read() | Out-Null
                }

    PROCESS {

                foreach ($Command in $Commands)
                {
                    $stream.Write("$Command`n")                    

                    Start-Sleep 5
                    # while (!($stream.EndExpect("$DeviceName#"))) { Start-Sleep 60 }
                    # while ($stream.DataAvailable -eq $true) { Start-Sleep 60 }
                    # $stream.WriteTimeout = 5000

                    $ResponseRaw = $stream.Read()                    
                    $Response = $ResponseRaw -split "`r`n" | %{$_.trim()}
                    $Response = $Response | ?{$_ -NotMatch "$DeviceName#"}
                    $Final += $Response
                }
            }

    END     {
                Return $Final
                $stream.Write("exit`n")
                Remove-SSHSession -Index 0 | Out-Null
            }

}
```

**Command:**  Send-SSHCommand -DeviceName "Cisco-device01" -Commands "sho log | include Aug 2.*

**Comment by MVKozlov** [comment]
the first candidate to eat something is here I think
```
Begin {
...
$stream.Read() | Out-Null
}
PROCESS {
```
If I really understant about what you call "first several lines from the $stream.Read() stream is truncated"

**Comment by mkanet** [comment]
Thank you so much for helping @MVKozlov !  First, let me explain the issue/symptom, so you understand...  

Presuming a Cisco device outputs the below (very long) output... after executing the command `sho log | include Aug 2.*(UPDOWN|BFD)`:

```
sho log | include Aug 2.*(UPDOWN|BFD)
Aug 23 00:46: %LINK-3-UPDOWN: Interface Port-channel1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/2, changed state to up
Aug 23 00:48: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan1, changed state to down
Aug 23 00:48: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/1, changed state to down 2
Aug 23 00:46: %LINK-3-UPDOWN: Interface Port-channel1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/2, changed state to up
Aug 23 00:48: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan1, changed state to down
Aug 23 00:49: %BGP-5-NBR_RESET: Neighbor 123.164.51.112 reset (BFD adjacency down)
Aug 23 00:46: %LINK-3-UPDOWN: Interface Port-channel1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/2, changed state to up
Aug 23 00:48: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan1, changed state to down
Aug 23 00:48: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/1, changed state to down 2
Aug 23 00:46: %LINK-3-UPDOWN: Interface Port-channel1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/2, changed state to up
Aug 23 00:48: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan1, changed state to down
Aug 23 00:49: %BGP-5-NBR_RESET: Neighbor 123.164.51.112 reset (BFD adjacency down)
Aug 23 00:46: %LINK-3-UPDOWN: Interface Port-channel1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/2, changed state to up
Aug 23 00:48: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan1, changed state to down
Aug 23 00:48: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/1, changed state to down 2
Aug 23 00:46: %LINK-3-UPDOWN: Interface Port-channel1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/2, changed state to up
Aug 23 00:48: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan1, changed state to down
Aug 23 00:49: %BGP-5-NBR_RESET: Neighbor 123.164.51.112 reset (BFD adjacency down)
.   ...........................................
.      
.    2 pages of text
.   ...........................................
Aug 24 01:50: %BGP-5-ADJCHANGE: neighbor 122.164.56.111 Down BFD adjacency down
Aug 24 06:51: %BGP-5-NBR_RESET: Neighbor 1100:523:100::D765 reset (BFD adjacency down)
Aug 24 08:45: %BGP-5-ADJCHANGE: neighbor 1100:523:100::D765 Down BFD adjacency down
Cisco-Router01#
```

**The captured PoSH-SSH stream will look like below using my script**
```
ROTO-5-UPDOWN: Line protocol on Interface Vlan1, changed state to down
Aug 23 00:49: %BGP-5-NBR_RESET: Neighbor 123.164.51.112 reset (BFD adjacency down)
Aug 23 00:46: %LINK-3-UPDOWN: Interface Port-channel1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/2, changed state to up
Aug 23 00:48: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan1, changed state to down
Aug 23 00:48: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/1, changed state to down 2
Aug 23 00:46: %LINK-3-UPDOWN: Interface Port-channel1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/1, changed state to up
Aug 23 00:47: %LINK-3-UPDOWN: Interface GigabitEthernet0/2, changed state to up
Aug 23 00:48: %LINEPROTO-5-UPDOWN: Line protocol on Interface Vlan1, changed state to down
Aug 23 00:49: %BGP-5-NBR_RESET: Neighbor 123.164.51.112 reset (BFD adjacency down)
.   ...........................................
.      
.    2 pages of text
.   ...........................................
Aug 24 01:50: %BGP-5-ADJCHANGE: neighbor 122.164.56.111 Down BFD adjacency down
Aug 24 06:51: %BGP-5-NBR_RESET: Neighbor 1100:523:100::D765 reset (BFD adjacency down)
Aug 24 08:45: %BGP-5-ADJCHANGE: neighbor 1100:523:100::D765 Down BFD adjacency down
Cisco-Router01#

```

Having said that, I am not sure how to use your solution in my script.  My script allows to send multiple commands in sequence to a cisco device as fast as possible; and, display the respective output when done.  The script works great... except for commands that take a long time get truncated.

Thanks again.  I tried many different ways unsuccessfully before asking for help.

**Comment by mkanet** [comment]
@MVKozlov please see below script.. which will explain what I'm trying to do:

```


function Send-SSHCommand {
    Param(
        [Parameter(Mandatory=$true)]
        [Array]$Commands,
        [Parameter(Mandatory=$false)]
        [string]$DeviceName
    )

    BEGIN       {
        
                    $Final = @()
                    remove-variable Response -ErrorAction SilentlyContinue
                    Get-SSHSession | select SessionId | Remove-SSHSession | Out-Null
                    New-SSHSession -ComputerName $DeviceName -AcceptKey -Credential $Credential -ErrorAction SilentlyContinue | Out-Null
                    while ((Get-SSHSession).Host -ne $DeviceName) {      
                    
                        New-SSHSession -ComputerName $DeviceName -AcceptKey -Credential $Credential -ErrorAction SilentlyContinue | Out-Null
                        sleep -mill 500
                    }

                    $session = Get-SSHSession -Index 0 
                    $stream = $session.Session.CreateShellStream("dumb", 0, 0, 0, 0, 1000)
                    $stream.Write("terminal Length 0`n")
                    sleep -mill 60
                    $stream.Read() | Out-Null
                }

    PROCESS {

                foreach ($Command in $Commands)
                {
                    $stream.Write("$Command`n")
                    $ResponseRaw = $stream.Read()

                    Sleep 1      #trying to replace this with:   while (!(($ResponseRaw).EndsWith("$DeviceName#"))) {sleep -mill 5}
                     
                    $Response = $ResponseRaw -split "`r`n" | %{$_.trim()}
                    $Response = $Response | ?{$_ -NotMatch "$DeviceName#"}
                     $Final += $Response
                }
            }

    END     {
                Return $Final
                $stream.Write("exit`n")
                Remove-SSHSession -Index 0 | Out-Null
            }

}
```

Send-SSHCommand -DeviceName "Cisco-Router01" -Commands "sho log | include Aug 2.*"

**Comment by mkanet** [comment]
@MVKozlov sorry for the confusion.  Please see my edited "original post" so my goal is easier to understand...

**Comment by MVKozlov** [comment]
Cannot say something about `$stream.EndExpect` because never use it
But `$stream.EndExpect()` and subsequent `$stream.Read()` look suspicious
A you sure that EndExpect() do not Read() your output inside ?

By the way, I hope you are prepared for some criticism :)
``` powershell
BEGIN {
...
New-SSHSession ...
while ((Get-SSHSession).Host -ne $DeviceName) {      
    New-SSHSession ...
}
$session = Get-SSHSession -Index 0 
```
this piece of code confused me
why are you trying to create a potentially infinite number of sessions but only use the first one later?

This will be much better
``` powershell
$session = New-SSHSession ...
if ($session.Connected)
```
 If You want to find session which is not hang, this not the first one

**Comment by mkanet** [comment]
Hi @MVKozlov the reason for the code in the BEGIN portion of my code is to get around [a cisco-related time-out bug](https://github.com/darkoperator/Posh-SSH/issues/340).  What I have currently automatically overcome the time-out exceptions when they occur; otherwise, it will not work at all when there's a time-out exception.  I will try to use your suggestion as an alternative, thanks.

Just to be clear, I am not familiar with any of the available methods/properties for $stream.  Below, are the ones I've _experimented_ with so far (commented out in my code currently). 
```
EndExpect              Method       string EndExpect(System.IAsyncResult asyncResult)
DataAvailable          Property     bool DataAvailable {get;}
WriteTimeout           Property     int WriteTimeout {get;set;}
```

I was just trying various desperate ways to wait the minimum amount of time after `$stream.Write("$Command`n")` in my code and before executing `$stream.Read()` in my code.   Can you or @darkoperator think of any way to do this?   The only alternative (which I don't want to do) is `Start-Sleep 5` which is too long of a wait for most quick commands that only take less than a second to capture.

**Comment by darkoperator** [comment]
Sorry I can not help at this time, Im in mission this week and will fly back home where my systems are next week

**Comment by mkanet** [comment]
> Sorry I can not help at this time, Im in mission this week and will fly back home where my systems are next week
> […](#)
> Sent from my iPhone
> On Aug 24, 2022, at 2:16 PM, MKANET ***@***.***> wrote: ﻿ Hi @MVKozlov the reason for the code in the BEGIN portion of my code is to get around a cisco-related time-out bug. What I have currently automatically overcome the time-out exceptions when they occur; otherwise, it will not work at all when there's a time-out exception. I will try to use your suggestion as an alternative, thanks. Just to be clear, I am not familiar with any of the available methods/properties for $stream. Below, are the ones I've experimented with so far (commented out in my code currently). EndExpect Method string EndExpect(System.IAsyncResult asyncResult) DataAvailable Property bool DataAvailable {get;} WriteTimeout Property int WriteTimeout {get;set;} I was just trying various desperate ways to wait the minimum amount of time after $stream.Write("$Commandn")in my code and before executing$stream.Read()in my code. Can you or @darkoperator think of any way to do this? The only alternative (which I don't want to do) isStart-Sleep 5` which is too long of a wait for most quick commands that only take less than a second to capture. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

No worries.  Thank you!  I can wait until you have time.

**Comment by MVKozlov** [comment]
> What I have currently automatically overcome the time-out exceptions when they occur

If the session creation timed out, New-SSHSession returns nothing and you can store the return value in a variable and test it for $null and $var.Connected
``` powershell
do {
  $session = New-SSHSession ....
} until ($session -ne $null -and $session.Connected)
```
Can't have access to any cisco device but
``` powershell
# while ($stream.DataAvailable -eq $true) { Start-Sleep 60 }
```
looks promising. and you can try to use `Start-Sleep -Milliseconds xxx`
or may be EndExpect() but I have no time just now to test it
and do not neglect the output of variables inside the loop for debugging

**Comment by MVKozlov** [comment]
Looked at `Expect()` in _Renci_ [source](https://github.com/sshnet/SSH.NET/blob/34ce2bd1d0eb7dc68f8ad5a68f407f66d774f9ed/src/Renci.SshNet/ShellStream.cs#L549)

This is definitely not what you need
`EndExpect()` it's a async companion to `BeginExpect()`

And `Expect()` itself is equal to `Read()` and `match()`, i.e. it wait for some string or regex and drop all internediate output

**Comment by mkanet** [comment]
> ```powershell
> do {
>   $session = New-SSHSession ....
> } until ($session -ne $null -and $session.Connected)
> ```

Unfortunately, when I use this:
```
Get-SSHSession | select SessionId | Remove-SSHSession | Out-Null
do {
    $session = New-SSHSession -ComputerName $DeviceName -AcceptKey -Credential $Credential
} until ($session -ne $null -and $session.Connected)
```
...it doesn't avoid the time-out issue.  Intermittently, I'll get the below exception:
```
New-SSHSession : Session operation has timed out
At C:\Users\MKANET\Desktop\dev\lab\test12.ps1:32 char:36
+ ...  $session = New-SSHSession -ComputerName $DeviceName -AcceptKey -Cred ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationTimeout: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], SshOperationTimeoutException
    + FullyQualifiedErrorId : SSH.NewSshSession
```
The code I've been using (below) was the only way I knew to avoid the above exception.  It works every time:
```
New-SSHSession -ComputerName $DeviceName -AcceptKey -Credential $Credential -ErrorAction SilentlyContinue | Out-Null
while ((Get-SSHSession).Host -ne $DeviceName) {      

    New-SSHSession -ComputerName $DeviceName -AcceptKey -Credential $Credential -ErrorAction SilentlyContinue | Out-Null
    sleep -mill 500
}
```

**Comment by mkanet** [comment]
> Looked at `Expect()` in _Renci_ [source](https://github.com/sshnet/SSH.NET/blob/34ce2bd1d0eb7dc68f8ad5a68f407f66d774f9ed/src/Renci.SshNet/ShellStream.cs#L549)
> 
> This is definitely not what you need `EndExpect()` it's a async companion to `BeginExpect()`
> 
> And `Expect()` itself is equal to `Read()` and `match()`, i.e. it wait for some string or regex and drop all intermediate output

I think I'll need to wait for darkoperator for this.  I wasn't able to figure out an effective way to take advantage of the available methods and properties for stream to wait the minimum amount of time between `$stream.Write("$Command``n")`  and `$stream.read()`

**Comment by mkanet** [comment]
@MVKozlov I think I figured it out!  Unless your or darkoperator can figure out a better way to do it, the below solution works every time!! 

``` powershell
$stream.Write("$Command`n")
$Length1 = $stream.length
sleep -mill 20
$Length2 = $stream.length
while ($Length1 -ne $Length2 ) {
    $Length1 = $stream.length
    sleep -mill 500
    $Length2 = $stream.length
}
$stream.Read() 
```
Note, the `while` command checks the length of the stream to see if it is still growing.  I just tried to simplify the above code using the below `while` command; however, I haven't gotten it to work yet.
``` powershell
while ($stream.length -ne $(sleep -mill 50 ; $stream.length)) {sleep -mill 500} 
```

**Comment by MVKozlov** [comment]
about _New-SSHSession_
my code just mimic your, but "the right way" :)
did you already try to use -ConnectionTimeout and -OperationTimeout switches ?

You just not Read() the stream if the length has grown in the last 500 milliseconds
if that suits you, so be it :)

**Comment by mkanet** [comment]
> about _New-SSHSession_ my code just mimic your, but "the right way" :) did you already try to use -ConnectionTimeout and -OperationTimeout switches ?
> 
> You just not Read() the stream if the length has grown in the last 500 milliseconds if that suits you, so be it :)

I was missing the -ConnectionTimeout and -OperationTimeout switches.  The below code works good and much nicer way to do it.  Thank you!
``` powershell
Get-SSHSession | select SessionId | Remove-SSHSession | Out-Null
do {
    $session = New-SSHSession -ComputerName $DeviceName -AcceptKey -ConnectionTimeout 5000 -OperationTimeout 5000 -Credential $Credential
} until ($session -ne $null -and $session.Connected)
```

Unless you or darkoperator can figure out a better solution the below code is the **only** way I know that can quickly capture the full stream without it getting truncated; assuming the stream doesn't get stuck while waiting for it to grow :).  I'll have to wait for darkoperator to see if there are any better solutions.  I appreciate all your help.

``` powershell
$stream.Write("$Command`n")
$Length1 = $stream.length
sleep -mill 200
$Length2 = $stream.length
while ($Length1 -ne $Length2 ) {
    $Length1 = $stream.length
    sleep -mill 200
    $Length2 = $stream.length
}
$stream.Read() 
```

**Comment by MVKozlov** [comment]
when i was need for cycle like that i use something like
``` powershell
$eol = 'device#'
$output = ''
do {
  Start-Sleep -Milliseconds 100
  if ($session.DataAvailable) {
    $output += $session.Read()
  }
} until ($ouput.EndsWith($eol))
```
you can try to combine this with yours

maybe your $eol is not just "$deviceName#" but "$deviceName# " or something like that...

btw, you can just `Get-SSHSession | Remove-SSHSession`

**Comment by mkanet** [comment]
Thank you!!  I really appreciate all your time to help.  Per your suggestion, I was finally able to reliably use the `.DataAvailable` method.  The code below works perfectly; and, MUCH better than my previous solution!
``` PowerShell
$eol = "$($DeviceName)#"
$output = ""
do {
  Start-Sleep -Milliseconds 100
  if ($stream.DataAvailable) {
    $output += $stream.Read()
  }
} until ($output.EndsWith($eol))
Write-Output $output
```
However, the below `New-Session` code sometimes gets stuck indefinitely.  I can't even press `<ctrl-break>` to stop it.  I'm not certain what is causing it to get stuck.  I'm guessing it might be related to the current time-out bug on Cisco devices.  Maybe you know how to prevent it from hanging?
```Powershell
Get-SSHSession | Remove-SSHSession | Out-Null
do {
    $session = New-SSHSession -ComputerName $DeviceName -AcceptKey -ConnectionTimeout 8000 -OperationTimeout 8000 -Credential $Credential
} until ($session -ne $null -and $session.Connected)
```
Currently, I have to rely on the "wrong way" below :-), which works reliably every single time:
```Powershell
Get-SSHSession | Remove-SSHSession | Out-Null
New-SSHSession -ComputerName $DeviceName -AcceptKey -Credential $Credential -ErrorAction SilentlyContinue | Out-Null
while ((Get-SSHSession).Host -ne $DeviceName) {      

    New-SSHSession -ComputerName $DeviceName -AcceptKey -Credential $Credential -ErrorAction SilentlyContinue | Out-Null
    sleep -mill 500
}
```

**Comment by MVKozlov** [comment]
Sorry, about the cisco timeout, I can not offer anything.

Can you test it a few times and look at `Get-SSHSession` - does it give any output with "lost" sessions or not ?

**Comment by mkanet** [comment]
I'll test it when I'm back at work on Monday...Thanks again.

**Comment by darkoperator** [comment]
closing since issue was resolved.

**Comment by darkoperator** [comment]
Actually expect was what I was going to recomment because it is what I use for sudo. Never dealt with an expired password. That is why I made this function https://github.com/darkoperator/Posh-SSH/blob/master/docs/Invoke-SSHStreamExpectSecureAction.md
