### ISSUE TITLE
No matching host key type found

### ISSUE THREAD

**Issue by Jup1tre** [darkoperator/Posh-SSH#476]
I am trying to ssh a Digi router using Posh-SSH. I was able to until they deprecates support for RSA signatures using the SHA-1 hash algorithm by default in the last firmwares version : 

Posh-SSH proposing : ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss
Router expecting : rsa-sha2-512,rsa-sha2-256

My question is, is there a way to add a support for those host key algorithms by configuring the Module?

For information, the script using Posh-SSH is designed to configure the router from the default config to the target config.

**Comment by darkoperator** [comment]
It would need to be added to SSH.Net since that is the library the module uses.

**Comment by darkoperator** [comment]
https://github.com/sshnet/SSH.NET The list of ciphers is in their readme and I believe some of those are supported

**Comment by Jup1tre** [comment]
thanks for you answer, but unfortunately they support only the below : 

Host Key Algorithms

SSH.NET supports the following host key algorithms:

    ssh-ed25519
    ecdsa-sha2-nistp256
    ecdsa-sha2-nistp384
    ecdsa-sha2-nistp521
    ssh-rsa
    ssh-dss

**Comment by darkoperator** [comment]
closing, sadly no much I can do there unless someone does a PR to the SSH.Net and adds the support.
