### ISSUE TITLE
support IPv6

### ISSUE THREAD

**Issue by lekshmanandgl** [darkoperator/Posh-SSH#477]
Hi All,

I am using the posh-sh module to connect a remote Linux machine. It works well in ipv4 but not in ipv6. Do I need to enable or configure anything in posh-ssh?

Note:

  Ipv6 is configured on a Linux machine and it's working fine.
   **I tested using ping
   Connected the Linux server using putty(used ipv6 address)**
Help Me to solve the issue.

**Comment by darkoperator** [comment]
Did you specify which interface to use with the <linklocal>%<my interface number> as the computername?
```
╰─❯ New-SSHSession -ComputerName fe80::4bfc:975e:cb93:f141%26 -Credential pi

PowerShell credential request
Enter your credentials.
Password for user pi: ********


Server SSH Fingerprint
Do you want to trust the fingerprint fc:e8:f3:2a:36:a1:f0:e:23:70:54:f5:49:91:7d:ae
[] Y  [] N  [?] Help (default is "N"): y
VERBOSE: Set host key for fe80::4bfc:975e:cb93:f141%26 to fc:e8:f3:2a:36:a1:f0:e:23:70:54:f5:49:91:7d:ae

SessionId  Host                                                      Connected
---------  ----                                                      ---------
    0      fe80::4bfc:975e…                                            True
```

**Comment by lekshmanandgl** [comment]
Thanks for your reply. I tried all the possiblity but not working

Ubandu server ip6 address :  **2001:0db8:85a3:0000:0000:0000:0000:0003**

I am able to ping, see the status

PS C:\Users\Administrator> **ping 2001:0db8:85a3:0000:0000:0000:0000:0003**

Pinging 2001:db8:85a3::3 with 32 bytes of data:
Reply from 2001:db8:85a3::3: time<1ms
Reply from 2001:db8:85a3::3: time<1ms
Reply from 2001:db8:85a3::3: time<1ms

Ping statistics for 2001:db8:85a3::3:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

and able to login using ssh.

login as: client
client@2001:0db8:85a3:0000:0000:0000:0000:0003's password:
Welcome to Ubuntu 12.04.5 LTS (GNU/Linux 3.13.0-32-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Wed Sep  7 05:45:07 EDT 2022

  System load:  0.11               Processes:           197
  Usage of /:   43.6% of 10.47GB   Users logged in:     1
  Memory usage: 46%                IP address for eth0: 
  Swap usage:   0%                 IP address for eth1:

  Graph this data and manage this system at:
    https://landscape.canonical.com/


Last login: Tue Sep  6 08:12:49 2022 from 

But when i tried new_sshsession , i got error 

PS C:\Users\Administrator> Get-NetAdapter -Name *

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Ethernet2                 Intel(R) 82574L Gigabit Network Co...#2      **20** Up                    1 Gbps


PS C:\Users\Administrator> **New-SSHSession -ComputerName 2001:0db8:85a3:0000:0000:0000:0000:0003%20** -Credential $RemoteCredential
New-SSHSession : The requested address is not valid in its context
At line:1 char:1
+ New-SSHSession -ComputerName 2001:0db8:85a3:0000:0000:0000:0000:0003% ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], SocketException
    + FullyQualifiedErrorId : SSH.NewSshSession

PS C:\Users\Administrator> Get-Module -Name pos-ssh
PS C:\Users\Administrator> Get-Module -Name poshssh
PS C:\Users\Administrator> Get-Module -Name posh-ssh

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
**Manifest   3.0.6      Posh-SSH                            {Get-SCPItem, Get-SFTPItem, Get-SSHJsonKnowHost, Get-SSHOpenSSHKnownHost...}**

**Comment by darkoperator** [comment]
sadly the output is not in a code block so hard to read. at least for linklocal IPv6 addresses is working here with me and my linux devices and VMs. My ISP does not support IPv6  so cant test outside of my local network. 

Raspian host :
```
pi@unifi:~ $ ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:2b:a5:1f brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.112/24 brd 192.168.1.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::4bfc:975e:cb93:f141/64 scope link
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 80:1f:02:d3:9c:90 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.118/24 brd 192.168.1.255 scope global dynamic noprefixroute wlan0
       valid_lft 64979sec preferred_lft 54179sec
    inet6 fe80::507:de4:79f2:a35b/64 scope link
       valid_lft forever preferred_lft forever
```
On My windows host:

```
Get-NetAdapter -InterfaceIndex 26

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
vEthernet (External)      Hyper-V Virtual Ethernet Adapter #3          26 Up           2C-F0-5D-3B-93-EC         1 Gbps

```

and when I connect to it over IPv6 from the interface in the same subnet I'm able to connect

```
 New-SSHSession -ComputerName fe80::4bfc:975e:cb93:f141%26 -Credential pi

PowerShell credential request
Enter your credentials.
Password for user pi: ********


SessionId  Host                                                      Connected
---------  ----                                                      ---------
    1      fe80::4bfc:975e…                                            True
```

**Comment by lekshmanandgl** [comment]
Thanks, 
Finally It worked.
i done the below command on ubandu server 

**ip -6 addr flush dev eth0 scope link
ip -6 link set eth0 up**


now connected using the below command.

**New-SSHSession -ComputerName 2001:0db8:85a3:0000:0000:0000:0000:0003 -Credential $RemoteCredential -ConnectionTimeout 10000**

**SessionId  Host                                                                                                                                 Connected
---------  ----                                                                                                                                 ---------
    1      2001:0db8:85a...                                                                                                                        True**

**Comment by darkoperator** [comment]
awesome!
