### ISSUE TITLE
Get-SFTPItem Error: The given path's format is not supported.

### ISSUE THREAD

**Issue by g4rry420** [darkoperator/Posh-SSH#479]
Hi,
On fetching the files from remote server into local `backup` folder, I am seeing the below error. Here is my code and screenshot of error.
```
$path = Split-Path -parent $PSScriptRoot
$remotePath = "/C:/Program Files (x86)/Apache Software Foundation/Apache2.4/htdocs/cdcitest"
# Puts currently deployed files into backup folder
Get-SFTPItem -SessionId $Session.SessionId -Path $remotePath -Destination "$($path)\backup" -Verbose
```
![Screenshot 2022-09-08 220610](https://user-images.githubusercontent.com/61521805/189257302-5b05c2da-43bf-4c45-9009-8c1f95a7912b.png)

**Comment by MVKozlov** [comment]
I think there is something wrong with `/C:/`.  first "/" or ":"

**Comment by g4rry420** [comment]
What do you mean ? Can you please elaborate ?

**Comment by darkoperator** [comment]
The forward slash before C:

**Comment by g4rry420** [comment]
Removing the slash before C; results in this error:
![Screenshot 2022-09-09 132117](https://user-images.githubusercontent.com/61521805/189409374-3c825bcc-6d12-4325-aa89-f13cdcabb805.png)

**Comment by g4rry420** [comment]
This worked for me. Thank you for help.

```
$remotePath = "../../Program Files (x86)/Apache Software Foundation/Apache2.4/htdocs/cdcitest/"

# Puts currently deployed files into backup folder
Get-SFTPItem -SessionId $Session.SessionId -Path $remotePath -Destination "$($path)\backup" -Verbose
```
