### ISSUE TITLE
New-SSHSession : Client not connected.

### ISSUE THREAD

**Issue by mpaszenda** [darkoperator/Posh-SSH#48]
I'm try to execute following line:
New-SSHSession -ComputerName blahblah -Credential (Get-Credential) -Verbose
And I've got error:
VERBOSE: Using SSH Username and Password authentication for connection.
VERBOSE: Fingerprint for blahblah: <deleted>
VERBOSE: Fingerprint matched trusted fingerprint for host blahblah
New-SSHSession : Client not connected.
At line:1 char:15
+ New-SSHSession <<<<  -ComputerName blahblah -Credential (Get-Credential) -Verbose
    + CategoryInfo          : NotSpecified: (:) [New-SSHSession], SshConnectionException
    + FullyQualifiedErrorId : Renci.SshNet.Common.SshConnectionException,SSH.NewSshSession
No matter if this is know host or completely new one same error persist.

**Comment by darkoperator** [comment]
Could you please provide more information, like:
- what device or SSH Server you are connecting to (OpenSSH, SSH.com)
- what errors are shown in your sever logs.
- what version of .Net are you using.

I need to replicate an issue to be able to fix it and need more info to be able to do it or figure out if it is a config issue on the server.

**Comment by darkoperator** [comment]
Also if you can provide a $error[0] | fl * -force and update with that output after you get the error to get more info on it.

**Comment by darkoperator** [comment]
closing since no further feedback provided.
