### ISSUE TITLE
Exclude a Folder from Get-SFTPChildItem command

### ISSUE THREAD

**Issue by g4rry420** [darkoperator/Posh-SSH#481]
Hi, I am fetching a folder from remote but I wanted to exclude one nested folder from it and in my case, it is `backup` folder. Also, `backup` folder has files in it that I also want to exclude. What is the good approach for this ? 
```
$GetDeployedFiles = Get-SFTPChildItem -SessionId $Session.SessionId -Path $remotePath -Recursive
foreach ($File in $GetDeployedFiles) {
    Write-Host $File.FullName
}
```

**Comment by MVKozlov** [comment]
` | Where-Object {$_.FullName -match '/backup\b' }`

**Comment by g4rry420** [comment]
Thanks, it worked.
One more thing, how can I create these files that I fetched from remote ?

**Comment by darkoperator** [comment]
Upload with set-sftpitemSent from my iPhoneOn Sep 20, 2022, at 8:37 AM, Gurkiran Singh ***@***.***> wrote:﻿
Thanks, it worked.
One more thing, how can I create these files that I fetched from remote ?

**Comment by g4rry420** [comment]
I am sorry, but I meant to create those files locally that I fetched from server using `Get-SFTPChildItem`. Can I do that using `Set-SFTPItem` ?

**Comment by g4rry420** [comment]
I was able to resolve this using `Get-SFTPItem` command

```
  $excludedDirectories = "backup|transfer"
  $GetDeployedFiles = Get-SFTPChildItem -SessionId $Session.SessionId -Path $remotePath | Where-Object {$_.FullName -notmatch $excludedDirectories }

  foreach ($File in $GetDeployedFiles) {
    Get-SFTPItem -SessionId $Session.SessionId -Path "$($remotePath)\$($File.Name)" -Destination "$($path)\backup" -Verbose -Force
  }
```
