### ISSUE TITLE
Error: Move-SFTPItem

### ISSUE THREAD

**Issue by g4rry420** [darkoperator/Posh-SSH#482]
Hi, after runnning this command, I am facing error:
```
Move-SFTPItem -SessionId $Session.SessionId -Path "$($remotePath)/transfer" -Destination $remotePath -Verbose
```
![Screenshot 2022-09-22 210021](https://user-images.githubusercontent.com/61521805/191883786-30c99e0f-e881-4f7b-b231-1a1053903369.png)

**Comment by MVKozlov** [comment]
since we don't know anything about your servers and the existence of the target file, you can explore this thread.
https://github.com/sshnet/SSH.NET/issues/582
maybe it's yours
