### ISSUE TITLE
Add option to show results from Invoke-SSHCommand as they are generated

### ISSUE THREAD

**Issue by FireInWinter** [darkoperator/Posh-SSH#49]
It would be nice if there were an option to just stream the results as they come in from Invoke-SSHCommand.  For example:

Invoke-SSHSession -SessionId 0 -Command "tail /tmp/app_server.log -f 2>&1" -StreamResult

This is something I've done before using plink, but is a lot harder with New-SSHShellStream and then using the stream object.  In the above example, you wouldn't output the Host or ExitStatus.  There are a number of cases I can think of this being a good thing as you could then use it in a pipeline and not have to use the memory to hold larger amounts of data (if using Invoke-SSHCommand).  You could even have a HostVariable parameter and an ExitStatusVariable parameter to still give the same information as it currently does.  The parameter could be called StreamResult, FastResult, NoStatus or something similar.

**Comment by darkoperator** [comment]
Sadly not possible with the library I'm using for the module

**Comment by FireInWinter** [comment]
I'm fairly new to .net (most of my experience is from PowerShell), but I think it should be possible to do this.  I've played around with code based on creating a StreamReader from the output and it seems to work, but I'm not sure of the edge cases where it might fail.  I currently did it as a separate command, but I just copied Invoke-SSHCommand.  Everything before the "$Async =" is the same as the original.  It isn't checking for ExitStatus, so it still needs more work and could possibly be combined with Invoke-SSHCommand.

```
$Async = $cmd.BeginExecute()
$Duration = [System.Diagnostics.Stopwatch]::StartNew()
$Reader = New-Object System.IO.StreamReader -ArgumentList $cmd.OutputStream

try
{
    while(-not $Async.IsCompleted -and $Duration.Elapsed -lt $cmd.CommandTimeout )
    {                   
        if ( $Reader.Peek() -gt -1)
        {
            $Result = $Reader.ReadLine()                            
            $Result -replace '\n\r$'
        }
        Start-Sleep 1                        
    }
}
catch
{
    Write-Error -Message "Error with Command: $_"                    
}
finally
{
    # Using finally clause to make sure the command is ended if Ctrl-C is used to cancel it.                    
    if (-not $Async.IsCompleted -and $Duration.Elapsed -ge $cmd.CommandTimeout )
    {
        $cmd.EndExecute($Async)
                     
    }
    elseif ( -not $Async.IsCompleted )
    {
        $null = $cmd.CancelAsync() 
        Write-Warning "Canceled execution"                        
    }
}
```

**Comment by darkoperator** [comment]
The principle of PowerShell is to work with objects. Right now the API call available for executing individual commands maps to the SSH Exec command that provides all the pertinent info of the command executed once it is finished. To have it behave like you want it would be to have it create an interactive shell and modify the library s it provides the different streams and map those to the PS shell if you want the error and output streams separately. That is why I provide the stream option for those that need a more interactive approach they can script around the stream object what they need. The purpose of the module is to be for automation not for interactive work with SSH.

**Comment by FireInWinter** [comment]
While I agree that objects are preferred, some built in commands return just strings.  Using Get-Content doesn't include the name of the file or any of the properties of the file in the output, it just returns the text.  This example I gave is a very common thing to do.  You aren't really doing it interactively, just watching the tail of the file as it is written to.  In this case you don't really need to do the work for redirecting the error stream, since you can grab the exit code and error from $cmd when it is done.  They might not have it while it is streaming, but it doesn't mean that the data can't be provided later.  I'll try to flesh out my example some more, so you can see what I mean.
