### ISSUE TITLE
$Async.IsCompleted in Invoke-SSHCommand missing "-not"

### ISSUE THREAD

**Issue by FireInWinter** [darkoperator/Posh-SSH#50]
The while loop in Invoke-SSHCommand to show the verbose message about it waiting for the command to finish is only executed if the command is actually already finished.  It was probably intended to be "-not $Async.IsCompleted".  Although it seems to be working without it, so maybe it should be removed (or not have it sleep in it).
```
$Async = $cmd.BeginExecute()
while($Async.IsCompleted)
{
    Write-Verbose -Message 'Waiting for command to finish execution'
    try
    {
        Start-Sleep -Seconds 2
    }
    finally
    {
        $Output = $cmd.EndExecute($Async)
    }
}
```

**Comment by Aurabolt** [comment]
I believe this is the cause of the error I sometimes get in my script. See the log excerpt below. The exception error loops indefinitely. I can't reproduce it on demand, but this script is SSH'ing to many different hosts and running a couple commands on each. Sometimes it works without a problem, and sometimes it gets stuck in this loop:

Fri, 15 May 2015 01:04:40 GMT - Executing command to get SSH version . . .
Fri, 15 May 2015 01:04:44 GMT - [E] Exception calling "EndExecute" with "1" argument(s): "Either the IAsyncResult object did not come from the
Fri, 15 May 2015 01:04:44 GMT - [E] corresponding async method on this type, or EndExecute was called multiple times with the same IAsyncResult."
Fri, 15 May 2015 01:04:44 GMT - [E] At C:\Scripts\includes\Posh-SSH\Posh-SSH.psm1:241 char:25
Fri, 15 May 2015 01:04:44 GMT - [E] +                         $Output = $cmd.EndExecute($Async)
Fri, 15 May 2015 01:04:44 GMT - [E] +                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fri, 15 May 2015 01:04:44 GMT - [E]     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
Fri, 15 May 2015 01:04:44 GMT - [E]     + FullyQualifiedErrorId : ArgumentException

Fri, 15 May 2015 01:04:46 GMT - [E] Exception calling "EndExecute" with "1" argument(s): "Either the IAsyncResult object did not come from the
Fri, 15 May 2015 01:04:46 GMT - [E] corresponding async method on this type, or EndExecute was called multiple times with the same IAsyncResult."
Fri, 15 May 2015 01:04:46 GMT - [E] At C:\Scripts\includes\Posh-SSH\Posh-SSH.psm1:241 char:25
Fri, 15 May 2015 01:04:46 GMT - [E] +                         $Output = $cmd.EndExecute($Async)
Fri, 15 May 2015 01:04:46 GMT - [E] +                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Fri, 15 May 2015 01:04:46 GMT - [E]     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
Fri, 15 May 2015 01:04:46 GMT - [E]     + FullyQualifiedErrorId : ArgumentException
