### ISSUE TITLE
Issue with New-SSHSession on RHEL 9

### ISSUE THREAD

**Issue by jfcd** [darkoperator/Posh-SSH#508]
Hello,

We have a number of Ubuntu computers that ssh into QEMU VMs using Posh-SSH within some packaging scripts. We're currently experiencing issues with New-SSHSession with a newly added RHEL 9 VM. I'm able to ssh into the VM normally but when I try to use New-SSHSession it gives the following output:
```
PS /home/engineer> New-SSHSession -ComputerName 127.0.0.1 -Force -Port 10022

cmdlet New-SSHSession at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
Credential
User: root
Password for user root: ********

WARNING: Host key for 127.0.0.1 is not being verified since Force switch is used.
New-SSHSession: An established connection was aborted by the server.
```
If I dump the logs of the sshd service on the other end it shows this:
```
[root@localhost ssh]# systemctl status sshd
● sshd.service - OpenSSH server daemon
     Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-02-02 11:29:42 EST; 31min ago
       Docs: man:sshd(8)
             man:sshd_config(5)
   Main PID: 1618 (sshd)
      Tasks: 1 (limit: 10944)
     Memory: 1.7M
        CPU: 17ms
     CGroup: /system.slice/sshd.service
             └─1618 "sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups"

Feb 02 11:29:42 localhost.localdomain systemd[1]: Starting OpenSSH server daemon...
Feb 02 11:29:42 localhost.localdomain sshd[1618]: Server listening on 0.0.0.0 port 22.
Feb 02 11:29:42 localhost.localdomain sshd[1618]: Server listening on :: port 22.
Feb 02 11:29:42 localhost.localdomain systemd[1]: Started OpenSSH server daemon.
Feb 02 12:00:51 localhost.localdomain sshd[1634]: Unable to negotiate with 10.0.2.2 port 37418: no matching host key type found. Their offer: ssh-rsa,ssh-dss [preauth]
```
In an attempt to remedy this I've added ssh-dss to HostKeyAlgorithms as well as PubkeyAcceptedAlgorithms but it doesn't seem to have made a difference. I've also been able to ssh into the VM with `ssh -o HostKeyAlgorithms=+ssh-dss -p 10022 root@localhost` successfully.

If it's of any help, the QEMU command I use to boot the VM is this: `qemu-system-x86_64 -cpu max -smp cores=2 -device e1000,netdev=net0 -boot menu=off -m 2G -drive "file=/path/to/file/Red-Hat-9-x64.qcow2,index=0,media=disk" -snapshot -netdev user,id=net0,hostfwd=tcp::10022-:22 -accel kvm`

We're using Posh-SSH version 3.0 and PS version 7.1.0-preview.6. Ubuntu version is 18.04.3 LTS. Appreciate any assistance you can give.

**Comment by MVKozlov** [comment]
Looks like you someway used old version of Posh-SSH (v2)
at least old Renci.SshNet

I was able to repeat this error when connecting to my new ubuntu 22 server with version 2 only
(ubuntu 22 removed ssh-rsa support from default config)

**Comment by jfcd** [comment]
I think it was more-so an error with RHEL 9. I re-enabled SHA1 in the cryptographic policies and that fixed it. Thanks for the assistance though.

**Comment by kpinel** [comment]
Sorry, but the issue does exist, at least with RHEL9. Testing below

> New-SSHSession -ComputerName rhnine01-tst
> 
> cmdlet New-SSHSession at command pipeline position 1
> Supply values for the following parameters:
> (Type !? for Help.)
> Credential
> User: pinel
> Password for user pinel: *************
> 
> New-SSHSession: An established connection was aborted by the server.

Used Cygwin to ssh in and set the default cyrpto to SHA1 and tried again.

> New-SSHSession -ComputerName rhnine01-tst
> 
> cmdlet New-SSHSession at command pipeline position 1
> Supply values for the following parameters:
> (Type !? for Help.)
> Credential
> User: pinel
> Password for user pinel: *************
> 
> 
> Server SSH Fingerprint
> Do you want to trust the fingerprint b4:89:16:ce:d9:83:ac:97:de:a4:74:dd:5a:81:72:ec
> [] Y  [] N  [?] Help (default is "N"): y
> 
> SessionId  Host                                                                                        Connected
> ---------  ----                                                                                        ---------
>     0      rhnine01-tst                                                                                   True
