### ISSUE TITLE
Invoke-SSHStreamExpectAction

### ISSUE THREAD

**Issue by tylerapplebaum** [darkoperator/Posh-SSH#51]
Does this work like I'm understanding?

Will -ExpectString 'RTR-INET-01# ip route x.x.x.x' actually wait for that sting to appear in the stream?

If so, wow, and thank you. If this works like I expect, I'll be releasing some router automation scripts with major accreditation to your Posh-SSH module.

**Comment by darkoperator** [comment]
It will input a specified text with carriage return when the specified text is shown in the output. It will timeout if not seen.
