### ISSUE TITLE
Supress command output

### ISSUE THREAD

**Issue by dgivulescu** [darkoperator/Posh-SSH#515]
Hi,

Is there a way to suppress the output of the  command? For example, New-SFTPItem displays information about the directory being created, Last access time, etc. 
If possible I'd rather have those in  a variable so I can display only the information I need.
Thank you,
Dan

**Comment by darkoperator** [comment]
It returns an object referencing what was created. You can pipe it to Out-Null if you dont want the returned object shown on the console if you dont plan on doing anything else with the object Sent from my iPhoneOn Mar 21, 2023, at 11:28 AM, dgivulescu ***@***.***> wrote:﻿
Hi,
Is there a way to suppress the output of the  command? For example, New-SFTPItem displays information about the directory being created, Last access time, etc.
If possible I'd rather have those in  a variable so I can display only the information I need.
Thank you,
Dan
