### ISSUE TITLE
New-SSHSession with multiple hosts stops on first host with error

### ISSUE THREAD

**Issue by FireInWinter** [darkoperator/Posh-SSH#52]
If you are using New-SSHSession with multiple hosts, it will stop processing all host once 1 host has an error.  I think returning an error is a good idea, but I'd prefer it to connect to try and connect to all of them, even if some fail.  It also doesn't matter what the ErrorAction variable is set to.

New-SSHSession -ComputerName 'Server1', 'Server2' -ErrorAction SilentlyContinue -Verbose

If you then give it a bogus credential, it fails on Server1, without trying to connect to Server2.

**Comment by darkoperator** [comment]
made changes in branch 1_7_5 and this should be fixed in the next release. it will not throw a terminating error but will return an error record and it will honor what is set in ErrorAction

**Comment by darkoperator** [comment]
Uploaded 1.7.5 to the gallery
