### ISSUE TITLE
Question about catching an error

### ISSUE THREAD

**Issue by elvovsky** [darkoperator/Posh-SSH#520]
I am having an intermittent error connecting to the sftp server. I know one of the conditions and it has to do with the host key algorithm that is not there by default on windows, there may be other issues. However, the only error I am seeing is that the **Session operation has timed out.**  In any case I am trying to build try catch block and the cat does not seem to be working. Skipping the rest of the script, but here is the code. 
`
try {
  New-SFTPSession -ComputerName $HostName -Credential $Creds -AcceptKey -Verbose -ConnectionTimeout 30 -OperationTimeout 30 
}

catch {
  Write-Host "An Error Occured connecting to server" -ForegroundColor RED
  write-host -ForegroundColor Red $PSItem.Exception.Message
  exit 6
}
`
I do get an error message sort of, but it does not execute catch block. What am I doing wrong? As far as the host key algorithm, I've searched the issues and I never saw the resolution. I know on linux or windows technically i can add a config file with the right parameters, though i am not sure this package is using sftp/ssh server/client settings.
Thank you for any help in advance !

**Comment by MVKozlov** [comment]
``` powershell
New-SFTPSession ... -ErrorAction Stop
```
?

**Comment by elvovsky** [comment]
@MVKozlov Thank you Max ! I can swear, I tried ErrorAction. I guess I did not. Much appreciated. Any ideas on how to create an equivalent of config file for ssh client or does this module have it's own. One thing I noticed that it creates it's own hosts.json file for saving the key ? Thanks in advance !

**Comment by MVKozlov** [comment]
@elvovsky, this module stores host keys only
and for your own config you always may use `Get-Content | ConvertFrom-Json`/`ConvertTo-Json | Set-Content` pairs or something similar

**Comment by elvovsky** [comment]
@MVKozlov Thanks Max, it is not about my config. It is about ssh parameter that is an issue. As I mentioned, I can set it on windows or Linux via ssh config files for openssh binaries to use. I don't see   any options here. I know that it is using a library for the ssh (Renci), and I was not sure if I am missing something there or if that library uses openssh behind the scenes or not. Anyway, for now I guess , thanks to your advice, I will see if I get a more clear error message as to what is going on.

**Comment by darkoperator** [comment]
Sadly Renci is a small fraction of the coverage of ciphers and algorithms that OpenSSH supports. Renci is its own implementation of the RFC

**Comment by elvovsky** [comment]
Thank you @darkoperator Carlos.
