### ISSUE TITLE
Get-SFTPItem uses as destination a part of initial folder

### ISSUE THREAD

**Issue by cnEUL** [darkoperator/Posh-SSH#526]
I started a PowerShell session in Windows Terminal on Windows 10 with PowerShell 7.3.4. The initial path for the session is, for example, 'C:\git\powershell\projectgreen'.

(I am using POSH-SSH Version 3.08)

When I switch to the $home directory and create a folder named 'test' and switch to it, the prompt changes to 'C:\users\c\test' as expected.

However, when I create a Posh-SSH session and download the files from the remote root using the command:

Get-SFTPItem -SessionId 0 -Path ./ -Destination 'C:\Users\cn\test' -force

It creates a subfolder 'projectgreen' within the 'test' folder, and all files and folders from the remote system are downloaded into it.
The files are then in:  'C:\Users\cn\test\projectgreen'.

I'm wondering what I'm doing wrong.

[update]
if i specify a single file, then it work like expected, problem occurs only if -Path should get entire remote folder (./)

Get-SFTPItem -SessionId 0 -Path ./logo.png -Destination .\ -force
or 
Get-SFTPItem -SessionId 0 -Path ./logo.png -Destination C:\users\cn\test -force

**Comment by MVKozlov** [comment]
it was designed that way with the advent of `Get-SFTPItem` in v2.1

**Comment by MVKozlov** [comment]
may be i misunderstood you but in your case folder will be **c:\temp\projectgreen**

where _projectgreen_ is current remote folder name (./)

**Comment by darkoperator** [comment]
for Path in Get-SFTPItem has to be the full target path.  It will not work with relative paths

**Comment by darkoperator** [comment]
so it is either the name of file or folder for the current location the session is in or the full path. ./ or ../ will not work
