### ISSUE TITLE
SSH-Key neg. problem with New-SFTPSession

### ISSUE THREAD

**Issue by cnEUL** [darkoperator/Posh-SSH#528]
Hello,

i am using the FileZille Enterprise Pro edition 1.70 under Windows. They support as SSH-Host keys three types:
1. ssh-ed25519
2. ssh-rsa
3. ecdsa-sha2-nistp256

if i use 2 or 3, i got error "New-SFTPSession: An established connection was aborted by the server."
if i use 1 i got error "New-SFTPSession: Key exchange negotiation failed."

in a older version there was one working host key (unkown format) which worked with POSH-SSH, but the Version 1.7 did not decode any more that old format. Ana idea, whats to do?

All hostkeys have the extension *.der
I am using the command line this: $SFTPSession = New-SFTPSession -ComputerName myremote.xyz.com -Credential $credential -AcceptKey
or it there saved the old fingerprint or something, that could be deleted?

Thank you
Christian

**Comment by cnEUL** [comment]
Hello, i figured out that the fingerprints are saved in $home\.poshssh in the file hosts.json. I deleted this file and than it worked. I dont know how to handle this automaticly. Because changing a key could happen, and i am using the option -accept.

Thank you
Christian

**Comment by darkoperator** [comment]
With this command you can remove trusted hosts from the file https://github.com/darkoperator/Posh-SSH/blob/master/docs/Remove-SSHTrustedHost.md

**Comment by cnEUL** [comment]
Thank you,

my understanding has now grown a bit... I think it's good to check the fingerprint, where the option -AcceptKey works when the SFTP server was unknown. It silently adds it to the trusted hosts. If a different fingerprint arrives for this server, you know that 'something is not right'. Accordingly, I now output a meaningful message with the option to invoke the 'Remove-SSHTrustedHost' command and a brief explanation to be cautious, etc.
Thank you for the support, I'm making progress now.

Christian

**Comment by darkoperator** [comment]
awesome! can I close the issue?

**Comment by cnEUL** [comment]
yes, i closed it.
