### ISSUE TITLE
POSH-SSH HMAC algorithm

### ISSUE THREAD

**Issue by Clover2303** [darkoperator/Posh-SSH#529]
Hello

When connecting to a device how is the HMAC algorithm chosen? 

I have been attempting to connect to a new device that uses  "hmac-sha2-256" which says it is supported but posh-ssh keeps trying to use "hmac-sha1", the new device does not accept "hmac-sha1" but does have support for "hmac-sha2-256"... so in all, can I choose which HMAC algorithm to use? or is there something I can do to enable this?

many thanks

**Comment by MVKozlov** [comment]
Algorithms chosen by underlying library
here
https://github.com/sshnet/SSH.NET/blob/072ba7e01323659d5ee12a59b6cb4f7cf583d64e/src/Renci.SshNet/ConnectionInfo.cs#L366
and somewhere from here
https://github.com/sshnet/SSH.NET/blob/072ba7e01323659d5ee12a59b6cb4f7cf583d64e/src/Renci.SshNet/Security/KeyExchange.cs#L101

Posh-SSH has no control over this

**Comment by darkoperator** [comment]
Max is correct, it is not something we can control from the module at this moment
