### ISSUE TITLE
Install Did Not Work

### ISSUE THREAD

**Issue by dschinkel** [darkoperator/Posh-SSH#53]
I ran the install from powershell using: iex (New-Object Net.WebClient).DownloadString("https://gist.github.com/darkoperator/6152630/raw/c67de4f7cd780ba367cccbc2593f38d18ce6df89/instposhsshdev")

It downloaded and says it's installed.  But it doesn't recognize any of the commands like New-SSHSession

**Comment by darkoperator** [comment]
Can you please provide more info, like 
$PSversion output to see what version of PowerShell you are running. 
What version of Windows.
$PSModulePath to see if you have your documents folder in the list. 

Thanks

**Comment by dschinkel** [comment]
Major  Minor  Build  Revision
-----  -----  -----  -------
2      0      -1     -1     

Windows 7

ran $PSModulePath, shows none.

**Comment by darkoperator** [comment]
since you have a old version of PowerShell check $env:PSModulePath you documents folder should include path to the folder where the module is located, Also since this is an old version of PowerShell you will have to load the module by hand since auto loading of modules is not supported. so you will have to do Import-Module Posh-SSH -verbose

**Comment by dschinkel** [comment]
thanks, let me install an updated Powershell version...and I'll try again.

**Comment by darkoperator** [comment]
You can use 2.0 just used it, in fact it was the most requested feature when I released the original one was to support PS 2.0. 
Just make sure to set your execution policy to RemoteSigned in a session running as administrator. 

Set-ExecutionPolicy RemoteSigned -Force

Run the install script and with a simple import-module it should work 

Here is on a Win7 VM 

PS C:\Windows\system32> Set-ExecutionPolicy remotesigned -force
PS C:\Windows\system32> Import-Module posh-ssh -verbose
VERBOSE: Loading module from path 'C:\Users\Carlos Perez\Documents\WindowsPowerShell\Modules\posh-ssh\posh-ssh.psd1'.
VERBOSE: Loading 'Assembly' from path 'C:\Users\Carlos
Perez\Documents\WindowsPowerShell\Modules\posh-ssh\Assembly\Renci.SshNet.dll'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Users\Carlos
Perez\Documents\WindowsPowerShell\Modules\posh-ssh\Format\SSHSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Users\Carlos
Perez\Documents\WindowsPowerShell\Modules\posh-ssh\Format\SFTPSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Users\Carlos
Perez\Documents\WindowsPowerShell\Modules\posh-ssh\Format\Renci.SshNet.SshCommand.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Users\Carlos
Perez\Documents\WindowsPowerShell\Modules\posh-ssh\Format\Renci.SshNet.Sftp.SftpFile.Format.ps1xml'.
VERBOSE: Loading module from path 'C:\Users\Carlos Perez\Documents\WindowsPowerShell\Modules\posh-ssh\PoshSSH.dll'.
VERBOSE: Importing cmdlet 'Get-SCPFile'.
VERBOSE: Importing cmdlet 'Get-SCPFolder'.
VERBOSE: Importing cmdlet 'Get-SFTPFile'.
VERBOSE: Importing cmdlet 'Set-SFTPFile'.
VERBOSE: Importing cmdlet 'New-SFTPSession'.
VERBOSE: Importing cmdlet 'New-SSHSession'.
VERBOSE: Importing cmdlet 'Set-SCPFile'.
VERBOSE: Importing cmdlet 'Set-SCPFolder'.
VERBOSE: Loading module from path 'C:\Users\Carlos Perez\Documents\WindowsPowerShell\Modules\posh-ssh\Posh-SSH.psm1'.
VERBOSE: Exporting function 'Get-SSHTrustedHost'.
VERBOSE: Exporting function 'New-SSHTrustedHost'.
VERBOSE: Exporting function 'Remove-SSHTrustedHost'.
VERBOSE: Exporting function 'Get-SFTPSession'.
VERBOSE: Exporting function 'Remove-SFTPSession'.
VERBOSE: Exporting function 'Get-SFTPChildItem'.
VERBOSE: Exporting function 'Test-SFTPPath'.
VERBOSE: Exporting function 'Remove-SFTPItem'.
VERBOSE: Exporting function 'Set-SFTPLocation'.
VERBOSE: Exporting function 'Get-SFTPLocation'.
VERBOSE: Exporting function 'Rename-SFTPFile'.
VERBOSE: Exporting function 'Get-SFTPPathAttribute'.
VERBOSE: Exporting function 'New-SFTPSymlink'.
VERBOSE: Exporting function 'Get-SFTPContent'.
VERBOSE: Exporting function 'Set-SFTPContent'.
VERBOSE: Exporting function 'New-SFTPFileStream'.
VERBOSE: Exporting function 'New-SFTPItem'.
VERBOSE: Exporting function 'New-SFTPDirectory'.
VERBOSE: Exporting function 'Get-SFTPDirectoryList'.
VERBOSE: Exporting function 'Remove-SFTPDirectory'.
VERBOSE: Exporting function 'Set-SFTPCurrentDirectory'.
VERBOSE: Exporting function 'Get-SFTPCurrentDirectory'.
VERBOSE: Exporting function 'Remove-SFTPFile'.
VERBOSE: Exporting function 'Get-SSHSession'.
VERBOSE: Exporting function 'Remove-SSHSession'.
VERBOSE: Exporting function 'Invoke-SSHCommand'.
VERBOSE: Exporting function 'Get-PoshSSHModVersion'.
VERBOSE: Exporting function 'New-SSHShellStream'.
VERBOSE: Exporting function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Exporting function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Importing function 'Get-PoshSSHModVersion'.
VERBOSE: Importing function 'Get-SFTPChildItem'.
VERBOSE: Importing function 'Get-SFTPContent'.
VERBOSE: Importing function 'Get-SFTPCurrentDirectory'.
VERBOSE: Importing function 'Get-SFTPDirectoryList'.
VERBOSE: Importing function 'Get-SFTPLocation'.
VERBOSE: Importing function 'Get-SFTPPathAttribute'.
VERBOSE: Importing function 'Get-SFTPSession'.
VERBOSE: Importing function 'Get-SSHSession'.
VERBOSE: Importing function 'Get-SSHTrustedHost'.
VERBOSE: Importing function 'Invoke-SSHCommand'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Importing function 'New-SFTPDirectory'.
VERBOSE: Importing function 'New-SFTPFileStream'.
VERBOSE: Importing function 'New-SFTPItem'.
VERBOSE: Importing function 'New-SFTPSymlink'.
VERBOSE: Importing function 'New-SSHShellStream'.
VERBOSE: Importing function 'New-SSHTrustedHost'.
VERBOSE: Importing function 'Remove-SFTPDirectory'.
VERBOSE: Importing function 'Remove-SFTPFile'.
VERBOSE: Importing function 'Remove-SFTPItem'.
VERBOSE: Importing function 'Remove-SFTPSession'.
VERBOSE: Importing function 'Remove-SSHSession'.
VERBOSE: Importing function 'Remove-SSHTrustedHost'.
VERBOSE: Importing function 'Rename-SFTPFile'.
VERBOSE: Importing function 'Set-SFTPContent'.
VERBOSE: Importing function 'Set-SFTPCurrentDirectory'.
VERBOSE: Importing function 'Set-SFTPLocation'.
VERBOSE: Importing function 'Test-SFTPPath'.
VERBOSE: Exporting function 'Get-PoshSSHModVersion'.
VERBOSE: Exporting function 'Get-SFTPChildItem'.
VERBOSE: Exporting function 'Get-SFTPContent'.
VERBOSE: Exporting function 'Get-SFTPCurrentDirectory'.
VERBOSE: Exporting function 'Get-SFTPDirectoryList'.
VERBOSE: Exporting function 'Get-SFTPLocation'.
VERBOSE: Exporting function 'Get-SFTPPathAttribute'.
VERBOSE: Exporting function 'Get-SFTPSession'.
VERBOSE: Exporting function 'Get-SSHSession'.
VERBOSE: Exporting function 'Get-SSHTrustedHost'.
VERBOSE: Exporting function 'Invoke-SSHCommand'.
VERBOSE: Exporting function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Exporting function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Exporting function 'New-SFTPDirectory'.
VERBOSE: Exporting function 'New-SFTPFileStream'.
VERBOSE: Exporting function 'New-SFTPItem'.
VERBOSE: Exporting function 'New-SFTPSymlink'.
VERBOSE: Exporting function 'New-SSHShellStream'.
VERBOSE: Exporting function 'New-SSHTrustedHost'.
VERBOSE: Exporting function 'Remove-SFTPDirectory'.
VERBOSE: Exporting function 'Remove-SFTPFile'.
VERBOSE: Exporting function 'Remove-SFTPItem'.
VERBOSE: Exporting function 'Remove-SFTPSession'.
VERBOSE: Exporting function 'Remove-SSHSession'.
VERBOSE: Exporting function 'Remove-SSHTrustedHost'.
VERBOSE: Exporting function 'Rename-SFTPFile'.
VERBOSE: Exporting function 'Set-SFTPContent'.
VERBOSE: Exporting function 'Set-SFTPCurrentDirectory'.
VERBOSE: Exporting function 'Set-SFTPLocation'.
VERBOSE: Exporting function 'Test-SFTPPath'.
VERBOSE: Exporting cmdlet 'Get-SCPFile'.
VERBOSE: Exporting cmdlet 'Get-SCPFolder'.
VERBOSE: Exporting cmdlet 'Get-SFTPFile'.
VERBOSE: Exporting cmdlet 'Set-SFTPFile'.
VERBOSE: Exporting cmdlet 'New-SFTPSession'.
VERBOSE: Exporting cmdlet 'New-SSHSession'.
VERBOSE: Exporting cmdlet 'Set-SCPFile'.
VERBOSE: Exporting cmdlet 'Set-SCPFolder'.
VERBOSE: Importing cmdlet 'Get-SCPFile'.
VERBOSE: Importing cmdlet 'Get-SCPFolder'.
VERBOSE: Importing cmdlet 'Get-SFTPFile'.
VERBOSE: Importing cmdlet 'New-SFTPSession'.
VERBOSE: Importing cmdlet 'New-SSHSession'.
VERBOSE: Importing cmdlet 'Set-SCPFile'.
VERBOSE: Importing cmdlet 'Set-SCPFolder'.
VERBOSE: Importing cmdlet 'Set-SFTPFile'.
VERBOSE: Importing function 'Get-PoshSSHModVersion'.
VERBOSE: Importing function 'Get-SFTPChildItem'.
VERBOSE: Importing function 'Get-SFTPContent'.
VERBOSE: Importing function 'Get-SFTPCurrentDirectory'.
VERBOSE: Importing function 'Get-SFTPDirectoryList'.
VERBOSE: Importing function 'Get-SFTPLocation'.
VERBOSE: Importing function 'Get-SFTPPathAttribute'.
VERBOSE: Importing function 'Get-SFTPSession'.
VERBOSE: Importing function 'Get-SSHSession'.
VERBOSE: Importing function 'Get-SSHTrustedHost'.
VERBOSE: Importing function 'Invoke-SSHCommand'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Importing function 'New-SFTPDirectory'.
VERBOSE: Importing function 'New-SFTPFileStream'.
VERBOSE: Importing function 'New-SFTPItem'.
VERBOSE: Importing function 'New-SFTPSymlink'.
VERBOSE: Importing function 'New-SSHShellStream'.
VERBOSE: Importing function 'New-SSHTrustedHost'.
VERBOSE: Importing function 'Remove-SFTPDirectory'.
VERBOSE: Importing function 'Remove-SFTPFile'.
VERBOSE: Importing function 'Remove-SFTPItem'.
VERBOSE: Importing function 'Remove-SFTPSession'.
VERBOSE: Importing function 'Remove-SSHSession'.
VERBOSE: Importing function 'Remove-SSHTrustedHost'.
VERBOSE: Importing function 'Rename-SFTPFile'.
VERBOSE: Importing function 'Set-SFTPContent'.
VERBOSE: Importing function 'Set-SFTPCurrentDirectory'.
VERBOSE: Importing function 'Set-SFTPLocation'.
VERBOSE: Importing function 'Test-SFTPPath'.
PS C:\Windows\system32>

t

**Comment by dschinkel** [comment]
the ultimate issue is this.  During the install, toward the end right before it's done it's probably trying that  Import-Module posh-ssh -verbose end I get this error.  I get this in powershell 2 and I just upgraded to 3, same deal.

Import-Module : The specified module 'posh-ssh' was not loaded because no valid module file was found in any
directory.
At line:17 char:1
+ Import-Module -Name posh-ssh
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (posh-ssh:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by darkoperator** [comment]
if you navigate to the module folder in <your my documents>\Windows PowerShell\Modules\Posh-SSH  and you do a import-module .\posh-ssh.psd1 does it work?

**Comment by chezbut** [comment]
an issue with the install that is unaddressed is finding a method to install that doesn't involve just pasting a URL to execute. There needs to be a more graduated install process, such as with an install script after a git clone.

**Comment by chezbut** [comment]
A user should not have to enable the execution of remote scripts to get the install done.

**Comment by darkoperator** [comment]
Not planning on building a MSI installer for it. You can always download the zip, unblock it and copy it to the correct location in your module path
