### ISSUE TITLE
New-SFTPSession : Specified cast is not valid.

### ISSUE THREAD

**Issue by sdstraub** [darkoperator/Posh-SSH#531]
This is really weird.

I just migrated some powershell scripts to a new server, and after doing so one scheduled task using posh-ssh to upload files to an sftp server failed.  The log file had this error:

```
PS>TerminatingError(New-SFTPSession): "Specified cast is not valid."
New-SFTPSession : Specified cast is not valid.
At \\SERVER\Test\Test.ps1:28 char:16
+ ... isSession = New-SFTPSession -ComputerName $SftpIp -Credential $Creden ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SFTPSession], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException,SSH.NewSftpSession
New-SFTPSession : Specified cast is not valid.
At \\SERVER\Test\Test.ps1:28 char:16
+ ... isSession = New-SFTPSession -ComputerName $SftpIp -Credential $Creden ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SFTPSession], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException,SSH.NewSftpSession
```

I ran the script in ISE fine, using the same machine/account that the task is set up to run the script under, using the same credentials for sftp, pulled from a file used for all of my tests.  I couldn't understand why it ran fine for me everywhere but in task scheduler.  In my troubleshooting, I finally decided to add -Verbose in case there was more information, and the script ran fine.

Here is the line that results in the error:

`$ThisSession = New-SFTPSession -ComputerName $SftpIp -Credential $Credential -AcceptKey:$true -ErrorAction Stop`

Here is the line that allows the script to run fine:

`$ThisSession = New-SFTPSession -Verbose -ComputerName $SftpIp -Credential $Credential -AcceptKey:$true -ErrorAction Stop`

The log from the successful run shows nothing out of the ordinary, just this line "VERBOSE: Using SSH Username and Password authentication for connection."

Here are the lines with the two options, one commented out:

`# $ThisSession = New-SFTPSession -Verbose -ComputerName $SftpIp -Credential $Credential -AcceptKey:$true -ErrorAction Stop`
`$ThisSession = New-SFTPSession -ComputerName $SftpIp -Credential $Credential -AcceptKey:$true -ErrorAction Stop
`

The only difference is "-Verbose".  What am I missing here?  I would believe I'm overlooking something obvious...

The old machine has 3.0.1 and the new one has 3.0.8.

**Comment by MVKozlov** [comment]
That may be the same issue as #503
Take a look also to #504 discussion

**Comment by sdstraub** [comment]
Yes @MVKozlov it seems it is the same issue, thanks.  When I use method 1 from #503, "$VerbosePreference = [System.Management.Automation.ActionPreference]::SilentlyContinue" it runs fine without the Verbose switch.  Fyi when I use method 2 it has the same problem though.  Does that mean you just need to use method 1 with newer versions?  Or is method 1 an example of what should be done always, regardless of whether this module is involved?  Or is there something that needs to be "fixed" in the code for this module?

**Comment by MVKozlov** [comment]
As already mentioned in the #504 discussion, this is a problem with the handling of variable inheritance in powershell, not a problem with the module itself.

Perhaps it would be possible to make the mentioned workaround, but the discussion, unfortunately, stopped. I'm is not yet ready to dive into the rework and for now, method 1 is enough for me :)
