### ISSUE TITLE
Get-SFTPItem doesn't preserve last write times of downloaded files

### ISSUE THREAD

**Issue by jaspain** [darkoperator/Posh-SSH#532]
The lastwritetime and other timestamps on local copies of downloaded files reflect the time of download rather than the original timestamps on the remote files. Preserving the original timestamps would be helpful for analyzing file recency. That information is available from Get-SFTPPathAttribute.

**Comment by darkoperator** [comment]
sadly dont see how to achive this using the current SSH.NET API
