### ISSUE TITLE
Remove-SSHSession Invalid Operation

### ISSUE THREAD

**Issue by erjuancho** [darkoperator/Posh-SSH#536]
Hi!. I'm getting this error when trying to remove the current session
Remove-SSHSession -SessionId 0
Remove-SSHSession -SSHSession $SshSession
Get-SSHSession | Remove-SSHSession

InvalidOperation: Method invocation failed because [SSH.SshSession] does not contain a method named 'Remove'

**Comment by darkoperator** [comment]
<img width="1150" alt="image" src="https://github.com/user-attachments/assets/76c551b2-b5b6-43eb-a347-ebd9e0c2b8e2">
should be fixed in the latest version
