### ISSUE TITLE
New-SSHSession times out on high latency link

### ISSUE THREAD

**Issue by FireInWinter** [darkoperator/Posh-SSH#54]
Most of the time connecting to a Linux server over a high latency link ( 60 ms rtt ) it will time out on the first attempt.  If I then try to connect again, it is able to sometimes connect.  However, when I connect to the same server in putty, it connects right away every time.  I'm using the same credentials for both New-SSHSession and putty.  It also doesn't seem to matter if I change the connection timeout  for the first attempt.  I've set it as high as 60 seconds and still have it time out.

**Comment by darkoperator** [comment]
If the timeout parameter of the cmdlet does not help there is not mouth I can do since I do not own or wrote the base library I'm using.

**Comment by darkoperator** [comment]
are you still having this problem with the latest build?

**Comment by Jim-Wright** [comment]
I'm seeing similar issues on a very low latency link in a script that is looping through connecting to multiple devices.  Opening an SSH session in SuperPutty or TeraTerm connects immediately, but the New-SSHSession command may time out multiple times on the same device, or it may work the first time.

Build 1.7.5 here.

**Comment by darkoperator** [comment]
Sadly I'm limited by the library and have no way to control the way it handles high latency connections
