### ISSUE TITLE
Invoke-SSHStreamShellCommand - properly wait until expected prompt, not a fixed time

### ISSUE THREAD

**Issue by JoseAPortilloJSC** [darkoperator/Posh-SSH#542]
Hello darkoperator,
Would it be possible to rewrite the Invoke-SSHStreamShellCommand cmdlet so it is more robust on a real network environment? I mean, not to wait for a hardcoded amount of time and then read all received text so far. The current implementation can lead to:

- empty response (if the remote device takes more than 500ms to start responding and/or a network delay occurs)
- truncated response (if the remote device takes more than 500ms to send the whole content and/or a network delay occurs).

The proper approach would be to wait for the expected prompt. It would suffice to implement it like done in Invoke-SSHStreamExpectAction, using $ShellStream.Expect(), something like this:
```powershell
function Invoke-SSHStreamShellCommand {
    [CmdletBinding()]
    [Alias()]
    [OutputType([string])]  # proper output type
    Param (
    ...
        # Number of seconds to wait for a match.
        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true,
                   Position=3)]
        [int]
        $TimeOut = 10
    ...
    Process {
        Write-Verbose -Message "Executing command $($Command)."
        $ShellStream.WriteLine($Command)
        $ShellStream.ReadLine() | Out-Null  # trash command echo

        Write-Verbose -Message "Matching on pattern $($promptRegEx)"
        $out = $ShellStream.Expect($promptRegEx, (New-TimeSpan -Seconds $TimeOut))}

        $outputLines = $out.Split("`n")
        foreach ($line in $outputLines) {
            if ($line -notmatch $promptRegEx) {
                $line
            }
        }
    }
}
```
Thank you!
Regards
Jose

**Comment by gabfv** [comment]
I had the same problem too and can confirm the fix with Expect() works much better. Previously, I was having duplicate responses for multiple sent commands but now, every command sent has the expected response.

**Comment by JoseAPortilloJSC** [comment]
This is the function I came up with.
I usually include it in my code after 'Import-Module -Name Posh-SSH' to override the original in the module.
I'm glad the Expect() version works better :)

```
# Custom override of Posh-SSH library's Invoke-SSHStreamShellCommand with Expect
function Invoke-SSHStreamShellCommand {
    [CmdletBinding()]
    [Alias()]
    [OutputType([string])]
    Param (
        # SSH stream to use for command execution.
        [Parameter(Mandatory = $true,
                   ValueFromPipelineByPropertyName = $true,
                   Position = 0)]
        [Renci.SshNet.ShellStream]
        $ShellStream,

        # Command to execute on SSHStream.
        [Parameter(Mandatory = $true,
                   ValueFromPipelineByPropertyName = $true,
                   Position = 1)]
        [string]
        $Command,

        [Parameter(Mandatory = $false,
                   ValueFromPipelineByPropertyName = $true,
                   Position=2)]
        [Alias("PrompPattern")]
        [string]
        $PromptPattern = '[\$%#>] $',

        # Number of seconds to wait for a match.
        [Parameter(Mandatory = $false,
                   ValueFromPipelineByPropertyName = $true,
                   Position=3)]
        [int]
        $TimeOut = 10
    )
    
    Begin {
        $promptRegEx = [regex]$PromptPattern
    }
    Process {
        Write-Verbose -Message "Executing command $($Command)."
        $ShellStream.WriteLine($Command)
        $ShellStream.ReadLine() | Out-Null  # trash command echo

        Write-Verbose -Message "Matching on pattern $($promptRegEx)"
        $out = $ShellStream.Expect($promptRegEx, (New-TimeSpan -Seconds $TimeOut))

        if ($out -ne $null) {
            $outputLines = $out.Split("`n")
            foreach ($line in $outputLines) {
                if ($line -notmatch $promptRegEx) {
                    $line
                }
            }
        }
    }
    End{}
}
```

**Comment by darkoperator** [comment]
Thanks for sharing. The original function was a a example one I wrote for vyos and got the same questions on how to read and write to a stream so much I simply copied it as a command.  Will look in to modifying it. Will need to set some time to setup some vms for it given I no longer do SSH automation

**Comment by darkoperator** [comment]
Improved the regex and added timeout support. if it still has issues I will switch to expect. Update in release 3.2.2

**Comment by MMouse23** [comment]
I was using Stream, as the fire and forget method, for me this solution breaks that feature :)
What would be a good prompt patern to return right away? "*" ?
How can i have stream command return right away?

**Comment by darkoperator** [comment]
you can still do $nameofstream.write(“my commmand `n”) and then do $nameofstream.read() untill you get all the output

**Comment by MMouse23** [comment]
> you can still do $nameofstream.write(“my commmand `n”) and then do $nameofstream.read() untill you get all the output

Thanks DarkOperator, by the way, PoshSSH rocks!!! You deliver solid quality work.
Ive been using your stuff for years. And i was very happy to see the dot net / ps 7 version.
Oh man, without your tool my life would actually be very different :)

**Comment by darkoperator** [comment]
you made my day! thanks. This is a side project where I have made $0 and with the majority of my workload no longer being outside of system management and automation I sometimes get unmotivated by all the support request.
