### ISSUE TITLE
Set-SCPItem cannot copy folders

### ISSUE THREAD

**Issue by arty-hlr** [darkoperator/Posh-SSH#544]
As opposed to what it written in the example for `Set-SCPItem`, it cannot copy a folder unless that folder already exists on the target,

Example from `Get-Help Set-SCPItem`:
```
Upload an item, either file or directory to a remote system via SCP.


    -------------------------- Example 1 --------------------------

    PS C:\> Set-SCPItem -ComputerName 192.168.1.169 -Credential carlos -Path .\testcode -Destination /tmp -Verbose
    VERBOSE: Using SSH Username and Password authentication for connection.
    VERBOSE: Fingerprint for 192.168.1.169: 5a:a3:85:c6:63:83:6b:6c:2a:8f:9b:44:20:70:eb:7c
    VERBOSE: Fingerprint matched trusted fingerprint for host 192.168.1.169
    VERBOSE: Connection successful
    VERBOSE: Uploading: C:\testcode
    VERBOSE: Destination: /tmp/testcode

    Uploade a directory to the target folder.
```

Expected behaviour (from scp as example):
```
PS C:\Users\florian\Documents> scp -r ./test/ florian@*****:/home/florian/test
florian@*****'s password:
a.txt                                                                                                                                                                          100%   14     0.2KB/s   00:00
b.txt                                                                                                                                                                          100%   14     0.2KB/s   00:00
c.txt
```

Observed behaviour with using the folder name to copy in `-destination`:
```
PS C:\Users\florian\Documents> set-scpitem -computername ***** -path ./test/ -destination /home/florian/test -verbose

cmdlet Set-SCPItem at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
Credential
VERBOSE: Using SSH Username and Password authentication for connection.
VERBOSE: ssh-ed25519 Fingerprint for *****
VERBOSE: Fingerprint matched trusted ssh-ed25519 fingerprint for host *****
VERBOSE: Connection successful
VERBOSE: Uploading: C:\Users\florian\Documents\test\
VERBOSE: Destination: /home/florian/test/test
set-scpitem : scp: /home/florian/test/test: No such file or directory
At line:1 char:1
+ set-scpitem -computername ***** -path ./test/ -desti ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Renci.SshNet.ScpClient:ScpClient) [Set-SCPItem], ScpException
    + FullyQualifiedErrorId : SSH.SetScpItem
```

Same behaviour without the folder name to copy in `-destination`:

```
PS C:\Users\florian\Documents> set-scpitem -computername ***** -path ./test/ -destination /home/florian/ -verbose

cmdlet Set-SCPItem at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
Credential
VERBOSE: Using SSH Username and Password authentication for connection.
VERBOSE: ssh-ed25519 Fingerprint for *****
VERBOSE: Fingerprint matched trusted ssh-ed25519 fingerprint for host *****
VERBOSE: Connection successful
VERBOSE: Uploading: C:\Users\florian\Documents\test\
VERBOSE: Destination: /home/florian/test
set-scpitem : scp: /home/florian/test: No such file or directory
At line:1 char:1
+ set-scpitem -computername ***** -path ./test/ -desti ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Renci.SshNet.ScpClient:ScpClient) [Set-SCPItem], ScpException
    + FullyQualifiedErrorId : SSH.SetScpItem
```

**Comment by arty-hlr** [comment]
It seems that moving multiple filies with a wildcard in `-Path` is not supported either, as it only moves one file...

**Comment by arty-hlr** [comment]
`-Force` has nothing to do with it, in the help for `Set-SCPItem`:
```
-Force [<SwitchParameter>]
        Do not check the remote host fingerprint.
```

As opposed to `Set-SFTPItem`, where it is used to force overwriting
```
-Force [<SwitchParameter>]
        Overwrite item on remote host if it already pressent.
```

Those parameters should be named differently as they force different things.

Currently the only way to copy folders that don't exist yet is with `Set-SFTPItem`, I'm not sure why `Set-SCPItem` can't do it.

As for wildcard not working, should I make an issue for that? It is not expected behaviour, neither from PowerShell nor from scp. Not being able to copy multiple files at once is definitely a problem.

**Comment by darkoperator** [comment]
No the API does not have any way to copy if the folder does not exist. You can make an issue about wildcard but with honesty, I only work on the module a couple of days a year in vacation, mostly bus since I no longer use the module in any of my two jobs and only do bug fixes when I can, feature requests depending on complexity and if there is a PR from someone. It may not be expected behavior for you, but there is no rule that says a path must support wildcards, I do not even advertise it as supported in the examples, descriptions or parameter help information. you can still use the pipeline if you want to copy multiple files.

**Comment by arty-hlr** [comment]
Ok, that is unfortunate that the API cannot do that. I'll mark this as closed then if nothing can be done about that.

About wildcards: a warning/info would be useful maybe in the help descriptions then, I'm sure I'm not the only one that would expect it to not only copy one file.
