### ISSUE TITLE
Move-SFTPItem missing a -force parameter

### ISSUE THREAD

**Issue by ChrisRe-Lal** [darkoperator/Posh-SSH#553]
Hello,

When moving an item between folder if the file name already exist in the destination we get an error.

```
[DBG]: PS C:\SCRIPT>> Move-SFTPItem -SessionId $SSHSesstion.SessionId -Path "./$($_.Name)" -Destination "./PDF/$($_.Name)"
Exception calling "MoveTo" with "1" argument(s): "Failed to rename file/home/abc@null.null_UUID_106_5/fakt_20231029_50014114.p.202954.pdf M: Error during remote request handle."
At C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.1.1\Posh-SSH.psm1:1393 char:17
+                 $itemInfo.MoveTo($Destination)
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SftpPathNotFoundException
``` 

 
Having a -Force option which would allow to automatically replace the file in the destination would be a great addition.

Chris

**Comment by darkoperator** [comment]
Sadly SSH.NET method for moving a file does not have a Overload that will allowme to force a move even if a file exists 

<img width="556" alt="image" src="https://github.com/user-attachments/assets/e9774760-8684-4ae0-aa54-4b28671fb49e">

So made it where it checks if it exists and it it does and -Fode is used it will delete then move. This will ne in the next release 

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/e48ddc4c-ac3b-479d-aab4-6a91724c795e">

**Comment by darkoperator** [comment]
Updated in release 3.2.2

**Comment by ChrisRe-Lal** [comment]
Thanks a lot.
Will test it and let you know
