### ISSUE TITLE
Remove-SFTPItem not returning any errors

### ISSUE THREAD

**Issue by turbo-donkey** [darkoperator/Posh-SSH#554]
No errors displayed nor is $Error being populated.

I'm using if (($Error[0]).CategoryInfo.Activity -eq "Remove-SFTPItem") {BlahBlah} to error handle in my script and this is the only command I've had any issue with.

**Comment by darkoperator** [comment]
sprry for the delay. It. should be there in the next release 

<img width="808" alt="image" src="https://github.com/user-attachments/assets/bbf74b36-ad3a-4e74-b5e4-5fd0f60f10c9">

**Comment by darkoperator** [comment]
updated in release 3.2.2
