### ISSUE TITLE
Set-SFTPItem fails sometimes with ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by DarkLite1** [darkoperator/Posh-SSH#556]
## Description
We have [a script](https://github.com/DarkLite1/Get-or-send-SFTP-file) that starts [multiple jobs](https://github.com/DarkLite1/Get-or-send-SFTP-file/blob/main/Send%20to%20SFTP.ps1) with `Start-Job` to upload or download files.

Once in a while we have a file that is not uploaded and we receive a **non terminating error** like this:
`The background process reported an error with the following message: Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index').`

## What we did to find the issue
When adding `Start-Transcript` to `Send to SFTP.ps1`, which is the script that is called within the job to upload the file, we get these verbose messages:

> VERBOSE: Test path '\\server\d$\interface_files\moha\out'
> VERBOSE: Get files in folder '\\server\d$\interface_files\moha\out'
> VERBOSE: Only include files with extension '.dat .txt'
> VERBOSE: Create SFTP credential
> VERBOSE: Start SFTP session
> VERBOSE: Using SSH Key authentication for connection.
> VERBOSE: Test SFTP path '/moha/out/' exists
> VERBOSE: Get all SFTP files
> VERBOSE: File '\\server\d$\interface_files\moha\out\MO_C_FIN.txt'
> VERBOSE: Rename source file
> VERBOSE: Upload file '\\server\d$\interface_files\moha\out\MO_C_FIN.txt.UploadInProgress'
> VERBOSE: Uploading \\server\d$\interface_files\moha\out\MO_C_FIN.txt.UploadInProgress to /moha/out/
> VERBOSE: File uploaded
> VERBOSE: Remove file
> VERBOSE: Renaming /moha/out/MO_C_FIN.txt.UploadInProgress to MO_C_FIN.txt
> VERBOSE: File renamed
> VERBOSE: File '\\server\d$\interface_files\moha\out\MO_Complet.dat'
> VERBOSE: Rename source file
> VERBOSE: Upload file '\\server\d$\interface_files\moha\out\MO_Complet.dat.UploadInProgress'

This is the end of the transcript. 

## The issue
It does never reach the message `Write-Verbose 'File uploaded'` and the function `Set-SFTPItem` does not throw a terminating error although we use `$ErrorActionPreference = 'Stop'` at the top of the script.

The file is never uploaded and this happens only occasionally. We run 5 jobs simultaneously. We're a bit lost on why this is not going to the `Catch` clause or why the file is not uploaded after calling `Set-SFTPItem`.

Thank  you for your help.

## Possible root cause
It looks like `Set-SFTPItem` quits the entire script when something goes wrong like say the SFTP server aborting the connection during transfer.

## Extra info
With downloading files by using `Get-SFTPItem` we never have an issue.

## System info
- PowerShell 7.4.0
- Windows Server 2022
- Posh-ssh 3.1.1

**Comment by MVKozlov** [comment]
You didn't show how exactly you call your script inside the `RSJob`

I suspect that the error is there, because you do not use the index in a `$sessionParams` , and the only mention of the index inside the `Set-SFTPItem` is just getting a `SessionId` from Index thru `$Global:SftpSessions`

You can also try using [my RSJob fork](https://github.com/MVKozlov/PoshRSJob) as it fixes a lot of original bugs, maybe yours is there :)

**Comment by DarkLite1** [comment]
Thank you for getting back to us. 

At line `579` of [this script](https://github.com/DarkLite1/Get-or-send-SFTP-file/blob/main/Get%20or%20send%20SFTP%20file.ps1) we call [the child script file](https://github.com/DarkLite1/Get-or-send-SFTP-file/blob/main/Send%20to%20SFTP.ps1) which `Start-Job`. At line `437` we of the child script we start `Set-SFTPItem`. 

Simplified view:

```powershell
# Main script "Get or send SFTP file.ps1"
$actions | foreach-Object {
   $invokeParams = @{
           FilePath     = '../Send to SFTP.ps1'
           ArgumentList = ....
   }
   Start-Job @invokeParams
}
```

```powershell
# Child script "Send to SFTP.ps1"
$params = @{
    ComputerName = $SftpComputerName
    Credential   = $sftpCredential
    AcceptKey    = $true
}
$sftpSession = New-SFTPSession @params

$sessionParams = @{
    SessionId = $sftpSession.SessionID
}

$params = @{
     Path        = $tempFile.UploadFilePath
     Destination = $SftpPath
}
Set-SFTPItem @sessionParams @params
```

Can you tell me what you mean with not using the `index` or how I should use the index correctly?

**Comment by DarkLite1** [comment]
Thanks for getting back to us.

We posted the full stack trace [here](https://github.com/PowerShell/PowerShell/issues/20860). It's probably related to .NET 8 but we're not knowledgeable enough to understand this in detail.

**Comment by DarkLite1** [comment]
This seems to be an [issue within PowerShell itself](https://github.com/PowerShell/PowerShell/issues/16894)
