### ISSUE TITLE
It doesn't work at all with Palo Alto Networks firewalls

### ISSUE THREAD

**Issue by sjborbajr** [darkoperator/Posh-SSH#557]
it is able to authenticate, but when I try to invoke a command nothing happens.

what I suspect is that it doesn't get to a point where it is able to see that the terminal is ready for input.

I was able to get my result from an expect script:
spawn ssh [lindex $argv 1]@[lindex $argv 0]
expect "yes/no" {
        send "yes\r"
        expect "*?assword" { send "[lindex $argv 2]\r" }
        } "*?assword" { send "[lindex $argv 2]\r" }

expect "> " { send "ping source [lindex $argv 0] count 10 host [lindex $argv 3]\r" }
expect "ping statistics ---"
expect "> " { send "exit\r" }
expect eof

is there any additional logs I can get to help figure out why?

Thank you for your work on this

**Comment by darkoperator** [comment]
Does the same happen with a streamshell? most network equipment have their own shell where invoke-sshcommand does not work Sent from my iPhoneOn Dec 22, 2023, at 9:13 PM, Steve Borba ***@***.***> wrote:﻿
it is able to authenticate, but when I try to invoke a command nothing happens.
what I suspect is that it doesn't get to a point where it is able to see that the terminal is ready for input.
I was able to get my result from an expect script:
spawn ssh [lindex $argv ***@***.*** $argv 0]
expect "yes/no" {
send "yes\r"
expect "?assword" { send "[lindex $argv 2]\r" }
} "?assword" { send "[lindex $argv 2]\r" }
expect "> " { send "ping source [lindex $argv 0] count 10 host [lindex $argv 3]\r" }
expect "ping statistics ---"
expect "> " { send "exit\r" }
expect eof
is there any additional logs I can get to help figure out why?
Thank you for your work on this

**Comment by sjborbajr** [comment]
Thank you - I think it does.  Now I just need to wrap my head around this.

I also tried without streamshell on  a cisco and it handled it better, but not as well as a linux machine.

thank you for the quick response
