### ISSUE TITLE
Invoke-SSHCommand -EnsureConnection throws exception if already connected

### ISSUE THREAD

**Issue by FireInWinter** [darkoperator/Posh-SSH#56]
When you use the EnsureConnection parameter of Invoke-SSHCommand, it throws an exception for each session that has a Connected property of True.  This makes the parameter not very useful as it will hide actual errors in the noise of making sure they are connected.

I would suggest something like the following to catch the exception if it is already connected. I'm guessing a specific exception could be captured instead of all exceptions, but I couldn't remember how to do that in PowerShell.
```powershell
if ($EnsureConnection)
{
    try
    {
        $Connection.session.connect()
    }
    catch
    {                            
        if ( $_.Exception.InnerException.Message -ne 'The client is already connected.' )
        { Write-Error -Exception $_.Exception }
    }
}
```

**Comment by darkoperator** [comment]
Need to remove that in the next version. Added it only for Cisco that killed each connection after executing a command. But now we have streams for that

**Comment by FireInWinter** [comment]
Ok.  Good to know.  I'll not use the option in that case.

Thanks for the fast response on issues.  I know I've put in a number in the last while, but I've only started trying to use it for more than simple testing.
