### ISSUE TITLE
Cisco Device HMAC Error

### ISSUE THREAD

**Issue by dfraire115** [darkoperator/Posh-SSH#566]
Using Posh-SSH version 3.1.3, I'm aware that versions 3.1.1 and above now use the 2023 SSH.Net Library. 
This library lists support for the MAC algorithm hmac-sha2-512. 
I'm attempting to create a New-SSHSession to a Cisco device, the device is configured to use hmac-sha2-512. The cmdlet fails citing a MAC error, when I manually change the hmac on the Cisco device to use hmac-sha2-256 the session is created successfully.
Is the 512 hmac algo not supported or is this an issue specific to Cisco devices?

**Comment by darkoperator** [comment]
Should work unless Cisco is doind different. Does an error show up in the Cisco logs? Dont have the gear to replicate
