### ISSUE TITLE
Inoke-SSHCommand - Photon 4 (vCenter v8) - All Commands Return "Unknown Command"

### ISSUE THREAD

**Issue by yootzee** [darkoperator/Posh-SSH#568]
Edit:
I forgot to include some basic info:
Powershell versions 5 and 7
Posh-SSH version 3.0.8
Windows 10

I realize this may not necessarily be a problem with the module specifically, but could be due to a change in the version of the target. But, I'm hoping someone may have some input that may be of some assistance.

I'm running commands against a vCenter Server Appliance, running vSphere v8. Specifically, I'm running the commands against the VCSA server itself, which is running Photon OS v4. 

The module version and commands are the same that I run successfully against VCSA 7.  The primary difference between the two, besides the vSphere version itself, is that v7 uses Photon v3.x vs v4.x.

The primary problem I'm encountering is that any command I send is returned as an "Unknown command".

Example:
PS > Invoke-SSHCommand -SSHSession $currSSHSession -Command "pwd"
Host          :  blah.lab
Output      :  {Unknown command: `pwd'}
ExitStatus  :  0

I have checked and double-checked that both SSH and the bash shell are active via the VCSA management interface.  And, the one command (okay, I can get ONE command to run...) that I seem to get success on is:

PS > Invoke-SSHCommand -SSHSession $currSSHSession -Command "shell '\n'"
Host          :  blah.lab
Output      :  {Shell access is granted to root}
ExitStatus  :  127

Even though is says success, it still appears that no commands are recognized.

Any ideas or input are welcome.  This is big stoppage for me as I've got 10 security check scripts to run against a new build and I am stuck as of now.

Thanks

**Comment by darkoperator** [comment]
This is because invoke-sshcommand does not execute in a shell, it acts like Plin. Try bash -c pwd as the command to pass

**Comment by yootzee** [comment]
Thanks for the reply. Unfortunately, it didn't work. Doing that just returns Unknown Command `bash' .  I can only assume the server is just not honoring bash being enabled.  it seems to be enabled, via the management setting and also via invoke-sshcommand "shell '\n'". no commands are recognized.

**Comment by darkoperator** [comment]
Maybe a shellstream will be a better alternative

**Comment by yootzee** [comment]
FYI, for anyone that happens to come here with the same issue.  The default shell on a vCenter appliance is their "Appliance Shell". The user normally drops to this shell, then has to start Bash.  I ended up changing the default shell to Bash, and all scripting works again.  I had to remember that I did that with v6 and v7 years ago.
