### ISSUE TITLE
Getting junk characters in output with shell stream method on HP Aruba devices 

### ISSUE THREAD

**Issue by Deepanraj324** [darkoperator/Posh-SSH#569]
Hi @darkoperator,

Good day.!

First, I would like to say a big THANKS to you for providing such a wonderful tool. I have been using this module since 2019 to do my stuffs on Network & Linux boxes. THANKS AGAIN..!

**_let me come to the issue I am facing now._**

- I am trying to connect and fetch the output of commands from HP Aruba devices.
- Able to establish the connection successfully.
- Able to execute the command on the target (HP Aruba) via shellstream ( as invoke-sshcommand is throwing errors)
- output is displaying with junk letters all over.

**Command Used:**

$session = Get-SSHSession -Index 0
$stream = $session.Session.CreateShellStream("dumb", 0, 0, 0, 0, 1000)
$stream.Write("terminal length 0`nshow uptime")
Start-Sleep -Seconds 5
$stream.read()

**Output sample 1:**

![image](https://github.com/darkoperator/Posh-SSH/assets/141644613/fa0217a3-6088-48ee-8e70-92efefa8d61a)

**Output sample 2:**

![image](https://github.com/darkoperator/Posh-SSH/assets/141644613/179ce91b-ce86-4031-9c50-2fe1c3bd8b91)

**Powershell version : 5.1
Source OS : Windows server 2019**

Could you please help me on this.. Thanks!

**Comment by darkoperator** [comment]
Could be color control chars, try from the MS Store Terminal app

**Comment by Deepanraj324** [comment]
> Could be color control chars, try from the MS Store Terminal app

Yes, getting desired output from PowerShell terminal. only with ISE getting this junk chars. Thanks a lot @darkoperator . much delighted. Cheers :-)
