### ISSUE TITLE
Invoke-SSHCommand will attempt to run against down host

### ISSUE THREAD

**Issue by FireInWinter** [darkoperator/Posh-SSH#57]
Invoke-SSHCommand will attempt to run against a session that has an IsConnected of False and the system has been shutdown.  It looks like it tries to connect if IsConnected is false, but doesn't check after that to see if it actually connected.  Should be a minor change to add another if statement.

**Comment by FireInWinter** [comment]
Actually it doesn't look like it does try to connect if it isn't connected.  It already had a type and was trying to do a $s.session.connect(), but $s isn't a variable in the script, so it would get an error.
>You cannot call a method on a null-valued expression.

So there are probably 2 things that could be changed in it with regards to disconnected hosts.

**Comment by darkoperator** [comment]
merged the part that fixes this separately from the pull request
