### ISSUE TITLE
Exit Status 22

### ISSUE THREAD

**Issue by philiprusinov** [darkoperator/Posh-SSH#570]
Hello,
I'm trying to execute some commands on HPE remote switch, and receive error code 22. I was not able to find what this code means. Connection to the switch is alive:

SessionId  Host                                  Connected
    0        X.X.X.X                                          True

but when I run the command Invoke-SSHCommand -Command $command -SessionId $SSH.SessionId the following error appears:

Host       : X.X.X.X
Output     : {}
ExitStatus : 22

The same command is executed via PuTTY without issues and I'm not sure how to proceed.

**Comment by darkoperator** [comment]
You need to use a shellstream. Invoke-sshcommand works more like plink where a a binary on the specified target is ran and its output is sent back. It is not an interactive shellSent from my iPhoneOn Mar 20, 2024, at 11:05 AM, philiprusinov ***@***.***> wrote:﻿
Hello,
I'm trying to execute some commands on HPE remote switch, and receive error code 22. I was not able to find what this code means. Connection to the switch is alive:
`SessionId  Host                                                                                                                     Connected

0        X.X.X.X                                                                                                                     True`

but when I run the command Invoke-SSHCommand -Command $command -SessionId $SSH.SessionId the following error apears:
Host       : X.X.X.X Output     : {} ExitStatus : 22
The same command is executed via PuTTY without issues and I'm not sure how to proceed.

**Comment by philiprusinov** [comment]
> You need to use a shellstream. Invoke-sshcommand works more like plink where a a binary on the specified target is ran and its output is sent back. It is not an interactive shellSent from my iPhoneOn Mar 20, 2024, at 11:05 AM, philiprusinov ***@***.***> wrote:﻿ Hello, I'm trying to execute some commands on HPE remote switch, and receive error code 22. I was not able to find what this code means. Connection to the switch is alive: `SessionId Host Connected 0 X.X.X.X True` but when I run the command Invoke-SSHCommand -Command $command -SessionId $SSH.SessionId the following error apears: Host : X.X.X.X Output : {} ExitStatus : 22 The same command is executed via PuTTY without issues and I'm not sure how to proceed. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thanks a lot, running shellstream is working!
