### ISSUE TITLE
Upgrade to SSH.NET 2024.0.0

### ISSUE THREAD

**Issue by peter-thomas-mgd** [darkoperator/Posh-SSH#573]
The latest version uses SSH.NET 2023.0.1.0, which does not support the MAC algorithms required by my Linux distro. I noticed that [SSH.NET 2024.0.0](https://github.com/sshnet/SSH.NET/releases/tag/2024.0.0) has been released recently, which adds support for a number of new MAC algorithms. Is it possible to put out a new release of Posh-SSH which bundles SSH.NET 2024.0.0 in its assembly package?

**Comment by darkmoon2** [comment]
Please update the 3.1.3 beta or make a 3.1.4 with this version it will resolve my issue with AWS Transfer Family that requires the following HMACs "hmac-sha2-256,hmac-sha2-512,hmac-sha2-512-96,hmac-sha2-256-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96" which all appear to have been added in to the new SSH.NET 2024.0.0 I would add this myself but I would not know where to start.

**Comment by darkoperator** [comment]
Should have a new release in the coming weeks with it.

**Comment by darkoperator** [comment]
just pushed 3.2.0 with the new library.
