### ISSUE TITLE
New issues establishing a SSH session that used to work on earlier host.   

### ISSUE THREAD

**Issue by buskeyl** [darkoperator/Posh-SSH#574]
Trying to establish as SSH connection to a ESXi 8.0 host.  

Conventional SSH@test-esxi works, on Powehrshell 5. 1.  Don't have access to POSH 7 yet.  
Standard Putty session also works fine.  
Posh-SSH (ver 2.2) worked fine on ESXI 7.x  

Upgraded the POSH-SSH module to the latest version available here.  

```
cmdlet New-SSHSession at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
ComputerName[0]: test-esx
ComputerName[1]: 
Credential
New-SSHSession : Exception has been thrown by the target of an invocation.
At line:1 char:1
+ New-SSHSession
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Renci.SshNet.SshClient:SshClient) [New-SSHSession], TargetInvocationException
    + FullyQualifiedErrorId : SSH.NewSshSession

```
Any help?  Not a SSH commando...

**Comment by darkoperator** [comment]
The new version dropped ripemd160 could the server be using it?

**Comment by buskeyl** [comment]
Thanks.  I have no idea.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darkoperator** [comment]
I just noticed you were talking about version 2.x that is quite an old version of the module.
