### ISSUE TITLE
ssh to juniper router with advance ciphers

### ISSUE THREAD

**Issue by shabbir1282** [darkoperator/Posh-SSH#576]
Hello experts,

i am trying to ssh to a juniper router with following ssh server configs i am getting error, mentioned below. if i remove these configs, all works fine. i checked documentation the cipher and key are mentioned are supported except group-exchange-sha2.

juniper ssh config
--------------------------------
lab@router1# show groups default system services ssh    
ciphers [ "aes128-gcm@openssh.com" "aes256-gcm@openssh.com" ];
key-exchange [ ecdh-sha2-nistp256 group-exchange-sha2 ];
--------------------------------
New-SSHSession -ComputerName 10.85.164.11 -Credential (Get-Credential) -Verbose
output: New-SSHSession: Client encryption algorithm not found

Posh-SSH module:
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
**3.2.0**                Posh-SSH                            PSGallery            Provide SSH and SCP functionality for ex…

**Comment by darkoperator** [comment]
Those AES algorithms are not supported in ssh.net under .net standard 2.0 that is used to compile the module against

**Comment by shabbir1282** [comment]
thanks @darkoperator , I checked their documentation the latest version does support.

mentioned on this link

https://github.com/sshnet/SSH.NET

**Comment by darkoperator** [comment]
This is weird as is in the release it works with the ciphers 
![image](https://github.com/darkoperator/Posh-SSH/assets/521246/edb9d979-bd77-4c18-84de-f32082a7fb54)

just tested against a CentOS server setup with the ciphers are rebooted for good measure. Tested wonder PS 5.1 and PS7

**Comment by darkoperator** [comment]
nope guess OpenSSH is ignoring the list and also offering others, need to figure how to force it, since I don't have juniper gear. 
```
PS C:\Users\administrator\Downloads\Posh-SSH> $sess = Get-SSHSession
PS C:\Users\administrator\Downloads\Posh-SSH> $sess.Session.ConnectionInfo


KeyExchangeAlgorithms             : {[curve25519-sha256, System.Func`1[Renci.SshNet.Security.IKeyExchange]],
                                    [curve25519-sha256@libssh.org, System.Func`1[Renci.SshNet.Security.IKeyExchange]],
                                    [ecdh-sha2-nistp256, System.Func`1[Renci.SshNet.Security.IKeyExchange]],
                                    [ecdh-sha2-nistp384, System.Func`1[Renci.SshNet.Security.IKeyExchange]]...}
Encryptions                       : {[aes128-ctr, Renci.SshNet.CipherInfo], [aes192-ctr, Renci.SshNet.CipherInfo],
                                    [aes256-ctr, Renci.SshNet.CipherInfo], [aes128-cbc, Renci.SshNet.CipherInfo]...}
HmacAlgorithms                    : {[hmac-sha2-256, Renci.SshNet.HashInfo], [hmac-sha2-512, Renci.SshNet.HashInfo],
                                    [hmac-sha2-512-96, Renci.SshNet.HashInfo], [hmac-sha2-256-96,
                                    Renci.SshNet.HashInfo]...}
HostKeyAlgorithms                 : {[ssh-ed25519,
                                    System.Func`2[System.Byte[],Renci.SshNet.Security.KeyHostAlgorithm]]}
AuthenticationMethods             : {password, keyboard-interactive}
CompressionAlgorithms             : {[none, ]}
ChannelRequests                   : {[env, Renci.SshNet.Messages.Connection.EnvironmentVariableRequestInfo], [exec,
                                    Renci.SshNet.Messages.Connection.ExecRequestInfo], [exit-signal,
                                    Renci.SshNet.Messages.Connection.ExitSignalRequestInfo], [exit-status,
                                    Renci.SshNet.Messages.Connection.ExitStatusRequestInfo]...}
IsAuthenticated                   : True
Host                              : 10.200.200.136
Port                              : 22
Username                          : local_admin
ProxyType                         : None
ProxyHost                         :
ProxyPort                         : 0
ProxyUsername                     :
ProxyPassword                     :
Timeout                           : 00:00:10
ChannelCloseTimeout               : 00:00:01
Encoding                          : System.Text.UTF8Encoding
RetryAttempts                     : 10
MaxSessions                       : 10
CurrentKeyExchangeAlgorithm       : curve25519-sha256
CurrentServerEncryption           : aes128-ctr
CurrentClientEncryption           : aes128-ctr
CurrentServerHmacAlgorithm        : hmac-sha2-256
CurrentClientHmacAlgorithm        : hmac-sha2-256
CurrentHostKeyAlgorithm           : ssh-ed25519
CurrentServerCompressionAlgorithm : none
ServerVersion                     : SSH-2.0-OpenSSH_8.7
ClientVersion                     : SSH-2.0-Renci.SshNet.SshClient.0.0.1
CurrentClientCompressionAlgorithm : none
```

**Comment by darkoperator** [comment]
was able to limit it, I compiled a version fo the module as .Net Standard 2.1 but no luck 

```
PS C:\Users\administrator\Desktop\netstandard2.1> Import-Module .\PoshSSH.dll -Verbose
VERBOSE: Loading module from path 'C:\Users\administrator\Desktop\netstandard2.1\PoshSSH.dll'.
VERBOSE: Importing cmdlet 'Get-SSHHostKey'.
VERBOSE: Importing cmdlet 'Get-SCPItem'.
VERBOSE: Importing cmdlet 'Get-SFTPItem'.
VERBOSE: Importing cmdlet 'New-SFTPSession'.
VERBOSE: Importing cmdlet 'New-SSHSession'.
VERBOSE: Importing cmdlet 'Set-SCPItem'.
VERBOSE: Importing cmdlet 'Set-SFTPItem'.
VERBOSE: Importing cmdlet 'New-SSHMemoryKnownHost'.
VERBOSE: Importing cmdlet 'Get-SSHJsonKnownHost'.
VERBOSE: Importing cmdlet 'Get-SSHOpenSSHKnownHost'.
VERBOSE: Importing alias 'Get-SSHJsonKnowHost'.
PS C:\Users\administrator\Desktop\netstandard2.1> New-SSHSession 10.200.200.136 local_admin

PowerShell credential request
Enter your credentials.
Password for user local_admin: ***********

New-SSHSession: Client encryption algorithm not found
```

**Comment by shabbir1282** [comment]
@darkoperator do you need a juniper device? do you have a computer with kvm? i can setup one on your computer which you can use to test or i can provide you an online image but that is available only for 6 hours per spin and is restricted to source ip of the operator. 

let me know i can help with multiple other options as well.

**Comment by darkoperator** [comment]
No need, I can not add support for those ciphers even when going .net standard 2.1, without adding the requirement for people to in addition of installing PWSH they need to install .Net 6 and break it for a lot of users that leverage it in Azure
