### ISSUE TITLE
Suggestion: Make New-SSHSession multi-threaded

### ISSUE THREAD

**Issue by FireInWinter** [darkoperator/Posh-SSH#58]
I would love it if New-SSHSession were multi-threaded.  I sometimes need to connect to a few hundred hosts and it takes a long time to connect to all of them.  If New-SSHSession were to be multi-threaded, then it wouldn't be nearly as bad to connect to all of them.

So something like
New-SSHSession -ComputerName 'Server1', 'Server2', 'Server3' -ThrottleLimit 10 -Credential $MyCred -ConnectionTimeout 30

Since it is already in C#, it shouldn't be too bad to make multi-threaded ( I hope).

Thanks for making this.  I'm starting to use Posh-SSH a little more and I'm liking it..

**Comment by darkoperator** [comment]
Need to improve my C# skills to be able to figure threads and PowerShell runspaces, but I do take pull requests ;)

**Comment by GregJobs** [comment]
Any progress on this by chance? I connect to over 2300 devices and while I can split my scripts/files up on a few machines and only have it take 12 hours it'd be great to have a way to multi-thread powershell / posh to hit maybe 10 at a time from a single machine.

**Comment by darkoperator** [comment]
So far none. I have tried but not been able to figure how to it

**Comment by MVKozlov** [comment]
@GregJobs  Did You try to look at https://github.com/proxb/PoshRSJob ?

**Comment by GregJobs** [comment]
I haven't tried it, looks like it could work though, thanks.
