### ISSUE TITLE
Get-SCPItem is deleting existing target files if source file is not available when using -Force

### ISSUE THREAD

**Issue by darknightMC** [darkoperator/Posh-SSH#582]
When running Get-SCPItem along with the -Force and the target file exists but the source file does not the cmdlet does the following: 

1. Deletes the target file (without any warning that it will do so)
2. Then the cmdlet errors out with the usual "No such file or directory" for the source file

By the end of the command execution, you are left without a target file!

To me, it seems like the code isn't checking for source file existence first. The cmdlet just straight up overwrites the target file and since the source does not exist...one is left with the target file.

**Comment by MVKozlov** [comment]
The code does not actually check for the existence of the remote file.

There is no such method in ScpClient
https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet/ScpClient.cs

**Comment by darknightMC** [comment]
> The code does not actually check for the existence of the remote file.
> 
> There is no such method in ScpClient https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet/ScpClient.cs

Please see below for example: 
Get-SCPItem -computernamer someservername -Credential username -Path "/home/user/Downloads/file.txt" -PathType File -Destination "C:\Users\user\Desktop\TestFolder\" -Force

WARNING: Host key is not being verified since Force switch is used.
WARNING: Overwritting C:\Users\user\Desktop\TestFolder\file.txt
Get-SCPItem: scp: /home/user/Downloads/file.txt: No such file or directory

After the Get-SCPItem command referenced above, C:\Users\user\Desktop\TestFolder\file.txt is gone. The documentation makes no mention of this behavior for -force flag. 

Shouldn't the source file be checked for existence before overwriting the target file?

**Comment by darkoperator** [comment]
I will update the documentation :) thanks for pointing it out, it was something I missed.

**Comment by darknightMC** [comment]
> I will update the documentation :) thanks for pointing it out, it was something I missed.

Great, and thanks for providing the Posh-SSH Module. Would it be possible to add a check for the source file before attempting to overwrite the target file ?

**Comment by darkoperator** [comment]
I believe that without force it will not download the file and overwrite and force will allow it but mot in front of my machine at this moment Sent from my iPhoneOn Jul 26, 2024, at 12:15 PM, darknightMC ***@***.***> wrote:﻿

I will update the documentation :) thanks for pointing it out, it was something I missed.

Great, and thanks for providing the Posh-SSH Module. Would it be possible to add a check for the source file before attempting to overwrite the target file ?

**Comment by darknightMC** [comment]
Thanks for the reply @darkoperator 

Unfortunately, in this case, -force seems to be tied to two different things: 

1. To overwrite existing files
2. "Do not check the remote host fingerprint."

In my workflow using Get-SCPItem, I do have to use -force for overriding the remote host fingerprint and from time to time, I do have to overwrite existing remote target files. 

In this case, I'd suggest adding a simple check on Get-SCPItem for source file existence first whenever using the -force switch to prevent the cmdlet from deleting existing remote/target files.

**Comment by MVKozlov** [comment]
@darknightMC, as I already said there is no method to check file existence over SCP, but you can use SFTP

If you want to continue using SCP you can try renaming your old file when downloading.
Then
 1. it will definitely not be lost,
 2. you will not need the `-Force` flag

**Comment by darkoperator** [comment]
I can not check via SCP on the remote host of the file is present or not sadly as mentioned there is no API support for that partSent from my iPhoneOn Jul 26, 2024, at 1:06 PM, darknightMC ***@***.***> wrote:﻿
Thanks for the reply @darkoperator
Unfortunately, in this case, -force seems to be tied to two different things:

To overwrite existing files
"Do not check the remote host fingerprint."

In my workflow using Get-SCPItem, I do have to use -force for overriding the remote host fingerprint and from time to time, I do have to overwrite existing remote target files.
In this case, I'd suggest adding a simple check on Get-SCPItem for source file existence first whenever using the -force switch to prevent the cmdlet from deleting existing remote/target files.

**Comment by darkoperator** [comment]
updated help info in 3.2.2
