### ISSUE TITLE
How to install on an offline machine?

### ISSUE THREAD

**Issue by JakeSmithQUT** [darkoperator/Posh-SSH#583]
Hey, is there a recommended method for installing this on non-internet connected device?

**Comment by MVKozlov** [comment]
`Save-Module` on connected device and manual transfer to disconnected

**Comment by darkoperator** [comment]
Will be putting out a video soon on how to do a manual install. In short you can download the nugget from the powershell gallery, decompress it since it is a zip file and place the module in one of the folders of $env:PSModulePath depending if you are going to install system wide or a specific user

**Comment by darkoperator** [comment]
Posh-SSH 3.X Installation
https://youtu.be/83g6Yy6eTbo

**Comment by JakeSmithQUT** [comment]
You're a king! Thanks mate!
