### ISSUE TITLE
Monitor SFTP folder in realtime

### ISSUE THREAD

**Issue by DarkLite1** [darkoperator/Posh-SSH#586]
Thank you for creating this amazing module. We use it every day in production with a [wrapper script](https://github.com/DarkLite1/Get-or-send-SFTP-file) and different input files.

For uploading data in realtime, we simply use the class [System.IO.FileSystemWatcher](https://learn.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-8.0). When a file is created, this class sees it and triggers the SFTP script to upload the file.

For downloading in realtime, that's a bit of a different story. Do we need to create a loop to trigger the function `Get-SFTPChildItem` every 5 seconds? Or is there a better way to do this?

This also brings me to questions like: How long does a session stay open?

**Comment by darkoperator** [comment]
I believe that would be the only option, do not know of an API where it could be triggered from the other side. It depends on how the server is configured in terms of timeout
