### ISSUE TITLE
Feature request: add property 'Extension' to 'Get-SFTPChildItem'

### ISSUE THREAD

**Issue by DarkLite1** [darkoperator/Posh-SSH#587]
Currently, when querying the files on an SFTP server, only the following properties are returned:
![image](https://github.com/user-attachments/assets/91e0af85-4401-4953-bfb8-016202307f4b)

It would be great if the function `Get-SFTPChildItem` would be more like `Get-ChildItem` and return the property `Extension`.

Thank you for considering this.

**Comment by darkoperator** [comment]
That would be a request more fore the SSH.NET project since for that I leverage what the library offers me over SSH. There are many that will not be possible since SSH has to offer access to those.

**Comment by darkoperator** [comment]
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/4f8ec8e7-1c22-414c-b801-a063426f9b7e">

Thought of why not have it as a noteproperty it is a file.

**Comment by darkoperator** [comment]
Added in 3.2.2 release
