### ISSUE TITLE
No Files found when using Get-SFTPChildItem (v3.2.2)

### ISSUE THREAD

**Issue by Sheepy-564** [darkoperator/Posh-SSH#590]
We use Get-SFTPChildItem with Powershell 5.1 to filter and download files in a specified folder:

```
$SessionSSH = New-SSHSession -ComputerName $Hostname -Credential $Credentials -KeyFile $KeyFile -Force
$SessionSFTP = New-SFTPSession -ComputerName $Hostname -Credential $Credentials -KeyFile $KeyFile -Force
if (($SessionSSH.Connected -eq "True") -and ($SessionSFTP.Connected -eq "True")) {
    $Tar = Get-SFTPChildItem -SessionId $SessionSSH.SessionId -Path "/home/admin/protocol" | Where-Object {$_ -match 'progress-tar'}
    if ($null -ne $Tar) {
        Write-Output "File found!"
    }
    else {
        Write-Output "No File found!"
    }
}
```

This command was working  until Module Version v3.2.1 and Files have been found
With 3.2.2, we don't receive objects anymore. (No File found)

What i checked so far:
- The File is in the desired folder and access is granted
- Exchanging $SessionSSH.SessionId to $SessionSFTP.SessionId didn't resolve the issue
- Using -SFTPSession instead of -SessionId did not work
- Adding Switch Parameter for -File or -Directory did not work
- Removing "Where-Object..." from the command also lead to no files returned in $Tar
- Using Wildcards to filter for files didn't work because it havent found any files.
- Changing the Path to "/home/admin/protocol/" or "home/admin/protocol" didn't change the response

Is there something we are overlooking?

**Comment by darkoperator** [comment]
Can confirm, the problem is on Windows. Working on fix

**Comment by darkoperator** [comment]
Download 3.2.3 and test

**Comment by Sheepy-564** [comment]
> Download 3.2.3 and test

I didn't found a tag 3.2.3 so i downloaded the Master-Branch.
The Fix is working and files are listed again.

Thank you

**Comment by darkoperator** [comment]
yeah pushed it to the gallery. Sorry for not mentioning it would be there

**Comment by DarkLite1** [comment]
Strange... I also expected GitHub Releases to show the latest release. Thought it was directly pushed to Gallery when it updated in GitHub.

Thx @Sheepy-564 for reporting and @darkoperator  for the quick fix. 

It could be a good idea to add some more Pester tests to the code, so we can catch small issues like these before they go live.

![image](https://github.com/user-attachments/assets/10982b2e-fcf6-4018-992b-6b000caf41ef)
