### ISSUE TITLE
Connection Issues with Posh-SSH 3.0 and RSA 2048 Keys on Linux 2023 OS

### ISSUE THREAD

**Issue by jmankotia** [darkoperator/Posh-SSH#600]
Hello everyone,

I am experiencing connection issues when using Posh-SSH 3.0 to establish an SSH connection with a Linux machine running the 2023 operating system. The connection fails because the OS does not allow RSA 2048 keys for authentication, likely due to security policies that favor stronger key algorithms.

Here are the details:

Environment: Using Posh-SSH 3.0 on a Windows machine.
Target OS: Linux 2023 OS.
Key Type: The SSH key currently being used is an RSA key with a bit length of 2048.
Error Message: Permission denied (publickey).

I would like to know if there is a workaround to enable the use of RSA 2048 keys on the Linux 2023 OS, for establishing the connection.
Any insights or suggestions would be greatly appreciated!

**Comment by darkoperator** [comment]
Can you upgrade to the latest version of Posh-SSH and test?

**Comment by AkshuDev** [comment]
Thanks. Latest version resolved the problem.
