### ISSUE TITLE
How to test TrustedHosts

### ISSUE THREAD

**Issue by FireInWinter** [darkoperator/Posh-SSH#61]
I'm wondering if there is an easy way to test the fingerprint associated with a TrustedHost ( Get-SSHTrustedHost ).  I have systems that I connect to where the IP Address can move between systems and will therefore fail on connecting.  If I could easily validate the fingerprints I could more easily verify if those system have moved to a valid host and can be removed/re-added to the TrustedHosts list.

Thanks.

**Comment by darkoperator** [comment]
have you tried usiing hostnames instead of IPs so those are saved in the registry associated to the host?

**Comment by darkoperator** [comment]
Uploaded 1.7.5 to the gallery and added a -Force parameter that will not verify the host key.
