### ISSUE TITLE
Proposal: have Output property as string array from Invoke-SSHCommand

### ISSUE THREAD

**Issue by FireInWinter** [darkoperator/Posh-SSH#62]
What would everyone think about having the Output property from Invoke-SSHCommand be split on the newline character.  Also, before splitting it, strip the final newline from the output since it has little meaning as the last character.

Basically it would look something like the following.
```
$Output -replace '\n$' -split '\n'
```
This would mean that the output would be a string array instead of just a string.  This could easily break some things, so that's why I'm asking.  At the very least, I'd like to remove the trailing newline character as it doesn't have much meaning when you get the results back into PowerShell.

Thanks.

**Comment by MikeMM70** [comment]
I think it sounds like a good idea since it would make parsing the output a
little simpler, but I only have a few scripts it would effect and it would
be fairly easy for me to fix them.

**Comment by darkoperator** [comment]
Even do I find it useful, I do not want to break backward compatibility, I did not even replaced cmdlets in the latest change and just had the deprecated ones print a warning.

**Comment by Ben-Conrad** [comment]
I've been using this to get a string array:

$sshCliOutput = (($stream.Read()).split("`n")).trim() 

Ben

**Comment by urlocalguru** [comment]
I am guessing this was implemented with 1.7.3 as some of my scripts are now broken and this topic explains exactly what is happening.

**Comment by darkoperator** [comment]
Just noticed that it got added by mistake on a pull request https://github.com/darkoperator/Posh-SSH/blob/master/Posh-SSH.psm1#L269 <https://github.com/darkoperator/Posh-SSH/blob/master/Posh-SSH.psm1#L269> it should have not happened since I find it kind of trivial for someone to add a split to their own code which is a small step rather than breaking backward compatibility for those already using it. Sorry for the inconvenience, I should have caught that before merging the pull request.

**Comment by urlocalguru** [comment]
I already found an easy workaround


$variable = $(Invoke-SSHCommand -index 0 -Command "stuff to do").output | Out-String

**Comment by urlocalguru** [comment]
Will this stay as is, be reverted, or added as a switch?

**Comment by darkoperator** [comment]
It will remain as is, been holding out new changes until MS Powershell team finishes the wrapper around their OpenSSH port
