### ISSUE TITLE
Stream.Writeline wait for execution

### ISSUE THREAD

**Issue by trondhindenes** [darkoperator/Posh-SSH#64]
Would it be possible to have $stream.Writeline wait for execution before it returns to prompt? I'm having some issues with bash commands that run for a while (cloning large git repos for example). I'm currently implementing this via some start-sleeps but that's pretty dirty.

The current implementation also means that the output of $stream.read() may vary as commands from write() are executed.

**Comment by darkoperator** [comment]
It is a limitation more of the library used than the module it self.
