### ISSUE TITLE
New-SSHSession : The located assembly's manifest definition does not match the assembly reference

### ISSUE THREAD

**Issue by akamac** [darkoperator/Posh-SSH#66]
I installed the module and get this error when trying to create new ssh session.
I have EMC PowerShell Toolkit installed which also has Renci.Ssh.Net.dll of an older version. This could be the reason. How can I solve it?

**Comment by darkoperator** [comment]
to be honest no clue on a solution since we both use the same assembly and in my case I have added patches to mine to fix some bugs I have the skill to fix since the project became abandoned.
