### ISSUE TITLE
Get-SFTPFile does not respect 

### ISSUE THREAD

**Issue by sdecker** [darkoperator/Posh-SSH#67]
The functions should respect $ProgressPreference='SilentlyContinue'. At least Get-SFTPFile does not.

**Comment by darkoperator** [comment]
agree need to figure how this is done on C# cmdlet

**Comment by sdecker** [comment]
I did a quick search but have not found anything yet. I'm surprised the cmdlet binding does not inject it like in PowerShell script functions. If I find something I'll update this issue.

**Comment by darkoperator** [comment]
ok was looking at this again and since I'm working inside an event handler the way I do progress printing bypasses this. Will work on a parameter to silence the progress.

**Comment by darkoperator** [comment]
Uploaded 1.7.5 to the gallery, a noprogress parameter has to be used, it will not honor the variable in a multithreaded upload as it does. have not been able to figure a workaround.

**Comment by sdecker** [comment]
Thanks!

On Sat, Jul 9, 2016 at 11:37 AM, Carlos Perez <notifications@github.com>
wrote:

> Uploaded 1.7.5 to the gallery, a noprogress parameter has to be used, it
> will not honor the variable in a multithreaded upload as it does. have not
> been able to figure a workaround.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/darkoperator/Posh-SSH/issues/67#issuecomment-231540263>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF3KDMo2XtULe-FNgmuWZenQeFVhSn4-ks5qT8AwgaJpZM4Fk4tR>
> .
>



-- 
--- "The obscure we see eventually, the completely apparent takes longer"
---- Edward R. Murrow
