### ISSUE TITLE
Pseudo-TTY with New-SSHSession

### ISSUE THREAD

**Issue by wbashir** [darkoperator/Posh-SSH#68]
Is there a way to enable pseduo-tty when creating a `New-SSHSession` ?

**Comment by darkoperator** [comment]
Sadly the library I’m using for the module does not support it.

**Comment by wbashir** [comment]
Thanks for the prompt reply.

**Comment by darkoperator** [comment]
I believe support for this was added recently to the core library so it should be doableSupport creating shell without PTY · Issue #1418 · sshnet/SSH.NETgithub.comSent from my iPhoneOn Jul 17, 2024, at 7:25 AM, p-gen ***@***.***> wrote:﻿
Do you think there is an alternative to forcing the allocation of a pseudo terminal?

**Comment by p-gen** [comment]
Hi,
thanks for answering.
What I would like is to be able to run a script using Invoke-SSHCommand with the equivalent of “ssh -t” to make sure the remote shell has a tty allocated as some programs need it.

**Comment by p-gen** [comment]
Yes, I think so, but it's a slightly more complex solution for non-interactive commands that still require a terminal.

**Comment by darkoperator** [comment]
Problem is that invoke-sshcommand does not create a TTY is has the same behavior as Plink where it executes a given binary with the parameters passed and returns the output.

**Comment by p-gen** [comment]
It's a real shame, so I'm going to use New-SSHShellStream even if it complicates things. Thanks again.
