### ISSUE TITLE
New-SSHSession (1.7.2) not honoring Active Directory domain in $cred

### ISSUE THREAD

**Issue by Ben-Conrad** [darkoperator/Posh-SSH#70]
I'm running 1.6 and 1.7.2 and am seeing that New-SSHSession is not passing the Active Directory domain credentials properly, looks like it's stripping out anything in front of the username:

PS E:\> $cred.username
mydomain\myuser

$session = New-SSHSession -computer $computer -Credential $cred -AcceptKey:$true

New-SSHSession : Sequence contains more than one elementAt line:1 char:12
+ $session = New-SSHSession -computer $computer -Credential $cred -AcceptKey:$true
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SSHSession], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,SSH.NewSshSession

On the Linux server (running Power Broker Identity Services) I see the login without the domain prepended.  when I perform a manual login with Putty I see the domain listed:

Oct  8 23:03:49 xxxxxxxxxx sshd[6137]: input_userauth_request: invalid user myuser
>>> myuser should be mydomain\myuser.

Any thoughts on this?

Ben

**Comment by darkoperator** [comment]
It should work, just in case I reviewed the code again and pushed a pinch of fixes in to master branch, can you download the latest build from master and test again? I know Kerberos is not supported but simple keyboard interactive method should pass the proprer username.

**Comment by Ben-Conrad** [comment]
Yup your changes fixed the issue.  I confirmed the current 1.7.2 still did not work, then replaced it with the one from Main.  It works!

Thanks,

Ben

**Comment by darkoperator** [comment]
Cool will update version and push a new version to the gallery
