### ISSUE TITLE
Invoking long running commands on Linux, how to wait for completion?

### ISSUE THREAD

**Issue by Ben-Conrad** [darkoperator/Posh-SSH#71]
Hi Guys,

I've got some long running commands (some are 10 seconds, some are 10 minutes) that I need to run on Linux and then I want to read the output and parse it.  I'm currently doing this which does not seem efficient:

$stream.WriteLine($cmd)
sleep 600 # sleep 10 minutes
$stream.read()

The problem is I have to guess how long to "sleep" for and that is error prone.

Is there any sort of cmdlet or method that will allow me to wait for some string (like the user prompt) and then automatically do a $stream.read()?  Something like a Invoke-SSHStreamExpect (which does not exist).

Pseudo code:
$cmd = "grep -R blah /etc" # This takes about 20 seconds to run
$result = $stream.expect($cmd, ']$')  # Run command and block until we see the last 2 characters of my user prompt.

Thanks,

Ben

**Comment by Ben-Conrad** [comment]
This kind of works but it's not synchronous and i don't know when the command has finished:

Invoke-SSHStreamExpectAction -ShellStream $stream -Command 'grep -R blah /etc' -action 'date' -ExpectString ']$'

**Comment by darkoperator** [comment]
I think the stream object has several methods you can use including a expect one. Other than that I do not know of any other way.

**Comment by Ben-Conrad** [comment]
Thanks for the tip.  I was reading the SSH.NET API Doc and got this code working as you describe:

$cmd = "grep -R blah /etc"
$stream.WriteLine($cmd)
$stream.Expect(']$')
#   Will block execution until the expect string is found, perfect!!!

$span = new-timespan -seconds 5
$cmd = "grep -R blah /etc"
$stream.WriteLine($cmd)
$stream.Expect('NeverMatchThisString',$span)
# This will block waiting for the string match and then quit after $span if string not matched
