### ISSUE TITLE
cisco

### ISSUE THREAD

**Issue by kfleming54** [darkoperator/Posh-SSH#73]
has anyone gotten this to work with CISCO fiber switch?
commands work fine from putty, but using them from Posh-ssh does not work
if go into configure mode

**Comment by darkoperator** [comment]
Are you using the stream instead of invoke-ssh ommand?

**Comment by kfleming54** [comment]
did it both ways and it fails on fiber switch after configure command

either way.

 

Unless there is something else with stream that I should be doing

 

$session = New-SshSession -ComputerName $ipAddress -Credential $cred -AcceptKey 

$session = Get-SshSession -index 0

$stream = $session.Session.CreateShellStream("FabA",0,0,0,0,3000)

foreach ($command in $commands)

{

      Write-Output "$($command) "

      $stream.Write($command)

}

Remove-SshSession -SessionId $session.SessionId

**Comment by darkoperator** [comment]
you have to check the output to make sure it finished running the command or it will hammer the session, another option is to put a sleep of a couple of seconds between commands

**Comment by darkoperator** [comment]
any update ?

**Comment by kfleming54** [comment]
sorry

I apologize

my priorities got changed

will get back to it as soon as I can

**Comment by BornToBeRoot** [comment]
@kfleming54 I currently working on a module for Brocade Switches... They use the same ssh-basic like cisco devices, It seems like the console need some time to response...

After each command i use a wait time (about 500 - 1000 Milliseconds)... 

If you are interesting, you can try my module (requieres posh-ssh). I could not test it on cisco switches, but maybe you are lucky and it work without problems. You can find it here: https://github.com/BornToBeRoot/PowerShell-SSH-Brocade

More details: https://www.reddit.com/r/PowerShell/comments/3tgql4/poshssh_shell_reading/

**Comment by darkoperator** [comment]
closing since no update. Re-open if still an issue
