### ISSUE TITLE
Posh-SSH and special commands

### ISSUE THREAD

**Issue by D33N01** [darkoperator/Posh-SSH#74]
Hello,

I'm working on an automation project, therefore I make use of Posh-SSH. 
For standard commands it works fine and most components I'm enable to automate. 

I got problems when I want to automate CheckPoint Firewall settings. I have to use a command that aspects  separate commands in the command itself. 

For an example 'nslookup' works the same. It's behaves likes a program. 
Posh-SSH can't handle it, It hangs on the command be cause it doesn't give a return. 

Even with a time-out and then trying to give another after it doesn't seem to work. 
Maybe there's a simple way to make it work but I can't seem to find it online.
Hopefully that you can help me out. 

Kind Regards,

Dane

**Comment by darkoperator** [comment]
have you tried using a stream?

**Comment by D33N01** [comment]
Are you maybe referring to these commands:
Invoke-SSHCommandStream
Invoke-SSHStreamExpectAction

I didn't try these yet, and while looking online I can't seem to find an example of the usage. 

Can you also use it with commands that require to have a yes of no answer?

**Comment by darkoperator** [comment]
Just look at the examples in the readme ;)
https://github.com/darkoperator/Posh-SSH/blob/master/Readme.md

**Comment by D33N01** [comment]
That seems to work out. The only problem I had was that the script was giving commands to fast with a writeline so I had to put start-sleep of 100 ms to make it work. 

Thanks for the assistance.
