### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Bhardin04** [darkoperator/Posh-SSH#75]
import-module : Could not load file or assembly
'file:///C:\Users\svc_fin_qlikview\Documents\WindowsPowerShell\Modules\posh-ssh\Assembly\Renci.SshNet.dll' or one of its
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ import-module  posh-ssh -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by darkoperator** [comment]
Can you check the DLL is not blocked by the OS. Right click, properties and you should see if it was or not

**Comment by darkoperator** [comment]
closing since no update. Re-open if still an issue

**Comment by Thelucifer666** [comment]
`
PS C:\> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force
PS C:\> Import-Module Posh-SSH -Verbose
VERBOSE: Loading module from path 'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Posh-SSH.psd1'.
VERBOSE: Loading 'Assembly' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Assembly\Renci.SshNet.dll'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Format\SSHSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Format\SFTPSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Format\Renci.SshNet.SshCommand.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Format\Renci.SshNet.Sftp.SftpFile.Format.ps1xml'.
Import-Module : Could not load file or assembly
'file:///C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Assembly\Renci.SshNet.dll' or one of its
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module Posh-SSH -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

PS C:\> Get-ExecutionPolicy
RemoteSigned
PS C:\> Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
PS C:\> Import-Module Posh-SSH -Verbose
VERBOSE: Loading module from path 'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Posh-SSH.psd1'.
VERBOSE: Loading 'Assembly' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Assembly\Renci.SshNet.dll'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Format\SSHSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Format\SFTPSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Format\Renci.SshNet.SshCommand.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Format\Renci.SshNet.Sftp.SftpFile.Format.ps1xml'.
Import-Module : Could not load file or assembly
'file:///C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Assembly\Renci.SshNet.dll' or one of its
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module Posh-SSH -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
`

**Comment by Thelucifer666** [comment]
`PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34014
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
`

**Comment by darkoperator** [comment]
If not installing from the gallery make sure the DLL is not marked as blocked. Windows will mark the zip and every file in it for security reasons and you will have to unblock them

**Comment by Thelucifer666** [comment]
Indeed. Almost all dll and ps1 files were blocked. I've unblocked all files but that still does not change the result.

`
PS C:\> Get-ChildItem C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Posh-SSH | Unblock-File
PS C:\> Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
PS C:\> Import-Module Posh-SSH -Verbose
VERBOSE: Loading module from path 'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Posh-SSH.psd1'.
VERBOSE: Loading 'Assembly' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Assembly\Renci.SshNet.dll'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Format\SSHSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Format\SFTPSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Format\Renci.SshNet.SshCommand.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Format\Renci.SshNet.Sftp.SftpFile.Format.ps1xml'.
Import-Module : Could not load file or assembly
'file:///C:\windows\system32\WindowsPowerShell\v1.0\Modules\Posh-SSH\Assembly\Renci.SshNet.dll' or one of its
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module Posh-SSH -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
`

**Comment by Thelucifer666** [comment]
I've verified all files in that directory are unblocked- even in all subfolders. Anything else I can check here?

`PS C:\> Get-ChildItem C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Posh-SSH -Recurse | Unblock-File`

**Comment by Thelucifer666** [comment]
OK...Module loaded successfully.

I had to first unblock the zip file before extracting the files and saving them in the PS modules library. 

Extracting the files and then unblocking the extracted files does not work (sneaky). Thanks for your help.

Great-module by the way.

**Comment by juicyjonny** [comment]
Can confirm that after unblocking the zip as a whole and then extracting I had success. Thanks guys

**Comment by LevKesha** [comment]
Hey guys, breaking my head on the same issue. The files are not blocked for definitely. Still, powershell ISE is reporting: 

Import-Module : Could not load file or assembly 'Renci.SshNet, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the 
file specified.

Nevertheless, I see it the directory(!!!). Please assist.

**Comment by LevKesha** [comment]
OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763

**Comment by LevKesha** [comment]
I've tried the dame from Powershell CLI console: 

PS C:\Users\dalevg> install-module posh-ssh -force -verbose
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='posh-ssh'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'posh-ssh'.
VERBOSE: Performing the operation "Install-Module" on target "Version '3.0.8' of module 'Posh-SSH'".
VERBOSE: The installation scope is specified to be 'AllUsers'.
VERBOSE: The specified module will be installed in 'C:\Program Files\WindowsPowerShell\Modules'.
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'Posh-SSH' with version '3.0.8' from the repository
'https://www.powershellgallery.com/api/v2'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Posh-SSH'' for ''.
VERBOSE: InstallPackage' - name='Posh-SSH',
version='3.0.8',destination='C:\Users\dalevg\AppData\Local\Temp\14\279110877'
VERBOSE: DownloadPackage' - name='Posh-SSH',
version='3.0.8',destination='C:\Users\dalevg\AppData\Local\Temp\14\279110877\Posh-SSH.3.0.8\Posh-SSH.3.0.8.nupkg',
uri='https://www.powershellgallery.com/api/v2/package/Posh-SSH/3.0.8'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/Posh-SSH/3.0.8'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/Posh-SSH/3.0.8'.
VERBOSE: Completed downloading 'Posh-SSH'.
VERBOSE: Hash for package 'Posh-SSH' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='Posh-SSH',
version='3.0.8',destination='C:\Users\dalevg\AppData\Local\Temp\14\279110877'
VERBOSE: Validating the 'Posh-SSH' module contents under
'C:\Users\dalevg\AppData\Local\Temp\14\279110877\Posh-SSH.3.0.8' path.
VERBOSE: Test-ModuleManifest successfully validated the module manifest file
'C:\Users\dalevg\AppData\Local\Temp\14\279110877\Posh-SSH.3.0.8'.
VERBOSE: Validating the authenticode signature and publisher of the catalog file or module manifest file of the module
'Posh-SSH'.
VERBOSE: Catalog file 'Posh-SSH.cat' is not found in the contents of the module 'Posh-SSH' being installed.
VERBOSE: For publisher validation, current module 'Posh-SSH' with version '3.0.8' with publisher name '' from root
certificate authority ''. Is this module signed by Microsoft: 'False'.
VERBOSE: For publisher validation, using the previously-installed module 'Posh-SSH' with version '3.0.8' under
'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.8' with publisher name '' from root certificate authority ''.
Is this module signed by Microsoft: 'False'.
VERBOSE: Checking for possible command collisions for the module 'Posh-SSH' commands.
WARNING: The version '3.0.8' of module 'Posh-SSH' is currently in use. Retry the operation after closing the
applications.
VERBOSE: Module 'Posh-SSH' is in currently in use or you don't have the required permissions.

Maybe it give you more ideas.

**Comment by LevKesha** [comment]
After uninstalling the module and re-installing it - all worked.

**Comment by LevKesha** [comment]
It works only on PS 32 and 64, but not the 86X version. Maybe the module not suitable for that version?

**Comment by darkoperator** [comment]
Confused, 32bit is x86. All testing is donde on x64 since x86 is mostly legacy code in modern environments Sent from my iPhoneOn Jun 29, 2023, at 6:52 AM, Lev Goldenberg ***@***.***> wrote:﻿
It works only on PS 32 and 64, but not the 86X version. Maybe the module not suitable for that version?

**Comment by MVKozlov** [comment]
btw, there is no x86 server versions since 2008, only x64
