### ISSUE TITLE
Way to import module from relative path

### ISSUE THREAD

**Issue by jeffchulg** [darkoperator/Posh-SSH#76]
Hello,

is there a way to either dot source the module or to Import it from outside of the normal powershell path ?

Regards,

Jefferson.

**Comment by dzeleski** [comment]
This is an issue for me as well, would like to get any input if possible.

**Comment by darkoperator** [comment]
you can import the module from what ever location you place it in as long as you specify the manifest for the module. In powershell that is .psd1 that is the file specifies the assemblies, help files, format files ..etc. a psm1 as the dll are just containers of functions and cmdlets. dot sourcing is to add functions in a ps1 or psm1 files not something you do to load a module.

**Comment by darkoperator** [comment]
I belive this is more user error since a module can not be dot source specially one that is a DLL and supporting PSM1 files.
