### ISSUE TITLE
Remove-SFTPItem only returns "Failure" when a directory is not empty

### ISSUE THREAD

**Issue by Cavorter** [darkoperator/Posh-SSH#77]
It took me a few tries to figure out that the reason why a call to Remove-SFTPItem with a valid directory was failing with just the following error until I figured out that it was because the directory wasn't empty:

> Exception calling "Delete" with "1" argument(s): "Failure"
> At C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\1.7.3\Sftp.ps1:326 char:17
> +                 $session.Session.Delete($Path)
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>     + FullyQualifiedErrorId : SshException

It looks like the function is already checking to see if the path exists before it attempts to delete it. Does it seem reasonable to also check to see if a directory is empty before attempting to delete it so that a better error can be thrown?

I took a look at what would be needed to do so and it seems like the only slightly thorny issue is to determine if the item being deleted is a directory. I think the most efficient method is to try a Get-SFTPChildItem on the path and if it succeeds see if the count of child items is greater than 2 and throw.

Any thoughts?

(BTW - Thanks for a great module. It's been a huge help on the project I'm working on.)

**Comment by darkoperator** [comment]
fixed in branch 1_7_5 once I fix other issued will push to master in github and publish module to the gallery.

**Comment by darkoperator** [comment]
Uploaded 1.7.5 to the gallery
