### ISSUE TITLE
Instructions for system wide (all users) installation

### ISSUE THREAD

**Issue by supercheetah** [darkoperator/Posh-SSH#78]
There ought to be instructions for installing the modules so that they're accessible to all users, and that should just involve installing into `$($env:ProgramFiles)\WindowsPowerShell\Modules`.

I made a version of `instposhsshdev` that does that here: https://gist.github.com/supercheetah/dd623ce39f1bf770f05f#file-instposhsshdev

It just modifies `$targetondisk`.

I can maintain that copy if you want.

**Comment by darkoperator** [comment]
next version abandons support for PSv2 and will be installed via the PowerShell gallery. With the galery you can choose system wide or only for the user with Install-Module.
