### ISSUE TITLE
SSHStream - send arrow keypress

### ISSUE THREAD

**Issue by urlocalguru** [darkoperator/Posh-SSH#81]
I have what might be a unique situation where I need to pass arrow keypress's into my SSHStream.  I cannot find any documentation that helps.

**Comment by darkoperator** [comment]
To be honest no clue there on how to do it

**Comment by urlocalguru** [comment]
Ill have to try this tomorrow.. but I don't think it will work

http://www.vexasoft.com/pages/send-keyboardinput

any chance this could be a feature request?

Sadly I am dealing with some poorly written corporate software that's only
available via a ssh gui similar to nano but for querying an in-house
database.  Update statements are no issue but trying to get data out isn't
doable as its formatted terribly.  There is an option to export it to a
file, but I have to hit the right arrow once to select that option.

There could be other benefits to having special key functionality;
f1-12, backspace, actually sending enter instead of a "", tab etc

~Will

On Tue, Dec 8, 2015 at 6:08 PM, Carlos Perez <notifications@github.com>
wrote:

> To be honest no clue there on how to do it
>
> Sent from my iPhone
>
> > On Dec 8, 2015, at 7:13 PM, urlocalguru <notifications@github.com>
> wrote:
> >
> > I have what might be a unique situation where I need to pass arrow
> keypress's into my SSHStream. I cannot find any documentation that helps.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/darkoperator/Posh-SSH/issues/81#issuecomment-163063359>
> .
>



-- 
~Guru
