### ISSUE TITLE
New session using username and pem file

### ISSUE THREAD

**Issue by bertyhell** [darkoperator/Posh-SSH#82]
I'm trying to setup a connection using a username and a .pem key file.
If i connect without the username, a dialog window pops up and asks for my credentials. When i enter the username only, it seems to connect
![image](https://cloud.githubusercontent.com/assets/1710840/11693667/6da3a28e-9ea6-11e5-8ef2-8f34a48f277f.png)
![image](https://cloud.githubusercontent.com/assets/1710840/11693698/9f43032a-9ea6-11e5-949a-f7c0c4e3b9c0.png)

But i can't seems to get to connect automatically:
![image](https://cloud.githubusercontent.com/assets/1710840/11693748/e23f6056-9ea6-11e5-932d-bd45ba4157df.png)

How do i pass in a username but no password, without a dialog window popping up?

**Comment by darkoperator** [comment]
You can create a pscredential object and use that in your script 
http://blogs.msdn.com/b/koteshb/archive/2010/02/13/powershell-creating-a-pscredential-object.aspx

**Comment by bertyhell** [comment]
Ok, that worked
This is the script that worked:
```powershell
$creds = New-Object -TypeName System.Management.Automation.PSCredential ("******", (new-object System.Security.SecureString))
New-SSHSession -ComputerName "***************" -Credential $creds -KeyFile "*******************.pem"
```
