### ISSUE TITLE
Session operation has timed out inside Azure Automation

### ISSUE THREAD

**Issue by oliverbock** [darkoperator/Posh-SSH#83]
I am trying to use Posh-SSH in an Azure Automation Runbook in order to run something on a Linux VM.  My script

    $password = Convertto-SecureString -String "xxxxxxx" -AsPlainText -Force
    $cred = New-Object -Typename System.Management.Automation.PSCredential -ArgumentList numbers, $password
    $ssh = New-SSHSession -ComputerName "example.com" -Credential $cred -AcceptKey -ConnectionTimeOut 100
    $(Invoke-SSHCommand -Index 0 -Command "echo dog").Output 

runs fine from my command line, but in Azure Automation I get the error

    Session operation has timed out

which is why I extended the timeout.  Do you know whether Posh-SSH operate in this environment?

**Comment by oliverbock** [comment]
The full error is

    New-SSHSession : Session operation has timed out
    At line:3 char:8
    + $ssh = New-SSHSession -ComputerName "example.com" -Credentia ...
    +        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [New-SSHSession], SshOperationTimeoutException
        + FullyQualifiedErrorId : Renci.SshNet.Common.SshOperationTimeoutException,SSH.NewSshSession

**Comment by oliverbock** [comment]
I have had more luck with [this SSH client implementation for PowerScript](https://gallery.technet.microsoft.com/scriptcenter/SSH-PowerShell-Module-17616e1a).

**Comment by darkoperator** [comment]
I don’t use Azure so no clue there. Only thing that comes to mind is they auth it does to check if the key it is one it knows about and you are not auto accepting the key.

**Comment by oliverbock** [comment]
Thanks.  Am I not accepting the key properly?  I included "-AcceptKey" alone because when I tried "-AcceptKey 1" or "-AcceptKey $true" then PowerShell (v3.0) complains about unexpected command-line parameters.

**Comment by urlocalguru** [comment]
basic usage would be
New-SSHSession -ComputerName fooserver -AcceptKey

I have run into issues with devices with a different key then what was previously accepted (due to re-image etc) and have to either cleanup after each script with the Remove-SSHTrustedHost function.  Or I can purge all keys with
foreach($i in Get-SSHTrustedHost){Remove-SSHTrustedHost -SSHHost $i.SSHHost -Verbose}

**Comment by darkoperator** [comment]
Thinking if I should add a -Force parameter that will not check the key at all and simply accept a session if the credentials are valid

**Comment by alfa164ls** [comment]
Drd3

**Comment by slavizh** [comment]
It would be good if you can fix this Carlos so we can use the full capabilities of this module in Azure Automation.
Besides that it is a great module and thank you for your work!

**Comment by darkoperator** [comment]
added -Force on the 1_7_5 branch, once I have some other issues fixed for that version I will push the version to GitHub and to the Gallery.

**Comment by darkoperator** [comment]
Uploaded 1.7.5 to the gallery

**Comment by rrbruin** [comment]
Even with the -Force parameter I am getting a timeout..

**Comment by darkoperator** [comment]
Anything on the target logs?

**Comment by rrbruin** [comment]
The target is a Fortigate firewall. But at the moment it's not producing any usable logs in the GUI. 
I will try to get more info.

Using the Posh-SSH module in a Powershell ISE session works perfect when connecting to the Fortigate.
It only fails when I use it from a Azure runbook.

**Comment by darkoperator** [comment]
The module requires to be ran under the context of a user since it accesses the registry for some tasks, do Azure Runbooks run under a user?

**Comment by rrbruin** [comment]
No, it completely runs inside the Azure environment. So, I don’t think there is even a register to access. 

I will try to run the runbook tough an Azure HybridWorker. In this case, it will run on a Windows VM using a service account.

This will add extra step which I rather avoid. But if that’s the only way to get it working, I have no choice. Or I should look for another SSH solution

I will let you know.

**Comment by darkoperator** [comment]
Ok, I do know the dev branch of version 2.0 does not have this restriction but 2.0 is not ready yet and it will introduce braking changes, that is why it will be a major number release

**Comment by darkoperator** [comment]
Under what context does Azure Automation run under? Never used Azure so I have little knowledge on it.

**Comment by rrbruin** [comment]
I think it will run under some kind of SYSTEM account.
It does work when I use the Azure HybridWorker option.
For now I can use this as an option.

**Comment by rbyrnedugan** [comment]
I am running into this issue as well.  Do you have any information on when version 2.0 will be released?

**Comment by Flodu31** [comment]
Hello,
I've the same problem on my Azure Automation account, with the -Force parameter, any idea? Thanks

**Comment by rbyrnedugan** [comment]
The only workaround I found was to use the Azure HybridWorker option as @rrbruin mentioned

**Comment by darkoperator** [comment]
Version 2 was released are you using the latest version?

**Comment by Flodu31** [comment]
Yes I downloaded it this afternoon.

 

Florent

**Comment by darkoperator** [comment]
The to be honest dont know what I could else do. I’m no longer checking the resgitry or trying to open it. Since I do not have Azure access there is no way for me to test to see what else it could be. Does it at least give you a specific error?

**Comment by Flodu31** [comment]
No, I've exactly the same. I'll try another module to see if the problem is the same and will keep you updated.

**Comment by Flodu31** [comment]
I'll use the workaround of @rbyrnedugan because I can't find a solution to this problem.
