### ISSUE TITLE
Get-SSHSession -SessionID 0 returns all sessions

### ISSUE THREAD

**Issue by dbason** [darkoperator/Posh-SSH#84]
Currently running version 1.7.3.  Get-SSHSession with SessionID of 0 returns all sessions.  SessionID > 0 works as expected.

**Comment by dbason** [comment]
After more testing the issue has stopped occurring.  I'm not sure what triggered it but it occurred after I had created multiple streams then use new-sshshellstream.

**Comment by darkoperator** [comment]
have not  been able to replicate. Closing the issue for now if it happens again please feel free to open it
