### ISSUE TITLE
connecting on non standard ports

### ISSUE THREAD

**Issue by senposage** [darkoperator/Posh-SSH#86]
doesn't seem to support  connecting on different ports 
e.g I enter 192.168.1.1:331 and it  returns New-SSHSession : No such host is known

**Comment by darkoperator** [comment]
It has a port option, you dont specify it in the conputername option

**Comment by senposage** [comment]
which would be where because its not mentioned in the docs

**Comment by darkoperator** [comment]
It should be in the get-help new-sshsession -full documentation 

Did you ran get-help against the cmdlet and looked at the parameter information?

**Comment by darkoperator** [comment]
I do see it in the documentation if the cmdlet it self 
<pre>
PS C:\Users\Carlos Perez> help New-SSHSession -Parameter port

-Port [<Int32>]
    SSH TCP Port number to use for the SSH connection.

    Required?                    false
    Position?                    named
    Default value
    Accept pipeline input?       True (ByPropertyName)
    Accept wildcard characters?  false





PS C:\Users\Carlos Perez> help New-SSHSession

NAME
    New-SSHSession

SYNOPSIS
    Creates an SSH Session against a SSH Server


SYNTAX
    New-SSHSession [-ComputerName] <String[]> [-Credential] <PSCredential> [-Port [<Int32>]]
    [-ProxyServer [<String>]] [-ProxyPort [<Int32>]] [-ProxyCredential [<PSCredential>]]
    [-ProxyType [<String>]] [-ConnectionTimeOut [<Int32>]] [-KeepAliveInterval [<Int32>]]
    [-AcceptKey [<Boolean>]] [<CommonParameters>]

    New-SSHSession [-ComputerName] <String[]> [-Credential] <PSCredential> [-Port [<Int32>]]
    [-ProxyServer [<String>]] [-ProxyPort [<Int32>]] [-ProxyCredential [<PSCredential>]]
    [-ProxyType [<String>]] [-KeyFile [<String>]] [-ConnectionTimeOut [<Int32>]]
    [-KeepAliveInterval [<Int32>]] [-AcceptKey [<Boolean>]] [<CommonParameters>]


DESCRIPTION
    Creates an SSH Session against a remote server. The command supports creating connection
    thru a Proxy and allows for
    authentication to the server using username and password. If a key file is specified the
    command will use the password
    in the credentials parameter as the paraphrase of the key.


RELATED LINKS

REMARKS
    To see the examples, type: "get-help New-SSHSession -examples".
    For more information, type: "get-help New-SSHSession -detailed".
    For technical information, type: "get-help New-SSHSession -full".
</pre>
