### ISSUE TITLE
Shell Stream usage

### ISSUE THREAD

**Issue by urlocalguru** [darkoperator/Posh-SSH#87]
Its not an issue per se.. but a lack of finding documentation.

I am using the Shell Streams to do some advanced logic and one of the more annoying things is getting a command in before the session can use it.

This is resolved wonderfully with the "Invoke-SSHStreamExpectAction" for one off things like password prompts.

The use I need is for the SSHStream to tell me when its done processing something.  Simple example would be "apt-get update".   I have written a function that does this to some extent by reading the stream looking for some value that signals the processing is done.

I recently noticed a few intriguing members of the New-SSHShellStream object
BeginExpect  & EndExpect
BeginRead  & EndRead
BeginWrite  & EndWrite

I cant tell how they are used based on the $ShellStreamObject | Get-Member

can anyone enlighten me on the use of these members?

Also curious if there are any other forms of communication to find out information.  Gitter, forum, or IRC channel that is frequented by DarkOP or others

**Comment by darkoperator** [comment]
The only additional way to figure those out would be to read the library documentation from the library I use https://sshnet.codeplex.com sadly the project has been abandoned and Im waiting for the version from the PS Team at MS that will have the .Net wrapper to migrate to that.

**Comment by darkoperator** [comment]
A CHM with API docs can be downloaded from here https://sshnet.codeplex.com/releases/view/120565
