### ISSUE TITLE
Bug with New-SSHSession after Remove-SSHSession

### ISSUE THREAD

**Issue by BornToBeRoot** [darkoperator/Posh-SSH#88]
Hello,

by creating SSH Sessions the Session ID Starts to count by 0.  

When i create 3 Session for the first time. Get-SSHSession looks like:

SessionId  Host                                                                Connected
---------  ----                                                                ---------
    0      TEST-01                                                           True
    1      TEST-02                                                           True
    2      TEST-03                                                           True

After Removing the first two Session. Get-SSHSession look like:

SessionId  Host                                                                Connected
---------  ----                                                                ---------
    2      TEST-03                                                           True

When i create new SSHSession the Session ID starts counting by 1 (not 0)

When the SessionID is in use (like SessionID 2, it still create a new Session with the SessionsID 2)

SessionId  Host                                                                Connected
---------  ----                                                                ---------
    1      TEST-01                                                           True
    2      TEST-02                                                           True
    2      TEST-03                                                           True

Is this a bug? Or did i something wrong? 

To create a new session i use this snipped:

$created_SSH_Session = New-SSHSession -ComputerName $ComputerName -Credential $Credentials -AcceptKey
    $SSH_Session = Get-SSHSession -Index $created_SSH_Session.SessionID
    $SSH_Stream = $SSH_Session.Session.CreateShellStream("dumb", 0, 0, 0, 0, 1000)

**Comment by darkoperator** [comment]
it is a bug, I will look at how to fix the logic

**Comment by BornToBeRoot** [comment]
I found the bug and fixed.

@darkoperator can you please have a look at https://github.com/darkoperator/Posh-SSH/pull/89
