### ISSUE TITLE
New-SSHSession Credential passing failure

### ISSUE THREAD

**Issue by alfa164ls** [darkoperator/Posh-SSH#90]
I am getting the error:-
 New-SSHSession : Sequence contains more than one element
when trying to pass in a credential to a New-SSHSession

I can create a new session if I use the cmdlet without specifying a -Credential parameter.

```
$cred   = Get-Credential -username Oracle -Message "Oracle password for server"
$sess  = New-SSHSession -ComputerName $server -Credential $cred -AcceptKey -Verbose
VERBOSE: Using SSH Username and Password authentication for connection.
VERBOSE: Fingerprint for<server.dc.dc.com>: aa:bb:cc:dd:ee:ff:00:10:ad:dd:94:4d:56:d8:b4:41
VERBOSE: Fingerprint matched trusted fingerprint for host <server.dc.dc.com>
New-SSHSession : Sequence contains more than one element
At line:1 char:14
+ ... sess   = New-SSHSession -ComputerName $server -Credential $cre ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SSHSession], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,SSH.NewSshSession
```

I have tried various options, but keep getting the same error message.

What am I doing wrong?
Thanks

**Comment by karezza** [comment]
upvote, getting the same issue but intermittently

**Comment by karezza** [comment]
In my case the problem was the wrong username/password combination.  Kind of a confusing error message.

**Comment by darkoperator** [comment]
Weird in my test with a bad password, none existent user, none permitted user all gave me permission denied and the method of auth in the error
PS C:\Users\Carlos Perez\Documents\ADAudit> New-SSHSession 192.168.1.164 (Get-Credential carlos)
New-SSHSession : Permission denied (password).
At line:1 char:1
+ New-SSHSession 192.168.1.164 (Get-Credential carlos)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SSHSession], SshAuthenticationException
    + FullyQualifiedErrorId : Renci.SshNet.Common.SshAuthenticationException,SSH.NewSshSession

PS C:\Users\Carlos Perez\Documents\ADAudit> New-SSHSession 192.168.1.164 (Get-Credential carlo)
New-SSHSession : Permission denied (password).
At line:1 char:1
+ New-SSHSession 192.168.1.164 (Get-Credential carlo)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SSHSession], SshAuthenticationException
    + FullyQualifiedErrorId : Renci.SshNet.Common.SshAuthenticationException,SSH.NewSshSession

PS C:\Users\Carlos Perez\Documents\ADAudit> New-SSHSession 192.168.1.164 (Get-Credential root)
New-SSHSession : Permission denied (password).
At line:1 char:1
+ New-SSHSession 192.168.1.164 (Get-Credential root)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SSHSession], SshAuthenticationException
    + FullyQualifiedErrorId : Renci.SshNet.Common.SshAuthenticationException,SSH.NewSshSession

**Comment by darkoperator** [comment]
against what OS and type of SSH server is this?

**Comment by darkoperator** [comment]
Closing issue since no reply has been received. Please re-open if still having the issue
