### ISSUE TITLE
Cannot Import Posh-SSH outside of the default module path

### ISSUE THREAD

**Issue by dzeleski** [darkoperator/Posh-SSH#91]
When trying to move Posh-SSH to another folder and then try to import it, it fails. This is a fairly major issue for scripts/workflows that need to run without a profile or to be easily shared between systems or users. 
```

Import-Module .\Posh-SSH.psm1

Multiple ambiguous overloads found for ".ctor" and the argument count: "1".
At C:\Users\dzeleski\Downloads\Posh-SSH-master\Posh-SSH-master\Sftp.ps1:581 char:5
+     [OutputType([Renci.SshNet.Sftp.SftpFileAttributes])]
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Multiple ambiguous overloads found for ".ctor" and the argument count: "1".
At C:\Users\dzeleski\Downloads\Posh-SSH-master\Posh-SSH-master\Sftp.ps1:893 char:5
+     [OutputType([Renci.SshNet.Sftp.SftpFile])]
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Multiple ambiguous overloads found for ".ctor" and the argument count: "1".
At C:\Users\dzeleski\Downloads\Posh-SSH-master\Posh-SSH-master\Sftp.ps1:1051 char:5
+     [OutputType([Renci.SshNet.Sftp.SftpFileStream])]
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Multiple ambiguous overloads found for ".ctor" and the argument count: "1".
At C:\Users\dzeleski\Downloads\Posh-SSH-master\Posh-SSH-master\Posh-SSH.psm1:581 char:5
+     [OutputType([Renci.SshNet.ShellStream])]
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest


```

**Comment by darkoperator** [comment]
because you import the manifest for a module with cmdlets, assemblies and function ;) you are importing the wrong file
```
 Import-Module .\Posh-SSH.psd1 -Verbose
VERBOSE: Loading module from path 'C:\Users\Carlos
Perez\Documents\WindowsPowerShell\Modules\Posh-SSH\Posh-SSH.psd1'.
VERBOSE: Loading 'Assembly' from path 'C:\Users\Carlos
Perez\Documents\WindowsPowerShell\Modules\Posh-SSH\Assembly\Renci.SshNet.dll'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Users\Carlos
Perez\Documents\WindowsPowerShell\Modules\Posh-SSH\Format\SSHSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Users\Carlos
Perez\Documents\WindowsPowerShell\Modules\Posh-SSH\Format\SFTPSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Users\Carlos
Perez\Documents\WindowsPowerShell\Modules\Posh-SSH\Format\Renci.SshNet.SshCommand.Format.ps1xml'
.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Users\Carlos
Perez\Documents\WindowsPowerShell\Modules\Posh-SSH\Format\Renci.SshNet.Sftp.SftpFile.Format.ps1x
ml'.
VERBOSE: Loading module from path 'C:\Users\Carlos
Perez\Documents\WindowsPowerShell\Modules\Posh-SSH\PoshSSH.dll'.
VERBOSE: Importing cmdlet 'Get-SCPFile'.
VERBOSE: Importing cmdlet 'Get-SCPFolder'.
VERBOSE: Importing cmdlet 'Get-SFTPFile'.
VERBOSE: Importing cmdlet 'Set-SFTPFile'.
VERBOSE: Importing cmdlet 'New-SFTPSession'.
VERBOSE: Importing cmdlet 'New-SSHSession'.
VERBOSE: Importing cmdlet 'Set-SCPFile'.
VERBOSE: Importing cmdlet 'Set-SCPFolder'.
VERBOSE: Loading module from path 'C:\Users\Carlos
Perez\Documents\WindowsPowerShell\Modules\Posh-SSH\Posh-SSH.psm1'.
VERBOSE: Exporting function 'Get-SSHTrustedHost'.
VERBOSE: Exporting function 'New-SSHTrustedHost'.
VERBOSE: Exporting function 'Remove-SSHTrustedHost'.
VERBOSE: Exporting function 'Get-SFTPSession'.
VERBOSE: Exporting function 'Remove-SFTPSession'.
VERBOSE: Exporting function 'Get-SFTPChildItem'.
VERBOSE: Exporting function 'Test-SFTPPath'.
VERBOSE: Exporting function 'Remove-SFTPItem'.
VERBOSE: Exporting function 'Set-SFTPLocation'.
VERBOSE: Exporting function 'Get-SFTPLocation'.
VERBOSE: Exporting function 'Rename-SFTPFile'.
VERBOSE: Exporting function 'Get-SFTPPathAttribute'.
VERBOSE: Exporting function 'New-SFTPSymlink'.
VERBOSE: Exporting function 'Get-SFTPContent'.
VERBOSE: Exporting function 'Set-SFTPContent'.
VERBOSE: Exporting function 'New-SFTPFileStream'.
VERBOSE: Exporting function 'New-SFTPItem'.
VERBOSE: Exporting function 'New-SFTPDirectory'.
VERBOSE: Exporting function 'Get-SFTPDirectoryList'.
VERBOSE: Exporting function 'Remove-SFTPDirectory'.
VERBOSE: Exporting function 'Set-SFTPCurrentDirectory'.
VERBOSE: Exporting function 'Get-SFTPCurrentDirectory'.
VERBOSE: Exporting function 'Remove-SFTPFile'.
VERBOSE: Exporting function 'Get-SSHSession'.
VERBOSE: Exporting function 'Remove-SSHSession'.
VERBOSE: Exporting function 'Invoke-SSHCommand'.
VERBOSE: Exporting function 'Get-PoshSSHModVersion'.
VERBOSE: Exporting function 'Invoke-SSHCommandStream'.
VERBOSE: Exporting function 'New-SSHShellStream'.
VERBOSE: Exporting function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Exporting function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Importing function 'Get-PoshSSHModVersion'.
VERBOSE: Importing function 'Get-SFTPChildItem'.
VERBOSE: Importing function 'Get-SFTPContent'.
VERBOSE: Importing function 'Get-SFTPCurrentDirectory'.
VERBOSE: Importing function 'Get-SFTPDirectoryList'.
VERBOSE: Importing function 'Get-SFTPLocation'.
VERBOSE: Importing function 'Get-SFTPPathAttribute'.
VERBOSE: Importing function 'Get-SFTPSession'.
VERBOSE: Importing function 'Get-SSHSession'.
VERBOSE: Importing function 'Get-SSHTrustedHost'.
VERBOSE: Importing function 'Invoke-SSHCommand'.
VERBOSE: Importing function 'Invoke-SSHCommandStream'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Importing function 'New-SFTPDirectory'.
VERBOSE: Importing function 'New-SFTPFileStream'.
VERBOSE: Importing function 'New-SFTPItem'.
VERBOSE: Importing function 'New-SFTPSymlink'.
VERBOSE: Importing function 'New-SSHShellStream'.
VERBOSE: Importing function 'New-SSHTrustedHost'.
VERBOSE: Importing function 'Remove-SFTPDirectory'.
VERBOSE: Importing function 'Remove-SFTPFile'.
VERBOSE: Importing function 'Remove-SFTPItem'.
VERBOSE: Importing function 'Remove-SFTPSession'.
VERBOSE: Importing function 'Remove-SSHSession'.
VERBOSE: Importing function 'Remove-SSHTrustedHost'.
VERBOSE: Importing function 'Rename-SFTPFile'.
VERBOSE: Importing function 'Set-SFTPContent'.
VERBOSE: Importing function 'Set-SFTPCurrentDirectory'.
```

**Comment by dzeleski** [comment]
Ah crap, I had the module imported already via my profile and when my function that adds our modules ran it bombed out. You are correct though, in my rush to get this up I missed that. The code used to import modules dynamically is below, note that I am on windows 10 PS 5.0. 

After removing the module from my profile it now imports correctly. Thanks!

```
foreach ($psModule in $modulesPath.Name) {
    if (-not(Get-Module -Name $psModule)) {
        if (Get-Module -ListAvailable -Name $psModule) {
            Write-Debug "Importing Module: $psModule"
            Write-Progress -Activity "Importing Module: $psModule" -percentcomplete 5
            Import-Module -Name $psModule -DisableNameChecking        
        }
    }
}
```

**Comment by steve-bg** [comment]
I saw several solutions on the net about not being able to import but none seems to work for me.

 Import-Module Posh-SSH -Verbose
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Posh-SSH.psd1'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\posh-ssh\3.0.0\Assembly\Newtonsoft.Json.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\posh-ssh\3.0.0\Assembly\Newtonsoft.Json.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\posh-ssh\3.0.0\Assembly\Renci.SshNet.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\posh-ssh\3.0.0\Assembly\Renci.SshNet.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\posh-ssh\3.0.0\Assembly\SshNet.Security.Cryptography.dll'.
VERBOSE: Loading 'Assembly' from path 'C:\Program Files\WindowsPowerShell\Modules\posh-ssh\3.0.0\Assembly\SshNet.Security.Cryptography.dll'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Format\SSHSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Format\SFTPSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Format\Renci.SshNet.SshCommand.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\Format\Renci.SshNet.Sftp.SftpFile.Format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module Posh-SSH.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\PoshSSH.dll'.
Import-Module : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
The system cannot find the file specified.
At line:1 char:1
+ Import-Module Posh-SSH -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand


===================================================================

Which file is missing and why? This is Windows server 2016, regularly patched.  The dll is there:

> dir 'C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0\PoshSSH.dll'


    Directory: C:\Program Files\WindowsPowerShell\Modules\Posh-SSH\3.0.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       2021-08-08   3:46 PM          43520 PoshSSH.dll

==============================================

Thank you!

**Comment by darkoperator** [comment]
Are you running PowerShell 7? It ia compiled for 5.1 or 7.x

**Comment by MVKozlov** [comment]
https://github.com/darkoperator/Posh-SSH/issues/437#issuecomment-1012539193
one more time ?

**Comment by steve-bg** [comment]
No, I am running 5:

PS C:\PSscripts> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.14393.4583
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.4583
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by steve-bg** [comment]
Since then I found a workaround by installing the module to another machine, however the problem remains unsolved on the first one. Currently it is not a problem for me. I am willing to troubleshoot for the benefit of other readers if provided with instructions.
Thank you.

**Comment by darkoperator** [comment]
Did you install the .Net version that Max linked the issue ?

**Comment by steve-bg** [comment]
No, sorry, I did not understand there was a link in his very short note. Will try soon. Thanks.
