### ISSUE TITLE
New-SSHSession : Sequence contains more than one element

### ISSUE THREAD

**Issue by karezza** [darkoperator/Posh-SSH#92]
Intermittent error thrown with unknown cause.  Verified ComputerName is a [string] and not an array of strings.  Verified $Credential is a System.Management.Automation.PSCredential and not an array of System.Management.Automation.PSCredential.  Able to reproduce error (sometimes) outside of script.

Unable to troubleshoot further.  Need to understand origin of error, or bug to be fixed.
___
PS Z:\Test> New-SSHSession -ComputerName $Target -Credential $Credential -Verbose
VERBOSE: Using SSH Username and Password authentication for connection.
VERBOSE: Fingerprint for testSystem: 00:11:22:33:44:55:.....:99
VERBOSE: Fingerprint matched trusted fingerprint for host testSystem
New-SSHSession : Sequence contains more than one element
At line:1 char:1
+ New-SSHSession -ComputerName $Target -Credential $Credential -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SSHSession], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,SSH.NewSshSession

**Comment by darkoperator** [comment]
Do you have multiple hosts with the same SSH server key? Probably a bad master image in a VM template that does not generate a new server key or an aggressive DHCP where the IP/key pair changes

**Comment by karezza** [comment]
The test system name and fingerprint here is obfuscated, the systems should all have unique keys.  I will check to be sure.

**Comment by karezza** [comment]
Embarrassingly, I think I may have just figured this out after working on it for a week.  The hostname was resolving to a different hostname with a different username / password.  Hopefully, this explains the problem in its entirety.  I'll post again if the problem reoccurs.  For now, I will say a more useful error message would have helped to troubleshoot this.  Hopefully issue posting will help the next person who encounters it.

**Comment by NelsonRothermel** [comment]
I was getting the same error with the correct server, username and password.  I tried another SSH client and got "Access Denied".  It turns out the account was locked out.  It was a valid error condition, but the error message is not very helpful and made me think I had a problem with my script.
