### ISSUE TITLE
New-SFTPItem Cannot Recursively Create Subdirectories

### ISSUE THREAD

**Issue by MrAusnadian** [darkoperator/Posh-SSH#93]
To create subdirectories like:
/test/1/2/3

I have to do:
New-SFTPItem -SessionId $session -Path /test -ItemType Directory
New-SFTPItem -SessionId $session -Path /test/1 -ItemType Directory
New-SFTPItem -SessionId $session -Path /test/1/2 -ItemType Directory
New-SFTPItem -SessionId $session -Path /test/1/2/3 -ItemType Directory

It would be great if I could do something like:

New-SFTPItem -SessionId $session -Path /test/1/2/3 -ItemType Directory -Recurse

**Comment by darkoperator** [comment]
Yep this should be addressed. I will look in to it when I get a chance to set some time to work on bug fixes and features.

**Comment by darkoperator** [comment]
Added the option in branch 1_7_5  code, once it is merged to master and released in to the gallery will let you know.

**Comment by darkoperator** [comment]
Uploaded 1.7.5 to the gallery

**Comment by MrAusnadian** [comment]
Thanks so much for this. Greatly appreciated! :+1:
