### ISSUE TITLE
New-SFTPItem Errors

### ISSUE THREAD

**Issue by TheSleepwalker** [darkoperator/Posh-SSH#94]
After creating an SFTP session, I'm trying to create a directory on the SFTP server.  I have confirmed that the user account I am using has full rights and that there is plenty of free space on the disk.  However, each time I try to create the directory I receive the error below.  Any ideas on what I'm doing wrong?

PS C:\Users\testuser> New-SFTPItem -SessionId 0 -Path /test -ItemType Directory -Verbose
VERBOSE: Creating directory /test
Exception calling "CreateDirectory" with "1" argument(s): "There is not enough space on the disk. "
At C:\Users\testuser\Documents\WindowsPowerShell\Modules\posh-ssh\Sftp.ps1:1236 char:25
+                         $sess.Session.CreateDirectory($Path)
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SshException

VERBOSE: Directory succesfully created.
Exception calling "Get" with "1" argument(s): "The requested file does not exist"
At C:\Users\testuser\Documents\WindowsPowerShell\Modules\posh-ssh\Sftp.ps1:1238 char:25
+                         $sess.Session.Get($Path)
+                         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SftpPathNotFoundException

PS C:\Users\testuser>

**Comment by darkoperator** [comment]
Are you logged in as root? Full path of /test is in the root file system, ./test would be in the current path of the session

**Comment by TheSleepwalker** [comment]
I'm logged in as a domain admin but I'm passing credentials native to the SFTP server. 

Both the client and SFTP server are Windows.

**Comment by darkoperator** [comment]
Never tested SSH on Windows but of it behaves like on unix systems / is the root of the filesystem. If the Windows SSH server you are using free so I can try to replicate?

**Comment by TheSleepwalker** [comment]
Cerberus FTP

They have a free trial and I believe it's free for personal use.

**Comment by darkoperator** [comment]
Ca you confirm your user has the permission to create directory

**Comment by TheSleepwalker** [comment]
I'll double-check and get back with you.

**Comment by darkoperator** [comment]
any update?

**Comment by darkoperator** [comment]
Uploaded 1.7.5 to the gallery, closing for now you can reopen if needed.
