### ISSUE TITLE
Missing New-SSHSession

### ISSUE THREAD

**Issue by uberbigun** [darkoperator/Posh-SSH#95]
The module installed with no errors, but no new-sshsession

PS C:\Users\scarpenter2> import-module Posh-SSH -verbose
VERBOSE: Importing function 'Get-PoshSSHModVersion'.
VERBOSE: Importing function 'Get-SFTPChildItem'.
VERBOSE: Importing function 'Get-SFTPContent'.
VERBOSE: Importing function 'Get-SFTPCurrentDirectory'.
VERBOSE: Importing function 'Get-SFTPDirectoryList'.
VERBOSE: Importing function 'Get-SFTPLocation'.
VERBOSE: Importing function 'Get-SFTPPathAttribute'.
VERBOSE: Importing function 'Get-SFTPSession'.
VERBOSE: Importing function 'Get-SSHSession'.
VERBOSE: Importing function 'Get-SSHTrustedHost'.
VERBOSE: Importing function 'Invoke-SSHCommand'.
VERBOSE: Importing function 'Invoke-SSHCommandStream'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Importing function 'New-SFTPDirectory'.
VERBOSE: Importing function 'New-SFTPFileStream'.
VERBOSE: Importing function 'New-SFTPItem'.
VERBOSE: Importing function 'New-SFTPSymlink'.
VERBOSE: Importing function 'New-SSHShellStream'.
VERBOSE: Importing function 'New-SSHTrustedHost'.
VERBOSE: Importing function 'Remove-SFTPDirectory'.
VERBOSE: Importing function 'Remove-SFTPFile'.
VERBOSE: Importing function 'Remove-SFTPItem'.
VERBOSE: Importing function 'Remove-SFTPSession'.
VERBOSE: Importing function 'Remove-SSHSession'.
VERBOSE: Importing function 'Remove-SSHTrustedHost'.
VERBOSE: Importing function 'Rename-SFTPFile'.
VERBOSE: Importing function 'Set-SFTPContent'.
VERBOSE: Importing function 'Set-SFTPCurrentDirectory'.
VERBOSE: Importing function 'Set-SFTPLocation'.
VERBOSE: Importing function 'Test-SFTPPath'.

**Comment by darkoperator** [comment]
Looks as if it did not load the main module DLL did you installed from the PowerShell gallery or manually?

**Comment by darkoperator** [comment]
Also what version of PS

**Comment by uberbigun** [comment]
Install method:
 iex (New-Object Net.WebClient).DownloadString("https://gist.github.com/darkoperator/6152630/raw/c67de4f7cd780ba367cccbc2593f38d18ce6df89/instposhsshdev")


$PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  0


I also tried to do a manual install after the download method failed

**Comment by uberbigun** [comment]
PS C:\Users\scarpenter2> remove-module posh-ssh
PS C:\Users\scarpenter2> import-module Posh-SSH -verbose
VERBOSE: Loading module from path 'C:\Users\scarpenter2\Documents\WindowsPowerShell\Modules\Posh-SSH\Posh-SSH.psd1'.
VERBOSE: Loading 'Assembly' from path
'C:\Users\scarpenter2\Documents\WindowsPowerShell\Modules\Posh-SSH\Assembly\Renci.SshNet.dll'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\Users\scarpenter2\Documents\WindowsPowerShell\Modules\Posh-SSH\Format\SSHSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\Users\scarpenter2\Documents\WindowsPowerShell\Modules\Posh-SSH\Format\SFTPSession.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\Users\scarpenter2\Documents\WindowsPowerShell\Modules\Posh-SSH\Format\Renci.SshNet.SshCommand.Format.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path
'C:\Users\scarpenter2\Documents\WindowsPowerShell\Modules\Posh-SSH\Format\Renci.SshNet.Sftp.SftpFile.Format.ps1xml'.
VERBOSE: Loading module from path 'C:\Users\scarpenter2\Documents\WindowsPowerShell\Modules\Posh-SSH\PoshSSH.dll'.
VERBOSE: Loading module from path 'C:\Users\scarpenter2\Documents\WindowsPowerShell\Modules\Posh-SSH\Posh-SSH.psm1'.
VERBOSE: Exporting function 'Get-SSHTrustedHost'.
VERBOSE: Exporting function 'New-SSHTrustedHost'.
VERBOSE: Exporting function 'Remove-SSHTrustedHost'.
VERBOSE: Exporting function 'Get-SFTPSession'.
VERBOSE: Exporting function 'Remove-SFTPSession'.
VERBOSE: Exporting function 'Get-SFTPChildItem'.
VERBOSE: Exporting function 'Test-SFTPPath'.
VERBOSE: Exporting function 'Remove-SFTPItem'.
VERBOSE: Exporting function 'Set-SFTPLocation'.
VERBOSE: Exporting function 'Get-SFTPLocation'.
VERBOSE: Exporting function 'Rename-SFTPFile'.
VERBOSE: Exporting function 'Get-SFTPPathAttribute'.
VERBOSE: Exporting function 'New-SFTPSymlink'.
VERBOSE: Exporting function 'Get-SFTPContent'.
VERBOSE: Exporting function 'Set-SFTPContent'.
VERBOSE: Exporting function 'New-SFTPFileStream'.
VERBOSE: Exporting function 'New-SFTPItem'.
VERBOSE: Exporting function 'New-SFTPDirectory'.
VERBOSE: Exporting function 'Get-SFTPDirectoryList'.
VERBOSE: Exporting function 'Remove-SFTPDirectory'.
VERBOSE: Exporting function 'Set-SFTPCurrentDirectory'.
VERBOSE: Exporting function 'Get-SFTPCurrentDirectory'.
VERBOSE: Exporting function 'Remove-SFTPFile'.
VERBOSE: Exporting function 'Get-SSHSession'.
VERBOSE: Exporting function 'Remove-SSHSession'.
VERBOSE: Exporting function 'Invoke-SSHCommand'.
VERBOSE: Exporting function 'Get-PoshSSHModVersion'.
VERBOSE: Exporting function 'Invoke-SSHCommandStream'.
VERBOSE: Exporting function 'New-SSHShellStream'.
VERBOSE: Exporting function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Exporting function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Importing function 'Get-PoshSSHModVersion'.
VERBOSE: Importing function 'Get-SFTPChildItem'.
VERBOSE: Importing function 'Get-SFTPContent'.
VERBOSE: Importing function 'Get-SFTPCurrentDirectory'.
VERBOSE: Importing function 'Get-SFTPDirectoryList'.
VERBOSE: Importing function 'Get-SFTPLocation'.
VERBOSE: Importing function 'Get-SFTPPathAttribute'.
VERBOSE: Importing function 'Get-SFTPSession'.
VERBOSE: Importing function 'Get-SSHSession'.
VERBOSE: Importing function 'Get-SSHTrustedHost'.
VERBOSE: Importing function 'Invoke-SSHCommand'.
VERBOSE: Importing function 'Invoke-SSHCommandStream'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Importing function 'New-SFTPDirectory'.
VERBOSE: Importing function 'New-SFTPFileStream'.
VERBOSE: Importing function 'New-SFTPItem'.
VERBOSE: Importing function 'New-SFTPSymlink'.
VERBOSE: Importing function 'New-SSHShellStream'.
VERBOSE: Importing function 'New-SSHTrustedHost'.
VERBOSE: Importing function 'Remove-SFTPDirectory'.
VERBOSE: Importing function 'Remove-SFTPFile'.
VERBOSE: Importing function 'Remove-SFTPItem'.
VERBOSE: Importing function 'Remove-SFTPSession'.
VERBOSE: Importing function 'Remove-SSHSession'.
VERBOSE: Importing function 'Remove-SSHTrustedHost'.
VERBOSE: Importing function 'Rename-SFTPFile'.
VERBOSE: Importing function 'Set-SFTPContent'.
VERBOSE: Importing function 'Set-SFTPCurrentDirectory'.
VERBOSE: Importing function 'Set-SFTPLocation'.
VERBOSE: Importing function 'Test-SFTPPath'.
VERBOSE: Exporting function 'Get-PoshSSHModVersion'.
VERBOSE: Exporting function 'Get-SFTPChildItem'.
VERBOSE: Exporting function 'Get-SFTPContent'.
VERBOSE: Exporting function 'Get-SFTPCurrentDirectory'.
VERBOSE: Exporting function 'Get-SFTPDirectoryList'.
VERBOSE: Exporting function 'Get-SFTPLocation'.
VERBOSE: Exporting function 'Get-SFTPPathAttribute'.
VERBOSE: Exporting function 'Get-SFTPSession'.
VERBOSE: Exporting function 'Get-SSHSession'.
VERBOSE: Exporting function 'Get-SSHTrustedHost'.
VERBOSE: Exporting function 'Invoke-SSHCommand'.
VERBOSE: Exporting function 'Invoke-SSHCommandStream'.
VERBOSE: Exporting function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Exporting function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Exporting function 'New-SFTPDirectory'.
VERBOSE: Exporting function 'New-SFTPFileStream'.
VERBOSE: Exporting function 'New-SFTPItem'.
VERBOSE: Exporting function 'New-SFTPSymlink'.
VERBOSE: Exporting function 'New-SSHShellStream'.
VERBOSE: Exporting function 'New-SSHTrustedHost'.
VERBOSE: Exporting function 'Remove-SFTPDirectory'.
VERBOSE: Exporting function 'Remove-SFTPFile'.
VERBOSE: Exporting function 'Remove-SFTPItem'.
VERBOSE: Exporting function 'Remove-SFTPSession'.
VERBOSE: Exporting function 'Remove-SSHSession'.
VERBOSE: Exporting function 'Remove-SSHTrustedHost'.
VERBOSE: Exporting function 'Rename-SFTPFile'.
VERBOSE: Exporting function 'Set-SFTPContent'.
VERBOSE: Exporting function 'Set-SFTPCurrentDirectory'.
VERBOSE: Exporting function 'Set-SFTPLocation'.
VERBOSE: Exporting function 'Test-SFTPPath'.
VERBOSE: Importing function 'Get-PoshSSHModVersion'.
VERBOSE: Importing function 'Get-SFTPChildItem'.
VERBOSE: Importing function 'Get-SFTPContent'.
VERBOSE: Importing function 'Get-SFTPCurrentDirectory'.
VERBOSE: Importing function 'Get-SFTPDirectoryList'.
VERBOSE: Importing function 'Get-SFTPLocation'.
VERBOSE: Importing function 'Get-SFTPPathAttribute'.
VERBOSE: Importing function 'Get-SFTPSession'.
VERBOSE: Importing function 'Get-SSHSession'.
VERBOSE: Importing function 'Get-SSHTrustedHost'.
VERBOSE: Importing function 'Invoke-SSHCommand'.
VERBOSE: Importing function 'Invoke-SSHCommandStream'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectAction'.
VERBOSE: Importing function 'Invoke-SSHStreamExpectSecureAction'.
VERBOSE: Importing function 'New-SFTPDirectory'.
VERBOSE: Importing function 'New-SFTPFileStream'.
VERBOSE: Importing function 'New-SFTPItem'.
VERBOSE: Importing function 'New-SFTPSymlink'.
VERBOSE: Importing function 'New-SSHShellStream'.
VERBOSE: Importing function 'New-SSHTrustedHost'.
VERBOSE: Importing function 'Remove-SFTPDirectory'.
VERBOSE: Importing function 'Remove-SFTPFile'.
VERBOSE: Importing function 'Remove-SFTPItem'.
VERBOSE: Importing function 'Remove-SFTPSession'.
VERBOSE: Importing function 'Remove-SSHSession'.
VERBOSE: Importing function 'Remove-SSHTrustedHost'.
VERBOSE: Importing function 'Rename-SFTPFile'.
VERBOSE: Importing function 'Set-SFTPContent'.
VERBOSE: Importing function 'Set-SFTPCurrentDirectory'.
VERBOSE: Importing function 'Set-SFTPLocation'.
VERBOSE: Importing function 'Test-SFTPPath'.
PS C:\Users\scarpenter2> Get-SSHSession
PS C:\Users\scarpenter2> help New-SSHSession
Get-Help : Get-Help could not find New-SSHSession in a help file in this session. To download updated help topics
type: "Update-Help". To get help online, search for the help topic in the TechNet library at
http://go.microsoft.com/fwlink/?LinkID=107116.
At line:55 char:7
+       Get-Help @PSBoundParameters | more
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-Help], HelpNotFoundException
    + FullyQualifiedErrorId : HelpNotFound,Microsoft.PowerShell.Commands.GetHelpCommand

**Comment by darkoperator** [comment]
Can you remove the module folder and try Install-Module Posh-SSH from version 5 so it installs from he gallery., If you still want to use the manual version for people using PSv2 can you check that the DLL is unblocked by navigating to the folder and right click on it and check its properties.

**Comment by uberbigun** [comment]
Same issue
PS C:\WINDOWS\system32>  Install-Module Posh-SSH

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
PS C:\WINDOWS\system32> help New-SSHSession
Get-Help : Get-Help could not find New-SSHSession in a help file in this session. To download updated help topics type: "Update-Help". To get help online, search for the help topic in the TechNet library at http://go.microsoft.com/fwlink/?LinkID=107116.
At line:55 char:7
+       Get-Help @PSBoundParameters | more
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-Help], HelpNotFoundException
    + FullyQualifiedErrorId : HelpNotFound,Microsoft.PowerShell.Commands.GetHelpCommand


PS C:\WINDOWS\system32> help Get-SSHSession

NAME
    Get-SSHSession

SYNOPSIS
    Get current SSH Session that are available for interaction.


SYNTAX
    Get-SSHSession [[-SessionId] [<Int32>]] [<CommonParameters>]


DESCRIPTION
    Get current SSH Session that are available for interaction.


RELATED LINKS
    Online version: http://sshnet.codeplex.com/
    http://www.darkoperator.com/

REMARKS
    To see the examples, type: "get-help Get-SSHSession -examples".
    For more information, type: "get-help Get-SSHSession -detailed".
    For technical information, type: "get-help Get-SSHSession -full".
    For online help, type: "get-help Get-SSHSession -online"




PS C:\WINDOWS\system32>

**Comment by darkoperator** [comment]
This is a new one I have not ever seen before … if you try to do import-module .\PoshSSH.dll -verbose -force in the folder where the module is located does it show anything? no clue as to why it is blocking he dll unless something like app locker is running and blocking unsigned DLLs but that should show an error.

**Comment by uberbigun** [comment]
PS C:\Installs\Posh-SSH\Posh-SSH-master> import-module .\PoshSSH.dll -verbose
VERBOSE: Loading module from path 'C:\Installs\Posh-SSH\Posh-SSH-master\PoshSSH.dll'.
PS C:\Installs\Posh-SSH\Posh-SSH-master> new-sshsession
new-sshsession : The term 'new-sshsession' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ new-sshsession
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (new-sshsession:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by darkoperator** [comment]
To be honest I have no clue as to why the error, of the over 5k downloads a month this is the first time someone has reported this error, if verbose does not shows the cmdlet being imported I have no clue as to why the DLL main module is not exporting the functions. 
on my Windows 7, Windows 8.1 and Windows 10 systems it imports without a problem
PS C:\Users\Carlos Perez\Documents\WindowsPowerShell\Modules\Posh-SSH> Import-Module .\PoshSSH.dll -Verbose
VERBOSE: Loading module from path 'C:\Users\Carlos
Perez\Documents\WindowsPowerShell\Modules\Posh-SSH\PoshSSH.dll'.
VERBOSE: Importing cmdlet 'Get-SCPFile'.
VERBOSE: Importing cmdlet 'Get-SCPFolder'.
VERBOSE: Importing cmdlet 'Get-SFTPFile'.
VERBOSE: Importing cmdlet 'Set-SFTPFile'.
VERBOSE: Importing cmdlet 'New-SFTPSession'.
VERBOSE: Importing cmdlet 'New-SSHSession'.
VERBOSE: Importing cmdlet 'Set-SCPFile'.
VERBOSE: Importing cmdlet 'Set-SCPFolder'.
PS C:\Users\Carlos Perez\Documents\WindowsPowerShell\Modules\Posh-SSH> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.122
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.122
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Are you sure no app locker, device guard or any other policy might be in play here blocking the loading of the library?

**Comment by darkoperator** [comment]
What version of windows is this?

**Comment by uberbigun** [comment]
Windows 10. No App locker. PS Run As Administrator. The really strange thing is that all of the other commandlets are there, just not New-SSHSession

**Comment by darkoperator** [comment]
Well all the ones in the DLL are not, new-SFPSession and the SCP ones that are also in the DLL so I cause event handling for progress, key validation and keyboard interactive auth are not being exported by the DLL. need to research as to why this is not working as it should.

**Comment by uberbigun** [comment]
S C:\WINDOWS\system32> get-command -Module Posh-SSH

ommandType     Name                                               Version    Source
----------     ----                                               -------    ------
unction        Get-PoshSSHModVersion                              1.7.3      Posh-SSH
unction        Get-SFTPChildItem                                  1.7.3      Posh-SSH
unction        Get-SFTPContent                                    1.7.3      Posh-SSH
unction        Get-SFTPCurrentDirectory                           1.7.3      Posh-SSH
unction        Get-SFTPDirectoryList                              1.7.3      Posh-SSH
unction        Get-SFTPLocation                                   1.7.3      Posh-SSH
unction        Get-SFTPPathAttribute                              1.7.3      Posh-SSH
unction        Get-SFTPSession                                    1.7.3      Posh-SSH
unction        Get-SSHSession                                     1.7.3      Posh-SSH
unction        Get-SSHTrustedHost                                 1.7.3      Posh-SSH
unction        Invoke-SSHCommand                                  1.7.3      Posh-SSH
unction        Invoke-SSHCommandStream                            1.7.3      Posh-SSH
unction        Invoke-SSHStreamExpectAction                       1.7.3      Posh-SSH
unction        Invoke-SSHStreamExpectSecureAction                 1.7.3      Posh-SSH
unction        New-SFTPDirectory                                  1.7.3      Posh-SSH
unction        New-SFTPFileStream                                 1.7.3      Posh-SSH
unction        New-SFTPItem                                       1.7.3      Posh-SSH
unction        New-SFTPSymlink                                    1.7.3      Posh-SSH
unction        New-SSHShellStream                                 1.7.3      Posh-SSH
unction        New-SSHTrustedHost                                 1.7.3      Posh-SSH
unction        Remove-SFTPDirectory                               1.7.3      Posh-SSH
unction        Remove-SFTPFile                                    1.7.3      Posh-SSH
unction        Remove-SFTPItem                                    1.7.3      Posh-SSH
unction        Remove-SFTPSession                                 1.7.3      Posh-SSH
unction        Remove-SSHSession                                  1.7.3      Posh-SSH
unction        Remove-SSHTrustedHost                              1.7.3      Posh-SSH
unction        Rename-SFTPFile                                    1.7.3      Posh-SSH
unction        Set-SFTPContent                                    1.7.3      Posh-SSH
unction        Set-SFTPCurrentDirectory                           1.7.3      Posh-SSH
unction        Set-SFTPLocation                                   1.7.3      Posh-SSH
unction        Test-SFTPPath                                      1.7.3      Posh-SSH

**Comment by uberbigun** [comment]
Strange mismatch in version numbers
PS C:\WINDOWS\system32> Get-PoshSSHModVersion
WARNING: You are running an outdated version of the module.

InstalledVersion CurrentVersion
---------------- --------------
1.7.3            1.7.4

**Comment by darkoperator** [comment]
need to update the gallery :)

**Comment by darkoperator** [comment]
Uploaded 1.7.5 to the gallery

**Comment by qitupx** [comment]
Same issue for me, exact same behavior. Running Windows 10 x64. I've also had the same issue with modules that are using DLL files. Works fine for me on Windows 7 and Server 2012 R2

**Comment by qitupx** [comment]
UPDATE: I was able to fix this by recompiling for .net 4.5. It was set to 3.5 before. I have .net 3.5 installed on this machine though. Weird.

**Comment by darkoperator** [comment]
Getting to the point where I will have to drop PSv2 support
