### ISSUE TITLE
Newest version isn't available on PowerShell Gallery

### ISSUE THREAD

**Issue by pcgeek86** [darkoperator/Posh-SSH#96]
# Issue

The newest version of this module isn't available on the PowerShell Gallery.

![image](https://cloud.githubusercontent.com/assets/466713/15080671/894173a4-137c-11e6-9c2e-a194b363b463.png)

# Expected Result

The newest version of the module should be available on the PowerShell Gallery.

Happy to help set up some automation for this, if you're interested!

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by darkoperator** [comment]
It is on purpose, the lasted minor build modified behavior that I know have some users used to and the majority from the gallery that do not, plan to make all other behavior changes in the next update and communicate it all better in that release so everyone is aware of the changes in output, error handling, changes in parameters and removed functions.

**Comment by pcgeek86** [comment]
@darkoperator Sounds good, thanks for the info.
