### ISSUE TITLE
Bug: Set-SFTPFile - Cannot upload large files

### ISSUE THREAD

**Issue by Zuldan** [darkoperator/Posh-SSH#97]
Hi I'm trying to upload large files (25GB) to a VMware ESXi 5.5 U3 host. For some reason they just suddenly stop transferring (usually around 11GB) with no error.

I then used WinSCP Powershell Module (http://dotps1.github.io/WinSCP/) to upload the same 25GB file and it worked perfectly.

**Comment by darkoperator** [comment]
Uploaded 1.7.5 to the gallery can you test with that version and use the param for not showing progress?

**Comment by darkoperator** [comment]
any update?

**Comment by Zuldan** [comment]
@darkoperator it appears to be working now. Thank you for resolving the issue.
