### ISSUE TITLE
Strip off ANSI/VT100 Terminal Control Escape Sequences

### ISSUE THREAD

**Issue by BasvanH** [darkoperator/Posh-SSH#98]
Hi,

I use Posh-SSH to automate backup of switches, firewalls and routers. Works great except for HP procurve switches, I get a lot of bogus characters in the stream:
[24;1H[2K[24;1H[1;24r[24;1H

Those are ANSI/VT100 Terminal Control Escape Sequences. Is it posible to strip off these escape characters in the stream?

Kind Regards,
Bastiaan

**Comment by darkoperator** [comment]
I do not see an option for it in the library.
