### ISSUE TITLE
Feature: New-SSHSession - Allow to use -keyfile  from string/stream, not just filesystem object

### ISSUE THREAD

**Issue by MVKozlov** [darkoperator/Posh-SSH#99]
Subj. It is needed alternative to -keyfile

Now -keyFile can be used only as path to filename with secret key.
Highly need support for selecting string/securestring/stream as key source.
we can store secret key highly encrypted, but for use now we need to save it to disk unencrypted. it is security risk.
I see that SSH.Net have support for PrivateKeyFile(Stream).
I find it more secure....

**Comment by darkoperator** [comment]
well a key is encrypted and protected with a passphrase, it has worked that way in many platforms so I do not agree on the argument of "More Secure" ;) but it is a feature I have planned for users that use CyberArk and Thycotic that get the key as a string from their password vaults.

**Comment by alefesta** [comment]
I'm using as workaround to this a simple tmp file where to store the key, using it and than remove the file. They key may be retrieved easily from virtually anywhere, in my case I store the key in a DB table.
This way you may take care of the string/stream object and use it whenver you need to issue commands.

something similar to this:

#Create a temporary file to use
$filetmp=[System.IO.Path]::GetTempFileName()

 #Get content of key from DB
 # in this line we use a proper file to emulate the behavior
 $key = Get-Content C:\PAG\Key\id_dsa | Out-File $filetmp

 #Open a session to TPAM
New-SSHSession -ComputerName $tpamurl -KeyFile $filetmp -Credential $username

#remove the file
remove-item $filetmp -force

Eventually you may exclusively lock the file to be sure nobody can use it
example:
http://stackoverflow.com/questions/21086051/locking-the-file-while-writing-in-powershell

**Comment by darkoperator** [comment]
I plan on adding the feature but it will take me a while since I’m traveling and teaching several offensive and defensive powershell and IR classes until decemeber and the mod is not a simple one.

**Comment by alefesta** [comment]
I may help if you like.. working right now on some scripting that uses your work. 

    Il Martedì 20 Settembre 2016 14:36, Carlos Perez <notifications@github.com> ha scritto:
 
 

 I plan on adding the feature but it will take me a while since I’m traveling and teaching several offensive and defensive powershell and IR classes until decemeber and the mod is not a simple one.

**Comment by darkoperator** [comment]
The changes are in C# in one of the classes and several cmdlets, how is your C#?

**Comment by alefesta** [comment]
A little bit rusty but I may at least work on a local copy and once is done show you so you may evaluate it.. 

    Il Martedì 20 Settembre 2016 14:42, Carlos Perez <notifications@github.com> ha scritto:
 
 

 The changes are in C# in one of the classes and several cmdlets, how is your C#?

**Comment by darkoperator** [comment]
this will be in the compiled version of 2.0, you can test the branch for the version

**Comment by alefesta** [comment]
thanks that's a great news! 

    Il Martedì 22 Novembre 2016 20:30, Carlos Perez <notifications@github.com> ha scritto:
 
 

 this will be in the compiled version of 2.0, you can test the branch for the version—
